### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [performancecopilot/pcp#10]
Would you like to add more error handling for return values from functions like the following?
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [rpm_init](https://github.com/performancecopilot/pcp/blob/f04f926f4c5dc9cea1c88d0da385d37c42a2c9e4/src/pmdas/rpm/rpm.c#L596)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [monitor_init](https://github.com/performancecopilot/pcp/blob/cec143a52ffd8deac816b5d3ad4ea2caf2d67f3d/src/pmdas/perfevent/perfmanager.c#L94)

**Comment by natoscott** [comment]
Yes.  Do you want to send a patch or pull request?

**Comment by kmcdonell** [comment]
According to my man page ... pthread_mutex_init always returns 0.
The pthread_create one though is a bug that I'll fix.
