### ISSUE TITLE
pmproxy: /pmapi/metric invalid series identifier within metric item response

### ISSUE THREAD

**Issue by Erbenos** [performancecopilot/pcp#1017]
Querying `/pmapi/metric?names=disk.dev.read` returns response with series field inside metric item containing series identifier, yet this identifier doesn't exist within response of call to `/series/query?expr=disk.dev.read*`

**Comment by natoscott** [comment]
One observation so far - I see it only seems to affect metrics with indoms / instances.  Will keep digging into it, out of time for today though.
