### ISSUE TITLE
PCP SELinux Issue on RHEL 6

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1032]
When installing current pcp git master (as of 2020-09-07) on RHEL 6 I see:

Installing : pcp-selinux-5.2.1-1.x86_64     2/63 
libsepol.print_missing_requirements: pcpupstream's global requirements were not met: type/attribute proc_security_t (No such file or directory).
libsemanage.semanage_link_sandbox: Link packages failed (No such file or directory).
semodule:  Failed!

Perhaps some RHEL 6 -specific conditions would be needed to resolve this.

Thanks.

**Comment by goodwinos** [comment]
The 'sandbox' messages are similar to BZ 1047673, posted against F20, which is probably similar vintage to RHEL6.x for some x. The BZ says to remove the sandbox module with "semodule -r sandbox" ... in any case it doesn't seem to be the fault of the pcp-selinux package.

Not sure about the proc_security_t messages - pcpupstream.te.in defines type proc_security_t but maybe RHEL6 SELinux doesn't know about it or something.

**Comment by kmcdonell** [comment]
Pretty sure the proc_security_t issue has been resolved by commit https://github.com/performancecopilot/pcp/commit/2f09752642cf84545adc78b6caa6157732426712.
And my local CentOS 6.10 build-n-install worked just fine.
@myllynen if the problem has not been resolved for you, please re-open and add details.
