### ISSUE TITLE
always use FQDN in redis

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1041]
Currently the hostname as returned by the `gethostname()` function is stored as the hostname label in redis. Afaics `gethostname()` returns the hostname from `/etc/hostname`, which is usually the short name of the machine.

I suggest we should store the fully qualified domain name (FQDN) instead, i.e. the hostname combined with the domainname.

Example:
```
[root@ci-vm-10-0-139-91 lemon]# hostname
lemon
[root@ci-vm-10-0-139-91 lemon]# hostname --fqdn
lemon.max.corp
[root@ci-vm-10-0-139-91 lemon]# pmseries -a $(pmseries kernel.all.sysfork)

72249e71e634fdd63055b72a55e0169d5c5f539a
    PMID: 60.0.14
    Data Type: 64-bit unsigned int  InDom: PM_INDOM_NULL 0xffffffff
    Semantics: counter  Units: count
    Source: 93d15ba94be5f1435a206996f43509fc36e06f2f
    Metric: kernel.all.sysfork
    labels {"agent":"linux","domainname":"localdomain","groupid":990,"hostname":"lemon","machineid":"f63ef00802e245678c0b3d3e29f9a9e4","userid":993}
```

The hostname label should match the output of `hostname --fqdn` instead, i.e. `lemon.max.corp` in this example.

Reasoning: pmseries/redis is intended for time series analysis of multiple hosts, and in big deployments the (short) hostname can occur multiple times, but the FQDN is unique (if configured properly).

**Comment by natoscott** [comment]
The domainname is a separate label, already.  This is a tricky situation and "configured properly" means different things to different people - we cannot change the systems representation of "hostname" in any reliable / meaningful way.  Note the section of the hostname(1) man page titled "THE FQDN" which states "avoid using hostname --fqdn".

```
[pcpqa@shard ~]$ hostname
shard
[pcpqa@shard ~]$ domainname 
scott.net.au
[pcpqa@shard ~]$ hostname --fqdn
shard
[pcpqa@shard ~]$ 
```

Lastly, if we were to change the hostname label contents, this would change every series identifier for every time series we currently have in Redis, which would cause a fairly nasty disconnect for everyone.

**Comment by andreasgerstmayr** [comment]
> The domainname is a separate label, already.

afaics the domainname label contains the NIS domain name (calling `getdomainname()`), not the DNS domain name (not sure if NIS is still in widespread use today?)

There can be also multiple DNS domain names, if the server is connected to multiple networks and each network's DHCP server sends a different DNS domain - afaics that's what the man page mentions. In that case, I would just go with the first returned one - imho that's better than no FQDN at all, and will serve most of the users.

> This is a tricky situation and "configured properly" means different things to different people

Reading [1] imho there is only one way which makes the most sense, use the short hostname and no FQDN as the system hostname. The man page of hostname(1) mentions: "/etc/hostname: Historically this file was supposed to only contain the hostname and not the full canonical FQDN. Nowadays most software is **able to cope** with a full FQDN here."

> Lastly, if we were to change the hostname label contents, this would change every series identifier for every time series we currently have in Redis, which would cause a fairly nasty disconnect for everyone.

+1
I was thinking the same - maybe we can just add a new label, called fqdn to avoid that situation?

[1] https://lists.freedesktop.org/archives/systemd-devel/2013-February/008899.html

**Comment by natoscott** [comment]
>  I was thinking the same - maybe we can just add a new label, called fqdn to avoid that situation?

Adding new labels also causes that situation to occur.  Each time series identifier hash is calculated using all of the intrinsic labels (hostname, domainname, etc).  We could add either an optional label (perhaps array-valued?) for DNS domain names, or a command-line option to pmcd allowing people to opt-in (i.e. not modifying existing setups timeseries, unless they choose to) to having new intrinsic label(s) for FQDN.  In the meantime, people can add their own labels already below /etc/pcp/labels[/optional] if that helps.

**Comment by andreasgerstmayr** [comment]
> Adding new labels also causes that situation to occur

Ah, you're talking about creating new time series, because the hash is different? From a user point of view this shouldn't be an issue, grafana-pcp handles multiple timeseries already - it's a regular case when a pmseries query spans multiple hosts. Are there other possible problems I'm not aware of if the hash changes?

> In the meantime, people can add their own labels already below /etc/pcp/labels[/optional] if that helps.

+1 - I'll recommend that to users asking for this in the meantime.
