### ISSUE TITLE
how to connect multiple remote pmcd via pmproxy

### ISSUE THREAD

**Issue by praveen-pcp** [performancecopilot/pcp#1045]
I am using PCP in distributed manner.
There are 4 hosts-
a)	Host1, Host2 : runs only pmcd
b)	Host3: runs only pmproxy
c)	Host4: running only Grafana server.

I am using Grafana pcp-vector to connect to Host1 & Host2 pmcd via pmproxy running on Host3.
But I am not able to specify pmcd host& port locations in pmproxy.conf file. (-h accepts only redis ip, but I am not running redis)
Please let me know how can I connect to multiple PMCD remotely via pmproxy.
Thanks

**Comment by natoscott** [comment]
pmproxy can connect to any number of pmcd daemons and this choice is made at runtime, not via configuration file.

See discussion of the 'hostspec' parameter on the pmwebapi(1) man page for REST clients like Grafana - Vector uses the /pmapi APIs - and perhaps also this may help:  https://grafana-pcp.readthedocs.io/en/latest/guides/multiple-vector-hosts.html

For regular PCP clients like pminfo(1), pmchart(1), pmie(1), and so on, see the examples in the PCPIntro(1) man page 'PMCD HOST SPECIFICATION' section.
