### ISSUE TITLE
/series/query: expr without time window should return SID rather than syntax error

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1050]
```
$ pmseries 'rate(kernel.all.pswitch)'
pmseries: [Error] cannot parse given string

rate(kernel.all.pswitch)
                       ^ -- syntax error
```

The time window in query expression operands should be optional in the grammar. Expressions should return a single fabricated SID (or maybe a list of length one SID). As discussed in #redis channel, the expr needs to be stored in redis.

If the optional expr {qualifier} is given it should also be stored as part of the expr. At this stage I think we decided this is necessary and not to worry about the order of elements in the qualifier list.

**Comment by ElephantZhang** [comment]
Fixed in [this PR](https://github.com/performancecopilot/pcp/pull/1114), please check if there are any issues.
