### ISSUE TITLE
/series/query: need an API to return functions and operators that are available

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1051]
The client side query editor in grafana-pcp (and other datasources) needs an API to return a list of functions and operators that are available. Something like /series/query?functions and /series/query?operators and maybe also an optional pattern parameter to filter what's returned.

**Comment by goodwinos** [comment]
Andreas and Nathan, any thoughts on what the above API calls should return? Just a list of functions and operators, or something more? e.g for functions maybe a JSON array of function name and type of parameters and perhaps the type of the result?

**Comment by andreasgerstmayr** [comment]
For the monaco editor I'll need to create a new language definition, like here: https://microsoft.github.io/monaco-editor/monarch.html
As the pmseries language can also change (in fact, it does with the upcoming release - previously no functions where possible at all), I suggest I just store the PCP version from which one a specific feature is available.

We currently have an `/series/ping` endpoint to check for redis. What about a `/series/status` endpoint which returns
```
{
   pcpVersion: '5.2.0',
   redis: {
      ok: true,
      error: null
   }
}
```
?

In the case of a connection error to redis, the error field contains the message and `ok` is set to `false`.

**Comment by goodwinos** [comment]
Sounds fine so long as you don't mind maintaining the per-version list of available functions and operators etc client-side rather than server side. That would be part of the Monarch specification I suppose? Regardless,  versioning is required because the data source may access downrev remote pmproxy/libpcp_web.

I think the pcpVersion string should also include the build number since new functions, operators or other query expression features or changes may be added (or removed) in a patched build. i.e. pcpVersion: 5.2.0-1 (instead of 5.2.0).

**Comment by andreasgerstmayr** [comment]
> Sounds fine so long as you don't mind maintaining the per-version list of available functions and operators etc client-side rather than server side. That would be part of the Monarch specification I suppose?

Yes

> I think the pcpVersion string should also include the build number since new functions, operators or other query expression features or changes may be added (or removed) in a patched build. i.e. pcpVersion: 5.2.0-1 (instead of 5.2.0).

Afaics patched builds usually contain only bugfixes. If I also maintain a list of patched builds, it needs to be different for every distribution (debian may have different patched builds than fedora). I think it's getting overly complicated - if some function is missing in the auto-complete, it's not a big deal, the query can still be executed.

**Comment by goodwinos** [comment]
The PCP version is already available as pmcd.version and pmcd.build, which coudl be fetched from a live pmapi context, e.g. 
'http://_pmproxyhost_:44322/pmapi/fetch?names=pmcd.version,pmcd.build'  (for some _pmproxyhost_, typically localhost but not necessarily depending on the data-source settings). If we also added a pmproxy.redis_status metric or some such, then I guess maybe there'd be no need for a new end-point. But we could always add one anyway returning the status info you suggested if it'd be easier for the data-source to process.

**Comment by natoscott** [comment]
> I think it's getting overly complicated

I agree - more fundamentally, I'm wondering if a version exchanging is really going to be worthwhile in this context.  Its not likely we're going to be adding functions every day of the week - there will be a bunch in the short term, then none for years once we have a good set I guess.  Simplest will be to just make latest grafana-pcp track the latest pmseries language IMO.  Its not the end of the world if the syntax highlighting / completion is missing / slightly wrong for down-rev versions, for some functions.

**Comment by goodwinos** [comment]
ok, we can probably close this out then. The version is there if it turns out to be needed

**Comment by andreasgerstmayr** [comment]
> The PCP version is already available as pmcd.version and pmcd.build, which coudl be fetched from a live pmapi context, e.g.
'http://pmproxyhost:44322/pmapi/fetch?names=pmcd.version,pmcd.build' (for some pmproxyhost, typically localhost but not necessarily depending on the data-source settings).

Maybe a rare case, but (I think?) it's possible that there is no pmcd running and pmproxy is only connected to redis (for a central monitoring host, for example running only redis server, grafana-server and pmproxy).

>  Its not likely we're going to be adding functions every day of the week - there will be a bunch in the short term, then none for years once we have a good set I guess.

Yep, I was already thinking the same - probably even basic versioning is already too much effort for little gain ;)

>  Its not the end of the world if the syntax highlighting / completion is missing / slightly wrong for down-rev versions, for some functions.

+1
Closing this issue.
