### ISSUE TITLE
buster 4.3.1 pcp: Grafana Vector/Redis Data source does not work

### ISSUE THREAD

**Issue by praveen-pcp** [performancecopilot/pcp#1059]
I am installing PCP from Buster mirror, and i am getting 4.3.1 pcp version.
I have configured Grafana and PCP, but Vector/Rdis data source does not work. I am getting following error-

Network error: Could not connect to http://10.100.71.79:44324/pmapi/context, please check the datasource and pmproxy settings. To use this data source, please configure the URL in the query editor.

Note: Same settings works if i use sid mirror / pcp version is 5.1x.

Is it a known issue with Buster PCP 4.3.1 version? Please let me know if I need to do some special configs.
Thanks
Praveen

**Comment by natoscott** [comment]
@praveen-pcp you'll need to use PCP v5 or later with modern Grafana and grafana-pcp.  Try packages from https://bintray.com/pcp
