### ISSUE TITLE
PCP won't install via RPM on CentOS 7 via bintray repo

### ISSUE THREAD

**Issue by jwhite530** [performancecopilot/pcp#106]
The repo appears to be broken.  I cannot install PCP packages:

Error: Package: pcp-pmda-systemd-3.11.3-1.x86_64 (@bintray-pcp-el7)
           Requires: pcp-libs = 3.11.3
           Removing: pcp-libs-3.11.3-1.x86_64 (@bintray-pcp-el7)
               pcp-libs = 3.11.3-1 
           Updated By: pcp-libs-3.11.4-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.11.4-1 
           Available: pcp-libs-3.10.5-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.10.5-1 
           Available: pcp-libs-3.10.6-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.10.6-1 
           Available: pcp-libs-3.10.6-2.el7.i686 (wsu-centos-7-base-x86_64-live)
               pcp-libs = 3.10.6-2.el7
           Available: pcp-libs-3.10.7-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.10.7-1 
           Available: pcp-libs-3.10.8-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.10.8-1 
           Available: pcp-libs-3.10.9-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.10.9-1 
           Available: pcp-libs-3.11.0-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.11.0-1 
           Available: pcp-libs-3.11.1-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.11.1-1 
           Available: pcp-libs-3.11.2-1.x86_64 (bintray-pcp-el7)
               pcp-libs = 3.11.2-1 
 You could try using --skip-broken to work around the problem

I have tried specifying exact version of all the packages I need, tried downgrading, tried removing and installing again, nothing.  Every single time yum complains it can't do what I asked.  When I went to the repo in a browser every package gives "The requested path was not found." when I try to download it.

**Comment by natoscott** [comment]
@jwhite530 I suspect this may be fallout from https://bugzilla.redhat.com/show_bug.cgi?id=1350301

Can you "rpm -e pcp-pmda-systemd" and see if that clears up the problem when you subsequently upgrade?

**Comment by jwhite530** [comment]
I removed pcp-pmda-systemd via yum before you posted that and it did work around the issue.  So the pcp-pmda-systemd package is missing/broken which in turn causes everything else PCP to break since yum wants to update everything but can't update pcp-pmda-systemd?

**Comment by natoscott** [comment]
Yes, I think that is whats happened here - because of that systemd pkg-config change, we end up no longer building pcp-pmda-systemd in some places that we would have previously.

**Comment by natoscott** [comment]
@kmcdonell has fixed this in commit 2fed1920bf which will re-enable this package in places it has been accidentally dropped, from pcp-3.11.5
