### ISSUE TITLE
fail on yum install (CRYPTO_num_locks)

### ISSUE THREAD

**Issue by jonhornstein** [performancecopilot/pcp#108]
Just tried to install pcp on an AWS machine.

I went to the download page to get instructions and got the following error. Any idea which dependency has not been handled?

cheers

Jon Hornstein

-bash-4.2$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

-bash-4.2$  sudo yum install pcp

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   /usr/lib64/python2.7/site-packages/pycurl.so: undefined symbol: CRYPTO_num_locks

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

**Comment by fche** [comment]
This looks relevant: http://stackoverflow.com/questions/23589971/yum-not-working
Maybe the default python link on this box has been replaced from the RHEL normal python2 one, and broke yum in general.  This is not a pcp error.
