### ISSUE TITLE
mem.vmstat.drop_pagecache & mem.vmstat.drop_slab are always zero

### ISSUE THREAD

**Issue by yogeshbabar420** [performancecopilot/pcp#1085]
Hello Team, 

On a fedora 32 system with 'pcp-5.2.0-1.fc32.x86_64'.  mem.vmstat.drop_pagecache & mem.vmstat.drop_slab metric values are always zero though the /proc/vmstat reflects them properly: 

$echo 3 > /proc/sys/vm/drop_caches 
$ echo 3 > /proc/sys/vm/drop_caches 
$ echo 2 > /proc/sys/vm/drop_caches 
$ echo 2 > /proc/sys/vm/drop_caches 
$ echo 1 > /proc/sys/vm/drop_caches 

$ cat /proc/vmstat | grep -i drop
  drop_pagecache 2
  drop_slab 2

$ pmrep mem.vmstat.drop_pagecache
  m.v.drop_pagecache
             count/s
                 N/A
               0.000
               0.000
               0.000
               0.000
               0.000

$ pmrep mem.vmstat.drop_slab
  m.v.drop_slab
        count/s
            N/A
          0.000
          0.000
^C

Regards

**Comment by yogeshbabar420** [comment]
Let me know if you need any other info.

**Comment by natoscott** [comment]
> Let me know if you need any other info.

I can see where the bug is, fix will be committed shortly.  Thanks @yogeshbabar420 !
