### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [performancecopilot/pcp#11]
The variables "[discoveryFlags](https://github.com/performancecopilot/pcp/blob/0d90a9f834c972bbc07ce8faa3b0f621aa093499/src/pmfind/pmfind.c#L21 "Update candidate")" and "[finished](https://github.com/performancecopilot/pcp/blob/dd13e059730747a7ef3dffc32c646a7144da76b6/src/pmsleep/pmsleep.c#L20 "Another update candidate")" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.").

**Comment by dbrolley** [comment]
The fix will apear in the upcoming PCP release 3.10.5.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/performancecopilot/pcp/commit/9478ca09877f90c5c890355324689ed2c103a5b4 "Reuse of sig_atomic_t").
