### ISSUE TITLE
pmlogger exiting with "Nothing to log, and not the primary logger instance ... good-bye"

### ISSUE THREAD

**Issue by yvk2493** [performancecopilot/pcp#1121]
Hi Team,

We are using PCP 4.2 and pmlogger was working properly in that version. But to use some features, we have upgraded to PCP 5.2.1 version and saw that pmlogger is failing with error:
"Nothing to log, and not the primary logger instance ... good-bye"

Our Config file is proper and has the metrics to collect.

Command to start pmlogger:
/usr/lib/pcp/bin/pmlogger -r -t 5m -u -v 288 -h 127.0.0.1:44320 -c /home/pcp/config/pmlogger/config.default /home/pcp/config/pmlogger/Fdr_Daily%Y%m%d.%H.%M

config file contents:
log mandatory on once {
        kernel.uname
        filesys.mountdir
        filesys.blocksize
        filesys.capacity
}
log mandatory on default {
        pmda.uname
        pmcd.numagents
        pmcd.numclients
        pmcd.services
        pmcd.version
        pmcd.build
        pmcd.agent.status
        pmcd.pmlogger
        pmcd.pmie
}

Can you please let us know what is wrong with this configuration? 
FYI: we are using PCP in a docker and everything used to work properly in PCP 4.2 version.

**Comment by yvk2493** [comment]
**pmloggger log file with this error:**
# cat pmlogger.log
Log for pmlogger on 5c7426da710d started Thu Oct 22 12:49:50 2020

preprocessor cmd: /usr/lib/pcp/bin/pmcpp -rs /home/pcp/config/pmlogger/config.vamsi -I /home/pcp/config/pmlogger

Log finished Thu Oct 22 12:49:50 2020
Config parsed
Starting logger for host "5c7426da710d" via "127.0.0.1:44320"
Nothing to log, and not the primary logger instance ... good-bye

Log finished Thu Oct 22 12:49:50 2020

**Comment by natoscott** [comment]
@yvk2493 is pmcd really running on port 44320?  Its usually 44321.

The only change I can imagine that might be contributing to this is the Fedora change from some time ago that made new installations default to PMCD_LOCAL=1  (see /etc/sysconfig/pmcd file for this setting).

**Comment by yvk2493** [comment]
It seems that problem is with pmcd port. Working fine after correcting it . Thanks for reply.
