### ISSUE TITLE
filesys metrics are (probably) too selective

### ISSUE THREAD

**Issue by zmc** [performancecopilot/pcp#113]
I won't claim that I need, or want, pcp to monitor all of these:
```
$ df -h
Filesystem                                               Size  Used Avail Use% Mounted on
udev                                                      16G     0   16G   0% /dev
tmpfs                                                    3.2G  338M  2.9G  11% /run
/dev/vda2                                                2.9T  133G  2.8T   5% /
tmpfs                                                     16G  6.5M   16G   1% /dev/shm
tmpfs                                                    5.0M     0  5.0M   0% /run/lock
tmpfs                                                     16G     0   16G   0% /sys/fs/cgroup
cgmfs                                                    100K     0  100K   0% /run/cgmanager/fs
172.21.5.114:6789,172.21.4.136:6789,172.21.6.130:6789:/  162T  116T   47T  72% /ceph
tmpfs                                                    3.2G     0  3.2G   0% /run/user/1102
[several more tmpfs entries follow]
```

But this seems a bit too selective:
```
$ pminfo -f filesys.mountdir
filesys.mountdir
    inst [0 or "/dev/vda2"] value "/"
```

It would be really helpful if pcp would at least track the ceph fs. I realize there's a ceph pmda, though I don't know what state it's in, but simple free space numbers could be collected pretty easily, it seems.

**Comment by natoscott** [comment]
As discussed on IRC, these are possibly candidates for pmdamounts(1) monitoring.  The pmdalinux code attempts to only export local, non-memory filesystem stats via filesys.* FWIW (as you found).

A specialized pmdaceph would be the best bet for exporting ceph statfs data, I suspect, e.g.
https://github.com/badone/pcp-pmda-ceph ... I'll send Brad a note about it.

**Comment by fche** [comment]
Why not keep this RFE open and construe it to refer to pmdamounts instead of pmdalinux?  pmdamounts is also filtering out lots of stuff.

**Comment by badone** [comment]
This looks like cephfs client statistic collection from the client side. The ceph pmda is being written to target monitoring performance data from the backend server daemons, although it will also monitor RADOS clients since they have an admin socket which is currently the criteria for what it will be able to monitor.

**Comment by natoscott** [comment]
@badone thanks!  @zmc pmdamounts(1) is best/only option available in pcp, short of writing a custom PMDA based on the pmdamounts code (or some other kind of extension there if you're not keen on the config).
