### ISSUE TITLE
pmrep - header and value is not matching, possibly due to indom changes

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#114]
I am requesting 25 metric, but pmrep responds with 41 values, how do i associate which value to what metric?

Example Data:
pmrep -h aic01 -t 1 -o csv kernel.all.cpu mem.physmem mem.freemem mem.util.bufmem mem.util.cached kernel.percpu.cpu.user
Time,kernel.all.cpu.user,kernel.all.cpu.nice,kernel.all.cpu.sys,kernel.all.cpu.idle,kernel.all.cpu.intr,kernel.all.cpu.steal,kernel.all.cpu.guest,kernel.all.cpu.vuser,kernel.all.cpu.wait.total,kernel.all.cpu.irq.soft,kernel.all.cpu.irq.hard,kernel.all.cpu.guest_nice,kernel.all.cpu.vnice,mem.physmem,mem.freemem,mem.util.bufmem,mem.util.cached,kernel.percpu.cpu.user
2016-09-15 09:07:23,466260580,375400,78926590,14075988910,5618390,0,0,466260580,9710720,5613640,4750,0,375400,65780248,290876,324,45863784,22796270,21988120,21720220,21179580,20951380,21086140,32033770,32072730,32125000,31663030,31819740,31684010,11116840,11790290,10959690,11042400,11193930,11198350,13132700,13492380,12901050,12748220,12851360,12713280

**Comment by hc000** [comment]
some more data point
pmrep -h aic01 -t 1 -s 3 kernel.all.cpu mem.physmem mem.freemem mem.util.bufmem mem.util.cached kernel.percpu.cpu.user
  k.a.c.user  k.a.c.nice  k.a.c.sys  k.a.c.idle  k.a.c.intr  k.a.c.steal  k.a.c.guest  k.a.c.vuser  k.a.c.w.total  k.a.c.i.soft  k.a.c.i.hard  k.a.c.guest_nice  k.a.c.vnice  m.physmem  m.freemem  m.u.bufmem  m.u.cached  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user  k.p.c.user
                                                                                                                                                                                                                                  cpu0        cpu1        cpu2        cpu3        cpu4        cpu5        cpu6        cpu7        cpu8        cpu9       cpu10       cpu11       cpu12       cpu13       cpu14       cpu15       cpu16       cpu17       cpu18       cpu19       cpu20       cpu21       cpu22       cpu23
        ms/s        ms/s       ms/s        ms/s        ms/s         ms/s         ms/s         ms/s           ms/s          ms/s          ms/s              ms/s         ms/s      Kbyte      Kbyte       Kbyte       Kbyte        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s        ms/s
         N/A         N/A        N/A         N/A         N/A          N/A          N/A          N/A            N/A           N/A           N/A               N/A          N/A   65780248    3538180         488    42642008         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A         N/A
     189.410       0.000     49.845   23716.077       0.000        0.000        0.000      189.410          0.000         0.000         0.000             0.000        0.000   65780248    3538208         488    42642080       0.000      29.907       0.000       0.000       9.969       0.000       0.000      19.938      19.938       9.969      29.907       0.000       0.000       0.000       0.000       0.000       0.000       0.000      19.938       0.000       9.969      19.938       9.969       0.000
     199.294       0.000     49.823   23696.045       0.000        0.000        0.000      199.294          0.000         0.000         0.000             0.000        0.000   65780248    3539480         488    42642080       9.965      19.929       9.965       9.965       9.965       0.000       9.965       9.965      19.929      19.929      29.894       0.000       0.000       9.965       9.965       0.000       9.965       0.000       0.000       0.000       0.000      19.929       9.965       0.000

**Comment by natoscott** [comment]
Marko's fix is merged, will be in pcp-3.11.6
