### ISSUE TITLE
Sym links for not installed PMDAs created after fresh PCP installation

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1150]
With current git code built on RHEL 8 and freshly installed PCP (without the pcp-zeroconf package) I see dead sym links being present for probably all PMDAs even if they are not installed:

```
root@rhel-8-server:~# ls -l /var/lib/pcp/pmdas/mssql/
total 0
lrwxrwxrwx. 1 root root 50 2020-11-19 12:08 Install -> ../../../../../usr/libexec/pcp/pmdas/mssql/Install
lrwxrwxrwx. 1 root root 49 2020-11-19 12:08 Remove -> ../../../../../usr/libexec/pcp/pmdas/mssql/Remove
lrwxrwxrwx. 1 root root 50 2020-11-19 12:08 Upgrade -> ../../../../../usr/libexec/pcp/pmdas/mssql/Upgrade
lrwxrwxrwx. 1 root root 39 2020-11-19 12:08 mssql.conf -> ../../../../../etc/pcp/mssql/mssql.conf
lrwxrwxrwx. 1 root root 59 2020-11-19 12:08 pmdamssql.python -> ../../../../../usr/libexec/pcp/pmdas/mssql/pmdamssql.python
root@rhel-8-server:~# rpm -q pcp-pmda-mssql
package pcp-pmda-mssql is not installed
root@rhel-8-server:~# ls -1 /var/lib/pcp/pmdas/ | wc -l
68
root@rhel-8-server:~# rpm -qa | grep pcp-pmda | wc -l
47
root@rhel-8-server:~# 
```

I think it would be better if PMDA dirs and sym links would only appear when installing the corresponding PMDA RPM.

Thanks.

**Comment by natoscott** [comment]
@myllynen what does 'rpm -qf /var/lib/pcp/pmdas/mssql/Install' report?

**Comment by myllynen** [comment]
```
root@rhel-8-server:~# ls -l /var/lib/pcp/pmdas/mssql/Install
lrwxrwxrwx. 1 root root 50 2020-11-20 11:59 /var/lib/pcp/pmdas/mssql/Install -> ../../../../../usr/libexec/pcp/pmdas/mssql/Install
root@rhel-8-server:~# rpm -qf /var/lib/pcp/pmdas/mssql/Install
file /var/lib/pcp/pmdas/mssql/Install is not owned by any package
```

I doublechecked that when reinstalling PCP the entire `/var/lib/pcp` directory was indeed removed so the sym link can't be a leftover from any previous installation. I now tested by installing only the `pcp` package, it pulls in some dependencies but I think these were created during post-scripts of the `pcp` package when starting the `pmcd` service.

**Comment by natoscott** [comment]
Related: https://github.com/performancecopilot/pcp/issues/1148  (same root cause)
