### ISSUE TITLE
PCPIntro(1) should be PCPIntro(7) on Linux

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1151]
Linux man-pages(7) states:

```
   Sections of the manual pages
       The manual Sections are traditionally defined as follows:

       1 Commands (Programs)
                 Those commands that can be executed by the user from within a shell.

       7 Overview, conventions, and miscellaneous
                 Overviews of various topics, conventions and protocols, [...].
```

Thus, strictly speaking, PCPIntro(1) should be PCPIntro(7) on Linux. But I'm not sure would this be worth the effort to change it so I'll merely report this minor finding here. Thanks.

**Comment by natoscott** [comment]
While probably strictly correct, I think this change will cause more harm than good with broken links and expectations.  OTOH, PCPIntro(1) is all about the PCP commands (while PCPIntro(3) is all about PMAPI topics - should that move too?  that'd be a problem with the shared name too) ... so perhaps one could argue these are in the right section and let's just leave be.
