### ISSUE TITLE
RFE: New PMIE action methods

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1180]
Background: https://groups.io/g/pcp/message/23377 and https://github.com/linux-system-roles/linux-system-roles.github.io/issues/47

It would be helpful to provide some additional PMIE action methods relevant for modern environments, this could include:

* alerta
* D-Bus
* email
* HTTP POST
* SNMP
* SMS
* syslog

Some of these could be implemented as shell scripts while others might be add-on/library code written in C like PMIE itself.

HTTP POST would appear as especially helpful, it could be used to "call home" a management or orchestration system (like AWX aka Ansible Tower) in case a condition is met to allow the management system to take an action depending on the overall environment and situation. D-Bus idea came from a monitoring agent that provides such an integration for one specific condition, see https://gitlab.freedesktop.org/hadess/low-memory-monitor/. SMS would probably use some existing service like Twilio. Obviously only one or few could be implemented initially and the others only if a need arises but having some of these available "out of the box" as references might make PMIE consumable for those not deeply familiar with PCP or PMIE (and could make implementing the above mentioned linux-system-role easier).

Thanks.

**Comment by natoscott** [comment]
HTTP POST has been implemented in the last few months - see the webhook action in pmieconf.
syslog and email have always been available.

The remainder I think are too specific for us to take on ourselves, and should be implemented via the shell action for anyone whose local environment needs 'em.
