### ISSUE TITLE
not able to launch a shell program using PMIE actions

### ISSUE THREAD

**Issue by yvk2493** [performancecopilot/pcp#1182]
Hi Team,

I have a simple pmie rule as stated below to get a list of process list when my metric reached a threshold. But all i get is a message in the console rathar than process list.
`pmcd.pid > 50  -> shell "'ps'" ;`

**output is** 
shell Tue Dec 22 15:16:54 2020: 'ps'
[Tue Dec 22 15:59:55] pmie(12893) Info: evaluator exiting

I am executing pmie on a archive file with below command
**/usr/bin/pmie -b -a Fdr_Monthly.0 -c pmie.rule**

content of pmie.rule file is
`pmcd.pid > 50  -> shell "'ps'" ;`

Please help me to find what is wrong here.

**Comment by natoscott** [comment]
@yvk2493 this is how pmie handles all actions when given an archive, because its dealing with historical data - it reports what it would have done if that time had been now.  You'll find the rule functions as you expect when pmie is running live (-g/--host).
