### ISSUE TITLE
Some pmdazfs metrics are missing help text

### ISSUE THREAD

**Issue by mac133k** [performancecopilot/pcp#1194]
There are 272 metrics listed in the help file, but 93 of them have no help text. The existing help text was mainly copied from the comments found in the [OpenZFS source files](https://github.com/openzfs/zfs.git), some was also copied from the Solaris PMDA. The author of pmdazfs was not confident enough to provide the metric descriptions on his own. Unless there is an authoritative source of the missing information the only quick solution is to remove or comment out the metrics without descriptions from the help file.

**Comment by natoscott** [comment]
@mac133k in situations where we don't know the meaning and its not clearly documented, we can instead describe the metric sampling mechanism / location - this sometimes is enough for a domain expert to work with.  e.g.

```
$ pminfo -t xfs.perdev.log_tail.push_ail.restarts
xfs.perdev.log_tail.push_ail.restarts [value from xs_push_ail_restarts field of struct xfsstats]
```
