### ISSUE TITLE
dstat can not output csv file

### ISSUE THREAD

**Issue by AkihaTohno** [performancecopilot/pcp#1210]
On Ubuntu 20.04, When I run dstat with output option,
it returned error message.

 ubuntu@ubuntu:~$ dstat --output hoge.csv
You did not select any stats, using -cdngy by default.
Traceback (most recent call last):
  File "/usr/bin/dstat", line 2847, in <module>
    main()
  File "/usr/bin/dstat", line 2687, in main
    scheduler.run()
  File "/usr/lib/python3.8/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/usr/bin/dstat", line 2806, in perform
    oline = oline + o.showcsv() + o.showcsvend(totlist, vislist)
  File "/usr/bin/dstat", line 547, in showcsv
    if isinstance(self.val[name], types.ListType) or isinstance(self.val[name], types.TupleType):
NameError: name 'types' is not defined

How can I do it?

dstat install command: sudo apt install dstat

**Comment by natoscott** [comment]
@AkihaTohno it looks like you may be using the old version of dstat?  (the traceback you've given shows code that does not exist in the PCP version).

To use the PCP version, try:

$ apt-get install pcp
$ pcp dstat [...]

cheers.
