### ISSUE TITLE
When I use "output" option with -t/T option, some charactor added before timestamp.

### ISSUE THREAD

**Issue by AkihaTohno** [performancecopilot/pcp#1211]
[dstat_log.txt](https://github.com/performancecopilot/pcp/files/5938668/dstat_log.txt)

Environment:
OS:
- openSUSE 15.2
- Ubuntu20.04 LTS
- Ubuntu20.10

Output Results:
Please see attachments.

**Comment by natoscott** [comment]
@AkihaTohno I guess these are special characters for setting console colors - you can workaround this using the --nocolor for now, but dstat should not be producing these with csv output.  I'll fix that up, thanks.
