### ISSUE TITLE
pmwebd graphite emulation: include analytical function support (Bugzilla #1094)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#122]
On 2014-12-03 13:06:34 -0600, Frank Ch. Eigler wrote:

> There has been a request to implement the &target=FOO(series)
> suite of functions in the pmwebd/graphite emulation code.
> 
> http://graphite.readthedocs.org/en/latest/functions.html

**Comment by gangelop** [comment]
I just want to raise my hand to express interest in this.
I just finished working with pcp/pmwebd + upstream grafana on a support case. I have worked with graphite+grafana before and made extensive use of the functions.
I don't know if I'll be able to contribute technically but I'll try to make time to look into it. I don't want to touch ksar and gnuplot *ever again*.

**Comment by fche** [comment]
Unfortunately progress on this code has been rather halting.  See the pmwebd/pmgraphite.cxx bits in this branch.  The next step there is a parser for the graphite function syntax.

https://sourceware.org/git/?p=pcpfans.git;a=shortlog;h=refs/heads/fche/pmfuntools-functions

**Comment by natoscott** [comment]
All efforts in the PCP REST APIs are towards the pmseries(1) language provided by the PMWEBAPI(3) REST interface.  pmwebd has been retired since PCP v5, replaced by pmproxy(1).
