### ISSUE TITLE
pmie depends on a local pmcd

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1223]
It should be possible to run pmie without having a local pmcd running, but in pmie's rc script it waits for a local pmcd: https://github.com/performancecopilot/pcp/blob/d0c53a0f9dd574cd23e22e721329e7e2d680b690/src/pmie/rc_pmie#L135-L138 (thanks @kurik for the analysis!)

Is this check required? Seemingly it only checks for local pmcds, and doesn't check whether remote pmcds are started or not, so it might be not required?

**Comment by andreasgerstmayr** [comment]
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1930284

**Comment by natoscott** [comment]
@andreasgerstmayr its not required, its a historical leftover - should have been removed at the same time it was removed from rc_pmlogger.  I'll fix this up, thanks for the reminder.
