### ISSUE TITLE
memory usage instrumentation and metrics for libpcp_web and pmproxy

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1225]
Add instrumentation needed for memory usage metrics, particularly for the dict caches. There is some existing infrastructure using MMV(3) API calls but it's mostly unimplemented (currently only have one metrics: pmproxy.pid). This will provide metrics for memory usage analysis and also to assist with garbage collection.

The proposal is to provide wrappers for dictCreate() and dictFind() and related functions to track statistics for named dicts (entry counts, space usage, dictFind call counters, etc) and export these as mmv dynamic metrics. Replace the existing per-module code in libpcp_web (that is largely unimplemented) and instead use the MMV(5) namespace with modules mapped to pmid clusters and module names as non-leaf pmns nodes and named individual dicts and other data structures of interest as the pmns leaf nodes. We only need one global mmv_registry for this (which can be private to the API) and so don't need to pass around module pointers in the instrumentation.

**Comment by natoscott** [comment]
> We only need one global mmv_registry for this (which can be private to the API) and so don't need to pass around module pointers in the instrumentation.

The end requirement is a single MMV registry for use throughout pmproxy and libpcp_web, with a shared namespace (below pmproxy.*) that is suitable for metrics beyond only the memory ones you're interested in right now - i.e. exposing counts of operations, redis message counts, pcp PDU counters, web API hit counters, and so on.

The existing hooks are in all the right places, and pmproxy sets everything up for you already to use libpcp_mmv throughout it & libpcp_web, so make use of the existing APIs please unless there's a *very* good reason not to (I can't imagine one).

I'll pre-emptively also mention to make use of the by-handle APIs in libpcp_mmv, and for metrics where we don't or can't directly update the MMV memory, add a timer-based callback (using similar mechanisms to the GC timer-based callback) that refreshes the MMV metrics from the local variables / structures.

**Comment by natoscott** [comment]
One other consideration is that libpcp_web has multiple users, not all of which want/should have instrumentation exported - pmseries(1) for example.  This was another reason why the registry-passing APIs were introduced.
