### ISSUE TITLE
Provide process info from sockets PMDA

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1231]
The sockets PMDA provides otherwise very complete information but the process name and id are not available.

Using the `-p` option with _ss(8)_ provides name, pid, and fd for network connections, it would be nice to include at least name/pid in the sockets PMDA metrics.

Thanks.

**Comment by goodwinos** [comment]
ss --p needs to run as root to provide the requested information for all sockets - that means the user/process info should not be exported without admin intervention to run the PMDA as root. There are no-doubt security related reasons for this restriction. Any thoughts or comments on this Marko?

**Comment by myllynen** [comment]
That's a very good point I didn't notice earlier since I was testing only as root on a test VM. I think it's clear that we shouldn't reveal any information to everyone which is not available by other means already.

When running ss(8) as root then `-p` works as expected but when running `ss -p` as a regular user it shows process information only about the user's own sockets. So in practice with `-p` we probably wouldn't get any additional information by default as `pcp` user is running the command. It would make it possible to have the information available if running as root but on the other hand it could leave to unwanted exposure if not being careful.

I don't have any exact use case at hand where this would be needed, as said earlier it'd be nice to have, but due to security concerns I don't know how to make it both safe and feasible. If there's no quick solutions for this one option would perhaps be to park this request and reconsider in more detail if concrete use cases appear.

Thanks.

**Comment by goodwinos** [comment]
ok thanks Marko - I'm closing this out. I'll save my draft patch in case we want to resurrect it sometime. Cheers
