### ISSUE TITLE
Clean up BCC PMDA network modules

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1234]
BCC PMDA netproc module seems to be superior in every way compared to the earlier tcpperpid module. I think dropping tcpperpid should be considered, I don't see it providing much additional value alongside with the netproc module.

In any case, I think the default _bcc.conf_ should switch using netproc unless there are some reasons no to do so? In fact, I think it might be best to have only the netproc module enabled as default as the other modules listed now are probably needed quite rarely.

tcpretransmit seems to be still useful. With netproc I'm not sure about tcplife and tcptop whether to keep them or drop them.

Thanks.

**Comment by myllynen** [comment]
Perhaps it could be mentioned under this "clean up" topic that the PMNS names for netproc metrics are really long, I'm not sure would it be possible to shorten them a bit. Thanks.

**Comment by andreasgerstmayr** [comment]
To be honest I also don't remember what especially marked a module as default or not - possibly the default ones were included in the default Vector dashboards (the standalone webapp, not Grafana)?

I'm fine with removing the other modules from the defaults (and dropping tcpperpid); fwiw, in the Grafana BCC dashboard there's now a prominent info text box telling users "This dashboards requires the bcc PMDA to be installed and configured with the following modules: runqlat, biolatency, tcptop, tcplife."

**Comment by andreasgerstmayr** [comment]
Regarding the second question:
the prefix is `bcc.proc.io.net.perpid.` - we could reduce that to `bcc.proc.net.`? `proc` already shows that metrics are per process
the individual fields are `tcp.send.calls` - we could replace `send` with `tx`, but that just saves 2 characters (and the syscalls are also called `tcp_sendmsg` etc.), so I wouldn't change that

When we change this, we mustn't forget to also update `netprocmetrics.map` in the atop folder. And we could also add a pmlogger rule to always log these metrics (if available)?

**Comment by myllynen** [comment]
> the prefix is bcc.proc.io.net.perpid. - we could reduce that to bcc.proc.net.

Yes, this sounds good. And I agree that send vs tx saving is not notable, and other metrics don't set an example for that either way.

If and when changing this, the recently updated `pmrep.conf` should also be adjusted. A pmlogger rule for these would sound reasonable, yes.

Thanks.

**Comment by myllynen** [comment]
In case the metric name is changed I think we should make a call and possibly a change wrt issue #1233 at the same time to avoid changes across several releases.

**Comment by natoscott** [comment]
+1 ... if we can make all metric renaming changes ASAP, that'd be great - we've got the pcp-5.3.0 release planned for end of next week with some other metric renames/reworks already (esp. interrupts related).

**Comment by andreasgerstmayr** [comment]
Just wanted to remove tcpperpid, but noticed tcpperpid has a process and port filter included, where netproc doesn't have filter capabilities. The netproc metrics are also used in pcp-atop now (and I just added a pmlogconf rule), adding a filter there might be confusing, so I left tcpperpid as-is for now.

PR for the above changes is incoming asap, I'm just testing the new pmlogconf rule.

**Comment by andreasgerstmayr** [comment]
PR: #1242
