### ISSUE TITLE
pmrep: improve instance filtering

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1236]
It would be helpful to be able to specify instances to report also by instance id instead of always requiring string or regex matching the instance name.

Currently:

```
$ pminfo -f proc.io.read_bytes | grep 1294
    inst [1294 or "001294 /usr/libexec/accounts-daemon"] value 0
$ pmval -s 1 -i 1294 proc.io.read_bytes   

metric:    proc.io.read_bytes
host:      localhost
semantics: cumulative counter (converting to rate)
units:     byte (converting to byte / sec)
samples:   1

              1294    
               0.0    
$ pmrep -s 2 -i 1294 proc.io.read_bytes
No matching instances found.

Requested global instances:
['1294']
$ pmrep -s 2 -i '.*1294.*' proc.io.read_bytes
  p.i.read_bytes
  001294 /usr/li
          byte/s
             N/A
           0.000
$
```

Proposal:

```
$ pmrep -s 2 -i 1294 proc.io.read_bytes
  p.i.read_bytes
  001294 /usr/li
          byte/s
             N/A
           0.000
$ pmrep -s 2 -i '.*1294.*' proc.io.read_bytes
  p.i.read_bytes
  001294 /usr/li
          byte/s
             N/A
           0.000
$
```

This requires some 20 lines of code and based on testing so far doesn't affect other client tools like `pcp-dstat` and passes all related QA tests.

I'm proposing that we'll add this code before 5.3.0 release without man page update so we don't fully commit to it yet. If no negative feedback before 5.3.1 or 6.0.0 then tweak the manual page to explain this alternative as well. Thanks.

**Comment by kmcdonell** [comment]
@myllynen Be very careful here.  Using the proc indom as a starting point is potentially dangerous ... this one has the unusual semantics that the internal instance identifier and the external instance name (up to the first space, which is all that matters) are the same ... so your -i option will match 1294 using either the internal instance identifier (an integer) or the external instance identifier (a string), but pmval is only using the string match.
For other instance domains, the internal instance identifier is usually (a) of no interest, and (b) not the same as the external instance name.
Regex pattern matching for pmrep's -i is OK, but the justification for that is a bit different to the argument used in this issue.

**Comment by myllynen** [comment]
Thanks for your insights, Ken. I checked `pmval` again and looks like I hadn't noticed that proc indom is special:

```
$ pminfo -f disk.dev.read                             

disk.dev.read
    inst [0 or "nvme0n1"] value 133889
$ pminfo -f proc.psinfo.pid | grep -e '\[1 ' -e '\[2 '
    inst [1 or "000001 /usr/lib/systemd/systemd"] value 1
    inst [2 or "000002 (kthreadd)"] value 2
$ pmval -s 1 -i 1 proc.psinfo.pid      

metric:    proc.psinfo.pid
host:      localhost
semantics: discrete instantaneous value
units:     none
samples:   1

          1 
          1 
$ pmval -s 1 -i 2 proc.psinfo.pid

metric:    proc.psinfo.pid
host:      localhost
semantics: discrete instantaneous value
units:     none
samples:   1

          2 
          2 
$ pmval -s 1 -i 0 disk.dev.read  
pmval: instance 0 not available
$ 
```

What do you think, which one of these would be the better approach for _pmrep(1)_ (in addition to the existing string/regex matching for instance name):

1) If the instance specified with `-i` is numeric, see if it matches the instance id
2) If the instance specified with `-i` is numeric and the first part of instance name is numeric, see if they match
3) If the instance specified with `-i` starts with colon and is numeric, see if it matches the instance id

It could in theory be possible to do both 1) and 3) or 2) and 3). In the end I think we should aim for the way of "minimal surprise" for users.

**Comment by kmcdonell** [comment]
Marco, I'd vote for not doing any of the above.  -i 1234 will work just fine for the proc indom (it is an external instance name as a string).  Add the re support for -i.  All of this deals with external instance names which is the most common use case.

This avoids any heuristics when parsing the -i value ... these are likely to come home to bite and surprise at some point down the track.

If you really want to allow internal instance identifiers, I'd suggest a different command line option, but I see pmrep is already suffering that ancient ls-itis condition, namely not enough lower case and upper case letters in the alphabet ... 8^) so maybe some obscure single letter option and a more user-friendly long option?

**Comment by myllynen** [comment]
Currently plain "-i 1234" does not work with pmrep and that was partially behind this ticket. I agree that instance internal ids might cause surprises in some cases (e.g., a particular instance with the same id is different across two runs of the tool) but OTOH they might be a nice shortcut in some corner cases.

I think it's best to move forward with a semi-cautious approach, namely implement 2) from above options first without documenting it initially so that if anything unexpectedly breaks the change can be easily reverted and if no surprises then add a sentence or two documenting it to the related man pages a bit later. And no plans to implement 1) now or later and only consider 3) at some later point if there's a real need for it.

**Comment by natoscott** [comment]
@myllynen can this issue be closed after those recent changes?

**Comment by myllynen** [comment]
I was initially thinking to give this a bit time to make sure no regressions are reported but after reviewing the code again and considering we see full QA pass with the recent changes I think it's ok to move ahead and add QA for these changes and update manual pages according without waiting for a release or two. I'm hoping to make these changes tomorrow or at least this week and will close this issue then. Thanks.

**Comment by myllynen** [comment]
I've pushed commit 9c990b4 which should fully document and QA the recent changes. Closing.
