### ISSUE TITLE
pmieconf error while installing pcp-zeroconf rpm

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1237]
Seen on Fedora 33 VM:

```
# rpm -Uvh /root/pcp.git/pcp-5.3.0/build/rpm/pcp-zeroconf-5.3.0-1.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:pcp-zeroconf-5.3.0-1             ################################# [100%]
pmieconf: error - no group or rule names match "dmthin"
```

Not sure what is causing this. Thanks.

**Comment by natoscott** [comment]
@myllynen the dmthin rules should arrive from the pcp-pmda-dm package, which is a dependency of pcp-zeroconf ... I'm not sure how they could be missing, we always install these files (unconditionally).

**Comment by myllynen** [comment]
This seems to go away if I manually copy _/etc/pcp/pmieconf/dm_ to _/var/lib/pcp/config/pmieconf_ (there was no `dm` dir under _/var/lib/pcp/config/pmieconf_), I'm not sure was that the correct fix or not but hopefully gives a hint about the root cause.

No directly related but when enabling the DM PMDA, I see this if `device-mapper-devel` package was not installed during build time, perhaps there should be a BuildRequires for this?

```
[Tue Apr  6 10:47:49] pmdadm(692635) Warning: built without support for dmstats metrics
```

Thanks.

**Comment by myllynen** [comment]
Also if uninstalling and installing pcp-zeroconf again then the error is not displayed.

**Comment by natoscott** [comment]
> This seems to go away if I manually copy _/etc/pcp/pmieconf/dm_ to _/var/lib/pcp/config/pmieconf_ (there was no `dm` dir under _/var/lib/pcp/config/pmieconf_), I'm not sure was that the correct fix or not but hopefully gives a hint about the root cause.

Yep - we're definitely missing a subdir install there for dm - I've added that to the makefile now.  If you have a /var that is 'special' (using ostree?  or some other reason that we'd lose /var contents that our systemd tmpfiles.d content restores) then I can see how this could've happened.

Let's see if this makefile fix resolves the problem as I think it will - if not, please reopen & add more info.

**Comment by myllynen** [comment]
Unfortunately the issues remains even after rebuilding the packages with the above change, the dm directory is still missing under /var/lib/pcp/config/pmieconf.

**Comment by natoscott** [comment]
@myllynen ok, thanks - will keep digging into it.  What does this report for you...?

```
$ rpm -qf /var/lib/pcp/config/pmieconf/dm
pcp-pmda-dm-5.3.0-1.x86_64
```

**Comment by myllynen** [comment]
With latest git I still see:

```
# rpm -qf /var/lib/pcp/config/pmieconf/dm
pcp-pmda-dm-5.3.0-1.x86_64
# rpm -V pcp-pmda-dm
missing     /var/lib/pcp/config/pmieconf/dm
missing     /var/lib/pcp/config/pmieconf/dm/data_high_util
missing     /var/lib/pcp/config/pmieconf/dm/metadata_high_util
```

To reproduce I'm uninstalling all PCP packages, removing all pcp directories, and installing the PCP packages again.

**Comment by natoscott** [comment]
Re "missing" lines - this is the key I guess, something (?) has deleted those files and directories after the package was installed.  For me, this doesn't happen FWIW and rpm -V reports all is well.

**Comment by myllynen** [comment]
D'oh! The directory was removed by my local "reinstall-pcp" script! I think it was related to some earlier investigation or test and then forgotten. So mea culpa but great that a few fixes were made in the process anyway :) Thanks.
