### ISSUE TITLE
Wish List / Backlog / RFEs (Bugzilla #942)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#124]
On 2013-04-19 22:22:17 -0500, Ken McDonell wrote:

> This is the master bugzilla entry to track wish list items, feature enhancement requests and backlog management for the core PCP functionality.
> 
> Any item for consideration should have its own bugzilla entry and then be related to this entry.  So please do not comments or items to this entry.

On 2013-04-19 22:48:28 -0500, Ken McDonell wrote:

> To add an item to the backlog: create a new bugzilla entry (or use an existing one) for the backlog item, and then update the bugzilla entry for the backlog item setting the _Blocks_ field to 942 (the bug number of _this_ bug, the Wish List master bugzilla entry).
> 
> To remove an item from the backlog (no longer considered useful): update the bugzilla entry for the backlog item and remove 942 from the _Blocks_ field.
> 
> To update the backlog when a work item is completed: update the bugzilla entry for the backlog item and set the _Status_ field to RESOLVED.

**Comment by kmcdonell** [comment]
Dragged across from Bugzilla ... this was an umbrella incident, no real issue here at all.
