### ISSUE TITLE
RFE: Provide proc.psinfo.policy_nm

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1244]
Recent versions of pidstat(1) (see https://www.mankier.com/1/pidstat#-R) report:

```
# pidstat -R -p SELF
Linux 5.11.14-200.fc33.x86_64 (localhost.localdomain) 	2021-04-20 	_x86_64_	(4 CPU)

09:50:21      UID       PID prio policy  Command
09:50:21        0      8292    0 NORMAL  pidstat
```

It would be helpful to have a string value available for process scheduling policy (proc.psinfo.policy_nm) in addition to the numeric value proc.psinfo.policy like there are few other metrics with numeric and string values already (like proc.id.gid and proc.id.gid_nm).

Process scheduling policies are defined in Linux uapi so their definitions should not change unexpectedly:

https://github.com/torvalds/linux/blob/master/include/uapi/linux/sched.h#L112

I don't have a strong opinion whether the string values should be upper or lower case.

Thanks.

**Comment by natoscott** [comment]
I'll add this.  Looks like there's a different convention in the proc.psinfo.* metrics of using an _s suffix for the string-variant metrics, so I'll stick with that.

**Comment by myllynen** [comment]
Thanks for your quick response!
