### ISSUE TITLE
Additional disk metrics for iostat compatibility

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1248]
iostat from sysstat-12.3 provides these metrics:

```
              d_await
                     The  average  time (in milliseconds) for discard requests
                     issued to the device to be served. This includes the time
                     spent by the requests in queue and the time spent servic‐
                     ing them.

              dareq-sz
                     The  average  size (in kilobytes) of the discard requests
                     that were issued to the device.

              f_await
                     The average time (in milliseconds) for flush requests is‐
                     sued  to  the  device to be served.  The block layer com‐
                     bines flush requests and executes at most one at a  time.
                     Thus  flush  operations  could be twice as long: Wait for
                     current flush request, then execute it, then wait for the
                     next one.
```

These would probably correspond to PCP metrics disk.dev.d_await, disk.dev.d_avg_rqsz, and disk.dev.f_await but these are not available (like such metrics are for reads and writes). I don't instantly see how these metrics could be derived from other metrics.

Please consider adding these metrics to PCP so that PCP would cover everything that iostat reports. Thanks.

**Comment by natoscott** [comment]
@myllynen I think these are the disk.dev.discard* and disk.dev.flush* metrics.

**Comment by myllynen** [comment]
Hmm, ok, now I see derived/iostat.conf which defines formulas for e.g. disk.dev.r_await and disk.dev.w_avg_rqsz. So looks like the solution would be to amend derived/iostat.conf with these metrics.

**Comment by myllynen** [comment]
I added these metrics to derived/iostat.conf, looked completely straightforward but if time permits please have a look that all ok.

Thanks.

**Comment by goodwinos** [comment]
> I added these metrics to derived/iostat.conf, looked completely straightforward but if time permits please have a look that all ok.
> 
> Thanks.

Hi Marko, thanks. as the original author of derived/iostat.conf I'll review (tomorrow), but a quick look and it's fine.  cheers
