### ISSUE TITLE
PMDAs should not be shipped without some QA coverage (Bugzilla #948)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#125]
On 2013-04-26 20:49:01 -0500, Ken McDonell wrote:

> This a "master" bug to cover a raft of PMDAs that are currently shipped but with no coverage at all in the PCP QA suite.
> 
> As a matter of principle, _every_ PMDA should have some QA coverage.
> 
> If the PMDA has special co-dependencies (e.g. special hardware, unusual kernel module, concurrent DBMS installation, ...) then it should _still_ have coverage in the PCP QA suite, using the existing "not run" infrastructure to avoid running the associated tests if the co-dependencies are not satisisfied ... this means there is a chance that someone will run the tests somewhere, even if it is outside the common QA processes.

**Comment by kmcdonell** [comment]
Another umbrella incident from Bugzilla ... no real issue here.
