### ISSUE TITLE
Use syslog for logging rather than stderr redirection (Bugzilla #867)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#126]
On 2010-03-11 10:31:20 -0600, Martin Hicks wrote:

> This comment is generally for the daemon processes, but would require major
> rework of the current logging in the PCP libraries in order to continue to allow
> applications to log to stderr or a specified logfile.
> 
> It is very desirable for daemon processes (pmlogger, pmie, pmcd, pmdas) to log
> via syslog.  This would allow for remote syslog logging, advanced filtering for error conditions, and centralized log rotation.

**Comment by natoscott** [comment]
No maintainer plans to work in this area - feel free to send patches though.
