### ISSUE TITLE
pmproxy discovery module callback throttle 

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1283]
pmproxy / libpcp_web discover module needs a throttle when it's ingesting  ("log-tailing") archive data on large pmlogger farms - this is to avoid the single threaded callback processing consuming 100% CPU, starving out the async redis request processing.

The essence of the proposed patch in discovery.c:changed_callback() :
```
+    /*
+     * dynamic callback throttle: at least one second for each monitored
+     * directory or archive, plus an extra second for every million inflight
+     * redis requests (to help clear the backlog).
+     */
+    if ((throttle = n_monitored / 40) < 1)
+       throttle = 1;
+    throttle += pmDiscoverGetInflightRedisRequests(p->module) / 1000000;

```
Scaling experiments with this patch show it's effective in maintaining pmproxy CPU usage around 10% with 100 loggers and yet doesn't introduce any unnecessary ingest latency for libpcp_web clients doing near-live monitoring on small deployments (e.g. with only one pmlogger).  It also dynamically adjusts as the redis inflight backlog grows and shrinks on large deployments, so we get the minimal tolerable latency.

**Comment by andreasgerstmayr** [comment]
> throttle += pmDiscoverGetInflightRedisRequests(p->module) / 1000000;

I suggest keeping the two condition separate, i.e. `if (time(&now) - p->lastcb < throttle || pmDiscoverGetInflightRedisRequests(p->module) > 1000000)`

Adding one second for each million inflight Redis requests doesn't help much. Especially at the start of pmproxy, lots of Redis requests are issued, and if we don't constrain them pmproxy queues them up, requiring multiple GBs of memory (and it might get pmproxy OOM-killed, depending on the amount of spare memory available).

With the above condition, pmproxy uses about 1 GB memory with 100 loggers (also during startup), which is imho an appropriate amount of memory.

**Comment by andreasgerstmayr** [comment]
thinking more about it, can we really just ignore these callbacks? In most cases it will be fine, because we'll get another filesystem event sooner or later (because the PCP archive got modified again).

But what about events which we only get once, for example the creation of a new archive? If we throttle (i.e. ignore) this one, `pmDiscoverTraverse(PM_DISCOVER_FLAGS_NEW, created_callback)` will never be called, and in turn `pmDiscoverMonitor()` will never be called to register the new directory. I think we need to make sure to only throttle existing-archive-changed events. But in that case we can also loose the last archive write before the log rotation and creation of a new archive.

**Comment by goodwinos** [comment]
> > throttle += pmDiscoverGetInflightRedisRequests(p->module) / 1000000;
> 
> I suggest keeping the two condition separate, i.e. `if (time(&now) - p->lastcb < throttle || pmDiscoverGetInflightRedisRequests(p->module) > 1000000)`
> 

ok, have changed the patch to keep them separate, and added an additional conjunct that the PM_DISCOVER_FLAGS_NEW flag isn't set (so we always process the callback for new archives or directories regardless of the throttle or req backlog). THis seems to be working pretty well on scaling3 with 100 loggers, including for daily logroll, and on a single pmlogger system.

regarding whether it's safe to skip callbacks - seems to be. At least no worse than a pmlogger reexec (`killall -USR2 pmlogger` exercises that, with no apparent ill effects or noticeably lost data)

So I'm going to commit the patch - it also updates the lock checking a bit. We can always tweak it if needed.
