### ISSUE TITLE
Makepkgs failing on Debian, pcp2xlsx gets only installed if openpyxl exists

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/pcp#1288]
Building from git fails since some weeks on Debian Buster for me. 
pcp2xlsx is getting built, but not getting installed. 

The system has no openpyxl installed, but apparently pcp2xlsx gets properly build. Modifying src/pcp2xlsx/GNUmakefile as follows fixes the build for me:
`
[..]
include $(BUILDRULES)

install: default
        $(INSTALL) -m 755 $(TARGET).py $(PCP_BIN_DIR)/$(TARGET)
        $(INSTALL) -S $(BASHDIR)/pcp $(BASHDIR)/$(TARGET)
        @$(INSTALL_MAN)

default_pcp: default
[..]
`

**Comment by natoscott** [comment]
@christianhorn can you paste ./configure output from that build please?  thanks.

**Comment by christianhorn** [comment]
[20210518_configure_out_plain.txt](https://github.com/performancecopilot/pcp/files/6498876/20210518_configure_out_plain.txt)

**Comment by natoscott** [comment]
Thanks!  This is the relevant snippet ...

| checking for Python module openpyxl... no

... and we lack correct handling of this in the Debian packaging I see now.  I'll push in a fix soon (probably tomorrow), thanks!

**Comment by christianhorn** [comment]
Works nicely, tnx!
