### ISSUE TITLE
Revise env vars vs conf file priorities for tools

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1290]
Modern applications override configuration file values with corresponding environment variable values. However, pmlogger and pmrep et al prioritize configuration file over environment variable, see their manual pages.

PCP v6 would be a good opportunity to review existing tools and their env vars vs conf file priorities, unify them across all tools, and change priorities if deemed appropriate.

I checked briefly tools that might be affected by this, so far I've come across only pmlogger and pmrep (et al). There might be one or two more but so far the scope seems to be rather limited, not sure would some related documentation or API changes be warranted.

**Comment by myllynen** [comment]
Refreshing my memory and testing a bit I see:

```
$ cat test.conf    
[test]
samples = 2
mem.util.free = ,,,,
$ PCP_SAMPLES=3 pmrep -c ./test.conf :test
  m.u.free
     Kbyte
   5067960
   5061020
   5072864
$ 
```

So will need to review and unify, and possibly change priorities. But since this has been like this for a long time I wouldn't want to change anything before PCP v6 which is in the horizon already.

**Comment by kmcdonell** [comment]
There was discussion (in private email) about this issue back in Jan 2022 (!) and the consensus was that despite the desirability of making things consistent, the breakage that might result for established installations with a change in semantics meant the potential disruption outweighs the gains.

So I'm closing this issue.
