### ISSUE TITLE
Auto-start redis.service in pmproxy.service

### ISSUE THREAD

**Issue by martinpitt** [performancecopilot/pcp#1296]
I am trying to show PCP metrics in Grafana. The documented way seem to be to enable pmproxy on the client side, and [the Grafana PCP plugin](https://grafana-pcp.readthedocs.io/en/latest/) on the Grafana side. This works fine by and large, but there is one step that seems a bit non-obvious: For `systemctl enable --now pmproxy` to actually work, you currently also need `systemctl enable --now redis`.

This is not part of the [plugin's Quickstart](https://grafana-pcp.readthedocs.io/en/latest/quickstart.html) (only in the [PCP redis section](https://grafana-pcp.readthedocs.io/en/latest/datasources/redis.html)), nor is it mentioned at all on the [manpage](https://linux.die.net/man/1/pmproxy).

But moreover, as pmproxy seems to pretty much depend on redis anyway, as otherwise queries hang forever (took me quite a while to figure this out, but it's already reported in #1134), could this just happen automatically?

IMHO the most elegant way would be to add

    Wants=redis.service
    After=redis.service

into pmproxy.service's `[Unit]` section. Then this will gracefully handle the case that redis is not installed at all, but start it if available ("unbreak my setup").

This also avoids a really difficult decision for both humands and UIs like Cockpit when you disable pmproxy.service again -- should you disable redis as well? It's a shared service, so it's not clear whether it was previously enabled only for pmproxy, or for some other service as well. Hence it would be best to not statically enable/disable it in the first place, but treat this as a dependency.

**Comment by martinpitt** [comment]
The most important question here is: is there a real-life use case where someone would use pmproxy *without* redis? I admittedly only looked at that case, I don't know if it's useful for anything else.

**Comment by natoscott** [comment]
@martinpitt yes there definitely are such cases - the grafana-pcp 'PCP Vector' and 'PCP bpftrace' datasources operate entirely without the need for Redis, accessing live data from PCP (pmcd) only.

**Comment by natoscott** [comment]
Also, the OpenMetrics export mechanism offered by pmproxy does not use Redis, nor does the PCP protocol proxying functionality ... so, there are quite a few deployment scenarios where Redis is not required.

**Comment by martinpitt** [comment]
Right, I'm aware of  the Vector/bpftrace data sources, but I thought they wouldn't use pmproxy? At least the documentation does not mention this at all.

However, I just saw that in principle one can configure pmproxy to use a Redis on a remote host.

Still a bit sad that this does not just work out of the box..

Thanks!

**Comment by christianhorn** [comment]
If redis is not active in the pcp/pmproxy/redis/grafana chain, you would first see from Grafana reporting an error from pmproxy, right? Maybe we could customize that error and hint at "is redis running at all?".

**Comment by natoscott** [comment]
> Right, I'm aware of the Vector/bpftrace data sources, but I thought they wouldn't use pmproxy?

pmproxy provides all REST API services for PCP.

> At least the documentation does not mention this at all.

The REST API docs cover this - there's the PMWEBAPI(3) man page and (same content in) https://pcp.readthedocs.io/en/latest/api/
 
You'll see these docs are divided into sections which map to the various groups of REST functionality offered by pmproxy.  The live metrics services are below the /pmapi and /metrics endpoints, whereas the Redis-based services are below /series.

**Comment by martinpitt** [comment]
Ack, thanks!

For a Cockpit UI that sets up a Grafana client (on-demand  package install of redis; enable pmproxy + redis; open firewalld service), I am wondering what to do for redis. Statically enabling it would be okay, but it's unclear what to do with redis when *disabling*  pmproxy, as there is no record whether redis is only being used by pmproxy. Hence I was thinking of adding/removing an `/etc/systemd/system/pmproxy.wants.d/redis.service` symlink, which is similar in spirit to my idea above, but in a more controlled fashion.

What do you think about that?

**Comment by andreasgerstmayr** [comment]
> For a Cockpit UI that sets up a Grafana client (on-demand package install of redis; enable pmproxy + redis; open firewalld service), I am wondering what to do for redis. Statically enabling it would be okay, but it's unclear what to do with redis when _disabling_ pmproxy, as there is no record whether redis is only being used by pmproxy. Hence I was thinking of adding/removing an `/etc/systemd/system/pmproxy.wants.d/redis.service` symlink, which is similar in spirit to my idea above, but in a more controlled fashion.
>
> What do you think about that?

There could still be the case that a user:
* does set up pmproxy+Redis through Cockpit
* at some point uses the same Redis instance for another application
* decides that he/she doesn't need pmproxy/Grafana anymore, disables it in Cockpit
* now "suddenly" Redis is not started anymore and the other application cannot connect to Redis

But imho you cannot guard against that in a proper way, except just leaving Redis enabled once it's enabled, or having a dedicated Redis instance only for Cockpit.

**Comment by martinpitt** [comment]
> at some point uses the same Redis instance for another application

Yes, and just like in this proposal that other application should also declare a dependency. Hence my question here whether this would be appropriate.

> except just leaving Redis enabled once it's enabled

Right, that would be the expensive and unfriendly, but safe fallback in the absence of proper dependencies.

> having a dedicated Redis instance only for Cockpit.

There is no such thing. Cockpit's UI helps you with configuring the services (just like it helps you to format disks or set the host  name or create a libvirt VM or what not), but none of these things are cockpit specific in any way. It is "the" pmproxy and "the" PCP.

Thanks!
