### ISSUE TITLE
Add load level pmie rule to /config/pmieconf (Bugzilla #897)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#130]
On 2010-08-31 14:41:39 -0500, David Wright wrote:

> Load level rule is not in pmieconf directory and lost when using
> pmieconf. Can we get the rule template back?

On 2010-12-06 15:39:18 -0600, Ken McDonell wrote:

> Created [attachment](https://gist.github.com/pcpemail/ce46246930b6f5f7cf15df728c77c0a1)
> Current cpu/load_average pmieconf file
> 
> We're including this file as /var/lib/pcp/config/pmieconf/cpu/load_average.
> 
> Dave is this what you're expecting?  If not, I need some further guidance on what sort of "load level" rule you are expecting.

**Comment by natoscott** [comment]
Inactive for a long time, and no response to Kens question - closing, but feel free to provide more info.
