### ISSUE TITLE
Consider name-spacing PCP commands

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1309]
There are few PCP commands and man pages that are very generic and don't have the `pm` prefix, perhaps most notably `newhelp` and `chkhelp`. It might be worth adding the `pm` prefix to these commands as well so that especially the manual pages would be under the typical `pm` namespace. If this would be done, PCP v6 might be suitable opportunity for this. Thanks.

**Comment by kmcdonell** [comment]
Firstly, thanks to Marko for looking at things with fresh eyes ... bit rot and inconsistency sneak in over time in small increments and are often overlooked.

But in this case, I'm not sure there is any real improvement here.  The list of executables **not** starting with ```pm``` is much longer:
```collectl2pcp, dbpmda, dstat, ganglia2pcp, genpmda, iostat2pcp, mrtg2pcp, pcp, pcp2csv, pcp2elasticsearch, pcp2graphite, pcp2influxdb, pcp2json, pcp2spark, pcp2xlsx, pcp2xml, pcp2zabbix, sar2pcp, sheet2pcp, chkhelp, discover/pcp-kube-pods, find-filter, install-sh, mkaf, newhelp, pcp-atop, pcp-atopsar, pcp-dmcache, pcp-dstat, pcp-free, pcp-htop, pcp-iostat, pcp-ipcs, pcp-lvmcache, pcp-mpstat, pcp-numastat, pcp-pidstat, pcp-python, pcp-shping, pcp-ss, pcp-summary, pcp-tapestat, pcp-uptime, pcp-verify, pcp-vmstat and telnet-probe```

It makes little sense to shoe-horn all of these into a ```pm``` prefix, e.g. we'd have to leave pcp and the pcp-* ones.  Similarly the pcp2* and *2pcp ones.  And dstat has to remain.

What remains is:
```dbpmda, genpmda, chkhelp, discover/pcp-kube-pods, find-filter, install-sh, mkaf, newhelp and telnet-probe```

I think I'd argue that this list is **not** of interest to the average PCP end-user (they are either PCP developer-only and/or used internally in other PCP scripts).  And in the specific case of ```newhelp``` and ```chkhelp```, only a PMDA developer would ever have reason to run ```newhelp``` and only a small subset of them (possibly me and a couple of others) would have ever run ```chkhelp```, and many PMDA developers using the copy-and-paste development model would never run either of these commands.

If that is the case then there is no real advantage in either (a) making things incompatible, or (b) carrying both old and new names forward.

I'll leave it to @myllynen to either close the issue or add further arguments that would justify going down this path.

**Comment by myllynen** [comment]
Thanks for looking into this! I should have mentioned that name-spacing would also be helpful for other projects, something like `chkhelp` help does not identify the tool in anyway and is in "global namespace of commands" (no such thing in reality but you see what I mean). Anyway, I agree that this might be workf for little or no gain and since you already did what was requested, i.e., considered, I'll go ahead and close this. Thanks.
