### ISSUE TITLE
Rework PDU assembly code (Bugzilla #944)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#132]
On 2013-04-19 23:02:51 -0500, Ken McDonell wrote:

> The current logic below __pmGetPDU() does include possible blocking when the data available is less than the (known after the PDU header) length of the PDU.
> 
> Mostly this works just fine, as the remainder of the PDU will be available "real soon now" (tm), but it does expose a possible DOS attack from a malicious client for servers processes that read PDUs from arbitrary clients (pmcd and pmproxy in particular).
> 
> To fix this requires moving PDU assembly up the food chain and the app mainline taking more of an event-driven view of I/O.  See the comment about "I/O routines transformed to continuation-passing style" in libpcp/src/pdu.c.
> 
> This approach needs to be an alternative to the classical approach, as we'd expect most PCP apps to continue to work without mainline changes and no DOS exposure from this possible attack vector.

**Comment by kmcdonell** [comment]
Event-driven I/O is not going to happen here.  And we have a dead-hand timer to thwart the most obvious DOS attack vector.
I'm going to close this one ... please reopen with additional evidence/arguments if you disagree.

**Comment by natoscott** [comment]
@kmcdonell FWIW this is being done in pmproxy.  I don't see it happening in pmcd though, agreed.

**Comment by fche** [comment]
Agreed that it's unlikely we will get the time to fix this.   The presence of this DoS vector makes it unsafe to expose a pmcd instance raw to an untrusted network, but that's already the status quo.
