### ISSUE TITLE
copying pmlogger archives to the grafana host does not show any data

### ISSUE THREAD

**Issue by NiklasMRL** [performancecopilot/pcp#1322]
**Data source:** PCP Redis and copies of pmlogger archives from foreign hosts (from at least the last day)

**Describe the bug**
copying pmlogger archives from foreign hosts (that run pmcd/pmlogger only locally) do not load automatically in grafana.
Using pmseries --load /var/log/pmlogger/hostname/ will show the host in the redis host overview, but won t display the data.

strangely the pcp data of the grafana host are only displayed for the time since pmlogger was lastly started, older archives are not displayed either.

**To Reproduce**
1. copy files to the grafana host
2. see that there s no historical data

**Expected behavior**
Copied pmlogger archives should show the host in pcp redis host overview and display data correctly

**Screenshots**
![grafana_host_mplogger](https://user-images.githubusercontent.com/84380600/118631044-6b39de80-b7cf-11eb-92a7-eb9f07046a68.PNG)

![foreign_host](https://user-images.githubusercontent.com/84380600/118631144-7f7ddb80-b7cf-11eb-90cc-e90193d3c84c.PNG)

**Versions (please complete the following information):**
 Standard version included with 8.3
 - Performance Co-Pilot: 5.1.1-4
 - Grafana: 6.7.4-3
 - grafana-pcp: 2.0.2-3
- Redis (if applicable): 5.0.3-2

**Additional context**
i checked that data is present in the copied pmlogger archives by using:
 pmdumplog /var/log/pcp/pmlogger/docker01/20210517.0.xz kernel.all.load

**Comment by goodwinos** [comment]
Closing - see documentation updates in BZ#2026726 and upstream commit:

```
commit c40983b44587027f8069df15690abe3e78cf7a34
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Fri Feb 11 12:09:50 2022 +1100

    docs: improve pmproxy --timeseries and pmseries --load documentation

```
