### ISSUE TITLE
libpcp: pmGetHighResArchiveLabel()

### ISSUE THREAD

**Issue by natoscott** [performancecopilot/pcp#1372]
Need pmHighResResult as arg (typical use case is pmFetch (becomes pmFetchHighRes), fiddle with pmValue in pmResult (becomes fiddle with pmValue in pmHighResResult) and pmStore (becomes pmStoreHighRes)

**Comment by kmcdonell** [comment]
I'm not sure we really need this.  The V2-V3 differences are all factored away behind __pmLogLoadLabel() which is callable for libpcp.h users, not pmapi.h users.  The returned __pmLogLabel data structure contains the start time as a __pmTimestamp, so Y2038 safe and nsec precision.
Potential users of pmGetHighResArchiveLabel() like pmdumplog, pmlogcheck, pmlogextract, pmloglabel and pmlogsize are already using __pmLogLoadLabel().
If we do need to add pmGetHighResArchiveLabel() to the PMAPI, then it is one more data structures with a struct timespec field and a thin shim around __pmLogLoadLabel().

**Comment by natoscott** [comment]
There's two aspects to this that led me to thinking we should add this at the general PMAPI level.

- it'd be most excellent if at the end of this exercise, we can write client tools using just one structure (and common units) to represent time.  So, where people choose to use struct timespec and nanosecond precision, I'd like to see all functionality available to such tools, and not see a need for code to convert between timeval / timespec for this special case.  But, yeah, this is a relatively uncommon API so maybe this is not good enough a reason in this case.

- we need an interface to expose the zoneinfo to client tools (and probably the enabled/disabled feature bits too) as we do with the original squashed timezone, in case people want to use this in a user interface or some other situation outside of libpcp.  If we accept we need that, then we may as well export it via a new HighRes API I guess.

**Comment by kmcdonell** [comment]
OK, but this means we end up with THREE variants of the pmLogLabel data structure (sigh).  I thought about possibly prompting __pmLogLabel to the PMAPI, but it would need struct timespec and we'd then need {struct timespec} <-> __pmTimestamp conversions in all the places where we use __pmLogLabel at the moment, or perhaps change to struct timespec internally (this would mean redoing a lot of what's been done already, along with changes on the archive i/o paths to convert between tv_nsec (64-bit) and nsec (32-bit)).
Not sure there is an elegant option here, but I think I'd vote for THREE pmLogLabel data structures (2 @ PMAPI + 1 internal) as the least evil of the options.

**Comment by natoscott** [comment]
Agreed - conceptually similar to the pmResult, pmHighResResult, __pmResult situation I guess, but much simpler this time fortunately.
