### ISSUE TITLE
libpcp, pmlogger, pmlc: new pmlc protocol version: pmResult -> pmHighResResult in LogControl send and recv, also 3 pmTimevals in __pmLoggerStatus -> __pmTimestamp

### ISSUE THREAD

**Issue by natoscott** [performancecopilot/pcp#1379]

**Comment by kmcdonell** [comment]
This work is done via a series of pmlc, pmlogger and libpcp commits.

1. pmResult left as is ... pmlc and pmlogger exchange a pmResult as part of the PDU_LOG_CONTROL and PDU_RESULT interchange, but neither of them uses the timestamp field to convey any information, so there is no reason to change to pmHighResResult
2. __pmLoggerStatus converted internally to __pmTimestamp
3. The current V2 protocol between pmlc-pmlogger converts a __pmLoggerStatus to a PDU_LOG_STATUS message with embedded pmTimevals
4. If pmlc and pmlogger negotiate V3 protocol, then the PDU_LOG_STATUS message contains embedded __pmTimestamps

A libpcp bug was found in the pmlc-pmlogger protocol version autonegotiation that is fixed (down-rev pmlc cannot connect to an up-rev pmlogger), so a new -I/--pmlc-ipc-version option has been added to pmlogger to force it to use V2 and not try to negotiate V3, should this be needed.
