### ISSUE TITLE
Missing QA for process PMDA (Bugzilla #957)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#139]
On 2013-04-27 16:22:11 -0500, Ken McDonell wrote:

> There are no QA tests at all in src/pcp/qa for the process PMDA.

**Comment by kmcdonell** [comment]
To quote the comment in the source code's GNUmakefile for the process PMDA:
```
# This PMDA is only valid on platforms with a procfs
# It is also superceded by the cgroup functionality on Linux
# thus has not been built for some time, for reference only.
```
So no QA for this puppy.
