### ISSUE TITLE
Add QA for additional PDU types

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#1393]
The  __pmTimestamp/V3 archive changes will trigger a bunch of new PDU types to mirror some existing PDU types but with higher precision timestamps.
At least these QA apps (and their associated test cases) will either need to be expanded, or parallel V3 versions:
- pdu-server.c
- pducheck.c
- pducrash.c

**Comment by goodwinos** [comment]
Please note I have new test qa/1828 in my upstream scsi-multipath branch (just to avoid annoying new test clashes!)

**Comment by kmcdonell** [comment]
Turns out there are not that many new PDU types (there are more new record types for V3 archives, but these are tested in places other than pdu-server, pducrash and pducheck.

The newly added qa/check-pdu-coverage script checks that all PDU types defined in the PCP headers are indeed checked in pdu-server, pducrash and pducheck, so this issue is "done".
