### ISSUE TITLE
review and tweak pmlogconf config files 

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1436]
Review pmlogconf config files to (a) avoid duplicate metrics being logged, and (b) reference leaf pmns names rather than non-leaves where that is feasible. This may help reduce pmlogger config parsing PDU traffic, which can be problematic over high latency networks, though issue #1433 may mitigate this somewhat.

On a typical install (as reported by Kenj), there appear to be 70-odd metric names duplicated in a default set of 1000+ metric names. So there is scope for a bit of a review and cleanup.

Related BZ#1973833 - [RFE] Improve remote pmlogger over slow network connections

**Comment by natoscott** [comment]
pmlogger was improved to drop duplicated and the startup sequence was substantially optimized in terms of PDU use too.
