### ISSUE TITLE
pmlogger: Incorrect ownership for /usr/lib/systemd/system/pmlogger.service.d ?

### ISSUE THREAD

**Issue by SunilMohanAdapa** [performancecopilot/pcp#1437]
In a [recent commit](
https://github.com/performancecopilot/pcp/blob/523c40b750a72f8b683270a59b2deb410436fa3a/src/pmlogger/GNUmakefile#L61), it looks like the ownership for /usr/lib/systemd/system/pmlogger.service.d is being set to PCP_USER and PCP_GROUP. It is unusual for files under /usr to be owned by anything but root:root. This is likely a mistake, feel free to close the issue otherwise.

CC: @goodwinos .

**Comment by goodwinos** [comment]
thanks yes you are correct, I'll fix that
