### ISSUE TITLE
pmlc / pmlogger IPC protocol failure, timeouts and pmlc exit status

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#1439]
after pmlogger_check launches a pmlogger it uses pmlc to wait for it to get started :

 ```
 554             if echo "connect $1" | pmlc 2>&1 | grep "Unable to connect" >/dev/null
 555             then
 556                 :
 557             else
 558                 $VERBOSE && echo " done"
 559                 return 0
 560             fi

```

This has several issues. If pmlc returns anything other than the grep'ed output, it is assumed to have worked. The PMLOGGER_REQUEST_TIMEOUT envar is not set, so this could hang. pmlc itself does not set exit status (always succeeds, even if it failed and stdin is not a tty), so we can't rely on that either.

In addition - there is a long delay between when pmlogger reports it has parsed it's config (which itself is too long on high latency networks but that is being delt with elsewhere) to when it is listening on it's pmlc control port. I've observed 30 to 40 seconds commonly, which when combined with the parse time is enough to trip the pmlogger systemd service start timeout of 120 seconds. Things go downhill from there ...

Finally, there is some kind of protocol error between pmlc and pmlogger running on the same host (so no up/downrev version concerns). Just before finally responding on it's control port, pmlogger reports IPC protocol failures in it's log, e.g.

```
Log for pmlogger on shack started Wed Oct  6 18:37:01 2021

preprocessor cmd: /usr/libexec/pcp/bin/pmcpp -rs ./kilcunda.config -I /var/lib/pcp/config/pmlogger
Config parsed
Starting logger for host "kilcunda" via "kilcunda"
Archive basename: 20211006.18.37
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure
error sending connection ACK to client: IPC protocol failure

```

I've noted these errors only occur when pmlogger is connected to a remote pmcd over a network with higher than local subnet latency (e.g. local VMs work fine). The errors in pmlogger.log are reported rapidly right before the pmlc connect command in pmlogger_check finally returns - which then succeeds provided the systemd timeout has been tweaked. If the service start timeout hasn't been increased, systemd kills it all off and retries.

**Comment by myllynen** [comment]
For reference, earlier related issues around pmlc are https://github.com/performancecopilot/pcp/issues/376 and https://github.com/performancecopilot/pcp/issues/378.

**Comment by kmcdonell** [comment]
Some progress, it appears the "error sending connection" messages (this is a new diag with -Dpdu) in pmlogger.log have a reason ...
```
__pmXmitPDU: socket _pmSend() result -1 != 16
__pmXmitPDU: PM_ERR_IPC because __pmSocketClosed() (maybe error 104 from oserror())
error sending connection ACK to client: IPC protocol failure
```
but as yet I have no clue why pmlc or pmlogger would be triggering ECONNRESET (errno == 104)

**Comment by kmcdonell** [comment]
OK, I think I understand what's happening now.

The environment setting PMLOGGER_REQUEST_TIMEOUT=2 **is** in play.

pmlogger_check is running pmlc repeatedly, each one tries a connect to pmlogger, but if pmlogger is still parsing the config file, pmlc times out after 2 seconds, and closes the connection.  On the pmlc side I'm seeing
```
__pmConnectLogger: timeout (after 2 secs)
Unable to connect to pmlogger on port 4331 at local:: Timeout, closed connection to the pmlogger instance

```

At the pmlogger end, it finishes parsing the config file, and then has a backlog of un-accepted connection requests from pmlc processes, which it accepts and then the first read fails because the socket has been closed at the pmlc end and pmlc has exited.

I am sure we can do a better job of the socket management here, but there is no functional failure I can see.

All of this is triggered by the longer time to parse pmlogger's config file, especially when deployed in environments with a slower connection between pmlogger and pmcd, coupled with the growth in the size of the default pmlogger config file over time.

As you said at the beginning, the pmlogger config file parsing speed up is work being done outside the scope of this issue.

**Comment by goodwinos** [comment]
> And the first "problem" is a non-problem I believe, as just ahead of the pmlc call in pmlogger_check, there is this snippet
> 
> ```
> [ -z "$PMLOGGER_REQUEST_TIMEOUT" ] && export PMLOGGER_REQUEST_TIMEOUT=2
> ```
> 
> and this explicitly sets the environment var unless it was already set in the environment.

ah yes correct, thanks. I wonder if the pmlogger_daily version of this (using a 'status' command instead of 'connect') may be more robust?

```
                    while true
                    do
                        # pmlc may race with pmlogger starting up here - a timeout is required
                        # to avoid pmlc blocking forever and hanging pmlogger_daily. RHBZ#1892326
                        [ -z "$PMLOGGER_REQUEST_TIMEOUT" ] && export PMLOGGER_REQUEST_TIMEOUT=2
                        echo status | pmlc $pid >$tmp/out 2>&1
                        if egrep "Connection refused|Transport endpoint is not connected|Timeout, closed connection" <$tmp/out >/dev/null
                        then
                            [ $i -eq 20 ] && break
                            i=`expr $i + 1`
                            sleep 1
                        else
                            break
                        fi
                    done
```

Anyway, maybe the simpler pmlogger_check version is not broken and so we shouldn't try and fix it.

**Comment by goodwinos** [comment]
> ```
> __pmConnectLogger: timeout (after 2 secs)
> Unable to connect to pmlogger on port 4331 at local:: Timeout, closed connection to the pmlogger instance
> ```
> 
> At the pmlogger end, it finishes parsing the config file, and then has a backlog of un-accepted connection requests from pmlc processes, which it accepts and then the first read fails because the socket has been closed at the pmlc end and pmlc has exited.

So it's likely the "error sending connection ACK to client: IPC protocol failure" messages in pmlogger.log are benign - it's just processing the backlog of pmlc connection attempts. If so perhaps we should not log them by default because they will scare users unnecessarily.

**Comment by kmcdonell** [comment]
I am pretty sure this issue is done with ... the communication between pmlc, pmlogger and pmlogger_check is as robust as I think we can make it, and there have been no recent sightings of "problems" in this area across the QA Farm and the CI QA infrastructure.
