### ISSUE TITLE
pmlogrewrite does not cull indom when no metric uses the indom (Bugzilla #978)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#148]
On 2013-06-27 19:18:01 -0500, Ken McDonell wrote:

> Various config file changes like
> metric foo { delete }
> or
> metric foo { indom -> 123.456 }
> have the effect of reducing the number of references to an indom in the archive ... if the number of references goes to zero, the indom should be culled from the metadata file.  This is not happening.
> 
> To understand why this is a problem, consider an archive with proc.\* metrics included by mistake ... this produces a huge metadata file that cannot be shrunk by pmlogrewrite, even if the proc.\* metrics are all deleted.

**Comment by kmcdonell** [comment]
This work was completed sometime ago.
The relevant commits are: 7b3609ecd, 3fb802862, b42f7e7f0 and 3b4ecfbb0
