### ISSUE TITLE
Multiple network addresses and check-vm

### ISSUE THREAD

**Issue by rvernica** [performancecopilot/pcp#15]
Hi,

I am trying to compile version `3.10.4` from Git. I get the following error during `check-vm`:
```
Warning: ... (127.0.1.1) not associated with a network interface
_getnetworkaddr: cannot handle multiple network addresses:
....78.7.203  Bcast:....78.7.255 255.255.252.0
192.168.7.2  Bcast:192.168.7.3 255.255.255.252
```
I have indeed two network interfaces on the device, but it seems that `pmcd` could be configured to a specific network interface if multiple interfaces are available. Is this an issue with `check-vm`?

Also, by looking at the `check-vm`, it seem that my `255.255.252.0` network mask won't be supported anyway https://github.com/performancecopilot/pcp/blob/master/qa/admin/check-vm#L76

Is this a real problem or `check-vm` requires just a little fixing? Thanks!

**Comment by kmcdonell** [comment]
Please just ignore this warning.
It only applies if you want to run the PCP QA where in some places we need to construct IP addr masks to check permission and access control services.
PCP in production use provides full support for multiple network interfaces and the daemons (pmcd in particular) can be configured to listen on some or all of the available network interfaces.
