### ISSUE TITLE
pmlc security (Bugzilla #981)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#150]
On 2013-07-12 15:11:28 -0500, Frank Ch. Eigler wrote:

> As of current git, any user on the local network can talk to a pmlogger instance's control channel (tcp port 4330 or elsewhere, helpfully supplied by the local pmcd.pmlogger.\* metrics).  This is an invitation for a DoS or worse.  pmlogger & pmlc (if the latter is still needed/helpful) should talk thorugh a secure channel such as a AF_UNIX socket in a protected directory.

On 2013-07-12 16:28:43 -0500, Ken McDonell wrote:

> We I (for one) use pmlc on one machine to interrogate (and sometimes control) pmlogger on another machine.
> 
> There are a number of use cases where this makes sense:
> 1. checking on the internal status of a remote pmlogger
> 2. the pmie -> alarm -> add metrics to be logged for a short time pattern that is really useful
> 
> Using AF_UNIX would stop any distributed use of pmlc.
> 
> There is already an access control clause available in the pmlogger configuration files, and I think Nathan's recent work on making a better fist of creating default pmlogger configuration files included turning off remote pmlc access to change the pmlogger config (stops my 2. above, but allows 1.).
> 
> I'd consider making this more restrictive (even a default opt-out behaviour from pmlogger if needs be) before preventing the channel from being available if required for remote operations.
> 
> It does not help Frank's concerns much, but pmlogger is no more of a DOS attack vector than pmcd is!  Based on lots and lots of experience, both tools are likely to be blocked at the corporate firewall and offered relatively generous access control for use behind the firewall.

On 2013-07-12 17:32:31 -0500, Frank Ch. Eigler wrote:

> > We I (for one) use pmlc on one machine to interrogate (and sometimes
> > control) pmlogger on another machine.
> 
> OK.  (Have you considered perhaps going through pmcd to talk to a pmlogger?
> That way we get networking & security.)
> 
> > There is already an access control clause available in the pmlogger
> > configuration files, and I think Nathan's recent work on making a better
> > fist of creating default pmlogger configuration files included turning off
> > remote pmlc access to change the pmlogger config (stops my 2. above, but
> > allows 1.).
> 
> For what it's worth, even unauthenticated localhost access does not fare
> much better from a security point-of-view.
> 
> > It does not help Frank's concerns much, but pmlogger is no more of a DOS
> > attack vector than pmcd is!
> 
> Except that the data stored by pmlogger can be manipulated by unauthorized
> pmlc usage (whereas pmcd is on the whole read-only), so that makes the
> pmlogger archives unreliable as a record of what happened.

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here (note the issue writeup is quite out of date though).
