### ISSUE TITLE
Ubuntu bionic systemd failed to parse service type exec

### ISSUE THREAD

**Issue by jasonk000** [performancecopilot/pcp#1514]
Bionic packages appear to have been built with incorrect systemd version, which is leading to a small issue when deployed
```
(nfsuper) ~ $ sudo journalctl | grep 'service type'
Dec 15 19:34:31 ubuntu systemd[1]: /lib/systemd/system/pmlogger_farm_check.service:7: Failed to parse service type, ignoring: exec
Dec 15 19:34:31 ubuntu systemd[1]: /lib/systemd/system/pmie_farm_check.service:7: Failed to parse service type, ignoring: exec
```

This change was introduced in https://github.com/performancecopilot/pcp/pull/1391/files .

The `configure` script seems OK, as I get the following on a fresh bionic instance:
```
test jkoch-dev-v000 us-east-1 i-0cc0c77538aa63a27
(nfsuper) ~/pcp $ systemd --version  |grep systemd
systemd 237

(nfsuper) ~/pcp $ ./configure 

....

(nfsuper) ~/pcp $ cat config.log | grep sd_service_type
sd_service_type='simple'
```

However, when I download [the binary package](https://performancecopilot.jfrog.io/ui/repos/tree/General/pcp-deb-release%2Fubuntu%2F18.04%2Famd64%2Fpcp%2Fpcp_5.3.5-1_amd64.deb) and extract its contents, I can see it specifes `Type=exec`, which is not supported by systemd on bionic.

Confirmed ubuntu systemd version is listed as 237.
- [Bionic systemd package details](https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=systemd) list 237
- [Bionic-updates systemd package details](https://packages.ubuntu.com/search?suite=bionic-updates&searchon=names&keywords=systemd) list 237

Putting all this together indicates to me that probably the build script is correct, but it is being executed on a host with systemd >= 239.

**Comment by andreasgerstmayr** [comment]
These two services use a hardcoded `Type=exec` and don't use the `sd_service_type` variable:
https://github.com/performancecopilot/pcp/blob/5.3.5/src/pmlogger/pmlogger_farm_check.service.in
https://github.com/performancecopilot/pcp/blob/5.3.5/src/pmie/pmie_farm_check.service.in

@natoscott do you recall any requirement for this? Can it just be replaced with `@SD_SERVICE_TYPE@` (and the `GNUmakefile` updated appropriately), like in the other services files?

**Comment by natoscott** [comment]
@andreasgerstmayr I think this is an oversight - I'll fix it up.

**Comment by andreasgerstmayr** [comment]
Thanks @natoscott for the fix!
I've verified that with the latest build (https://github.com/performancecopilot/pcp/actions/runs/1746780489, build-ubuntu1804-container) there is no systemd unit with `Type=exec` anymore.
