### ISSUE TITLE
pmcd should not permanently give up on tardy pmdas (Bugzilla #1036)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#152]
On 2013-11-18 14:38:26 -0600, Frank Ch. Eigler wrote:

> It can happen for benevolent reasons that a PMDA can't procure
> answers to a query relayed by PMCD for more than _pmcd_timeout.
> 
> Some transient kernel business could lock up /proc/$pid/FILE for
> a few seconds.  A burst of I/O could knock out access to a pmda
> input log file awhile.  A pmda request may contend with application-level
> locking over some shared files.  Should any of these happen, pmcd
> shuns the pmda for the rest of its own lifetime.
> 
> It would be desirable not to overreact so badly.  PMCD could impose a
> timeout on requests, and notify clients.  But it should be willing
> to exchange further messages with the slow PMDAs, once their in-progress
> work finishes up and normal response times return.  This is especially
> important considering the absence of a capability to restart PMDAs on
> demand (which, if overdone, could make a busy system's situation
> worse).

On 2013-11-18 18:50:53 -0600, Nathan Scott wrote:

> So, my 2c - as discussed on IRC, I don't really think of this as improving the situation.  PMDA tardiness is a domain-specific problem, and to my mind tackling it (as best one can, its not generally solvable & ultimately practical tradeoffs end up being made) is thus best left to the individual PMDAs - IMO.  It'd also add more code to pmcd, for what I feel is an error/corner case, which also adds to my reluctance.
> 
> Finally, it feels like we'd be taking a stance of being more accepting of mediocrity (these delays reduce the quality/accuracy of the data we export) - if we are to add code, I'd prefer it to be along the lines of helping to find root causes of those latency problems.  Perhaps timing mechanisms and new pmcd metrics to help identify those PMDAs which are suffering latency spikes.  Even if timeouts are not reached, where pmcd is seen to "overreact", those PMDAs are still contributing to overall reduction of quality in terms of value/timestamp accuracy.
> 
> Also as discussed on IRC, we could implement a scheme where pmie is used to trigger restarts on those PMDAs that are timed out, using pmcd.agent.status.  Counter-point being: pmie runs unprivileged, thus it can only sighup and not restart pmcd (which means root/non-pcp PMDAs get no love).  Counter-counter-point: a scheme where pmie touches a file in a safe place (probably not a world-writable-sticky-bit set directory), could be checked by a trivial root cronjob and restarted thusly.  Pretty horrifying, but then so is being accepting of PMDA tardiness IMO. :)
> 
> In other news, I wonder if we should consider adding pmcd.agent.uid metrics to export the user account identifier under which each PMDA is running?

On 2013-11-19 14:44:51 -0600, Frank Ch. Eigler wrote:

> (In reply to comment # 1)
> 
> > So, my 2c - as discussed on IRC, I don't really think of this as improving
> > the situation.  PMDA tardiness is a domain-specific problem, and to my mind
> > tackling it [there is better...]
> 
> Not necessarily.  As we discussed, momentary system overload (whether
> deliberately induced by an attacker, or accidental) can affect all PMDAs.
> So can a VM or power suspend/resume.  So can systemwide clock jumps.  So
> can some administrator's misguided debugging activity.
> 
> > Finally, it feels like we'd be taking a stance of being more accepting of
> > mediocrity 
> 
> I suspect a lot of your concerns come from here, but IMHO it is a separate
> subject.  The issue is not whether to whether to shorten or lengthen
> timeouts to a PMAPI client; the current default five seconds seems too
> long for that, if anything.  The issue is how to handle the occasional
> excursion beyond the timeout: how to optimally _recover_.
> 
> > Perhaps timing mechanisms and
> > new pmcd metrics to help identify those PMDAs which are suffering latency
> > spikes.  Even if timeouts are not reached, where pmcd is seen to
> > "overreact", those PMDAs are still contributing to overall reduction of
> > quality in terms of value/timestamp accuracy.
> 
> Sure, such introspection metrics would be nice to have.
> 
> > Also as discussed on IRC, we could implement a scheme where pmie is used to
> > trigger restarts [...] by a trivial root cronjob and restarted thusly.  
> 
> These cannot do the job well.  Between the time that a PMDA exceeds
> the timeout the first time, and the time that this cron job would
> eventually run, the PMDA has been DoS'd.  Restarting the entire PMCD
> and its fleet of PMDAs means an even larger temporary DoS and impact
> on unrelated PMDAs.

On 2013-11-20 18:13:34 -0600, Nathan Scott wrote:

> > ... momentary system overload (whether deliberately induced by an attacker,
> > or accidental) can affect all PMDAs.  So can a VM or power suspend/resume.
> > So can systemwide clock jumps.
> 
> These all affect pmcd just as much as the PMDAs.  Thus, they seem to me to not be good examples to support your argument ... e.g. how often would a power suspend resume affect a PMDA and not pmcd itself!?!  Thats just silly, no amount of new pmcd code is going to help for these cases.
> 
> For all the realistic cases I can think of, or have observed, they are/were domain-specific issues where the PMDA was in the best/only position to dodge 'em.
> 
> > So can some administrator's misguided debugging activity.
> 
> Surely not on a production system?  :)  For more responsible sysadmins, for whom lack of service from pmcd and its merry agent-men is a problem, dbpmda(1) would be a more suitable tool, and is readily available on their system if they really must debug it on the production system itself.
> 
> There seems to be an underlying suggestion that this is readily fixable and pmcd is taking this action lightly - "if only pmcd would just wait, surely everything will be just peachy?"
> 
> That's simply not the case.  Life goes on while the tardy PMDA is off with the weeds.  pmcd simply doesn't know _what is going on_ with that PMDA, and it could be minutes/hours before the PMDA resurfaces.  And who knows what state it - and the horse/communication channel it rode in on - is in at that point if/when it does resurface.
> 
> New clients may have arrived, sent in their authentication information which pmcd has duly forwarded on to all the (other) agents ... except, who knows what these agents have been up to while they're off doing their own thing for awhile, and they've missed out.  Does pmcd need to resend those PDUs?  (yes, I think it does have to, and in-order with other PDUs - becomes a hard problem to solve inexpensively).
> 
> Or what if the PMDA was in the middle of a PDU exchange with pmcd when it stopped talking - does pmcd need to queue everything up that happens while the PMDA is off in lala land, indefinitely?  (including partial PDU reads and writes!!!  argh!)
> 
> Or clients have asked (sequentially) for names, PMIDs, descriptors, instances, then started fetching - and one PMDA went away briefly somewhere in the middle there, then comes back and we wonder why the client isn't getting values?  No evidence trail either - later, the PMDA is running fine when we try to debug the problem.
> 
> In theory it'd be nice to have; but in practice, I can't see how it can possibly work in a reliable fashion, nor does it fix the perceived problem it sets out to.  And yes, I suspect developers would take this as an easy "out" to not set good response time requirements for their PMDAs (alternatively, it'll make responding quickly something they can come back to, someday - i.e. never).
> 
> "Perfect" is the enemy of "good" in this case, or so it seems to me anyway.

**Comment by natoscott** [comment]
No further work is currently planned on this area.  In general however, use pmie(1) to assist here as pcp-zeroconf does.
