### ISSUE TITLE
Stopping PCP services under systemd is not straightfoward

### ISSUE THREAD

**Issue by portante** [performancecopilot/pcp#1521]
When running a PCP logger farm in order to stop all the PCP services to service something is more involved that expected:

```
systemctl stop pmproxy
systemctl stop pmlogger \
    pmlogger_farm_check.timer \
    pmlogger_farm_check.service \
    pmlogger_check.timer \
    pmlogger_daily.timer
systemctl stop pmie \
    pmie_farm_check.timer \
    pmie_farm_check.service \
    pmie_check.timer \
    pmie_daily.timer
```

Is there a way to simplify this?

**Comment by natoscott** [comment]
@portante is this on Fedora under pcp-5.3.5?  If so (I think so), there's commits upstream that resolve this (we need to backport patches or do a little 5.3.6 release) - certainly it should not require all those additional steps, and should just be the two "stop pmlogger" and "stop pmie".

**Comment by portante** [comment]
RHEL 8.4 and 8.5 with pcp-5.3.5.

**Comment by natoscott** [comment]
Ah, yep, that would have the same issue - I'll talk to the other maintainers & see if we get a point release out soon to tackle this.

Thanks!

**Comment by natoscott** [comment]
pcp-5.3.6 is released and contains a series of pmlogger/pmie farm systemd fixes.
