### ISSUE TITLE
Why do I see pmie processes via `systemctl status` in a user scope and under the `pmie_farm.service`?

### ISSUE THREAD

**Issue by portante** [performancecopilot/pcp#1522]
Why do I see pmie processes via `systemctl status` in a user scope and under the `pmie_farmer.service`?

I had to restart both the pmlogger and pmie service to update the configuration on my Fedora 34, pcp 5.3.5-1.fc34, installation.

I would have expected to have see one pmie process per host, like I do with the pmloggers.  But instead, `systemctl status` reported 9 of the 12 expected hosts under some user slice, and all 12 of the expected hosts under the `pmie_farmer` service.

**Comment by portante** [comment]
Seems easy to re-create.  Just `systemctl restart pmie` (which takes a very long time to execute, 30+ seconds).

**Comment by natoscott** [comment]
Best if @goodwinos replies to this (currently on PTO, back soon though) - it relates to recent changes he's been working on.

**Comment by goodwinos** [comment]
Clearing assignment

**Comment by natoscott** [comment]
I've figured out the underlying problem now - there's some missing configuration associated with the pmie systemd unit files that exists for pmlogger, and so the correct cgroup setup doesn't happen for pmie.  Fix to follow shortly.
