### ISSUE TITLE
pmdalogger docs lack config file (Bugzilla #1050)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#153]
On 2014-04-10 12:41:38 -0500, Frank Ch. Eigler wrote:

> The pmdalogger man page contains the usual pmda boilerplate info,
> but apprx. nothing about what makes this pmda useful: how it works,
> how to configure it, how to use it.  There is no sample config file,
> nor a reference to the Install script that can make one.

**Comment by natoscott** [comment]
No further work is currently planned on this area.
