### ISSUE TITLE
pmproxy/pmcd TLS security not working

### ISSUE THREAD

**Issue by praveen-pcp** [performancecopilot/pcp#1530]
Hi,
I am trying to enable TLS security with pmcd and pmproxy using self signed certificates.
But I am not able to enable it. I have followed the steps mentioned in the guide to enable tls security.
1. pminfo also not able to connect to pmcd- as it throws "certifiate required" , and e have right certificates in place.
2. same with pmproxy, I am using curl to talk to pmproxy using https and certificate, but it also doe not work.
Please guide.
Thanks
Praveen

**Comment by praveen-pcp** [comment]
PCP version used- 5.3

**Comment by natoscott** [comment]
Secure connections were reworked in PCP v6 and are documented here now:
https://pcp.readthedocs.io/en/latest/QG/EncryptedConnections.html
