### ISSUE TITLE
pmdalogger should have an tail -F (vs tail -f) mode (Bugzilla #1051)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#154]
On 2014-04-10 12:45:51 -0500, Frank Ch. Eigler wrote:

> In the presence of logfile rotation, simply hanging onto an original
> file descriptor and reading from the end, is not good enough.  If the
> file disappears and reappears, it should be reopened anew.  Similarly,
> if someone truncates the file (so it becomes empty again), we should
> lseek to the beginning and go from there.

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here - feel free to send patches though.
