### ISSUE TITLE
libpcp_web: discover.c needs new log TYPE_INDOM logic (needs v3 archive logic)

### ISSUE THREAD

**Issue by natoscott** [performancecopilot/pcp#1548]

**Comment by goodwinos** [comment]
pmDiscoverDecodeMetaInDom() in libpcp_web/src/discover.c should be able to call __pmLogLoadInDom() with a NULL acp and pre-read indom record in buf. This decodes TYPE_INDOM, TYPE_INDOM_DELTA and TYPE_INDOM_V2, returning a __pmLogInDom_io, which is basically a pmInResult with a timestamp. So we can easily translate that into a pmInResult and a timestamp, which are then passed to pmDiscoverInvokeInDomCallBacks.

__pmLogLoadInDom(__pmArchCtl *acp, int rlen, int type, __pmLogInDom_io *lidp, __int32_t **buf)
If acp is NULL then this function expects the indom metadata record from disk to be already read into buf.
