### ISSUE TITLE
acls relying on names should not rely on cached DNS results (Bugzilla #1052)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#155]
On 2014-04-11 10:25:53 -0500, Frank Ch. Eigler wrote:

> In libpcp/src/access.c, DNS resolution for ACL entries is done
> once, at __pmAccAddHost() time (generally the startup time of
> the daemon).  This ignore the possibility of DNS entries
> changing.  Given that there appears to be no posix resolver API
> that lets apps know the TTL of DNS information they supply, the
> app can really only use the the DNS data instantaneously.
> 
> So it seems to me that we would need to do the ACL name->address
> resolution at __pmAccAddClient time (whenever clients connect).
> Perhaps we can add a little cache-TTL of our own, if the libc
> resolvers turn out measurably too slow.
> 
> Related, getmyhostid() in libpcp/src/access.c shouldn't
> imagine that there is a single "real IP address" for the host,
> nor that it is unchanging.

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here - feel free to send patches though.
