### ISSUE TITLE
linux pmda does too much work for network.interface queries (Bugzilla #1067)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#157]
On 2014-09-24 20:26:55 -0500, Frank Ch. Eigler wrote:

> Created [attachment](https://gist.github.com/pcpemail/db1ab77c3b6408a652f44e68d6a574a6)
> strace output
> 
> An strace of pmcd, for a query of only "pminfo -f network.interface.in.bytes"
> indicates it's doing too much work.
> 
> % sudo strace  -T -tt -f -p $(pgrep pmcd) &
> 
> % pminfo -f network.interface.in.bytes
> 
> network.interface.in.bytes
>     inst [0 or "lo"] value 29794011946
>     inst [2 or "p2p1"] value 4606099151404
> 
> % kill [strace]
> 
> The strace log indicates multiple opens of /proc/net/dev, and a slew of
> ioctl's and other /sys/class/net/FOO/... reads, all just to answer data
> that's available in a single read from /proc/net/dev.  That extra work
> should be avoided.

On 2015-04-08 18:14:17 -0500, Carlos L. Torres wrote:

> Created [attachment](https://gist.github.com/pcpemail/1a2030a6d417683d6bf7ccb23ca7abdd)
> strace_pmdalinux

On 2015-04-08 18:17:18 -0500, Carlos L. Torres wrote:

> attachment 327 shows strace output of process pmdalinux when requesting the following metrics over pmwebd, from a host with 25 interfaces (bridges, bonds).
> 
> network.interface.in.bytes,
> network.interface.out.bytes,
> network.interface.in.packets,
> network.interface.out.packets
> 
> It takes more than 1 second to return a response, and pmwebd times out when using the default time-out for PMCD_REQUEST in pmwebd.options of 1 second.

On 2015-04-11 11:41:06 -0500, Michele Baldessari wrote:

> Seems that when we call refresh_proc_net_dev(INDOM(NET_DEV_INDOM)) we then
> unconditionally call:
> ...  
>  /\* Issue ioctls for remaining data, not exported through proc */
>  memset(&netip->ioc, 0, sizeof(netip->ioc));
>  if (refresh_net_dev_ioctl(p, netip) < 0)
>      refresh_net_dev_sysfs(p, netip);
> ...
> 
> Those two functions do the whole ioctl/sysfs dance.
> I assume we could cache the values we fill in those functions, namely:
> netip->ioc.mtu
> netip->ioc.linkup
> netip->ioc.running
> netip->ioc.speed
> netip->ioc.duplex
> 
> Any other thoughts here?

On 2015-04-11 11:43:38 -0500, Frank Ch. Eigler wrote:

> IMHO, we should barely cache anything - and certainly not intentionally prefetch unrelated information.

On 2015-04-12 15:22:07 -0500, Michele Baldessari wrote:

> One fairly non intrusive and quick ameliorating change (it's not a full fix
> obviously) would be to always fetch most/all the interface attributes via
> sysfs via the SIOCETHTOOL/SIOC\* calls.
> 
> At least in Carlos' strace it took one whole second:
> 23:06:19.435643 ioctl(8, SIOCETHTOOL, 0x7fff7d76d0e0) = 0 <1.038297>
> 
> Since SIOCETHTOOL does poke the driver itself, whereas the sysfs attributes
> won't, it seems this could be a fairly quick win (at least RHEL 5 has those
> files for most interfaces) and should an older kernel not have them
> we can always fall back to SIOCETHTOOL.
> 
> We could then discuss separately how the linux pmda is fetching too much
> data when poked for a few metrics and maybe tackle that in a more intrusive/
> architectural way (I have a hunch that network.interface.\* is not the only
> one). This is likely to at least improve Carlos' situation where a driver might
> decide to take a long time to reply to an ethtool poking.

On 2015-04-12 18:44:37 -0500, Nathan Scott wrote:

> (In reply to comment # 5)
> 
> > One fairly non intrusive and quick ameliorating change (it's not a full fix
> > obviously) would be to always fetch most/all the interface attributes via
> > sysfs via the SIOCETHTOOL/SIOC\* calls.
> > 
> > At least in Carlos' strace it took one whole second:
> > 23:06:19.435643 ioctl(8, SIOCETHTOOL, 0x7fff7d76d0e0) = 0 <1.038297>
> > 
> > Since SIOCETHTOOL does poke the driver itself, whereas the sysfs attributes
> > won't, it seems this could be a fairly quick win (at least RHEL 5 has those
> > files for most interfaces) and should an older kernel not have them
> > we can always fall back to SIOCETHTOOL.
> 
> +1 ... this should be a fairly simple, low-risk change.
> 
> > We could then discuss separately how the linux pmda is fetching too much
> > data when poked for a few metrics and maybe tackle that in a more intrusive/
> > architectural way (I have a hunch that network.interface.\* is not the only
> > one). This is likely to at least improve Carlos' situation where a driver
> > might
> > decide to take a long time to reply to an ethtool poking.
> 
> There's an existing Linux PMDA model to handle this in linux_refresh(), problem is its designed around each cluster having a single sampling mechanism and in this case that's not what happens.  So, yes, need to rethink that, but that's a fair bit more invasive.

On 2015-04-19 03:52:02 -0500, Michele Baldessari wrote:

> Created [attachment](https://gist.github.com/pcpemail/dde819b14cef7ecb19a93409c7fd6feb)
> Initial draft of improvement-patch
> 
> Carlos,
> 
> can you give this one a try and see if it improves things
> on your system?
> 
> I still need to make the code a bit prettier, but functionally this
> should favour the /sys/class/net interface when available.
> 
> Thanks,
> Michele

On 2015-04-21 15:40:33 -0500, Carlos L. Torres wrote:

> I tried the patch above but I'm getting a segfault whenever I request network data, other data works fine.
> 
> dmesg shows this:
> 
> [  953.058160] pmdalinux[10280]: segfault at 0 ip 0000000000409c76 sp 00007fff88aff3e0 error 4 in pmdalinux[400000+17000]

On 2015-04-22 04:29:20 -0500, Michele Baldessari wrote:

> Hi Carlos,
> 
> I saw something similar when I did an upgrade from stock fedora rpm to
> patched rpms built with makekpg. After a reboot it all worked correctly but
> I did not manage to investigate into detail why that happened. Can you make
> sure that is not the case?
> 
> Also can you paste an "ip a" output so I can try and mimic your setup in case
> the above is not relevant?
> 
> cheers,
> Michele

On 2015-04-22 12:21:21 -0500, Carlos L. Torres wrote:

> Created [attachment](https://gist.github.com/pcpemail/86c1559645b914561e1776c2bb7cf912)
> ip_address_output.txt
> 
> Michele,
> 
> I pulled the latest changes from the git repo, then applied the patch, and re-compiled and re-installed everything, and got the segfault when requesting network data. Then, I tried a reboot, but still I have the same problem.
> 
> Attached you find the output of  ip a (there are about 23 interfaces)
> 
> These are distro and kernel version I'm running on in case you need it:
> 
> Ubuntu 14.04.2 LTS
> Linux 3.13.0-34-generic # 60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
> 
> and the PCP versions, and PMDAs I'm running:
> 
> services: pmcd pmwebd
>      pmcd: Version 3.10.5-1, 6 agents, 1 client
>      pmda: root pmcd proc xfs linux[720904] mmv jbd2

On 2015-04-29 13:25:52 -0500, Michele Baldessari wrote:

> Created [attachment](https://gist.github.com/pcpemail/23bd4572224e021f3649fe2ab7e33241)
> V2 of the patch
> 
> Hi Carlos,
> 
> can you try this patch and report back? I've fixed the segfault and 
> another bug around the 'running' metric (due to the fact that it turns out that
> /sys/net/class/.../flags != flags returned by SIOCGIFFLAGS)
> 
> Thanks and regards,
> Michele

On 2015-04-29 16:14:00 -0500, Carlos L. Torres wrote:

> Created [attachment](https://gist.github.com/pcpemail/53e8fc59b969c71065230085e30f4520)
> strace output with patch
> 
> Now it is working and is not segfaulting any more. But in terms of performance, there was no improvement.
> 
> Attached you'll find the strace output with the new patch, and the request for these metrics network.interface.in.bytes, network.interface.out.bytes, network.interface.in.packets, network.interface.out.packets. 
> 
> The total request/response took over 4 seconds. There are some instances where ioctl(8, SIOCETHTOOL, 0x...) syscalls are taking a little over 1 second.

On 2015-04-30 01:04:13 -0500, Michele Baldessari wrote:

> Hi Carlos,
> 
> the reason seems to be:
> 19022 21:06:19.492609 open("/sys/class/net/p4p2/speed", O_RDONLY) = 9 <0.000037>
> 19022 21:06:19.492680 fstat(9, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000014>
> 19022 21:06:19.492726 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa6c1eb1000 <0.000015>
> 19022 21:06:19.492772 read(9, 0x7fa6c1eb1000, 4096) = -1 EINVAL (Invalid argument) <0.000014>
> 19022 21:06:19.492817 close(9)          = 0 <0.000015>
> 19022 21:06:19.492860 munmap(0x7fa6c1eb1000, 4096) = 0 <0.000016>
> 19022 21:06:19.492905 ioctl(8, SIOCETHTOOL, 0x7ffff046c520) = 0 <1.038097>
> 
> What kind of interface is this? Can you give the output of "ethtool -i p4p2" and
> "ethtool p4p2". The issue is that this driver does not fill /sys/class/net/p4p2/speed (likely some virtual driver?) and also takes ages to reply to a SIOCETHTOOL
> ioctl. Is this a physical system ?
> 
> thanks,
> Michele

On 2015-05-01 12:30:29 -0500, Carlos L. Torres wrote:

> Michele,
> 
> This a physical system set up to run plugged to several isolated networks for KVM VMs and other services (e.g. a compute node for OpenStack instances, with private and public network access, etc).
> 
> Each of those network devices are physical NICs ports, the p#p# network devices are PCI NICs (some 1Gb, some 10Gb), and the em# network devices are on-board NICs.
> 
> For the 10Gb NICs, here's the ethtool output:
> # ethtool -i p4p2
> 
> driver: ixgbe
> version: 3.15.1-k
> firmware-version: 0x546c0001
> bus-info: 0000:42:00.1
> supports-statistics: yes
> supports-test: yes
> supports-eeprom-access: yes
> supports-register-dump: yes
> supports-priv-flags: no
> 
> and for the 1Gb NIC,
> # ethtool -i p7p1
> 
> driver: igb
> version: 5.0.5-k
> firmware-version: 1.67, 0x80000ba6, 15.0.28
> bus-info: 0000:05:00.0
> supports-statistics: yes
> supports-test: yes
> supports-eeprom-access: yes
> supports-register-dump: yes
> supports-priv-flags: no
> 
> One interesting, and perhaps useful fact, is that the network device p4p2 is actually DOWN which is probably why is not populating /sys/class/net/p4p2/speed
> 
> Thanks for your help.

On 2015-05-05 03:08:29 -0500, Michele Baldessari wrote:

> Hi Carlos,
> 
> thanks that is useful info. I think it makes little sense to fetch
> speed and duplex for devices when they are down, especially for Ethernet
> devices where they need to be up to have the negotiation take place 
> (in theory it makes little sense for most devices, virtual ones
> included, but I'd prefer being conservative in this change)
> 
> Let me see how I can tweak this.
> 
> Cheers,
> Michele

On 2015-05-05 05:26:50 -0500, Frank Ch. Eigler wrote:

> When the pcp client asks for {out,in}.{bytes,packets} only, we shouldn't gather speed / duplex / etc. info in the first place.  The "refresh" (= preemptively load everything) mechanism is itself suspect.

On 2015-05-05 05:34:36 -0500, Michele Baldessari wrote:

> (In reply to comment # 16)
> 
> > When the pcp client asks for {out,in}.{bytes,packets} only, we shouldn't
> > gather speed / duplex / etc. info in the first place.  The "refresh" (=
> > preemptively load everything) mechanism is itself suspect.
> 
> Fully agreed, but that is more of an architectural change for which
> I won't have time ATM. If you prefer I can split this specific "speed/duplex" 
> issue into a separate BZ and we leave the more architectural one here. (The speed/timeout issue will still be present in Carlos' setup, although not when
> fetching {out,in}.{bytes,packets})

On 2015-07-20 10:30:18 -0500, Frank Ch. Eigler wrote:

> Nice progress in pcp git, especially for this particular metric.  Would you like a separate PR opened for others like 'network.interface.duplex', where restricting the instance domain still makes the pmda fetch /sys/class/net/*/duplex for all interfaces?

On 2015-07-20 16:48:11 -0500, Nathan Scott wrote:

> (In reply to comment # 18)
> 
> > [...]
> > like a separate PR opened for others like 'network.interface.duplex', where
> > restricting the instance domain still makes the pmda fetch
> > /sys/class/net/*/duplex for all interfaces?
> 
> The CPU-time-shaving progress here (which we should expect to be small
> in terms of the overall sample time) was mainly convenient fallout from
> refactoring the code to deal with net/mnt namespace switching correctly.
> 
> If there's evidence of any significant overhead there, sure, go ahead
> and open a new bug if you like (or better, just hack on it, if you are
> certain there is still something worth fixing there - I don't believe
> anyone else intends to continue hacking on this at this stage, unless
> there's a genuine observed problem reported).
> 
> The real gains from the recent changes were the switch from ioctl to sysfs
> by default, resolving the root-cause problem Carlos & Michele identified,
> which was not related to the original diagnosis.
> 
> Resulting from that switch, I hope to see Carlos' Vector-induced pmwebd
> timeouts resolved now - it would be good to have that confirmed, Carlos?

On 2015-07-21 12:05:59 -0500, Carlos L. Torres wrote:

> Created [attachment](https://gist.github.com/pcpemail/071e8d6a68d2cc0c47d5ea4ae2d35784)
> strace output for pmdalinux process with latest changes
> 
> Yes, I can confirm that the issue I was experiencing has been solved with the latest patches from master.
> 
> One observation I wanted to point out for future reference, is that requests through pmwebd, returns responses typically within < 100 ms (~40-70ms), but there are occasional hiccups that makes the response to be returned > 1 second, it seems pmdalinux periodically scans /sys, /proc, /dev, whenever these two coincide then response time increases. Seems to be happening every 30 seconds, which probably are triggered by pmlogger.
> 
> Anyway, thanks for taking the time to address these issues.

**Comment by natoscott** [comment]
Much work was done at this at one point, no further work is currently planned on this area.
