### ISSUE TITLE
pmlogger output semantic or physical compression (Bugzilla #1072)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#159]
On 2014-11-18 14:28:34 -0600, Frank Ch. Eigler wrote:

> buffalo todo list item # 3:
> - pcp todo item 3: pmlogger logging proc.\* - data quantity
>   - it is desirable to log some textual proc.\* bits for analysis, like
>     a hypothetical (?) proc.psinfo.environ metric, but this is very large
>     [...]
>   - repeated data values bloat the log file
>   - (a sign of this is how gzip-compressible archives are: >>90% common)
>   - pmlogger should get a mode to skip same-as-last-value entries
>     - (though this would not reduce query load on target pmcd)
>   - semantics may permit this sort of change without archive file format revision
>   - or use libz to compress on the fly & decompress on the fly too
>     - ideally retaining compatible .index file-offset format

**Comment by natoscott** [comment]
Much work was done on sub-volume compression some time ago.  No further work is currently planned on this area.
