### ISSUE TITLE
5.3.7 generates a broken pmie.service

### ISSUE THREAD

**Issue by Xake** [performancecopilot/pcp#1590]
With commit 7043b64f7d7d48b00dbd213e0410400fc4a9adf5 to the stable branch @PCP_SYSCONFIG_DIR@ was introduced to the file, however the commit 548628e90c91e7a169675754553298ca5e41732c on branch main was forgotten to backport as well, resulting in the variable never being set during build.

Please backport 548628e90c91e7a169675754553298ca5e41732c to stable from main.

**Comment by natoscott** [comment]
@Xake np, I've cherry-picked this fix into the stable branch for you.  Since its a benign (albeit annoying!) warning, we'll simply include this in the next release (which is likely to be PCP v6 at this stage).
