### ISSUE TITLE
pmlogger on-the-fly one-shot recording (Bugzilla #1073)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#160]
On 2014-11-18 14:29:40 -0600, Frank Ch. Eigler wrote:

> buffalo
> - pcp todo item 4: need to log some metrics on demand, oneshot type
>   - to match exact moment of job start/stop
>   - something like % pmlc log oneshot _metriclist  perhaps?
>   - or deploy job-lifetime-matched temporary pmloggers
>     - almost as in % pmlogger --lifetime PID
>     - related to earlier idea re. pmval -c CMD in papi context

**Comment by natoscott** [comment]
This has long-since been implemented.
