### ISSUE TITLE
pmseries --load should have an option to ignore metrics/indoms

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1606]
For pmproxy discovery, we exclude
```
# comma-separated metrics name (globs) to skip during discovery
exclude.metrics = proc.*,acct.*

# comma-separated list of instance domains to skip during discovery
exclude.indoms = 3.9,3.40,79.7
```
by default.

When you load an archive with `pmseries --load` into Redis, these settings are not respected and afaics there is currently no way to ignore these metrics/indoms while importing.

I'm not sure what's the best way; maybe read `pmproxy.conf` and use these settings (however, they are under the `[discover]` section), and add a new CLI argument for the case when I explicitly do not want to exclude these metrics?
Excluding these metrics will of course considerably speed up the import process.

**Comment by natoscott** [comment]
FWIW pmseries already reads pmproxy.conf via the pmseries.conf symlink - I vote we just honour that discovery setting in pmseries too.

**Comment by andreasgerstmayr** [comment]
> FWIW pmseries already reads pmproxy.conf via the pmseries.conf symlink - I vote we just honour that discovery setting in pmseries too.

+1
