### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by jasonk000** [performancecopilot/pcp#1609]
opening as a tracking log / current status,

building [here](https://github.com/jasonk000/pcp/pull/new/ubuntu-2204).

**Comment by jasonk000** [comment]
first pass on my local machine resulted in a few failures
```
(294 326 532 918 1661).
Failed 5 of 1305 tests
```
It was good to see it build without issues so I'll spin it up on a full size instance and proceed from here.

**Comment by kmcdonell** [comment]
G'day @jasonk000

I've upgraded one of my local Ubuntu systems to 22.04 ... but I'm seeing different QA failures:
```
1385 1701 1702 1704 1706 1707 1722 1723 1724 1725
```
while all of the failures mentioned in your post above are passing for me.  Are yours "hard" or "flakey" failures?  You can use the check-flakey script in the qa dir to rerun tests with .out.bad files and this will give some indication if the failures are flakey or not.  If you have "hard" failures, perhaps you could email me the .out.bad and .full files for the failing tests.

My failures are (a) the openmetrics PMDA goes nuts (1385) and (b) bpftrace(1) looks broken or a victim of the LTO change (all of the 17?? ones).  Did check run these tests for you?  It is possible you don't have optional packages installed or services running, so these ones were "notrun" for you ... it would be nice to know if any of my failures passed (as opposed to notrun) on your system.

Also, over on slack you mentioned some "package changes" for Ubuntu 22.04 ... if these are not already in
```
qa/admin/package-lists/Ubuntu+22.04+x86_64
```
I'd be interested in the details.

Cheers, Ken.

**Comment by jasonk000** [comment]
A few extra packages required to support the pmdabpf implementation (since libbpf is available now on ubuntu22).

From an ec2 instance with a built pcp-6.x trunk, I see the following errors.
```
Failures: 036 063 119 151 169 241 244 250 255 279 280 294 304 338 344 359 392 429 430 457 471 503 529 530 532 641 649 658 664 674 681 686 805 870 892 893 925 999 1049 1087 1108 1166 1190 1297 1351 1426 1429 1480 1546 1701 1722 1723 1768 1897
```

I've not yet reviewed them though, but only a couple of overlaps.

**Comment by jasonk000** [comment]
I'll keep a list running list of issues found / resolved
- Additional packages etc were required, to install `fakeroot` and the bpf PMDA dependencies. I put these in the `ubuntu-2204` branch.
- `sudo mount -o remount,exec /var/tmp` required as `/var/tmp` is by default mounted as `noexec`
- ... wip 241

**Comment by kmcdonell** [comment]
I've added 1701, 1722 and 1723 to the triaged list for Ubuntu 22.04 pending the arrival of the upstream fix from https://github.com/iovisor/bpftrace/pull/2264

**Comment by kmcdonell** [comment]
@jasonk000 if 608 and/or 749 fail again could you please either email the .out.bad and .fail files to me, or attach 'em to this issue?

**Comment by kmcdonell** [comment]
qa/430 is fixed in commit 045e5d8b4

**Comment by kmcdonell** [comment]
qa/1480 is fixed in commit 0d56ed200

**Comment by kmcdonell** [comment]
qa/892 is now _notrun if no IPv6 entry for localhost in /etc/hosts.  Fix is in commit 8a9da013d

**Comment by kmcdonell** [comment]
qa/749 was not being run here (systemtap was not in the packages list).  When I installed that the test passes.  The error ```./scripts/pahole-flags.sh: line 7: return: can only `return' from a function or sourced script``` has nothing to do with PCP, it comes from linux-headers.
I really don't want to filter it away in qa/749, so would rather leave it failing until linux-headers is fixed.

**Comment by jasonk000** [comment]
I think this can be closed now, correct? Anything outstanding?
@kmcdonell @natoscott

**Comment by natoscott** [comment]
All sorted I believe, yep.

**Comment by natoscott** [comment]
Oh, I should also mention - you can follow daily CI status on all platforms via the #pcpqa channel on PCP slack.

**Comment by kmcdonell** [comment]
Hi Jason,

I don't have any outstanding issues specific to this version of Ubuntu.  
I've been using Ubuntu 22.04 for some time as one of my development 
systems and PCP seems just fine there.

Cheers, Ken.
