### ISSUE TITLE
3d chart view: opengl pmview and/or pmwebd/webgl webapp (Bugzilla #1074)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#161]
On 2014-11-19 15:57:24 -0600, Frank Ch. Eigler wrote:

> buffalo todo
> - pcp todo item 6: 3d view
>   - used because anomaly detection still manual with mk. 1 eyeball
>   - old sgi pmview still attractive, especially if considering topology
>   - an openscenegraph-based partial reimplementation exists
>     - so dies a unity 3d/gl-based one, with browser blob etc.
>   - maybe have pmwebd / webgl reimplementation

On 2014-11-20 13:29:08 -0600, Ken McDonell wrote:

> The partial implementation of pmview is actually quite close to working.
> It is in the source tree (src/pmview).
> All of the parser, scene graph construction, scene visualization parts appear to be working.
> There is some issue with the connection to the time controller that is currently blocking any pmFetch from happening, so the scene is not modulated.

**Comment by natoscott** [comment]
No further work is currently planned on this area, although if someone wants to hack reviving pmview or a 3D Grafana plugin, please open new PRs.
