### ISSUE TITLE
Not able to see some metrics for zoneinfo

### ISSUE THREAD

**Issue by sagarramdev173** [performancecopilot/pcp#1615]
Hi ,

I'm not able to see some metrics for zoneinfo available for data recording ,the metrics I'm looking for are following 
  pagesets
    cpu: 0
              count: 203
              high:  378
              batch: 63
  vm stats threshold: 48
    cpu: 1
              count: 325
              high:  378
              batch: 63
  vm stats threshold: 48
    cpu: 2
              count: 285
              high:  378
              batch: 63
  vm stats threshold: 48
    cpu: 3
              count: 350
              high:  378
              batch: 63
  vm stats threshold: 48
  node_unreclaimable:  0
  start_pfn:           1048576
Node 0, zone  Movable
  pages free     0
        min      0
        low      0
        high     0
        spanned  0
        present  0
        managed  0
        protection: (0, 0, 0, 0, 0)
Node 0, zone   Device
  pages free     0
        min      0
        low      0
        high     0
        spanned  0
        present  0
        managed  0
        protection: (0, 0, 0, 0, 0)

**Comment by natoscott** [comment]
> I'm not able to see some metrics for zoneinfo available for data recording ,the metrics I'm looking for are following
> pagesets

Some of these metrics exist, some do not (yet?) ...

> cpu: 0
> count: 203
> high: 378
> batch: 63
> vm stats threshold: 48
> cpu: 1
> count: 325
> high: 378
> batch: 63
> vm stats threshold: 48
> cpu: 2
> count: 285
> high: 378
> batch: 63
> vm stats threshold: 48
> cpu: 3
> count: 350
> high: 378
> batch: 63
> vm stats threshold: 48

These first ones do not exist as PCP metrics.  Are they useful?
They're exported per-node-and-per-CPU which makes them quite a
complex metric, and alot of data.  Not impossible though - have
a look at 'pminfo -f mem.zoneinfo.protection' for example, this
shows how to construct a complex per-node-and-per-region metric.

> node_unreclaimable: 0
> start_pfn: 1048576

Again these don't exist - I'm not sure if they're useful though?
(nor what they mean exactly).  They're simpler metrics - just per
node, not per-CPU-and-per-node - so easier to implement these 2.

If you need them, please go ahead and add them - they're fairly
simple to add to PCP (see src/pmdas/linux/proc_zoneinfo.c for
reference code) - and please open a pull request in case other
folk want them too.

> Node 0, zone Movable
> pages free 0
> min 0
> low 0
> high 0
> spanned 0
> present 0
> managed 0
> protection: (0, 0, 0, 0, 0)
> Node 0, zone Device
> pages free 0
> min 0
> low 0
> high 0
> spanned 0
> present 0
> managed 0
> protection: (0, 0, 0, 0, 0)

These ones are already PCP metrics, from pminfo(1) -t ...

```
mem.zoneinfo.free [free space in each zone for each NUMA node]
mem.zoneinfo.min [min space in each zone for each NUMA node]
mem.zoneinfo.low [low space in each zone for each NUMA node]
mem.zoneinfo.high [high space in each zone for each NUMA node]
mem.zoneinfo.scanned [scanned space in each zone for each NUMA node]
mem.zoneinfo.spanned [spanned space in each zone for each NUMA node]
mem.zoneinfo.present [present space in each zone for each NUMA node]
mem.zoneinfo.managed [managed space in each zone for each NUMA node]
mem.zoneinfo.protection [protection space in each zone for each NUMA node]
```

cheers.
