### ISSUE TITLE
pcp htop doesn't work with archive option

### ISSUE THREAD

**Issue by sagarramdev173** [performancecopilot/pcp#1622]
Hi,

I just figured out pcp-htop doesn't work with archives but other utilities like pcp-atop work with archives, was it done intentionally or I'm missing something?

**Comment by natoscott** [comment]
@sagarramdev173 it's just not yet implemented (requires additional code in pcp-htop) ... currently I don't have time to work on it myself, but it'd be great if someone else does.

**Comment by sagarramdev173** [comment]
pcp-htop fields look similar to ps output, is it the one to behave like ps output or some other utility eg. "pcp-ps" work is in progress.

**Comment by natoscott** [comment]
PCP  separates sampling of metrics from reporting.  There is no pcp-ps but it could certainly be implemented if you wish.  You might find the existing pcp-pidstat has similar functionality too.
