### ISSUE TITLE
archive access api across network (Bugzilla #1076)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#163]
On 2014-11-20 10:11:55 -0600, Frank Ch. Eigler wrote:

> buffalo item
> - pcp todo item 10: archive access api across network
>   - to let analytics / guis run remotely from archive files
>   - already in plans of one flavour of the "grand unified context"
>   - pmwebd graphite interface one possible near-term hack for this
> 
> See also earlier "grand unified context" threads.

**Comment by natoscott** [comment]
The current pmproxy REST API now provides this, and grafana-pcp makes extensive use of it.
