### ISSUE TITLE
pmda fetch timeout toleration (Bugzilla #1079)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#165]
On 2014-11-20 10:31:21 -0600, Frank Ch. Eigler wrote:

> buffalo item
> - pcp todo item 13: proc pmda timeouts
>   - well known problem, hits ccr (and other larger servers) good and hard
>   - http://oss.sgi.com/bugzilla/show_bug.cgi?id=1036
>   - kenj had drafted work for pmda timeout-detecting thread for fetches
>     - still need this!
>   - pmie-based auto-pmcd-restarting possible too, though one must run with root/sudo
>     - and restarting doesn't guarantee persistency of pmids etc. 
>   - elevated-privileged split-pmcd a possible solution too (it could restart pmda
>     processes)

**Comment by natoscott** [comment]
There are no plans for further work in this area, seems to have become a much less reported in modern years too.
