### ISSUE TITLE
Install instructions on macOS X

### ISSUE THREAD

**Issue by moghun** [performancecopilot/pcp#1654]
It is almost impossible to setup and use PCP on macOS right now. It is not included in homebrew and there are no instruction on how to build via using tar.gz file provided

**Comment by moghun** [comment]
When I try to install from the source, I get this fatal error "FATAL ERROR: could not fathom your compiler's bit field allocation scheme". It is probably I am a M1 user. If pcp is not usable for M1 Mac users, please at least inform us...

**Comment by natoscott** [comment]
@moghun looking like I may have some access to this hardware in a little while, will get this fixed up then - thanks for the report.

**Comment by christianhorn** [comment]
@moghun I have some notes on  https://fluxcoil.net/wiki/software/performance_co-pilot/compiling_on_macosx regarding compiling on MacosX. You should use GCC - but also with that the build fails later at a point where I also did not get further.

**Comment by natoscott** [comment]
@moghun @christianhorn I'm pushing the initial fixes now that get PCP on M1 Macs working into PCP main branch - more will follow over the coming days/weeks as time permits.

With this first round of commits, the "could not fathom your compiler's bit field allocation scheme" error is fixed.

If anyone would like to assist me in getting PCP fully functional on Mac once more, and ultimately back into brew, please join us in the #osx channel on PCP slack - https://pcp.io/community.html for details.
