### ISSUE TITLE
pmcd result timestamping (Bugzilla #1080)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#166]
On 2014-11-20 10:34:30 -0600, Frank Ch. Eigler wrote:

> buffalo item
> - pcp todo item 14: pmfetch timestamps
>   - especially for slightly tardy pmdas, the pmResult timestamp is
>     ambiguous: is it at beginning, end, or middle of process?
>   - having too-short inter-fetch timestamp intervals can lead to
>     crazy-big rate-converted values
>   - maybe just confirm/fix pmcd to return beginning-of-operation timestamps
>   - apps can also confirm that timestamp is reasonable, by comparing to
>     their own clocks around pmFetch()
>   - pmlogger could emit diagnostics for violations
> 
> Note src/pmcd/src/dofetch.c:530, __pmtimevalNow() is called -after- all
> the subsidiary agent fetches are complete.

**Comment by natoscott** [comment]
No further work is currently planned on this area, the status quo is deemed just fine.
