### ISSUE TITLE
Shell scripts should get rid of "fgrep" and "egrep" as these are deprecated

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1684]
Recently, during September 2022, Fedora updated grep to the version 3.8. This version of grep is throwing warning message, informing users about deprecation of "fgrep" and "egrep" commands: https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html

This extra warning message is causing problem especially to the pcp-testsuite as this warning becomes part of test cases outputs, making such test cases to fail.

Platforms using GNU tools should use "grep -E" resp "grep -F" instead. However I am not sure what other platforms, PCP supports, are using, so these might not have the "-E" or "-F" implemented.

**Comment by natoscott** [comment]
@kurik this is fixed in commit 4c71ed2d3e083ba4fc3c3db3f94d3c7c98cf4d2c ... or are you coming across cases I missed there?

**Comment by kurik** [comment]
Ah, I overlooked this. Thanks for the fix.
Sure, I can test it...

**Comment by kurik** [comment]
I tested this on top of the currently latest commit f966436e848429045c1ceaa0b1df9fedf0ac154a.
The testing has passed as I have not find any issue related to the fgrep/egrep deprecation.

Thanks @natoscott for the fix.
