### ISSUE TITLE
gpfs pmda (Bugzilla #1083)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#169]
On 2014-11-20 10:42:03 -0600, Frank Ch. Eigler wrote:

> buffalo item
> - pcp todo item 17: gpfs pmda
>   - need it
> 
> (I believe this referred to the proprietary
> https://en.wikipedia.org/wiki/IBM_General_Parallel_File_System .)

On 2014-11-20 16:15:09 -0600, Jan-Frode Myklebust wrote:

> Do you have any ideas for which metrics should be included in this PMDA?
> 
> There's quite a lot available via SNMP, https://github.com/mcallaway/sdm/blob/master/sdm-mibs/mibs/GPFS-MIB.txt 
> 
> Will it be cheating to fetch from SNMP? I guess the same numbers could be pulled via "mmpmon", but it's probably a good idea to be limiting the performance collecting to a single node (like they do for SNMP).
> 
> Some monitoring links for GPFS:
> 
> https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/General%20Parallel%20File%20System%20%28GPFS%29/page/Monitoring%20and%20Tools

On 2014-11-20 17:40:17 -0600, Nathan Scott wrote:

> > Will it be cheating to fetch from SNMP? 
> 
> Heh.  Generally I've found it best to reduce reliance on "extra" daemons/packages
> wherever it possible/feasible (its more admin overhead, more things that can go wrong, sometimes much less efficient, etc) - if its feasible to extract data more directly I'd recommend going that route.  It'd be interesting to see how the code backing that MIB extracts the stats (via API? or running mmpmon/mmfsadm? or...).

On 2014-11-21 13:48:08 -0600, Jan-Frode Myklebust wrote:

> Ok, I've asked on the gpfsug if anybody has any ideas for how the snmp agent gathers its metrics:
> 
> http://gpfsug.org/pipermail/gpfsug-discuss/2014-November/000597.html
> 
> BTW: I see there's quite a lot of counters easily available with mmpmon. These are probably a good start:
> ## "mmpmon io_s"
> 
> mmpmon node 192.168.42.28 name popimap1 io_s OK
> timestamp:      1416599060/588460
> bytes read:     35495396803892
> bytes written:  1132075346666
> opens:           390711997
> closes:          374730575
> reads:          3901906749
> writes:          230450025
> readdir:          24539957
> inode updates:   142537717
> ## "mmpmon fs_io_s"
> 
> mmpmon node 192.168.42.28 name popimap1 fs_io_s OK
> cluster:        atmailcluster.ulh
> filesystem:     atmailusers
> disks:                  11
> timestamp:      1416599111/431751
> bytes read:      151420466
> bytes written:     3914687
> opens:              427398
> closes:             425296
> reads:             1928948
> writes:              49214
> readdir:               324
> inode updates:       17270
> 
> mmpmon node 192.168.42.28 name popimap1 fs_io_s OK
> cluster:        atmailcluster.ulh
> filesystem:     gpfsmailstore
> disks:                  12
> timestamp:      1416599111/431751
> bytes read:     35495469736251
> bytes written:  1132076341564
> opens:           390287891
> closes:          374308462
> reads:          3900001260
> writes:          230402025
> readdir:          24539918
> inode updates:   142521531

On 2014-11-23 16:43:54 -0600, Nathan Scott wrote:

> (In reply to comment # 3)
> 
> > BTW: I see there's quite a lot of counters easily available with mmpmon.
> > These are probably a good start:
> 
> Yep, looks like a good interface to use.

**Comment by kmcdonell** [comment]
Since the gpfs PMDA first appeared in the PCP source tree in Jan 2015 apparently using the mmpmon interface, I'm going to take a wild punt that this is done (at least in context of this issue), and close this one.
