### ISSUE TITLE
Logging at an instance / cgroup level

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#17]
Hello All,

I want to see if its possible to log certain things such as memory at an instance level.

Here is the api url
http://host:44323/pmapi/1281741401/_fetch?names=mem.util.cached,mem.util.used,mem.util.free,mem.util.bufmem

i get [-1] in the instance values, is there a way to get it to return with actual instance values?

Here is the response I get back.
 {
"pmid": 251659268,
"name": "mem.util.bufmem",
"instances": [{"instance": -1,"value": 225412}]
}

When I run the queryname as containers.state.running,containers.name I get back proper instance and value for all the cgroups, would be beneficial to be able to see other info such as memory and cpu at an cgroup level.

Thanks!

**Comment by natoscott** [comment]
The cgroup.memory.* and cgroup.cpuacct.* metrics may be what you're after here?
The mem.* metrics are system-wide.

**Comment by hc000** [comment]
Thanks!

I see that these are available, any suggestion on which one to use for free/used/total within containers?

cgroup.memory.stat.cache
cgroup.memory.stat.rss
cgroup.memory.stat.rss_huge
cgroup.memory.stat.mapped_file
cgroup.memory.stat.writeback
cgroup.memory.stat.swap
cgroup.memory.stat.pgpgin
cgroup.memory.stat.pgpgout
cgroup.memory.stat.pgfault
cgroup.memory.stat.pgmajfault
cgroup.memory.stat.inactive_anon
cgroup.memory.stat.active_anon
cgroup.memory.stat.inactive_file
cgroup.memory.stat.active_file
cgroup.memory.stat.unevictable
cgroup.memory.stat.total.cache
cgroup.memory.stat.total.rss
cgroup.memory.stat.total.rss_huge
cgroup.memory.stat.total.mapped_file
cgroup.memory.stat.total.writeback
cgroup.memory.stat.total.swap
cgroup.memory.stat.total.pgpgin
cgroup.memory.stat.total.pgpgout
cgroup.memory.stat.total.pgfault
cgroup.memory.stat.total.pgmajfault
cgroup.memory.stat.total.inactive_anon
cgroup.memory.stat.total.active_anon
cgroup.memory.stat.total.inactive_file
cgroup.memory.stat.total.active_file
cgroup.memory.stat.total.unevictable
cgroup.memory.stat.recent.rotated_anon
cgroup.memory.stat.recent.rotated_file
cgroup.memory.stat.recent.scanned_anon
cgroup.memory.stat.recent.scanned_file

**Comment by fche** [comment]
@hc000, see also the pmapi hostspec url (as supplied to the /pmapi/context?hostspec=FOO call) containing "&container=NAME".  (The code in issue #2 here can expose this option.)  That mechanism, under development, should eventually permit the display of automatic per-container cgroup etc. data.

**Comment by natoscott** [comment]
>  any suggestion on which one to use for free/used/total within containers?

These metrics appear to be missing currently (they need to be sourced from a different location to the other memory metrics, it seems) - I'll add them in for the next PCP release.

**Comment by hc000** [comment]
thanks for the quick response guys! can't wait for next release :)

**Comment by natoscott** [comment]
These metrics have been merged, will be in pcp-3.10.5 and onward...

$ pminfo cgroup.memory | head -3
cgroup.memory.usage
cgroup.memory.limit
cgroup.memory.failcnt
