### ISSUE TITLE
pmdabpf is missing biosnoop.so module on F36

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#1701]
QA 1452 is failing on F36 (vm22).

The root cause is initially
```
dlopen failed: /var/lib/pcp/pmdas/bpf/modules/biosnoop.so
```
which seems to be because biosnoop.o never makes it into $(PMDABPF_MODULES) from builddefs which in turn is because biosnoop is never mentioned in configure.ac.

I don't understand how this can be working anywhere??

**Comment by natoscott** [comment]
@smalinux can you help with a PR to fix this up?  thanks!
