### ISSUE TITLE
bpftrace PMDA QA failure on F36

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#1704]
The issues are all related to the subtest "test2".

First I fixed the grep in the test so that the (new?) error message:
```
FATAL: Invalid probe type made it to attachpoint parser
```
is mapped along with other variants of the error message to "error message (invalid probe) found".

But this diff in the .out remains and I don't know what's the right thing to do here.
```
*** 1705.out	2021-05-08 19:07:48.725663389 +1000
--- 1705.out.bad	2022-11-04 08:55:17.235925798 +1100
***************
*** 17,23 ****
  error message (invalid probe) found
  
  bpftrace.scripts.test2.exit_code
!     value 1
  
  === syntax error ===
  bpftrace.control.register old value="{}" new value="// name: test3
--- 17,23 ----
  error message (invalid probe) found
  
  bpftrace.scripts.test2.exit_code
!     value -6
  
  === syntax error ===
  bpftrace.control.register old value="{}" new value="// name: test3
```

Note that the "error" has been elevated to FATAL, is that related?  And is -6 and acceptable answer here for bpftrace.scripts.test2.exit_code?

**Comment by natoscott** [comment]
Resolved via 8247ca396bdb6ac186a48c3288c09e019defbcc5 recently.
