### ISSUE TITLE
bcc PMDA failing with AVCs on selinux

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#1708]
On CentOS Stream8 (vm04) the bcc PMDA is failing lots of QA tests: 1115, 1116, 1117, 1126, 1150, 1151, 1153, 1155, 1156, 1158, 1165, 1168, 1170, 1171, 1172, 1173, 1175, 1178, 1179 and 1181.

The common theme is
```
type=AVC msg=audit(1667609858.474:204363): avc:  denied  { open } for  pid=1687790 comm="python3" scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:system_r:pcp_pmcd_t:s0 tclass=perf_event permissive=0
```

**Comment by natoscott** [comment]
Can you check if commit ed6a42b67a714e252112c5257f7436e7391bc8dd was in place Ken?  Should resolve this one as it adds back manage_perf_event_perms when available (el8) which includes open.

**Comment by kmcdonell** [comment]
@natoscott that's a good guess, but it is not as simple as that ...

First, I missed this snippet in the pcp-daily log
```
Error: Failed dependencies:
        pcp = 6.0.1 is needed by (installed) pcp-pmda-bpftrace-6.0.1-12.x86_64
        pcp-libs = 6.0.1 is needed by (installed) pcp-pmda-bpftrace-6.0.1-12.x86_64
```
so I was **not** running the latest rpms although your commit is in the source and the rpms I built.

I've mentioned before that I think this is a problem when an rpm (pcp-pmda-bpftrace in this case) is built for some version of PCP in a platform, and then at some later date we no longer build this rpm on that same platform.  I checked in src/include/builddefs and indeed, PMDA_BPFTRACE = false and it must have been true up until about a week ago.

So is this a problem?

Second, I tried to remove the offending rpm, and ...
```
$ sudo dnf remove pcp-pmda-bpftrace
Dependencies resolved.
...
Running transaction
  Preparing        :                                                                                                              1/1 
  Running scriptlet: pcp-pmda-bpftrace-6.0.1-12.x86_64                                                                            1/1 
error: %preun(pcp-pmda-bpftrace-6.0.1-12.x86_64) scriptlet failed, exit status 1
```
so this looks like another potential problem.

Finally, 
```
$ sudo rpm -e --nopreun pcp-pmda-bpftrace
```
worked, I re-installed the 6.0.2 PCP rpms, and qa check -g pmda.bcc now passes.

So the original "issue" is a false alarm, but there are two other knock-on issues ... I'll wait for comments from @natoscott before closing this one (and maybe opening new issues).

**Comment by natoscott** [comment]
Hi Ken - off the top of my head I don't recall changing anything about bpftrace deps myself - I think this will be one we need @andreasgerstmayr to chime in on.

**Comment by andreasgerstmayr** [comment]
> I've mentioned before that I think this is a problem when an rpm (pcp-pmda-bpftrace in this case) is built for some version of PCP in a platform, and then at some later date we no longer build this rpm on that same platform. I checked in src/include/builddefs and indeed, PMDA_BPFTRACE = false and it must have been true up until about a week ago.

The code enabling/disabling the bpftrace PMDA in the configure script is unchanged since 2 years (https://github.com/performancecopilot/pcp/blame/main/configure.ac#L1244).

However, I just noticed one thing: If I run `bpftrace --help` on CentOS Stream 9, it crashes:
```
# bpftrace --help
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)
```

That'll be the reason why the bpftrace PMDA didn't get included anymore.

> Running transaction
>   Preparing        :                                                                                                              1/1 
>   Running scriptlet: pcp-pmda-bpftrace-6.0.1-12.x86_64                                                                            1/1 
> error: %preun(pcp-pmda-bpftrace-6.0.1-12.x86_64) scriptlet failed, exit status 1

The preun scriptlet is the standard scriptlet (no bpftrace specific changes):
```
# rpm -q --scripts pcp-pmda-bpftrace
preuninstall scriptlet (using /bin/sh):

if [ "$1" -eq 0 ]
then
    PCP_PMDAS_DIR=/var/lib/pcp/pmdas
    PCP_PMCDCONF_PATH=/etc/pcp/pmcd/pmcd.conf
    if [ -f "$PCP_PMCDCONF_PATH" -a -f "$PCP_PMDAS_DIR/"bpftrace"/domain.h" ]
    then
        (cd "$PCP_PMDAS_DIR/"bpftrace"/" && ./Remove >/dev/null 2>&1)
    fi
fi
```
Is there any log/output what failed exactly, except just the exit code?

In general, there have not been any changes to the bpftrace PMDA in a while.

**Comment by natoscott** [comment]
Fixed in most recent selinux policy I believe.
