### ISSUE TITLE
Performance overhead

### ISSUE THREAD

**Issue by abitrolly** [performancecopilot/pcp#1710]
What would be performance overhead for using `pcp` as a backend for GNOME shell extensions like https://github.com/fflewddur/tophat ? Compared to https://gitlab.gnome.org/GNOME/libgtop/

Would be nice to get some methods to actually measure it.

**Comment by natoscott** [comment]
@abitrolly you'll find the overheads comparable in my experience.  With PCP you only sample from the kernel those metrics of interest (many generic libraries will always sample all metrics they know of, whether the data is used or not).  If only interested in localhost kernel metrics you might find the local context mode to pmNewContext(3) useful also.

Feel free to ask (slack, IRC, pcp@groups.io) if assistance is needed once someone starts coding, but I'll close this issue for now since there's no PCP issue here.

**Comment by natoscott** [comment]
The pcp mailing list is probably a better place then.

First step would be to come up with a list of the kernel data you need to display, then find the PCP metric names corresponding to each, then you can start measuring the sampling time.

**Comment by abitrolly** [comment]
I would start with what it takes to CPU, Mem, Swap and Network data separately.

![image](https://user-images.githubusercontent.com/8781107/201022720-9045762a-79db-4304-a680-e214b5f1cba0.png)

**Comment by abitrolly** [comment]
Does that include the overhead of spinning up the `pminfo` process from `bash`? Because some applets may try to do this each second.

**Comment by natoscott** [comment]
It does, yes, so it's an over-estimation - best approach is to write code using the PMAPI(3) rather than using tools.

**Comment by abitrolly** [comment]
So how to use that PMAPI(3) from JavaScript? https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/b359d888fd3fcccf1252f5f1dc390299e701493e/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L1317

And how to measure the performance overhead of that PMAPI(3)?

**Comment by natoscott** [comment]
Good questions!   We have a ctypes-based PMAPI wrapper API for python but nothing for Javascript.  I hear alot about WASM these days as the way to go to interface C and Javascript, but I'm not familiar with the details.

In terms of measuring the overheads, pminfo is using the PMAPI internally so we have a ballpark figure.  You could fine-tune it with a custom program putting caliper points around the pmFetch call, but we already know its only a few milliseconds at most so not really worth digging deeper.

**Comment by abitrolly** [comment]
The JavaScript extension above [is using](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/b359d888fd3fcccf1252f5f1dc390299e701493e/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L55) GObject Introspection interface to access `libgtop` C API - https://gi.readthedocs.io/en/latest/

Is there a PMAPI binding for that?

**Comment by natoscott** [comment]
Not that I'm aware of.
