### ISSUE TITLE
Extend the pmiostat(1) command for increased compatibility (Bugzilla #1090)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#173]
On 2014-11-24 18:04:46 -0600, Nathan Scott wrote:

> A number of people have asked us to provide drop-in replacements for sysstat reporting tools like iostat(1), so they can more easily transition to using PCP.  Command line option compatibility is highly desirable, but the existing pmiostat(1) python script does not offer that.
> 
> It would be possible to add a pcp-iostat(1) symlink to pmiostat(1) that uses a different pmOptions subclass (switch based on argv[0]), to provide the desired level of compatibility while still leveraging the work done in the pmiostat(1) command.

**Comment by natoscott** [comment]
No further work is currently planned on this area.
