### ISSUE TITLE
pmapi extension for regularly scheduled fetches (Bugzilla #1091)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#174]
On 2014-12-03 12:40:08 -0600, Frank Ch. Eigler wrote:

> In order to limit unnecessary load, it would be helpful if the PMAPI
> included a single operation to fetch metrics in a recurrent manner.
> 
> The aim would be to eliminate having to wake up pmlogger just to send
> the inquiry, let it go to sleep awaiting network/pmcd, then waking it
> up again when each response comes.  It could help synchronize
> 
> A possible PMAPI-flavoured extension might look like:
> 
> int pmFetchRecurrent(int numpid, pmID _pmidList, struct timeval interval,
>                      int (_consumerCallBack)(pmResult *),
>                      volatile int *cancel);
> 
> (where the consumer callback and the cancel flag could determine how
> long the operation is to continue).  PDU state-machine design etc. TBD.

On 2014-12-03 13:28:27 -0600, Frank Ch. Eigler wrote:

> As a random additional data point, a cross-network pmlogger instance
> running with a default pmlogconf indicates, under strace:
> - apprx. 900 bytes sent per fetch request
> - a delay of 60 milliseconds awaiting a response
> - a write of the result to disk within 30 microseconds
> 
> At the pmcd end, under strace:
> - those 900 bytes are received
> - after 300 microseconds, the PMDAs start collecting data
>   (doing too much work, as noted at bug # 1067 etc.)
> - sending overall response of some 9000 bytes back 56 milliseconds after
>   receiving request
>   (without pmcd running under strace, it is considerably faster)
> 
> ... an additional 4ish milliseconds remain unaccounted for in terms of
> network/kernel latencies

On 2014-12-03 15:42:06 -0600, Nathan Scott wrote:

> NAK - I don't support this at all.  This introduces server side memory load and complexity (signficiant per-client server state would be needed), at the cost of tiny amounts of network traffic & small latency.  It goes against the design of pmcd to be small, lightweight, and stateless.  It'd also removes the implicit feedback loop that is designed into the protocol.
> 
> If you're concerned about it, it would be better to understand where that existing latency is coming from and optimise that - such optimisations will help all client tools and allows pmcd to stay lean.

On 2014-12-03 16:41:14 -0600, Frank Ch. Eigler wrote:

> (In reply to comment # 2)
> 
> > This introduces server side memory load and complexity (significant per-client
> > server state would be needed),
> 
> The amount of per-client state would be approximately equal to one fetch packet,
> namely one kilobyte in this case.  The complexity may be more accurately judged
> via a straw design.
> 
> > at the cost of tiny amounts of network traffic & small latency.
> 
> As for network traffic, in this test it was 10% of the total, and
> apprx. 100% duplicative of previous traffic.  As for latency, that's
> not easily answered, since it is a composite of multiple scheduling
> delays & context switches, and hops across the network.
> 
> > It goes against the design of pmcd to be small, lightweight, and stateless.
> 
> Only "stateless" is impacted here, and even that not severely.  In the
> model roughly proposed, pmcd would remain stateless across individual PMAPI
> calls (except, well, for state already stored, like indom profiles).  It
> would just mean that instead of one response to the fetch pdu, pmcd would
> issue multiple responses over time, until the operation is complete.  For
> example, no nesting of operations is necessary.
> 
> If you mean "stateless" to mean the structure of the relatively simple main
> message handling loop, then yes, that part would be somewhat complicated.
> 
> > It'd also removes the implicit feedback loop that is designed into the
> > protocol.
> 
> Please elaborate what you mean.
> 
> > If you're concerned about it, it would be better to understand where that
> > existing latency is coming from and optimise that - such optimisations will
> > help all client tools and allows pmcd to stay lean.
> 
> Sure, but that is orthogonal to reducing effort and traffic that is, from
> the application point of view, pure overhead.  We should reduce both.

**Comment by natoscott** [comment]
There are no current plans to work on this.
