### ISSUE TITLE
Cannot find metric bcc.runq.latency. Please check if the PMDA is enabled.

### ISSUE THREAD

**Issue by yahia-kr-coder** [performancecopilot/pcp#1746]
General/[PCP Vector: eBPF/BCC Overview]

When i run the  eBPF/BCC on PCP Vector, No data shown for the forth metrics (run queue latency, disk latency,..) 

By reading  (https://github.com/performancecopilot/grafana-pcp/issues/35#issue-568047675) i have installed the kernel headers and i have installed python-bpfcc (I have got a lot of dependency and installed them all :python-minimal (= 2.7.16-1), libpython-stdlib (= 2.7.16-1), python2 (= 2.7.16-1), python2.7). Because i ma running Ubuntu 22.04.2 LTS in which those are deprecated versions, so a lot of newly python dependencies  are replaced with those old ones, so i have lost a lot of functionalities and features of Ubuntu jammy version. 
![Screenshot from 2023-02-22 17-44-50](https://user-images.githubusercontent.com/85415870/220697361-37901267-bae5-43ec-9f2f-adb23ce55fd9.png)

I have installed PCP and pmdabcc
![Screenshot from 2023-02-22 17-43-37](https://user-images.githubusercontent.com/85415870/220697038-22a8162f-f97c-4c52-afaa-57cd59a7016e.png)

And enabled it:
![Screenshot from 2023-02-22 17-47-07](https://user-images.githubusercontent.com/85415870/220697887-9882126a-3413-4835-8b0c-4cbe0be41135.png)

Then `sudo ./Install`
![Screenshot from 2023-02-22 17-48-21](https://user-images.githubusercontent.com/85415870/220699058-fb667605-29f6-4590-8551-0fe9a7df0814.png)
![Screenshot from 2023-02-22 17-48-53](https://user-images.githubusercontent.com/85415870/220699131-f67d7da9-54dc-41d6-96bd-80267ede0d8a.png)

Then Running `Me@Ubuntu: /var/lib/pcp/pmdas/bcc$  pminfo --fetch bcc` 
![Screenshot from 2023-02-22 17-50-57](https://user-images.githubusercontent.com/85415870/220698947-ec1782f2-81d5-4060-a633-955eb127445c.png)

 

My bcc.conf in /var/lib/pcp/pmdas/bcc
![Screenshot from 2023-02-22 17-41-48](https://user-images.githubusercontent.com/85415870/220696739-77af95f2-bb21-482e-9e8e-63cdc7114e25.png)

**Versions (please complete the following information):**
 - Performance Co-Pilot: 6.0.2-1
 - Grafana:v9.3.6
 - grafana-pcp: 5.1.1

I have installed BCC,bpftrace from source.

**Comment by natoscott** [comment]
+1 - you can also see at the agent ./Install time that it reports "0 values" - bcc.log contents should indicate the problem.

**Comment by yahia-kr-coder** [comment]
Thanks for answering me, screenshot from `/var/log/pcp/pmcd/bcc.log` is the following
![Screenshot from 2023-02-23 23-22-45](https://user-images.githubusercontent.com/85415870/221044490-0f63c10a-5c77-43c1-be96-f22fc5a9fefa.png)

and the grafana server:
![Screenshot from 2023-02-23 23-25-29](https://user-images.githubusercontent.com/85415870/221044578-25b632c5-f29b-4eeb-82d3-f86102df5a5a.png)

**Comment by natoscott** [comment]
That looks like the root cause may be: https://github.com/iovisor/bcc/issues/4261

Try disabling the biolatency module in bcc.conf.

**Comment by yahia-kr-coder** [comment]
By disabling biolatency i have got this:
![Screenshot from 2023-02-23 23-52-56](https://user-images.githubusercontent.com/85415870/221049674-262af50e-aa86-44f9-b5a9-30da5d1c73c2.png)

But biolatency is no more working in Vector-pcp

**Comment by natoscott** [comment]
OK, well that's looking much healthier - for biolatency to function once more, we'll need that BCC issue I linked resolved.  Until then there is not much we can do in PCP.

**Comment by yahia-kr-coder** [comment]
I appreciate your help sir.

**Comment by yahia-kr-coder** [comment]
If you don't mind i have an other issue where i cant create a new unix user ( pcptestuser) and add it to the user database:

![Screenshot from 2023-02-24 00-13-43](https://user-images.githubusercontent.com/85415870/221052830-5c8ede1c-295e-40a2-b128-1de74d359705.png)

Because bpftrace-pcp is not working:

![Screenshot from 2023-02-24 00-02-04](https://user-images.githubusercontent.com/85415870/221052930-a7baf6e3-54dc-404e-bca4-a924e581ae59.png)

and the `bpftrac.log` shows this:
![Screenshot from 2023-02-24 00-02-46](https://user-images.githubusercontent.com/85415870/221052995-af743df9-2817-4089-b82c-2008fd9bb027.png)

**Comment by yahia-kr-coder** [comment]
If you don't mind i have an other issue with PCP-bpftrace where :
![Screenshot from 2023-02-24 00-02-04](https://user-images.githubusercontent.com/85415870/221055040-f791b274-59e9-4955-9c3e-e83c9ed2c8fa.png)

my `bpftrace.conf` is as follows
![Screenshot from 2023-02-24 00-03-34](https://user-images.githubusercontent.com/85415870/221055127-e21e1577-62c2-416a-88b8-3b45a9731ed6.png)

I have configured the required authentication:
![Screenshot from 2023-02-24 00-34-19](https://user-images.githubusercontent.com/85415870/221055420-5fd2cdec-797b-4f53-a732-e7994692b8fb.png)

my `bpftrace.log` is showing this:
![Screenshot from 2023-02-24 00-36-11](https://user-images.githubusercontent.com/85415870/221055628-79dc646b-b6ed-4d15-9ef1-c42aeb58e5bb.png)

**Comment by yahia-kr-coder** [comment]
I have an other question sir, where i cant' know which port to use in vector web application https://github.com/Netflix/vector.
