### ISSUE TITLE
pkgconfig .pc file for pcp-libs (Bugzilla #1095)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#176]
On 2014-12-05 08:47:50 -0600, Frank Ch. Eigler wrote:

> To ease conditional pcp clients' autoconf duties, we should
> include a pkg-config .pc file in pcp-libs-devel.
> 
> http://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by natoscott** [comment]
This was implemented years ago.
