### ISSUE TITLE
nfsclient PMDA is dying

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#1762]
Jeff Avila is seeing this in his HPC cluster (I'll add platform info once I have it).

It is serious because the PMDA dies, pmcd resets and in the process triggers IPC errors for pmlogger, and if the pmlogger is just starting (parsed config file, fetching metadata, not yet created the archive) then pmlogger cannot recover and dies ... so he's not getting critical PCP logs for HPC jobs.

```
Log for pmdanfsclient on [node1951.oscar.ccv.brown.edu](http://node1951.oscar.ccv.brown.edu/) started Wed May 31 12:22:57 2023

Traceback (most recent call last):
  File "/var/lib/pcp/pmdas/nfsclient/pmdanfsclient.python", line 1483, in <module>
    NFSCLIENTPMDA("nfsclient", 62).run()
  File "/var/lib/pcp/pmdas/nfsclient/pmdanfsclient.python", line 1477, in __init__
    self.nfsclient_refresh()
  File "/var/lib/pcp/pmdas/nfsclient/pmdanfsclient.python", line 599, in nfsclient_refresh
    client.xprt.srcport = values[1]
TypeError: bytes or integer address expected instead of str instance

Log finished Wed May 31 12:22:57 2023
```

**Comment by natoscott** [comment]
@kmcdonell pretty sure this one's fixed already via commit f4e34cd32bc73b53c2fc94c8deb670044d9d18d6
