### ISSUE TITLE
pmie_daily failed

### ISSUE THREAD

**Issue by humantex** [performancecopilot/pcp#1764]
I'm running Fedora Workstation 37, and occasionally there's a failed service start noted in Copilot. All updates are applied and current, as of 6/14/2023, 12:54 pm EST

`pmie_daily failed - see /var/log/pcp/pmie/pmie_daily.log`

**pmie_daily.log** contents:

```
/usr/libexec/pcp/bin/pmie_daily: line 532: /var/log/pcp/pmie/hp-705g3-dns-local/pmie.log.20230613: Permission denied
/usr/libexec/pcp/bin/pmie_daily: line 533: /var/log/pcp/pmie/hp-705g3-dns-local/pmie.log.20230613: Permission denied
pmie_daily: Error: problems moving logfile "/var/log/pcp/pmie/hp-705g3-dns-local/pmie.log" for host "local:"
[/etc/pcp/pmie/control.d/local:5] ... inference engine for host "local:" unchanged
xz: pmie.log.20230610.xz: Cannot set the file group: Operation not permitted
```

**pmie_daily.log.prev** contents:

`xz: pmie.log.20230609.xz: Cannot set the file group: Operation not permitted`

A reboot will clear the service alert, and appears to run the log, but checking a day later, the failed service will be noted again.

Screen grab of all 'pmi....' services from Copilot after rebooting:

![pmi-services](https://github.com/performancecopilot/pcp/assets/16087649/e4eca071-0b5a-4129-8c83-29dca0f0ade9)

**Comment by kmcdonell** [comment]
Hi @humantex I'm pretty sure this issue was recently fixed upstream via commit 5cab8aa53.
Your options are either wait for the next PCP release, or apply the simple patch as follows:
```
diff --git a/src/pmie/pmie_check.sh b/src/pmie/pmie_check.sh
index 84d557db4..3f3f57d51 100755
--- a/src/pmie/pmie_check.sh
+++ b/src/pmie/pmie_check.sh
@@ -839,6 +839,7 @@ NR == 3     { printf "p_pmcd_host=\"%s\"\n", $0; next }
                else
                    echo "---- from $prog @ `date` ---" >>$logfile.$SUMMARY_LOGNAME
                    cat $logfile >>$logfile.$SUMMARY_LOGNAME
+                   chown $PCP_USER:$PCP_GROUP $logfile.$SUMMARY_LOGNAME >/dev/null 2>&1
                fi
            fi
 
diff --git a/src/pmie/pmie_daily.sh b/src/pmie/pmie_daily.sh
index 2ff0d7ae8..b3fd492a5 100644
--- a/src/pmie/pmie_daily.sh
+++ b/src/pmie/pmie_daily.sh
@@ -549,6 +549,7 @@ NR == 3     { printf "p_pmcd_host=\"%s\"\n", $0; next }
                    _error "problems moving logfile \"$logfile\" for host \"$host\""
                    touch $tmp/err
                fi
+               chown $PCP_USER:$PCP_GROUP $logfile.$SUMMARY_LOGNAME >/dev/null 2>&1
            fi
        fi
```
to add the chown lines to pmie_daily and pmie_check (the latter is the more important one).

I'll leave this issue open for a while, pending any feedback from you.

**Comment by humantex** [comment]
I had one more instance with the service failing -but- nothing for several days after that, on up to today when doing another manual check and update. I never did see any notice that pcp was being updated, however, I do have security updates set to auto install, so it's possible that it was done w/o any notice from me.

Anyway... errors have disappeared, so might as well close this for now

**Comment by humantex** [comment]
Well, no sooner than posting that, rebooting after the system update, and waiting a day... it's back with the same service error. So... I'll just wait for the update.

**Comment by humantex** [comment]
Checked updates today and `pcp` shows in the list... and should be fixed, per: https://bugzilla.redhat.com/show_bug.cgi?id=2217209

**Comment by humantex** [comment]
After waiting to make sure, looks like the fix is working, and shows no more service failures.... closing.
