### ISSUE TITLE
JFrog repo returns 429 error on attempted update

### ISSUE THREAD

**Issue by scrufulufugus** [performancecopilot/pcp#1771]
# Description

The JFrog repository for CentOS/RHEL is returning and HTTP 429 when we attempt to update packages.

## Versions

```sh
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

## Reproduction

```
$ dnf update --disablerepo=* --enablerepo=performancecopilot
Updating Subscription Management repositories.
Performance Co-Pilot                                                                                       1.4 kB/s | 196  B     00:00
Errors during downloading metadata for repository 'performancecopilot':
  - Status code: 429 for https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/8/x86_64/repodata/repomd.xml (IP: 52.224.25.21)
Error: Failed to download metadata for repo 'performancecopilot': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

## /etc/yum.repo.d/performancecopilot.repo

```ini
[performancecopilot]
name=Performance Co-Pilot
baseurl=https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/$releasever/$basearch
enabled=1
gpgcheck=0
gpgkey=https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/$releasever/$basearch/repodata/repomd.xml.key
repo_gpgcheck=1
```

**Comment by edehde** [comment]
Requesting e.g. https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/8/x86_64/repodata/repomd.xml or https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/7/x86_64/repodata/repomd.xml reveals:

```
{
  "errors": [
    {
      "status": 429,
      "message": "You have reached your monthly quota for Data Transfer. To continue and start enjoying unlimited transfer, upgrade your subscription"
    }
  ]
}
```

Seems like PCP OSS project hit some JFrog limits for whatever reasons...

**Comment by natoscott** [comment]
We are encountering the issue discussed here:
https://www.reddit.com/r/linux/comments/13yld5j/jfrog_killing_their_free_debrpm_repo_tier_in_30/

@kmcdonell has put in a request for assistance for us as a long-standing oss project, so we'll see how we fare.

**Comment by webbnh** [comment]
> Requesting e.g. https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/8/x86_64/repodata/repomd.xml or https://performancecopilot.jfrog.io/artifactory/pcp-rpm-release/centos/7/x86_64/repodata/repomd.xml reveals:
> 
> ```
> {
>   "errors": [
>     {
>       "status": 429,
>       "message": "You have reached your monthly quota for Data Transfer. To continue and start enjoying unlimited transfer, upgrade your subscription"
>     }
>   ]
> }
> ```
It's now redirects to https://landing.jfrog.com/reactivate-server/performancecopilot which reports that "JFrog's Free-Tier subscription has been deactivated."

Is there any recommended alternative?

**Comment by scrufulufugus** [comment]
@natoscott the top comments of that Reddit post mention SUSE's [Open Build Service](https://build.opensuse.org/) as a good alternative.

**Comment by natoscott** [comment]
Yep - is there anyone out there who would be interested in helping with this transition?  (or funding our JFrog use?)
I'm flat out like a lizard drinking, and would love to get more people involved here.

One area where JFrog was good for us, where OBS is maybe not ideal, is that we've already built and QA'd the releases as part of our CI pipeline (using containers via github actions) and we'd prefer to use those bits, rather than yet another set of builds (this issue is mentioned in the 3rd or fourth comment in that reddit thread).

Another option might be gemfury.com also mentioned in that thread.

Yet another idea that @christianhorn put forward yesterday would be to see if its possible to host the packages via github releases with some apt/dnf repo magic.

**Comment by natoscott** [comment]
We've transitioned to using the services of the kind folk at [Packagecloud.io](url) now.

Please update your local repos to https://packagecloud.io/performancecopilot/pcp
