### ISSUE TITLE
Push PCP metrics to Prometheus 

### ISSUE THREAD

**Issue by mallilinux1980** [performancecopilot/pcp#1777]
How to expose pcp metrics to Prometheus? Can fluentbit be leveraged push metrics to Prometheus remote write?

**Comment by natoscott** [comment]
pmproxy(1) provies a /metrics endpoint - see the pmwebapi(3) man page for more details.

**Comment by mallilinux1980** [comment]
Actual question was around how to push metrics to Prometheus instead of Prometheus pulling from target pmproxy which may not suit well for enterprise environment.

**Comment by natoscott** [comment]
To achieve what you're after we'd need a pcp2prometheus or pcp2openmetrics utility I think.  It doesn't exist yet but there are many similar tools in PCP - it would be great if someone were to take this one on (little python project).

**Comment by natoscott** [comment]
Some sample python code I wrote a little while ago that may be useful here.
It show's how to convert PCP metric metadata into openmetrics format:
https://gist.github.com/natoscott/5186664bab2ebbba8e7596f81d3d5feb

**Comment by mallilinux1980** [comment]
Thanks for prompt response.

we’re thinking to use this as an alternative provided fluentbit is enabled every collector host. Do you have any thoughts or concerns?

https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-remote-write#

**Comment by natoscott** [comment]
No reason it wont work AFAICT.  It would be more efficient to combine the pcp2json+fluentbit into a single pcp2openmetrics script though, but I guess you need to work with what is available today.

**Comment by natoscott** [comment]
pcp2openmetrics(1) exists since pcp-6.2.1.
