### ISSUE TITLE
--container=NO_SUCH_CONTAINER succeeds (Bugzilla #1111)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#179]
On 2015-05-14 21:17:50 -0500, Frank Ch. Eigler wrote:

> % pminfo -f pmcd.hostname --container=NO_SUCH_CONTAINER
> 
> gives out host hostnames.  (Some metrics sometimes do
> seem to return "container does not exist" errors, but
> this is not consistent.)

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here - feel free to send patches though.
