### ISSUE TITLE
pcp cross-compile

### ISSUE THREAD

**Issue by joseii** [performancecopilot/pcp#18]
Hi, 
I am working on a project for IoT and it seems pcp would fit quite well to it.
I am trying to cross-compile the code for an arm architecture on a linux machine, however on the config phase (./config --host=linux-arm), the script skips the section to set the ps command when it is "checking the ps style".
Since the variable that sets the ps model is not set, the ps style is unknown and the scripts exits.

My target machine has a busybox, and the ps behavior is different from the system I am compiling the code. 
Does it make sense to cross compile?
I can also cross compile specific versions of ps, grep, whatever I need, but it is not clear to me if these binaries are being used to the compilation part (on my linux machine) or if they they are used to parse the output on my target machine.

**Comment by natoscott** [comment]
> Does it make sense to cross compile?

Sounds like it, yes.  (although you might be able to use the pre-built Fedora arm64 packages?)

If you wish to cross-compile, you will need to inject some results for certain configure checks, as appropriate for your target platform - see the config.mingw file, and the configure.ac section around line 175...

if test "$cross_compiling" = "yes"; then
    if test -f ./config.$target_os; then
        . ./config.$target_os

cheers.
