### ISSUE TITLE
documentation of new exported pmapi functions (Bugzilla #1126)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#180]
On 2015-11-24 08:55:39 -0600, Frank Ch. Eigler wrote:

> New exported functions have been added to pmapi (libpcp/src/exports), such as __pmStringValue etc., without documentation.  If they are important enough to be put into libpcp for use by multiple packages, they should be covered in a man page.  If they are not important enough, they should not be in libpcp.  Prefixing with __ just ducks the issue.
> 
> The HACKING file should be extended to be more explicit about new APIs, and set a goal to bring old APIs to that standard too.

**Comment by natoscott** [comment]
There are no current plans to document these functions, feel free to open a PR though.
