### ISSUE TITLE
pcp netstat and meminfo runs in loop

### ISSUE THREAD

**Issue by orasagar** [performancecopilot/pcp#1804]
@mohith-kumar-thummaluru 
There are two issues I have observed with the netstat and meminfo utilities they are following:-
1 After running the utility it should by default give one sample output only , which is not happening in the two utility cases.
2. In the header of the output machine info should be printed which is missing in these two utilities which makes them inconsistent among other pcp tool

**Comment by mohith-kumar-thummaluru** [comment]
@orasagar The issues mentioned above are handled in the following pull requests, which are merged
- https://github.com/performancecopilot/pcp/pull/1805
- https://github.com/performancecopilot/pcp/pull/1806
