### ISSUE TITLE
context inappropriate connection sharing logic incomplete (Bugzilla #1128)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#182]
On 2015-11-24 09:44:06 -0600, Frank Ch. Eigler wrote:

> Connection sharing protections in commit ec7da652c etc. does not do a complete job: it ignores that pmDupContext and subsequent pmStore container-changing on one copy will affect both clients.  Similarly, two container-less pmNewContexts, one of which gets a container-changing pmstore.  Problem found by inspection.  Indirectly confirmable by number of connections / pmcd.client tuples associated with such an application: just 1. 
> 
> http://oss.sgi.com/pipermail/pcp/2015-October/008595.html
> 
> PS.  The pmcd.client\* metrics should be documented with respect to their peculiar pmStore semantics (incoming instance#s ignored & redirected to the current client, which makes sense because the instance numbers aren't meaningful to pmapi clients in the first place).

On 2016-03-14 21:07:31 -0500, Michael Walton wrote:

> **\* Bug 1139 has been marked as a duplicate of this bug. ***

**Comment by fche** [comment]
This bug has been fixed by disabling connection sharing altogether.

**Comment by kmcdonell** [comment]
Thanks Frank.
