### ISSUE TITLE
pmlogger went crazy

### ISSUE THREAD

**Issue by GerryHickman** [performancecopilot/pcp#1833]
pcp-6.0.1-5.el9_2.x86_64

I've been running a pmlogger farm for a long time, with no problems.
This week, I noticed high 'kernel.all.cpu.sys', but 'kernel.all.cpu.user' was normal (strange in itself).
I noticed a huge number of exec calls (new processes) related to pmlogger.
Thousands of these in a few seconds:

```
grep             2407324 2407300   0 /usr/bin/grep -E ^/var/log/pcp/pmlogger/webwsts01/[^/]*$ /var/lib/pcp/tmp/pmlogger/18603
grep             2407326 2407300   0 /usr/bin/grep -q -e \.rpmsave$ -e \.rpmnew$ -e \.rpmorig$ -e \.dpkg-dist$ -e \.dpkg-old$ -e \.dpkg-new$
grep             2407327 2407300   0 /usr/bin/grep -E ^/var/log/pcp/pmlogger/webwsts01/[^/]*$ /var/lib/pcp/tmp/pmlogger/20831
grep             2407329 2407300   0 /usr/bin/grep -q -e \.rpmsave$ -e \.rpmnew$ -e \.rpmorig$ -e \.dpkg-dist$ -e \.dpkg-old$ -e \.dpkg-new$

```
I tried to check the PPID (parent pid) to identify the caller, but these were very short lived processes, and the pid was gone.
Something is wrong here anyway, /var/log/pcp/pmlogger/ does not have any "hostname" subdirs.
After stopping all timers and restarting all pmlogger services, everything returned to normal (very low cpu etc), but after ten minutes it's gone crazy again.

**Comment by kmcdonell** [comment]
OK @GerryHickman this is going to take a bit of tracking down.

The only place I can see in the source code that has grep usage that matches what you're seeing is pmlogctl.

And pmlogctl is really only going to be launched automatically from the pmlogger_farm_check.service.

What does systemctl say about the status of pmlogger_farm?

I'd be interested in the output from: $ pmlogctl -NV -m check

**Comment by GerryHickman** [comment]
I think the issue is with 'pmlogger_farm_check.service', as opposed to 'pmlogger_farm.service'. In other words, the pmlogger farm is working correctly, but the "check" is failing.

In my environment, I have $PCP_ARCHIVE_DIR set to '/data/pcp/pmlogger', as opposed to '/var/log/pcp/pmlogger'

I think 'pmlogger_farm_check.service' is looking in the wrong place.

Running 'pmlogctl -NV -m check' shows hundreds of errors where it's looking in the wrong place.

**Comment by kmcdonell** [comment]
OK.  It is pmlogger_farm_check that is running pmlogctl.
Can you please send me one of your /etc/pcp/pmlogger/control.d files and the matching output from pmlogctl -NV -m check for this control file?
And the output from $ grep -E 'PCP_ARCHIVE|PCP_LOG' /etc/pcp.conf please.
And finally, are you aware of any configuration changes or package updates prior to things going pear-shaped?

**Comment by GerryHickman** [comment]
The first step was to stop
```
pmlogger_farm_check.timer
pmlogger_farm_check.service
```
At this point, the server returned to normal, cpu close to zero, no more process explosion.

Running the check manually
`/usr/bin/pmlogctl -NVV -m check`
showed that it was looking for the pmlogger archive files in the wrong place.
(but it doesn't explain why 'pmlogctl' went into a suspected infinite loop).
The default location for archive logs is '/var/log/pcp/pmlogger', but I'm using 'PCP_ARCHIVE_DIR'.

Looking at 'pmlogctl', I see a function
`line 549: _expand_control()`
has this search / replace line
`-e "s;PCP_ARCHIVE_DIR/;$PCP_LOG_DIR/pmlogger/;g" \`
NOTE, it's changing the archive dir back to the default, but why?
after changing this line in 'pmlogctl', the output now says "Nothing to do".

I also noticed it thinks my host names are "regex", not sure why, but they do have a hyphen in them.
`abcd-webserver01`.

**Comment by kmcdonell** [comment]
@GerryHickman Good catch on PCP_ARCHIVE_DIR ... that is wrong (and variants of the same mistake appear in multiple places within pmlogctl).  I've fixed these now ... would you be able to drop in a replacement pmlogctl to confirm it works for you? 
The looping is (I suspect) because pmlogctl is failing badly.
I am curious about the "regex" comment ... how did you [notice] it thinks my host names are "regex"?  The test in the code is for ^[a-zA-Z0-9][a-zA-Z0-9.-]*$ as NOT regex which would seem to match abcd-webserver01

**Comment by GerryHickman** [comment]
Regarding the changes made in '1253363'.
They look exactly like my local copy, which I've already tested.

**Comment by GerryHickman** [comment]
Regarding why the script goes into an infinite loop.
It uses a lot of global scope, including with dot sourced scripts which assume variables or tmp files will exist and make sense. My own bash scripts start with 'set -u' which puts them into strict mode, but I don't know if that works (or helps) with this style of 'sh' scripts.

**Comment by GerryHickman** [comment]
Regarding why the host is seen as a "regep host".
Is there some confusion between '_host' and just 'host'?
function
```
_get_matching_hosts()
if [ $# -eq 0 ]
set -- '[^#$]'
for _host; do
if echo "$_host" | grep '^[a-zA-Z0-9][a-zA-Z0-9.-]*$' >/dev/null
It appears to be setting _host to regexp '[^#$]', and then piping it into grep?


```
