### ISSUE TITLE
investigate automatic pmReconnectContext (Bugzilla #1131)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#184]
On 2015-12-14 08:52:26 -0600, Frank Ch. Eigler wrote:

> If we can guarantee that a post-reconnection pmcd will not give rise to harmful conflicts with cached metadata (e.g., changed name->pmid or pmid->type/unit/scale or indom changes), then we should do pmReconnectContext() within libpcp, so that pmapi applications don't have to worry about temporarily dropped connections.

**Comment by natoscott** [comment]
No further work is currently planned on this area.
