### ISSUE TITLE
libvirt PMDA is missing from centos7 release

### ISSUE THREAD

**Issue by Tualua** [performancecopilot/pcp#1842]
Hello!

libvirt PMDA is available only for centos8 and newer. Is there a reason for it?

**Comment by kmcdonell** [comment]
This PMDA needs the Python (version 3.6.8 in this case) module for libvirt.  As far as we can tell, this module is not available for CentOS 7, so the PCP packages do not include the libvirt PMDA.

**Comment by Tualua** [comment]
There is python36-libvirt package in EPEL which works.

```
diff --git a/build/rpm/pcp.spec.in b/build/rpm/pcp.spec.in
index 80280c2..a5161f8 100755
--- a/build/rpm/pcp.spec.in
+++ b/build/rpm/pcp.spec.in
@@ -1771,8 +1771,12 @@ Requires: python3-pcp python3-lxml
 %if "%{_vendor}" == "suse"
 Requires: python3-libvirt-python
 %else
+%if "%{rhel}" == "7"
+Requires: python36-libvirt
+%else
 Requires: libvirt-python3
 %endif
+%endif
 %else
 Requires: %{__python2}-pcp
 Requires: %{__python2}-lxml
```
I worked out a patch and built pcp from source. It works.

![image](https://github.com/performancecopilot/pcp/assets/32481693/bf6beb81-55db-4a72-a124-06d4670e5a28)

**Comment by kmcdonell** [comment]
Thanks for this @Tualua.
I've reworked your patch slightly and added the necessary pcp package list changes ... this is all in commit 68edd7c60.
I'll close the issue, please re-open if this does not OK to you.

**Comment by Tualua** [comment]
Hello! As I understand, this commit is included in 6.2.1, I just built RPMs from 6.2.1 source and still got the same error

```--> Finished Dependency Resolution
Error: Package: pcp-pmda-libvirt-6.2.1-1.x86_64 (pcp)
           Requires: libvirt-python3
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest```

I looked through your patch and found that you're checking centos version only. You need to check also for rhel, like in my patch to cover Oracle Linux 7

**Comment by Tualua** [comment]
Please open this issue as it is not completed and doesn't solve the original problem

**Comment by Tualua** [comment]
https://github.com/performancecopilot/pcp/pull/1962
