### ISSUE TITLE
linux pmda does too much work for process queries (Bugzilla #1141)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#185]
On 2016-04-08 06:22:28 -0500, Frank Ch. Eigler wrote:

> +++ This bug was initially created as a clone of Bug # 1067 +++
> 
> The analogous issue has long existed and been long reported in the proc pmda.  A large amount of extra /proc scanning work is done for queries related to individual metrics / individual processes.  This makes it more likely that the pmda interferes with the kernel (competing for process-table locks), and times out.  That in turn in effect kills the pmda.  (See also bug # 1036, bug # 1079).
> 
> The phenomenon is easily observed with strace.
> 
> For example: a % pmval -i $$ proc.psinfo.ppid 
> involves reads to /proc/$$/stat, /wchan, /environ, only one of which was needed.
> 
> For example: an active hotproc pmda scans multiple proc files for every process, even if hotproc metrics are not being fetched; even involving files not necessary to evaluate the hotproc selection criteria.

On 2016-04-08 09:11:17 -0500, Frank Ch. Eigler wrote:

> For example, the three proc.\* metrics commonly included in default pmlogger configurations (proc.runq.blocked, proc.runq.runnable, proc.nprocs) require little to no actual /proc/_/{stat,cmdline} traffic.  The values in /proc/stats and /proc/loadavg, and possibly a directory enumeration of /proc/_ (to count processes vs. threads) should satisfy the metrics.  Instead the pmda goes through a "refresh", checking per-process stats and command lines and stuff.  Unnecessary.

**Comment by lukas999** [comment]
I had an interesting observation while playing with errsnoop SystemTap script. It seems that the pmdaproc process has maybe 200 of failed open syscalls with 6/ENXIO error on /etc/passwd and /etc/group in RHEL7.2, PCP 3.11.9 plus some more. The display period seems to be at about 4 seconds and the pmdaproc lines appear once per two perdiods.

Although this may not have a big impact, it may give a hint for improvement. This is what I see for pmdaproc:

# stap errsnoop.stp 
HITS ERRSTR                 SYSCALL         PROCESS   PID ARGSTR
 224   6/ENXIO                 open        pmdaproc  1098 "/etc/group", O_RDONLY|O_CLOEXEC
 224   6/ENXIO                 open        pmdaproc  1098 "/etc/passwd", O_RDONLY|O_CLOEXEC
 161  90/EMSGSIZE         read        pmdaproc  1098 6, 0x7ffc5b13e190, 1024
  94  14/EFAULT               read        pmdaproc  1098 6, 0x7ffc5b13e190, 1023
  42  11/EAGAIN                read        pmdaproc  1098 6, 0x7ffc5b13e190, 1024
  37  12/ENOMEM             read        pmdaproc  1098 6, 0x7ffc5b13e190, 1024
  34  13/EACCES              read        pmdaproc  1098 6, 0x7ffc5b13e190, 1023
  32  17/EEXIST               read        pmdaproc  1098 6, 0x7ffc5b13e190, 1023
  24  21/EISDIR                read        pmdaproc  1098 6, 0x7ffc5b13e190, 1023
  23   7/E2BIG                  read        pmdaproc  1098 6, 0x7ffc5b13e190, 1023

**Comment by fche** [comment]
For reference, note that on one busy server (sourceware.org, hundreds of processes running, dozens per second turning over) where git-master-level pcp is generally running, the proc pmda fails frequently.  In this case, within 7 minutes (!!!) of startup: 

Log for pmcd on sourceware.org started Fri Jun 30 14:23:11 2017
[...]
[Fri Jun 30 14:30:24] pmcd(96182) Warning: pduread: timeout (after 5.000 sec) while attempting to read 12 bytes out of 12 in HDR on fd=12
[Fri Jun 30 14:30:24] pmcd(96182) Info: CleanupAgent ...
Cleanup "proc" agent (dom 3): protocol failure for fd=12

Now yeah, auto-pmda-restart may work.  But such a short MTBF indicates and a design problem that a periodic rate-controlled restart cannot adequately work around.

**Comment by goodwinos** [comment]
The dynamic nature of per-process data may require a more efficient export mechanism - /proc/PID/{psinfo,status,etc} is hardly efficient. Maybe a bcc module could provide a more direct output for the process table and various fields of struct task_struct, mm_struct, etc.  - this could perhaps eliminate the kernel text encoding and decoding overheads and all the problematic parsing goop that goes with it.

**Comment by fche** [comment]
The problem with the `/proc/PID/....` files is not really their textual content.  That's just a matter of a bit of userspace CPU.  The bigger problem is that each time such a `/proc` file is opened, the kernel must take & release process-table-related locks.  In the presence of a busy server (with lots of process/thread turnover), and pcp doing *unsolicited* polling of `/proc/*` files/directories, that lock contention appears to lead to regular timeouts.

It would be better if procpmda never polled unsolicited proc files/directories.

**Comment by jasonk000** [comment]
Hi @goodwinos is this likely to get any movement do you think?

On our container hosts, querying 5 containers, for 6 metrics, once per second results in over 100K syscalls per second from pmdaproc. IOW well over 3000 syscalls per fetched metric.

```
[19:39:10]
SYSCALL                   COUNT
stat                      82860
getdents                   8080
close                      4070
openat                     4070
fstat                      4070
read                        450
sendto                       10
write                        10
recvfrom                     10

```

**Comment by goodwinos** [comment]
Hi Jason, there have been some important bugfixes and improvements in the proc PMDA recently, e.g.

```
commit 4a2cef6023390d2b8f645012de449ce2c657dbfe
Author: Nathan Scott <nathans@redhat.com>
Date:   Tue Aug 6 10:18:03 2019 +1000
    pmdaproc: remove legacy /proc/ksyms and System.map readers

commit 775bd386c2b9a6e553c61a5c0f86d29d9c2320a8
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Thu Jul 25 13:30:05 2019 +1000
    pmdaproc: fix memory leak in pidlist refresh
    RHBZ #1721107
```

The above two fixes went into pcp-4.3.4. The memory leak was particularly nasty on large systems with high process churn.

What version of PCP are you running in your containers? And which 6 metrics are you fetching? As @fche suggests, there may be scope for improving the refresh granularity.

**Comment by fche** [comment]
see also https://github.com/performancecopilot/pcp/issues/191

**Comment by jasonk000** [comment]
> What version of PCP are you running in your containers?

4.3.2 at present, we can look into upgrading.

> And which 6 metrics are you fetching?

```
      - cgroup.cpuacct.usage
      - cgroup.cpusched.shares
      - cgroup.cpusched.cfs_quota
      - cgroup.memory.limit
      - cgroup.memory.stat.rss
      - cgroup.memory.stat.cache
```

**Comment by goodwinos** [comment]
Hi Jason, here's a script that reproduces your issue - see below. Running the script on my laptop shows over 18000 stat calls for each refresh/fetch of the 6 cgroup metrics when run in local context mode (-L flag to pminfo). The stat() calls are from cgroup_scan(), which is recursive :

```
#! /bin/sh
. /etc/pcp.env

pmdalinux=$PCP_PMDAS_DIR/linux/pmda_linux.so,linux_init
pmdaproc=$PCP_PMDAS_DIR/proc/pmda_proc.so,proc_init

strace -c pminfo -L -K clear -K add,60,$pmdalinux -Kadd,3,$pmdaproc -d -f \
    cgroup.cpuacct.usage cgroup.cpusched.{shares,cfs_quota} \
    cgroup.memory.{limit,stat.rss,stat.cache} >/dev/null
```

And here's the output on my mostly idle laptop :

```
$ sudo ./cgroup_strace.sh 
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 51.95    0.064658           3     18492           stat
 14.53    0.018084           4      3983           openat
 10.50    0.013070           3      4082           read
  7.88    0.009809           2      3983           close
  7.36    0.009158           2      3985           fstat
  6.46    0.008034           4      1684           getdents64
  0.67    0.000832           4       181           mmap
  0.17    0.000216           3        69           brk
  0.16    0.000197           3        55           mprotect
  0.13    0.000163           2        59           lseek
  0.05    0.000058           3        17           write
  0.03    0.000039          19         2           connect
<snip>
```

Looking at the detailed strace, there are a lot of paths being stat'd more than once, e.g.

```
$ grep ^stat output  | sed -e 's/stat("//' -e 's/",.*$//' | sort | wc -l
18494
```

With a unique sort, looks like we're doing roughly 3x more stat calls than may be necessary 

```
$ grep ^stat  output | sed -e 's/stat("//' -e 's/",.*$//' | sort -u | wc -l
6869
```

Even that sounds excessive. I'll investigate some more.

**Comment by natoscott** [comment]
Much work was done in this area - please open a new issue if any other, specific perf issues are found.
