### ISSUE TITLE
pcp2json doesn't support pmrep config derived metricsets

### ISSUE THREAD

**Issue by dustinblack** [performancecopilot/pcp#1870]
The man page for pcp2json seems to imply that it supports the same metricset definitions as pmrep. However, testing and some code review seems to show that no derived metricsets in the form of `:metricsetname` are supported.

This seems to be an oversight in either the code or the documentation, and either way I think needs a fix.

**Comment by natoscott** [comment]
@myllynen any thoughts?

**Comment by myllynen** [comment]
I would have expected it to work. I can investigate this a bit in 2-3 weeks from now to see what's going on. Thanks.

**Comment by myllynen** [comment]
I managed to had a quick look at this since this sounded familiar.. Indeed, support for using pmrep config files was added in https://github.com/performancecopilot/pcp/commit/7d700d56c4eef8fb7fd98c4d734ed2a103eb958f.

However, pcp2json and friend do not by default read the pmrep's config dir /etc/pcp/pmrep. To use the metricsets provided by default you could do:

`pcp2json -c /etc/pcp/pmrep/vmstat.conf -s 2 -t 0.2 :vmstat`

Perhaps we could make the out-of-the-box experience smoother by tweaking the default configs pcp2json is checking?

**Comment by dustinblack** [comment]
It's been a little while, so I'd have to go back an confirm it, but I believe I have tried pointing `pcp2json` directly to both the config directory and individual config files in `/etc/pcp/pmrep` with no change to the behavior.

**Comment by dustinblack** [comment]
```
$ podman run -it --rm --entrypoint=/bin/bash quay.io/arcalot/arcaflow-plugin-pcp:latest
[root@1b97a911b3fe arcaflow_plugin_pcp]# rpm -qa |grep pcp
pcp-libs-5.3.7-18.el8.aarch64
python3-pcp-5.3.7-18.el8.aarch64
pcp-system-tools-5.3.7-18.el8.aarch64
pcp-conf-5.3.7-18.el8.aarch64
pcp-5.3.7-18.el8.aarch64
pcp-export-pcp2json-5.3.7-18.el8.aarch64
[root@1b97a911b3fe arcaflow_plugin_pcp]# /usr/libexec/pcp/lib/pmcd start
Starting pmcd ... 
[root@1b97a911b3fe arcaflow_plugin_pcp]# /usr/bin/pmlogconf pmlogger.conf
Creating config file "pmlogger.conf" using default settings ...
................................................................................
[root@1b97a911b3fe arcaflow_plugin_pcp]# /usr/bin/pmlogger -c pmlogger.conf -t 1 pmlogger-out
[root@1b97a911b3fe arcaflow_plugin_pcp]# /usr/bin/pcp2json -c /etc/pcp/pmrep -s 2 -t 0.2 :vmstat
Invalid metric no (PM_ERR_NAME Unknown metric name).
[root@1b97a911b3fe arcaflow_plugin_pcp]# /usr/bin/pcp2json -c /etc/pcp/pmrep/vmstat.conf -s 2 -t 0.2 :vmstat
Invalid metric no (PM_ERR_NAME Unknown metric name).
```

**Comment by myllynen** [comment]
The PCP version is missing the needed patches so it doesn't work with metricsets. I tried your example and saw what you saw, then manually applied the needed patches and it started working. Thanks.

**Comment by dustinblack** [comment]
Confirmed on my end. Thanks for the help @myllynen !
