### ISSUE TITLE
security bug (information disclosure) in linux-proc pmda - case 2: old kernel (Bugzilla #1102)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#189]
On 2015-01-02 12:35:03 -0600, Frank Ch. Eigler wrote:

> The finding at the tail end of 
> http://oss.sgi.com/pipermail/pcp/2014-November/006062.html
> is reproduced thusly on 3.9.10, on a 2.6.18-398.el5 kernel.
> (3.9.10 happens to be freshest on epel-testing.)
> (# - run as root;  % - run as unprivileged user)
> # sudo service pmcd restart
> 
> % cat /proc/1/maps
> cat: /proc/1/maps: Permission denied
> % pmval -s 1 -i 1 proc.memory.maps
> [...]
>           1
>          ""
> [i.e., value not available ... though no error, hm]
> # service pmcd restart
> # pmval -s 1 -i 1 proc.memory.maps
> 
> [...shows results, as expected...]
> % pmval -s 1 -i 1 proc.memory.maps
> [...shows results, as unexpected!...]
> 
> In this case, unlike for bug # 1101, the kernel does report
> a read error (EACCES) for the proc/1/maps file descriptor,
> so the new client is not permitted to get new data.  But...
> The pmda (due to its "refresh" caches?) goes on to supply
> stale and confidential data to the unprivileged pcp client.

On 2015-05-06 21:32:56 -0500, Nathan Scott wrote:

> This is not reproducible here with current code ... will close out soon unless someone has more details or is still able to reproduce it.
> 
> thanks.

On 2015-05-14 21:00:30 -0500, Frank Ch. Eigler wrote:

> proc.memory.maps doesn't show it for some reason, but proc.psinfo.environ does.  Those "refresh" cache mechanism is itself suspect (also as per bug # 1067).

On 2015-05-15 09:13:00 -0500, Martins Innus wrote:

> Created [attachment](https://gist.github.com/pcpemail/36a5d362bbcc58975a211cbe6d33b298)
> environ access patch
> 
> Frank,
> 
> ```
> Can you try this patch? Fixes environ for me for this case. Copied from the maps guard, we missed this in the initial implementation.
> ```
> 
> Thanks
> 
> Martins

On 2015-05-19 20:02:47 -0500, Nathan Scott wrote:

> (In reply to comment # 3)
> 
> > ```
> > Can you try this patch? Fixes environ for me for this case. Copied from
> > ```
> > 
> > the maps guard, we missed this in the initial implementation.
> 
> Yep, that patch is definitely correct & merged now, thanks Martins.

**Comment by natoscott** [comment]
Martins' fix was merged years over 5 ago.
