### ISSUE TITLE
fuzzy container hex-id naming leads to nondeterminism (Bugzilla #1109)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#190]
On 2015-05-14 19:33:06 -0500, Frank Ch. Eigler wrote:

> Consider 
> 
> % pmval pmcd.hostname --container 0
> 
> relying on src/pmdas/root/docker.c docker_name_matching's fuzzy code.
> With that running, now start some docker jobbies, enough to get some
> with a hex 0DEADBEEF instance-id:
> 
> % for i in `seq 30`
> do
> docker run --rm busybox sleep 200 </dev/null &
> done
> 
> Wait a while and do it again.
> 
> Observe how pmval's output will change periodically, depending on
> which container it happens to match; what containers and other copies
> of pmval happened to be running at the moment when it first connected;
> how containers die and get born.
> 
> In short, it is a non-identifying identifier, even within the lifetime
> of a single pcp client.

On 2015-05-14 20:16:02 -0500, Nathan Scott wrote:

> (In reply to comment # 0)
> 
> > [...]
> > In short, it is a non-identifying identifier, even within the lifetime
> > of a single pcp client.
> 
> Hmm.  By design, what is supposed to be happening is the "fully qualified" name (once looked up via the docker fuzzy matching, just like the docker client tools do) is returned to the requesting PMDA, which can then use it as a unique identifier going forward in subsequent requests - rendering this a non-issue.
> 
> However, on inspection it would appear that only the cgroups PDU is actually doing this - will need to go back and resolve the PID PDU at least, possible one or two others.
> 
> Thanks for the test case, its almost a QA test already.

On 2015-05-14 21:14:24 -0500, Frank Ch. Eigler wrote:

> > Hmm.  By design, what is supposed to be happening is the "fully qualified"
> > name (once looked up via the docker fuzzy matching, just like the docker
> > client tools do) is returned to the requesting PMDA, which can then use it
> > as a unique identifier going forward in subsequent requests - rendering this
> > a non-issue.
> 
> Even if this were done, it still makes the mapping non-deterministic,
> because more than one container can match that substring; a client has
> no way of knowing whether its choice was unique.  Emulating the docker
> client's apparent non-determinism is not obviously necessary.
> 
> We could instead say that the name matching is done exactly once (at
> connection time), and fails if ambiguous.

On 2015-05-14 21:36:56 -0500, Nathan Scott wrote:

> (In reply to comment # 2)
> 
> > a client has
> > no way of knowing whether its choice was unique.
> 
> A user can choose to use unique names at any time, this fuzzy matching is only there to give users the behaviour they know and expect based on using the Docker tools.
> 
> > We could instead say that the name matching is done exactly once (at
> > connection time), and fails if ambiguous.
> 
> No, definitely not - that's not sensible behaviour from the users point of view.
> People expect to be able to specify containers just like they would with Docker - we have already seen this from several people using this already (without it, would have seen several bug reports & confusion).
> 
> It's an important usability issue, it absolutely must match Docker behaviour.  The whole point of the fuzzy matching is to provide the behaviour that users expect (same reason why a docker: prefix on all names was never going to fly).

On 2015-05-14 21:42:32 -0500, Mark Goodwin wrote:

> Why can't we just use the 12 hex digit abbreviations that docker commands like 'docker ps' and so forth use by default?
> # docker ps --no-trunc -q
> 
> SHA: ca3f061a18b548d6faa92276a86b479c96fd335c9e7ffe39c8206c384c27e229
> # docker ps -q
> 
> ca3f061a18b5
> 
> 16^12 is a big number
> 
> Allow either the 12 digit abbreviated container id, or it's full name, no fuzzy required ..?

On 2015-05-14 21:46:46 -0500, Nathan Scott wrote:

> (In reply to comment # 4)
> 
> > Why can't we just use the 12 hex digit abbreviations that docker commands
> > like 'docker ps' and so forth use by default?
> 
> Docker allows many more than just those two options... and there's also the human-readable names.
> 
> cheers.

On 2015-05-14 21:49:20 -0500, Frank Ch. Eigler wrote:

> > It's an important usability issue, it absolutely must match Docker
> > behaviour.  The whole point of the fuzzy matching is to provide the
> > behaviour that users expect
> 
> According to a little experiment here, docker-1.6 (f21) actually behaves
> in the way that I proposed: ambiguous container prefixes are rejected.
> Try:
> 
> % for i in `seq 20`  
> do
> docker run --rm busybox sleep 128 </dev/null &
> done
> 
> over and over until you get some containers with the same first-two bytes 0xAB.
> Then try
> 
> % docker inspect AB
> 
> you will see docker reject it.  Then do:
> 
> % docker kill ABFIRST ABSECOND # but not ABLAST
> 
> Then wait a moment, then
> 
> % docker inspect AB
> 
> will now be accepted and describe ABLAST.  I haven't inspected docker golang
> code to confirm.
> 
> > (same reason why a docker: prefix on all name was never going to fly).
> 
> Then you suffer collisions between docker and non-docker container
> namespaces: something irrelevant to docker end-users but significant
> to a sysadmin with both lxc & docker on the system.
> 
> (Again I don't mind heuristics, but they should be unambiguous.)

On 2015-05-14 22:03:40 -0500, Nathan Scott wrote:

> (In reply to comment # 6)
> 
> > > It's an important usability issue, it absolutely must match Docker
> > > behaviour.  The whole point of the fuzzy matching is to provide the
> > > behaviour that users expect
> > 
> > According to a little experiment here, docker-1.6 (f21) actually behaves
> > in the way that I proposed: ambiguous container prefixes are rejected.
> 
> OK, sold - we should follow that.
> 
> > > (same reason why a docker: prefix on all name was never going to fly).
> > 
> > Then you suffer collisions between docker and non-docker container
> > namespaces: something irrelevant to docker end-users but significant
> > to a sysadmin with both lxc & docker on the system.
> 
> Right, and when we see a real world site like that, then we should start
> thinking about this as a non-academic exercise.  It's solvable, keeping current behaviour too - its just the number of people for whom it will ever be an issue makes it not worth worrying about in the short/medium-term, probably even in the long term, really.

On 2015-07-15 08:16:34 -0500, Frank Ch. Eigler wrote:

> (In reply to comment # 7)
> 
> > > According to a little experiment here, docker-1.6 (f21) actually behaves
> > > in the way that I proposed: ambiguous container prefixes are rejected.
> > 
> > OK, sold - we should follow that.
> 
> Considering "It's an important usability issue, it absolutely must match Docker behaviour.", how is that going?

On 2015-08-11 18:16:31 -0500, Nathan Scott wrote:

> (In reply to comment # 8)
> 
> > (In reply to comment # 7)
> > 
> > > > According to a little experiment here, docker-1.6 (f21) actually behaves
> > > > in the way that I proposed: ambiguous container prefixes are rejected.
> > > 
> > > OK, sold - we should follow that.
> > 
> > Considering "It's an important usability issue, it absolutely must match
> > Docker behaviour.", how is that going?
> 
> Hmm, somehow missed this question earlier.  The "important usability issue ... must match Docker" refered to being able to specify Docker containers in both shortened form (as in, "docker ps" form), full long ID form, or via their human readable name - all of which are sensibly unique for some value of sensible, IMO.
> 
> Handling bizarre input like --container=0 or similar can certainly be improved, as discussed, but I don't think it warrants higher priority than the many other issues / requests from actual users.  I'll get back to it as soon as I can though, fear not.

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here - feel free to send patches though.
