### ISSUE TITLE
excessive workload in pmdaroot for --container clients (Bugzilla #1110)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#191]
On 2015-05-14 19:51:15 -0500, Frank Ch. Eigler wrote:

> Each and every pcp client fetch to a container-aware metric involves IPC and context-switching to-from pmdaroot.  For example, during the operation of bug # 1109, an strace over pmdaroot shows:
> 
> recvfrom(6, "\1\220\0\0\32\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\2\0\0\0000\0", 8192, 0, NULL, NULL) = 26
> stat("/var/lib/docker/containers", {st_mode=S_IFDIR|0700, st_size=20480, ...}) = 0
> stat("/var/lib/lxc", 0x7ffd4bab1310)    = -1 ENOENT (No such file or directory)
> stat("/var/lib/docker/containers/SHA: 1a478e901ca8e98da2d02060c89a480a6d016ba33d30a3947004ae2538892049/config.json", {st_mode=S_IFREG|0644, st_size=2034, ...}) = 0
> stat("/var/lib/docker/containers/SHA: 113bb058e2c31e009230cb7b381182384794f8115b6e1ce9a9dc5a06ac6f63c9/config.json", {st_mode=S_IFREG|0644, st_size=2033, ...}) = 0
> stat("/var/lib/docker/containers/SHA: d2e561fba8c9fd3ce0234dba1cf97c6af883656217ebb0c297669cffec19c2cd/config.json", {st_mode=S_IFREG|0644, st_size=2041, ...}) = 0
> [.... repeated for each container, dozens or hundreds of times ...]
> sendto(6, "\2\220\0\0\30\0\0\0\221\317\377\377\1\0\0\0\0\0\0\0\0\0\0\0", 24, 0, NULL, 0) = 24
> select(9, [0 3 6 7 8], NULL, NULL, NULL^CProcess 30267 detached
> 
> for a single query from pmval (or pminfo), even if there is no lifespan
> change to the set of containers.
> 
> This is a failure to scale in several ways:
> - with many containers running, the stat(3)s alone start consuming serious time even for a single client
> - with many clients running, the effect multiplies: pmdaroot becomes a point of contention (creating extra latency)
> 
> One can see what happens with something like pmlogconf (dozens of short-lived pcp clients) running against each of a set of containers: geometric explosion in terms of cpu & time consumption.
> 
> 1 query per second over each of 50 containers' pmcd.hostname metrics is enough to take >10% system CPU in pmdaroot alone.
> 
> Worker pmdas should not need to communicate with pmdaroot after a container name is resolved at connection time.

On 2015-05-14 20:25:24 -0500, Nathan Scott wrote:

> (In reply to comment # 0)
> 
> > Each and every pcp client fetch to a container-aware metric involves IPC and
> > context-switching to-from pmdaroot. 
> 
> Yes, as each and every client fetch involves IPC and context-switching to/from pmcd - this in itself is not an issue.
> 
> > for a single query from pmval (or pminfo), even if there is no lifespan
> > change to the set of containers.
> 
> The first two (directory) stats are there to (attempt to) ascertain lifespan changes - if the code continues forward from there (as evidenced here and by Marks reports earlier), indeed there woud appear to be plenty of scope for optimisation.
> 
> > Worker pmdas should not need to communicate with pmdaroot after a container
> > name is resolved at connection time.
> 
> The PMDAs need to ascertain whether the container is running at all, somehow, and whether it has restarted and is running with a different PID since last fetch.  But, agreed, these things can and will certainly need to be optimised.
> 
> cheers.

On 2016-06-30 16:12:49 -0500, Frank Ch. Eigler wrote:

> > The PMDAs need to ascertain whether the container is running at all,
> > somehow, and whether it has restarted and is running with a different
> > PID since last fetch. 
> 
> They could cache the PIDs, and send a   kill($pid,0)   to check for liveness.  If worried about PID wraparund/reuse, throw away the cached PIDs periodically.

On 2016-10-04 09:49:47 -0500, Frank Ch. Eigler wrote:

> A quick update on pcp 3.11.5:
> 
> % for i in `seq 0 5`; do docker run --rm busybox sleep 999 &; done
> % docker ps    # pick any one
> % pmval --container=ONE_OF_THEM pmcd.hostname
> 
> while in another window
> # strace -p `pgrep pmdaroot`
> 
> Each and every fetch of just one container's pmcd.hostname metric involves this much work from pmdaroot ... and that's for a small fixed set of containers.
> 
> ) = 1 (in [6])
> recvfrom(6, "\1\220\0\0$\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\f\0\0\0tiny_lea"..., 8192, 0, NULL, NULL) = 36
> stat("/var/lib/docker/containers", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
> stat("/var/lib/lxc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
> open("/var/lib/docker/containers/SHA: e0316c46a124f00a6af91f5345dbfe2ae302f221c8914d4c62d6ce1d326d4e6f/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: e0316c46a124f00a6af91f5345dbfe2ae302f221c8914d4c62d6ce1d326d4e6f/config.v2.json", {st_mode=S_IFREG|0666, st_size=2377, ...}) = 0
> open("/var/lib/docker/containers/SHA: 830962e85e49c5574f837c5f48c91559d7c20407eef04c45780ae6a387ad9149/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: 830962e85e49c5574f837c5f48c91559d7c20407eef04c45780ae6a387ad9149/config.v2.json", {st_mode=S_IFREG|0666, st_size=2382, ...}) = 0
> open("/var/lib/docker/containers/SHA: fc06343e7ec4077174d002e31889ae48f3fef7ee617a9c0b8fa93b3fba0d405c/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: fc06343e7ec4077174d002e31889ae48f3fef7ee617a9c0b8fa93b3fba0d405c/config.v2.json", {st_mode=S_IFREG|0666, st_size=2381, ...}) = 0
> open("/var/lib/docker/containers/SHA: 6ff13ca4a1936a71131f4ec04041d072d2acaa681276cd07ecbe19bbcd1e1610/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: 6ff13ca4a1936a71131f4ec04041d072d2acaa681276cd07ecbe19bbcd1e1610/config.v2.json", {st_mode=S_IFREG|0666, st_size=2378, ...}) = 0
> open("/var/lib/docker/containers/SHA: d5b272e2a5b4515de989b7deee851947cb6740beb987336e61385b770623395d/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: d5b272e2a5b4515de989b7deee851947cb6740beb987336e61385b770623395d/config.v2.json", {st_mode=S_IFREG|0666, st_size=2378, ...}) = 0
> open("/var/lib/docker/containers/SHA: 6b55c8b9e9173d603d464195fd824278e660821a7f6d731e2196d89c53fd6628/config.v2.json", O_RDONLY) = 11
> close(11)                               = 0
> stat("/var/lib/docker/containers/SHA: 6b55c8b9e9173d603d464195fd824278e660821a7f6d731e2196d89c53fd6628/config.v2.json", {st_mode=S_IFREG|0666, st_size=2377, ...}) = 0
> open("/proc/10919/ns/uts", O_RDONLY)    = 11
> setns(11, CLONE_NEWUTS)                 = 0
> close(11)                               = 0
> uname({sysname="Linux", nodename="6b55c8b9e917", ...}) = 0
> setns(10, CLONE_NEWUTS)                 = 0
> sendto(6, "\2\220\0\0$\0\0\0\0\0\0\0\2\0\0\0\247*\0\0\f\0\0\0006b55c8b9"..., 36, MSG_NOSIGNAL, NULL, 0) = 36
> select(15, [0 3 6 7 8 9], NULL, NULL, NULL

**Comment by natoscott** [comment]
Several improvements were made some time back.  No further work is currently planned on this area.
