### ISSUE TITLE
Derived metric giving impossible values

### ISSUE THREAD

**Issue by orasagar** [performancecopilot/pcp#1921]
There is strange behavior I have seen with the derived metric disk.dev.util which is defined in iosatat.conf as 
disk.dev.util = 100 * rate(disk.dev.avactive)
disk.dev.util(oneline) = percentage of time device was busy processing requests

giving impossible values in the archive attached 
#pmval disk.dev.util -a buggy_archive
19:04:21.955            4.295E+08                0.0
...
19:05:47.955            4.295E+08                0.0 

During this time frame, i saw its base metric value being read as "!"
pmval disk.dev.avactive -a buggy_archive
19:04:21.955          !      0.0    
19:04:22.955          !      0.0  
...
19:05:45.955          !      0.0    
19:05:46.955          !      0.0    
19:05:47.955          !      0.0    

I have checked the code of pmval it seems like when the delta of this metric value becomes negative it returns this. My guess is  somehow this value is not propagated to the derived metric due to which it's giving impossible values 

I have attached the buggy archives.
[buggy_archive.0.xz.gz](https://github.com/performancecopilot/pcp/files/14649196/buggy_archive.0.xz.gz)
[buggy_archive.index.xz.gz](https://github.com/performancecopilot/pcp/files/14649197/buggy_archive.index.xz.gz)
[buggy_archive.meta.xz.gz](https://github.com/performancecopilot/pcp/files/14649198/buggy_archive.meta.xz.gz)

**Comment by kmcdonell** [comment]
@orasagar sorry it has taken a while to get back to this ... I can see the cause (the counters go "backwards" in the archive, probably due to a reboot or some other kernel-disk-stats-resetting event).  Fix should not be too hard.

I'd like to include your buggy_archive files in the QA suite ... are you able to agree to this, and to whom should the copyright be assigned?

**Comment by orasagar** [comment]
@kmcdonell thanks for looking into it. it would be great if you can take the Oracle copyright header

**Comment by kmcdonell** [comment]
All done here.
