### ISSUE TITLE
activate more compiler warnings (Bugzilla #1137)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#193]
On 2016-03-01 13:37:01 -0600, Frank Ch. Eigler wrote:

> With gcc6, a variety of new high-quality warnings are available,
> some of which have helped find genuine bugs.  (For example, it
> finds the file->type == FILE_TAIL duplication in perl/PMDA/local.c).
> We should get the autoconf.\* machinery to activate
> 
> -Wextra
> -Wduplicated-cond
> 
> and probably others, if $CC supports them.

**Comment by natoscott** [comment]
No work is actively planned on this, please feel free to open a PR though.
