### ISSUE TITLE
when pmcd gives up on a pmda, it should explain what it was doing (Bugzilla #1144)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#194]
On 2016-06-06 15:16:47 -0500, Frank Ch. Eigler wrote:

> When there is a pmcd<->pmda communication breakdown (timeout or whatever), the pmcd logs are quite opaque as to -why-.  It should log the last request to the pmda (a fetch?  initial handshaking?  ...?) and any other such nearby info that can help a pcp developer diagnose what went wrong.
> 
> Similarly, a pmda that encounters an EOF from pmcd should log its recent history, like the type of packet it was just trying to respond to.

**Comment by natoscott** [comment]
No further work is currently planned on this area.
