### ISSUE TITLE
pcp/ubuntu, missing dependency?

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/pcp#2002]
On Ubuntu 23.04/RISC-V, package 'pcp' ships also /var/lib/pcp/pmdas/openmetrics. Trying to install the pmda:
```
[root@star64 57c ~]$ cd /var/lib/pcp/pmdas/openmetrics/
[root@star64 57c openmetrics]$ ./Install
Traceback (most recent call last):
  File "/var/lib/pcp/pmdas/openmetrics/pmdaopenmetrics.python", line 35, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Arrgh! failed to create /var/lib/pcp/pmdas/openmetrics/domain.h.python from /var/lib/pcp/pmdas/openmetrics/pmdaopenmetrics.python
[root@star64 58c openmetrics]$
```
Package python3-requests was required, should we add this as dependency? On Ubuntu, package 'pcp' comes with a whole collection of pmdas, adding all of their dependencies might bring in many other packages.. maybe not doing that was a deliberate decision?

**Comment by natoscott** [comment]
@christianhorn yes, for Debian it was a deliberate decision since we don't have the same fine-grained sub packages like with RPM.
