### ISSUE TITLE
Pmproxy behind NGINX returns "413 Payload Too Large" for /metrics

### ISSUE THREAD

**Issue by jp-berg** [performancecopilot/pcp#2023]
With  `curl localhost:44322/metrics` I get the nearly 1MB of data from pmproxy. However when being put behind NGINX pmproxy returns:

`curl https://myserver.com/pcp/metrics`
```html
<html>
<head><title>413 Payload Too Large</title></head>
<body>
<h1>413 Payload Too Large</h1>
<p><b>webapi servlet</b>: HTTP 1.0 request result exceeds server limits</p><hr>
<p><small><i>pmproxy/6.2.0</i></small></p>
</body>
</html>
```
NGINX forwards requests to myserver.com/pcp towards localhost:44322:

```
location /pcp/ {
                proxy_pass http://localhost:44322;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                rewrite ^/pcp/(.*)$ /$1 break;
                client_max_body_size 100M;
 }
```
This config seems to be fine, because `curl https://myserver.com/pcp/metrics?names=hinv.physmem` returns
```
# PCP5 hinv.physmem 60.1.9 u32 PM_INDOM_NULL discrete Mbyte
# HELP hinv_physmem total system memory metric from /proc/meminfo
# TYPE hinv_physmem gauge
hinv_physmem{hostname="D-3170S06",machineid="27703c35a29542798c2934617933c425",domainname="localdomain"} 3824

```

And NGINX responds just fine when I request files of megabyte-size from other locations. Also the requests are logged to access.log and not error.log.

The pmproxy.log does not seem to show anything relevant:

```
 pmproxy: PID = 975638, PDU version = 2, user = pcp (996)
 pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok    12       unix   /run/pcp/pmproxy.socket
  ok    13 44322 inet   INADDR_ANY
  ok    14 44322 ipv6   INADDR_ANY
  ok    15 44323 inet   INADDR_ANY
  ok    16 44323 ipv6   INADDR_ANY
```

I also tried to tweak the `-L`-argument, with no success. Is there any setting that I am overlooking, any configuration that I may have missed?

**Comment by natoscott** [comment]
@jp-berg hi!  pmproxy has a preference for using HTTP 1.1 where possible as it wants to use chunk-encoding and keep-alive connections, but it looks like NGINX does not match that:

```
<p><b>webapi servlet</b>: HTTP 1.0 request result exceeds server limits</p><hr>
```

Does setting the default protocol to 1.1 (instead of 1.0) in NGINX configuration help?

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

**Comment by jp-berg** [comment]
That solved the issue, thank you very much!

**Comment by natoscott** [comment]
@jp-berg that's great to hear, thanks for following up.  If anyone is keen, there's enough subtle configuration required here that this might make a handy, short "how to" guide that could be added to the set starting here: https://pcp.readthedocs.io/en/latest/QG/ListAvailableMetrics.html

**Comment by jp-berg** [comment]
I am sorry for reviving this old issue (please tell me if I should open a new one), but I encountered another problem: While I  seem to be able to execute the `/metrics`-query via curl (some metrics are displayed), it now cuts off with 
```
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```
Even when using ` curl --http1.1 -i https://myserver.com/pcp/metrics `, I get

```
curl: (18) transfer closed with outstanding read data remaining
```

For each I get an identical error (only the protocol version changes) in the nginx-log:

```
[error] 1075#1075: *4118 upstream prematurely closed connection while reading upstream, client: IP_ADDRESS, server: myserver.com, request: "GET /pcp/metrics HTTP/1.1", upstream: "http://127.0.0.1:44322/metrics", host: "myserver.com"
```
pmproxy is listening on 44322 and I increased all NGINX-timeouts (read, connect, send) on /pcp to a minute.

Could this be due to another subtlety with the pmproxy-API? Or should I look elsewhere for the cause?

**Comment by jp-berg** [comment]
_Two days of on-and-off thinking about the problem cannot solve what 10 minutes of writing down the problem can. Rubber duck-debbugging is real._

Solved the problem!
Since I am not a NGINX-pmproxy-expert please take the following instructions with a grain of salt:

[This question](https://stackoverflow.com/questions/46771389/why-does-nginx-proxy-pass-close-my-connection) lead me to believe that the pmproxy-port needs to be wrapped in an [upstream-block](https://nginx.org/en/docs/http/ngx_http_upstream_module.html). In that block the `keepalive`-option has to be set.

That results in an `/etc/nginx/sites-available/default`-config, that looks like this:

```
upstream upstreampcp {
        server localhost:44322;
        keepalive 8;    
}

server {
       ...
       location /pcp/ {
               proxy_pass http://upstreampcp;
               proxy_set_header Host $host;
               proxy_set_header Connection "";
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               rewrite ^/pcp/(.*)$ /$1 break;
               proxy_http_version 1.1;
     }
      ...
}       
```

I have only a vague idea why this works, but for me this works. This also fixed the issue I had when using bpftrace-queries via the grafana-pcp-plugin. I hope this helps someone else.
