### ISSUE TITLE
https://github.com/performancecopilot/pcp/blob/main/INSTALL.md hints at invalid "qa/admin/check-vm -bfp"

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/pcp#2053]
[chris@космос pcp]$ qa/admin/check-vm -bfp
qa/admin/check-vm: illegal option -- b
Usage: qa/admin/check-vm [options]
  -v           verbose (debugging)

**Comment by kmcdonell** [comment]
The instructions here are all pretty much wrong, or at least out of date ... check-vm is really no longer useful, or at least the package checking parts of it should be replaced by list-packages.
I'll fix check-vm and then update INSTALL.md.
Thanks @christianhorn

**Comment by kmcdonell** [comment]
Correction, check-vm is still useful, and it already uses list-packages ... so what is needed is some editorial fixes in INSTALL.md.
Incoming.
