### ISSUE TITLE
PCP Windows installation procedure

### ISSUE THREAD

**Issue by mathidasan** [performancecopilot/pcp#2065]
Hi
I'm trying to install pcp in my Windows machine to collect Windows system metrics. When I download/checkout release repo from below git url, it shows error "repository not found". Tried both .zip & .exe files, getting same error. Could you please guide me the procedure to install pcp on windows machine?

https://github.com/git-for-windows/build-extra/releases/tag/git-sdk-1.0.8

![image](https://github.com/user-attachments/assets/6b7ff1dd-67b9-4342-a8c7-973d1149e2b4)

![image](https://github.com/user-attachments/assets/78cb033d-ed50-46e3-8b46-fb13c1f8f802)

**Comment by natoscott** [comment]
There are currently no automated PCP builds for Windows, and no packaging - so it cannot be installed until someone does the work to revive the Windows port.
