### ISSUE TITLE
process level metrics in grafana + redis

### ISSUE THREAD

**Issue by mallilinux1980** [performancecopilot/pcp#2077]
how do i configure pcp and metrics to be collected by pmlogger and visualize cpu/memory/network/disk metrics in grafana + redis by individual processes?

**Comment by natoscott** [comment]
@mallilinux1980 sending metrics for all processes has been found to have a crippling effect on many Redis installations due to memory required to hold such high cardinality data.  One way to tackle this is to use the "hotproc" functionality in pmdaproc(1) to produce a reduced set of interesting processes, once recorded those metrics will be automatically indexed into Redis.

**Comment by mallilinux1980** [comment]
are there few examples hotproc.conf ? 

another question I've is can I store or how do I store derived merics into redis and visualize them in grafana?

**Comment by natoscott** [comment]
> are there few examples hotproc.conf ?

There's a samplehotproc.conf shipped in PCP and the pmdaproc(1) man page has multiple examples.

> another question I've is can I store or how do I store derived merics into redis and visualize them in grafana?

The grafana-pcp Redis data source uses the pmseries(1) query language which is similar but different to derived metrics.  Derived metrics only exist for PMAPI contexts (in grafana-pcp, this means the Vector datasource).

**Comment by mallilinux1980** [comment]
> @mallilinux1980 sending metrics for all processes has been found to have a crippling effect on many Redis installations due to memory required to hold such high cardinality data. One way to tackle this is to use the "hotproc" functionality in pmdaproc(1) to produce a reduced set of interesting processes, once recorded those metrics will be automatically indexed into Redis.

able to see proc level metrics in grafana after hotproc is configured (cpuburn > 0.10) and setting up sasl based basic authentication. But since yesterday I'm seeing same process and its value all time so what needs to be done for real-time display in the grafana?

**Comment by natoscott** [comment]
@mallilinux1980 check the values via "pminfo -f hotproc" - if Vector is displaying something out-of-date compared to that, please open a grafana-pcp github issue with details.

**Comment by mallilinux1980** [comment]
Interestingly pminfo -f hotproc most metrics says no value found.
