### ISSUE TITLE
pcp on valkey

### ISSUE THREAD

**Issue by mallilinux1980** [performancecopilot/pcp#2086]
given redis is not open source anymore we're planning to use valkey but are there any specific configs to be modified in pmproxy or any other w.r.t valkey?

**Comment by natoscott** [comment]
pcp-6.3.1 is the first release which we tested with Valkey.  Some configuration files (e.g. pmproxy.conf) now support an alternate non-redis syntax, however the old format will also be supported forever so there is no need to change anything at the end user level.
