### ISSUE TITLE
pcp tries to send emails for "unresolvable problems"

### ISSUE THREAD

**Issue by spiermar** [performancecopilot/pcp#22]
We've noticed tons of error messages from local sendmail instances because PCP was trying to send  some error information via email, to our fake domain. We don't really care about these errors, so it would be good to have the option to completely ignore those (and not send emails) or output them to a log file.

**Comment by spiermar** [comment]
See the "FC19 et al QA failures ..." thread on the mail list.

**Comment by natoscott** [comment]
This behaviour was changed in pcp-3.10.6, should no longer get any mail unless explicitly requested.
