### ISSUE TITLE
Should pcp2graphite run as a service?

### ISSUE THREAD

**Issue by lmiccini** [performancecopilot/pcp#24]
Hi,

$subject says it all. I am relying on pcp2graphite to forward metrics to a carbon/graphite instance.
I ended up having to write a pcp2graphite.service systemd unit file to keep it running.

Should pcp provide such init file/systemd unit file (or document the need for it) or maybe we have other options available / in the works (like a "metrics forwarding facility" that can then use pcp2graphite)?

Thanks!

**Comment by fche** [comment]
Luca, please consider sending your .service file for inclusion in pcp.  (For such a trivial service, perhaps even just including a template in the pcp2graphite man page could be sufficient, since configuration rather than invocation mechanics represents the bulk of the content.)

**Comment by lmiccini** [comment]
Hi Frank, I agree on the manpage.

Here it is anyway:

[Unit]
Description=Performance Co-Pilot data pump
Documentation=man:pcp2graphite(8)
After=pmcd.service

[Service]
ExecStart=/usr/bin/pcp2graphite -m pcp-%H. -g <graphite_host> kernel mem
network disk filesys

**Comment by fche** [comment]
(By the way, have you found it a problem that pcp2graphite reopens a new socket to graphite at every time interval?  Some versions of carbon can apparently accept persistent connections; was thinking pcp2graphite should grow an option for that.)

**Comment by lmiccini** [comment]
I can live with the current behaviour, but that sounds like an improvement for sure.
I can submit a pull request for the man page if you like.

**Comment by fche** [comment]
yes please!

**Comment by lmiccini** [comment]
submitted https://github.com/performancecopilot/pcp/pull/25

**Comment by natoscott** [comment]
Looks like consensus earlier was that a man page update suffices here, which has long been merged - closing.
