### ISSUE TITLE
Missing metrics for disk partitions

### ISSUE THREAD

**Issue by marcliangma7** [performancecopilot/pcp#26]
Hi,

I would like to get metrics for each disk partition using PCP. The following is the list of metrics I can get, however it seems to be missing several metrics comparing to disk.dev and disk.dm. Can anyone help to answer the reason behind this or any workaround to get these missing metrics? Thanks. 

disk.partitions.read
disk.partitions.write
disk.partitions.total
disk.partitions.blkread
disk.partitions.blkwrite
disk.partitions.blktotal
disk.partitions.read_bytes
disk.partitions.write_bytes
disk.partitions.total_bytes

These following metrics are missing from disk.partitions:

disk.dev.read_merge
disk.dev.write_merge
disk.dev.avactive
disk.dev.read_rawactive
disk.dev.write_rawactive
disk.dev.aveq

iostat seems can output these missing metrics for disk partitions.

**Comment by natoscott** [comment]
(these missing metrics have now been added)
