### ISSUE TITLE
MMV not immediately usable after clean install 

### ISSUE THREAD

**Issue by ryandoyle** [performancecopilot/pcp#268]
Heya I think there is a regression in 3.11.6 with how the MMV pmda is registered when installed.

It looks like the MMV directory does not exist after a clean install. 
```
$ sudo apt-get install -y pcp
$ pminfo -f mmv
mmv.control.files
    value 0
mmv.control.debug
    value 0
mmv.control.reload
    value 0 
$ ls -l /var/lib/pcp/tmp/mmv
ls: cannot access /var/lib/pcp/tmp/mmv: No such file or directory
```
I've only done a small amount of digging and couldn't see any changes in `debian/` that could cause this. It looks like the `./Install` script is the one that creates that directory. Perhaps its not being invoked anymore? 

I don't mind looking into this but someone might already have an idea of what is different between 3.11.5 and 3.11.6 regarding this issue.

**Comment by natoscott** [comment]
@ryandoyle this isn't a recent change - it's a result of commit 0cfa8763b8649 ... we are between a rock and a hard place in terms of setting up this directory, and we ended up leaving it for the user to sort out (I'd really prefer not to; but I can't see any better solution).  See the INSTALLATION section in pmdammv(1) and the git log from the commit, but the original issue was this:  (from git log 0cfa8763b86)

    Folks have complained that we are creating world-writable-sticky
    bits in somewhat unorthadox locations, and question the need for
    PCP to be doing that, arguing it opens up unnecessarily potential
    exposure to security issues via attacks from hostile local users.
