### ISSUE TITLE
pmlogconf: Cannot connect to PMCD on host "node1": PMCD requires a client certificate

### ISSUE THREAD

**Issue by learner321** [performancecopilot/pcp#269]
OS: redhat 7.2
pcp informantion:

 Performance Co-Pilot configuration on node1:
 platform: Linux node1 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64
 hardware: 24 cpus, 2 disks, 2 nodes, 64150MB RAM
 timezone: CST-8
 services: pmcd
 pmcd: Version 3.11.3-1, 9 agents, 2 clients 
 pmda: root pmcd proc xfs linux mmv infiniband jbd2 simple

I installed the pcp-3.11.3 in CENTOS 6.6, It all goes well. 
In Redhat 7.2, when I use "pmlogconf -cqrv /var/lib/pcp/config/pmlogger/config.node1", everything goes well. But when I use "pmlogconf -cqrv -h node1 /var/lib/pcp/config/pmlogger/config.node1", I got the message "pmlogconf: Cannot connect to PMCD on host "node1": PMCD requires a client certificate". So I cannot fetch performance metrics from collector hosts in my cluster. I checked the pmcd & pmlogger, they are running as well.  I do not know why, does someone have a solution to this problem?   Thank you very much.

**Comment by natoscott** [comment]
@learner321 could you paste "pminfo --fetch --host node1 pmcd.feature" output?  thanks.

**Comment by learner321** [comment]
the output as follows:
"pminfo: Cannot connect to PMCD on host "node1": PMCD requires a client certificate"
but when I use "pminfo --fetch pmcd.feature", I got the message like follows.

pmcd.feature.secure
    value 0

pmcd.feature.compress
    value 0

pmcd.feature.ipv6
    value 1

pmcd.feature.authentication
    value 0

pmcd.feature.creds_required
    value 0

pmcd.feature.unix_domain_sockets
    value 1

pmcd.feature.service_discovery
    value 1

pmcd.feature.containers
    value 1

pmcd.feature.local
    value 0

pmcd.feature.client_cert_required
    value 1

The hostname of the monitoring host in my cluster is "node1", I do not know why "pminfo" cannot connet to PMCD if I use "-h node1". 
Thank you very much.

**Comment by natoscott** [comment]
From your output, it looks like you have mandatory client certificates enabled ...

| pmcd.feature.client_cert_required
|   value 1

And I guess you've not setup pminfo to have access to a client certificate.  Can you paste the output from "ps -ef | grep pmcd" on node1?

http://pcp.io/docs/lab.secureclient.html has details on setting up the "secure client" feature.

**Comment by learner321** [comment]
the output as follows:
root     19019 17053  0 11:18 pts/0    00:00:00 grep --color=auto pmcd
pcp      23427     1  0 Nov21 ?        00:00:00 /usr/libexec/pcp/bin/pmcd

I Installed pcp-3.11.3 from source. If I donnot want to enable the client certificates, how should I do now. Thank you very much.

**Comment by natoscott** [comment]
Hmm, I was expecting to see -Q option to pmcd there - is it listed in /etc/pcp/pmcd/pmcd.options?
Somehow, client-certificates mode is being enabled in pmcd - @minnus any ideas to cause, if it turns out pmcd -Q is not enabled?

**Comment by minnus** [comment]
Hmm.  I seem to remember someone else seeing this a while ago. Maybe Ken on one of his VMs?? I recall not being able to reproduce it, but don't recall the resolution. 

I'll dig through my emails to try to find it.

Martins

**Comment by learner321** [comment]
I checked the pmcd.options, but there is no -Q option.
Is this related to the OS, It all goes well in centos 6.6. 
thank you very much.@minnus@natoscott

**Comment by minnus** [comment]
Looking at your output and the fact that you built from source, and that pmcd.feature.secure==0, my guess is something in the logic where PCP is built without secure libraries is/was broken.  I'm guessing you didn't have the secure devel libs installed during build.  I think there was a patch to fix this.....Looking.....

Yup:

https://github.com/performancecopilot/pcp/commit/a94e419041eb28101af92c8f71a7cf6e5e220943

Is there a reason you need 3.11.3?  I'd suggest building from a newer source or using the bintray builds:

https://bintray.com/pcp

**Comment by learner321** [comment]
Thank you for your reply! I added a few metrics in pmdas and that version is 3.11.3. Is the newer source downward compatibility？I download the pcp source from github last week，I got the same message.I'll check the secure devel libs and try the patch. Thank you again!

**Comment by natoscott** [comment]
| Is the newer source downward compatibility?

Yes, you're new metrics/PMDAs will work fine with latest PCP.

**Comment by learner321** [comment]
Ok, thank you very much!

**Comment by learner321** [comment]
I use the patch and now the pcp all goes well. Thank you very much! @minnus @natoscott
