### ISSUE TITLE
boolean / quantified operations for derived-metrics

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#270]
It would be nice to be able to express pmie-like boolean expressions in the derived-metric language, so that timelines can be constructed of the true/false values.  pmdasummary, being systemwide, is not a good substitute.

The minimum would probably be language extensions for:
- boolean operators (> == <  etc.)
- quantification over instances (any(x) all(x) none(x))
- type/scale conversion operator   (e.g.,  convert(x, "kbytes/hour"))
- maybe, historical-value operator (\@0 etc., recast into functional notation?)
- maybe, accept floating point literals, not just integers

**Comment by wcohen** [comment]
Would also like to have a defined() or similar operator to determine if a particular metric is available and has numeric values.  This would allow derived metrics to work around variations in the available metrics.  For example  newer linux kernels might have just provide a pgscan_direct entry in /proc/vmstat and not various subtypes that older kernels provided in /proc/vmstat:

mem.vmstat.pgscan_direct_all = (defined(mem.vmstat.pgscan_direct) ? mem.vmstat.pgscan_direct : mem.vmstat.pgscan_direct_dma + mem.vmstat.pgscan_direct_dma32 + mem.vmstat.pgscan_direct_dma + mem.vmstat.pgscan_direct_movable + mem.vmstat.pgscan_direct_normal)

**Comment by kmcdonell** [comment]
William, just starting to think about this (thanks for the prod) ...
- boolean operators: your examples are relational operators that yield boolean values ... (a) would you expect the value to be a C-style integer with the value 0 (false) or 1 (true)? (b) do you want boolean operators as well (!, && and ||)?
- quantification over instances: same question as above wrt value, and is none(x) needed (this is !some(x) or some(x) == 0), but more importantly, what is "x" ... it makes no sense for it to be a metric or an arithmetic expression, so I am guessing you want "x" to be a relational expression.
- conversion: OK
- historical values: that's messy and definitely not for Phase 1.
- floating point literals: OK
- defined(): not sure defined() conveys the right semantics ... for a metric x, it may be undefined (not in the PMNS), defined but fetch returns an error (e.g. PM_ERR_APPVERSION), defined but fetch returns no values, or defined and fetch returns one or more values ... I can't see this predicate being evaluated in real-time, so it would be true or false (and defined the resultant expression tree) whenever a new PMAPI context is established, i.e. at the second phase of semantic checking for derived metric expressions.  Not sure exactly what's required here, but I suspect "defined and fetch returns one or more values" (and even that won't work robustly in some cases, e.g. the PM_ERR_NYI and PM_ERR_AGAIN PMDAs)

**Comment by fche** [comment]
For `defined(X)`, maybe think about it as `available(METRIC) ? VALUE : VALUE` or `default(METRIC,VALUE)`, as a fetch-time-evaluated calculation for PM_ERR_NYI/AGAIN.  If the METRIC is not available even in the PMNS, then it could const-propagate as a false into the expression tree and not be reevaluated later.

**Comment by wcohen** [comment]
Yes, boolean operators (with short-circuiting) would be useful.  A common idiom in analyzing performance is computing a ratio between two values and would want make sure that divide by zero does not occur.  For example trying to compute the equivalent to "sar -B" %vmeff.  The %vmeff is sum(mem.vmstat.pgsteal_*)/sum(mem.vmstat.pgscan_*).  if mem.vmstat.pgscan_* are all zero because there is plenty of memory and no page reclaimation has been attempted that divide is not going to work.

Maybe a special bounded divide operator where 1/0 is considered infinity and the function takes an argument for the max value it will return.

bounded_divide(numerator, denominator, bound)

bounded_divide(1, 0, 2) == 2
bounded_divide(1, 2, 2) == 0.5

**Comment by kmcdonell** [comment]
@wcohen I've just commited changes for floating point numeric constants and relational operators.
I'll tackle some of the other RFEs as time permits.

**Comment by wcohen** [comment]
@kmcdonell I was able to recode some of my examples predicate tests using the conditionals added to the derived  metric support. thanks.

Still thinking what would be best as the results of the binary || && etc. Wondering if maybe returning something other than C style 0 and 1 might be useful.  Have short-circuiting for the logical || and &&. For || return left value if non-zero otherwise return right side value.  For && return right hand value if left-hand side non-zero.  

bounded_divide(num, denom, max)  I think could be turned into the following:

((denom!=0) && ( num/denom )< max && (num/denom) ) || max

**Comment by kmcdonell** [comment]
@wcohen I am in the process of completely rewriting the parser ... almost done, and you'll get && and ||, ! (boolean negation), scaled numeric constants, ... all for free.  When this is all checked out, I'll return to the remaining open issues and will be able to add new functions much more easily.

**Comment by kmcdonell** [comment]
OK.
I've opted for C-style "truth" ... 0 is false, anything else is true.  The way the evaluator works I'm not going to try for any early evaluation of boolean operators, so don't rely on any assumptions about the order of subexpression evaluation.
The ternary operator: a ? b : c is more general than bounded_divide() so I'm not planning on doing bounded_divide().
Next I'm back to thinking about available() or similar ... it _will_ be evaluated at run-time.  At the moment, I'm leaning towards defined(metricname) that would be evaluated at bind time (i.e. pmNewContext()) as I need the PMID of metricname from that point on, if it is going to be used elsewhere in an expression ... this probably only makes sense in a construct like defined(x) ? x : (defined(y) ? y : some-default-value).  And then I'm thinking of has_values(expr) which returns 0 or 1 at run-time, so this could be used in expressions like has_values(metric) ? metric : 0

@wcohen (in particular), are these thoughts on the same track as yours?

Just a note in passing, in derived metric land some_value / 0 is 0 ... the evaluator enforces this at run-time, so the concern about divide by zero above may be a non-issue ... but now with ternary expressions it is possible to over-ride this behaviour, e.g. to use -1 as a sentinal value for cases where the divisor is zero.

**Comment by kmcdonell** [comment]
If I change count() to return 0 in the case of an error (numval < 0), then this is has_values() done.
This was so simple that I've done this now.

Next is defined(), then rescale() (aka convert() in Frank's original posting).

**Comment by kmcdonell** [comment]
I've added defined() ... I think that clears the backlog of RFEs from @wcohen.
Still on the list of RFEs from @fche are:
1. quantification over instances (any(x) all(x) none(x)) and
2. maybe, historical-value operator (@0 etc., recast into functional notation?)

Frank, I'd like to see some concrete examples to convince me of the need for 2.

And for 1. I'm not sure of the semantics you're after ... assuming x is an expression over an instance domain, futher let's assume x is a relational or boolean expression (the argument is only a little more convoluted if they are arithmetic expressions where any(), all() and none() have to make some assumption abouth truth values), then it seems to me
any(x) is the same as sum(x) > 0
all(x) is the same as sum(x) == count(x)
none(x) is the same as sum(x) == 0
... so are we done for 1.?  If not, I'll need some further explanation.

**Comment by kmcdonell** [comment]
This issue has become somewhat convoluted, and I'm done with all I plan to do at this stage (the commits were done many weeks ago).
If there are remaining outstanding issues, I suggest opening new issue(s) to track those.
