### ISSUE TITLE
PCP metrics in Hawkular?

### ISSUE THREAD

**Issue by sghosh151** [performancecopilot/pcp#274]
Are there plans to connect PCP metrics collection to Hawkular metrics-storage via something like ptrans - https://github.com/hawkular/hawkular-metrics/tree/master/clients/ptranslator ?

**Comment by natoscott** [comment]
Hi Subhendu,
Yes, this is one of the proposed GSoC project ideas for this year ...
http://pcp.io/gsoc/2017/ideas.html#hawkular

**Comment by sghosh151** [comment]
Great, Thanks.
Good to see Prometheus on the gsoc list as well.

**Comment by fche** [comment]
FWIW, the quickest bang for both those bucks would be a `pmwebd` extension that serves queries in the https://prometheus.io/docs/instrumenting/exposition_formats/.  Hawkular can ingest that via its hawkular-apm agent http://www.hawkular.org/blog/2016/04/22/collecting-metrics-from-prometheus-endpoints.html, and of course so can prometheus directly.

**Comment by joehandzik** [comment]
+1 on interest in this over at HPE (specifically the Prometheus part), FWIW.

**Comment by myllynen** [comment]
Given recent developments in this area (esp. the emergence of Prometheus), is this RFE still relevant?

See also https://www.hawkular.org/blog/2017/04/19/hawkular-apm-jaeger.html.

**Comment by natoscott** [comment]
Yeah, not really - lots has changed in this space - if anyone is still keen, please re-open, preferably with a PR :)
