### ISSUE TITLE
RFE: pminfo option to indicate which metrics are actually available (an inverse of -v option)

### ISSUE THREAD

**Issue by wcohen** [performancecopilot/pcp#275]
pminfo lists out the metrics it knows about on a machine.  However, not all of these metrics work on a particular machine.  "pminfo -v" will list which metrics don't work machine.  It would be nice to have a inverse option (maybe call it --survey) to list which metrics will provide values on the particular machine, taking the "-f" option data and just listing the metrics that were successful fetched and discarding the data.

**Comment by kmcdonell** [comment]
William, this is simple enough ... except for the "No values" metrics ... these are currently reported with -v.

These are metrics that might never have a value on a particular machine (e.g. tape.dev on a machine with no scsi tape units) or might have a value at some time in the future (e.g. the hotptroc metrics).

Should these metrics be included with the new option (so skip metrics that return errors only), or excluded with the new option (so only include metrics with at least one value)?

**Comment by wcohen** [comment]
I hadn't considered the the case where whether the metric returns a valid value is time dependent.  I was thinking keep it simple and just report on the metrics that have valid values at the moment. However, for an archive not sure want to scan through the entire archive to see if a valid value exists for an particular recorded metric.

**Comment by kmcdonell** [comment]
@wcohen I wonder if the use case you're considering is already covered by pmprobe?  This is lighter-weight than pminfo, and the second value reported is the number of values available, else a PMAPI erorr code (<0).  This anambiguously indicates if there are values behind one or more metrics, and if not the caller can choose to handle the numval == 0 and numval < 0 cases separately or together, as they wish.

**Comment by wcohen** [comment]
Thanks for the suggestion. pmprobe looks like it will do.  The one-liner below give me the list of metrics that have values:

pmprobe |grep -v " 0" |grep -v "-"|awk '{print $1}'

**Comment by kmcdonell** [comment]
Yep, or even simpler:
pmprobe | awk '$2 > 0 { print $1 }'
