### ISSUE TITLE
RFE: make zbxpcp multi-host

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#281]
Marko's zbxpcp code hardcodes "localhost" as its target pmcd.  It would be easy to make that configurable (getenv("PCP_HOST") ?: "localhost" kind of thing).  It would be harder and neater to let zbxpcp maintain a farm of connections to remote hosts ("PCP_HOSTLIST"?), and let zbx poll any subset of them.  Think of it like making the ZBX_PCP_METRIC_PREFIX fan out with a host-name component.

**Comment by natoscott** [comment]
No work planned on this.
