### ISSUE TITLE
few allow rules should be added to pcpupstream.pp

### ISSUE THREAD

**Issue by milosmalik** [performancecopilot/pcp#287]
Found some AVCs on RHEL-7.4 which are related to pcp. Result of audit2allow is:
allow pcp_pmie_t systemd_systemctl_exec_t:file { execute read };
allow pcp_pmie_t systemd_unit_file_t:file getattr;
allow pcp_pmproxy_t self:capability net_admin;
allow pcp_pmproxy_t sysctl_net_t:file read;

**Comment by milosmalik** [comment]
Raw AVCs from enforcing mode:
----
type=SYSCALL msg=audit(04/05/2017 09:54:13.548:281) : arch=x86_64 syscall=open success=no exit=EACCES(Permission denied) a0=0x7f290afc6540 a1=O_RDONLY a2=0x1b6 a3=0x24 items=0 ppid=1 pid=6669 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmproxy exe=/usr/libexec/pcp/bin/pmproxy subj=system_u:system_r:pcp_pmproxy_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 09:54:13.548:281) : avc:  denied  { read } for  pid=6669 comm=pmproxy name=disable_ipv6 dev="proc" ino=9994 scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=file 
type=AVC msg=audit(04/05/2017 09:54:13.548:281) : avc:  denied  { net_admin } for  pid=6669 comm=pmproxy capability=net_admin  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability 
type=AVC msg=audit(04/05/2017 09:54:13.548:281) : avc:  denied  { net_admin } for  pid=6669 comm=pmproxy capability=net_admin  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability 
type=AVC msg=audit(04/05/2017 09:54:13.548:281) : avc:  denied  { net_admin } for  pid=6669 comm=pmproxy capability=net_admin  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability 
type=AVC msg=audit(04/05/2017 09:54:13.548:281) : avc:  denied  { net_admin } for  pid=6669 comm=pmproxy capability=net_admin  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability 
----
type=SYSCALL msg=audit(04/05/2017 09:58:27.740:303) : arch=x86_64 syscall=access success=no exit=EACCES(Permission denied) a0=0x13a0120 a1=X_OK a2=0x7ffd989916a0 a3=0x7ffd98991550 items=0 ppid=7072 pid=7073 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 09:58:27.740:303) : avc:  denied  { execute } for  pid=7073 comm=pmie name=systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 09:58:27.740:304) : arch=x86_64 syscall=access success=no exit=EACCES(Permission denied) a0=0x13a0120 a1=R_OK a2=0x7ffd989916a0 a3=0x7ffd98991550 items=0 ppid=7072 pid=7073 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 09:58:27.740:304) : avc:  denied  { read } for  pid=7073 comm=pmie name=systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 09:58:27.742:305) : arch=x86_64 syscall=stat success=no exit=EACCES(Permission denied) a0=0x13a02f0 a1=0x7ffd98991e40 a2=0x7ffd98991e40 a3=0xb items=0 ppid=1 pid=7004 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 09:58:27.742:305) : avc:  denied  { getattr } for  pid=7004 comm=pmie path=/usr/lib/systemd/system/pmie.service dev="dm-1" ino=4203 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_unit_file_t:s0 tclass=file 
----

**Comment by milosmalik** [comment]
Output from audit2allow in permissive mode:
allow pcp_pmie_t init_t:unix_stream_socket connectto;
allow pcp_pmie_t initrc_var_run_t:file { lock open read };
allow pcp_pmie_t systemd_systemctl_exec_t:file { execute execute_no_trans open read };
allow pcp_pmie_t systemd_unit_file_t:file getattr;
allow pcp_pmproxy_t self:capability net_admin;
allow pcp_pmproxy_t sysctl_net_t:file { getattr open read };

Raw AVCs from permissive mode:
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.080:345) : arch=x86_64 syscall=access success=yes exit=0 a0=0x21da160 a1=X_OK a2=0x7fff5eefcf80 a3=0x1c items=0 ppid=8938 pid=8939 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.080:345) : avc:  denied  { execute } for  pid=8939 comm=pmie name=systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.080:346) : arch=x86_64 syscall=access success=yes exit=0 a0=0x21da160 a1=R_OK a2=0x7fff5eefcf80 a3=0x1c items=0 ppid=8938 pid=8939 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.080:346) : avc:  denied  { read } for  pid=8939 comm=pmie name=systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.080:347) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x21da160 a1=0x21da910 a2=0x21dc380 a3=0x7fff5eefce80 items=0 ppid=8938 pid=8939 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=runlevel exe=/usr/bin/systemctl subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.080:347) : avc:  denied  { execute_no_trans } for  pid=8939 comm=pmie path=/usr/bin/systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
type=AVC msg=audit(04/05/2017 10:24:45.080:347) : avc:  denied  { open } for  pid=8939 comm=pmie path=/usr/bin/systemctl dev="dm-1" ino=3402 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.081:348) : arch=x86_64 syscall=open success=yes exit=3 a0=0x7fe5b193798c a1=O_RDONLY|O_CLOEXEC a2=0x7fe5b193797d a3=0xfffffffffffff9c9 items=0 ppid=8938 pid=8939 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=runlevel exe=/usr/bin/systemctl subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.081:348) : avc:  denied  { open } for  pid=8939 comm=runlevel path=/run/utmp dev="tmpfs" ino=12392 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file 
type=AVC msg=audit(04/05/2017 10:24:45.081:348) : avc:  denied  { read } for  pid=8939 comm=runlevel name=utmp dev="tmpfs" ino=12392 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.081:349) : arch=x86_64 syscall=fcntl success=yes exit=0 a0=0x3 a1=F_SETLKW a2=0x7fff9aaa7540 a3=0x8 items=0 ppid=8938 pid=8939 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=runlevel exe=/usr/bin/systemctl subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.081:349) : avc:  denied  { lock } for  pid=8939 comm=runlevel path=/run/utmp dev="tmpfs" ino=12392 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.082:350) : arch=x86_64 syscall=stat success=yes exit=0 a0=0x21dbcd0 a1=0x7fff5eefd770 a2=0x7fff5eefd770 a3=0xb items=0 ppid=1 pid=8870 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmie exe=/usr/bin/bash subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.082:350) : avc:  denied  { getattr } for  pid=8870 comm=pmie path=/usr/lib/systemd/system/pmie.service dev="dm-1" ino=4203 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:systemd_unit_file_t:s0 tclass=file 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.084:351) : arch=x86_64 syscall=connect success=yes exit=0 a0=0x3 a1=0x55646a769148 a2=0x16 a3=0x7fff1e1cbfc0 items=0 ppid=8870 pid=8941 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemctl exe=/usr/bin/systemctl subj=system_u:system_r:pcp_pmie_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.084:351) : avc:  denied  { connectto } for  pid=8941 comm=systemctl path=/run/systemd/private scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.771:356) : arch=x86_64 syscall=open success=yes exit=0 a0=0x7fd18782a540 a1=O_RDONLY a2=0x1b6 a3=0x24 items=0 ppid=1 pid=9669 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmproxy exe=/usr/libexec/pcp/bin/pmproxy subj=system_u:system_r:pcp_pmproxy_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.771:356) : avc:  denied  { open } for  pid=9669 comm=pmproxy path=/proc/sys/net/ipv6/conf/all/disable_ipv6 dev="proc" ino=9994 scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=file 
type=AVC msg=audit(04/05/2017 10:24:45.771:356) : avc:  denied  { read } for  pid=9669 comm=pmproxy name=disable_ipv6 dev="proc" ino=9994 scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=file 
type=AVC msg=audit(04/05/2017 10:24:45.771:356) : avc:  denied  { net_admin } for  pid=9669 comm=pmproxy capability=net_admin  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability 
----
type=SYSCALL msg=audit(04/05/2017 10:24:45.771:357) : arch=x86_64 syscall=fstat success=yes exit=0 a0=0x0 a1=0x7fffc8727cf0 a2=0x7fffc8727cf0 a3=0x7fffc8727b10 items=0 ppid=1 pid=9669 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pmproxy exe=/usr/libexec/pcp/bin/pmproxy subj=system_u:system_r:pcp_pmproxy_t:s0 key=(null) 
type=AVC msg=audit(04/05/2017 10:24:45.771:357) : avc:  denied  { getattr } for  pid=9669 comm=pmproxy path=/proc/sys/net/ipv6/conf/all/disable_ipv6 dev="proc" ino=9994 scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=file 
----

**Comment by lberk** [comment]
Merged last night, closing for now
