### ISSUE TITLE
bintray ubuntu binaries should include debuginfo

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#289]
Our code has one or two bugs.  When they strike, users need the ability to debug / valgrind them to give us a chance at fixing them.  This is obstructed by the lack of debugging data on the bintray repos.  The ubuntu/debian builds appear to have no -dbgsym bits anywhere.  (The el6 ones do.)  Please let's make sure that our binaries are unstripped, or come with preserved stripped debugging data packages.

**Comment by natoscott** [comment]
There are no maintainer plans to do any further work here - feel free to send patches though.
