### ISSUE TITLE
pmlogrewrite memory corruption

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#290]
IRC user @insubordinate reports a custom pmlogrewrite script on an atypical pmlogger-generated archive causes memory corruption at run time.  Archive cannot be shared due to confidential content, and we've had difficulty reproducing it.  The reports implicate indom processing, and the archive contents hint at hotproc.

[valgrind2.txt](https://github.com/performancecopilot/pcp/files/962109/valgrind2.txt) <- valgrind error
[valgrind3.txt](https://github.com/performancecopilot/pcp/files/962110/valgrind3.txt) <- valgrind trace-malloc
[pminfo.txt](https://github.com/performancecopilot/pcp/files/962118/pminfo.txt) <- archive pminfo

**Comment by dbrolley** [comment]
Several pmlogrewrite memory misuse problems corrected by commit c640d472282bcf7adbb4fbdcf78a74094b605bf4
