### ISSUE TITLE
new metrics, smart hdd

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#291]
more info on SMART here
https://en.wikipedia.org/wiki/S.M.A.R.T.

**Comment by lberk** [comment]
Hey Henry,

hc000 <notifications@github.com> writes:
> more info on SMART here
> https://en.wikipedia.org/wiki/S.M.A.R.T.

Could you provide a bit more detail on what specific metrics you're
looking for, or think should be a priority, in the pmda?

Briefly skimming over smartctl(1), there is quite a variety of
information that we can pull, various vendor attributes, logs,
temperatures and more.  What're the most used and could be focused on to
start?

Lukas

**Comment by hc000** [comment]
I think we can focus on these metrics first.

hdd.command_timeout
hdd.current_pending_sector_count
hdd.offline_uncorrectable
hdd.reallocated_sector_count
hdd.reported_uncorrectable_errors
ssd.available_reserved_space
ssd.media_wearout_indicator
ssd.reallocated_sector_count
ssd.wear_leveling_count

**Comment by fche** [comment]
So in other words, the SMART attribute values / overall-health, as opposed to error-log or similar historical status info.  It's basically the same stuff smartd would use to trigger a problem notification email.

**Comment by natoscott** [comment]
smart PMDA added to PCP sometime back.
