### ISSUE TITLE
Figures missing from pdf documents

### ISSUE THREAD

**Issue by wcohen** [performancecopilot/pcp#292]
The pdf version of the programmers guide ( http://pcp.io/books/PCP_PG/pdf/PCP-3-pcp-programmers-guide-en-US.pdf) is missing the figures.  For example "Figure 1.2. Process Structure for Distributed Operation" in the pdf file has nothing.  However, looking at the html versions see pretty pictures in http://pcp.io/books/PCP_PG/html/LE21795-PARENT.html and http://pcp.io/books/PCP_PG/html-single/

**Comment by natoscott** [comment]
@wcohen thanks Will, looks like this publican issue is the underlying cause:
https://bugzilla.redhat.com/show_bug.cgi?id=1290423

**Comment by natoscott** [comment]
Fixed, and new versions of the pdfs have been uploaded to pcp.io.
