### ISSUE TITLE
A json pmda example similar to the mmv acme example

### ISSUE THREAD

**Issue by wcohen** [performancecopilot/pcp#300]
I have been learning how feed metrics data into pcp's pmcd via the json pmda.  The JSON README talks about the files needed.  However, it would be nice to have example code that works like the existing mmv acme example.  There is code on https://github.com/wcohen/pcp/tree/wcohen/docs  to do this, but it is still a work in progress.  The src/pmdas/json/GNUMakefile is not quite right.  It gets an error when doing a "./Makepkg":

../../../install-sh -o root -g root -m 644 acme_json.c /usr/share/pcp/demos/json
ERROR: unsupported install usage
Usage: install-sh [-o owner] [-g group] [-m mode] -d directory
or     install-sh [-o owner] [-g group] [-m mode] file directory/file
or     install-sh [-o owner] [-g group] [-m mode] file file [file ...] directory
or     install-sh -S file target  (creates "target" symlink)

The $DIST_MANIFEST and $DIST_ROOT environment variables affect the
behaviour of this command - see comments in the script.

GNUmakefile:44: recipe for target 'install_pcp' failed
make[4]: *** [install_pcp] Error 1

Also the code could be a bit better in how the updated data.json is written.  Currently, the pmda could be reading the data.json when it is being updated.

**Comment by natoscott** [comment]
I see you fixed the install-sh usage Will - all good.
