### ISSUE TITLE
autoreconf generates incomplete configuration

### ISSUE THREAD

**Issue by whbruce** [performancecopilot/pcp#304]
Thanks to commit 50ecaedaeefe8c4066bc914747088e7cd6bda684 autoreconf now completes without error. However the resulting configuration is incomplete, missing macros such as PCP_CALL and PCP_DATA which results in build error. I have limited autotools knowledge but can see that the generated config.h.in differs significantly from the checked in version. 

Use case is adding pcp to Yocto buillt Linux image, so this generates a configuration for cross-compilation.

**Comment by fche** [comment]
ISTM the problem is that the src/include/pcp/config.h.in file may have once been generated with `autoheader`, it has since been many times patched with manual changes.  It probably needs to be ripped apart, so that the handmade parts can go into a separate file (impl.h?) and the rest be automatically generated.

**Comment by whbruce** [comment]
Agreed. I'm not sure why configure and config.h.in are checked in as they should be generated. Also project doesn't seem to be setup up well for cross compilation.

**Comment by natoscott** [comment]
> ISTM the problem is [...]

Yes, you've just repeated what I discussed with @whbruce on IRC of weeks or so ago, when this was first reported (which led to the referenced initial commit).

The main problem is not that people don't understand what needs to be done, it's that noone has worked on fixing it yet -  @fche would you care to submit a patch?

Thanks for the placeholder issue @whbruce - if noone else looks at it, I'll see if I can find some time later this week.

**Comment by whbruce** [comment]
@natoscott I appreciate your responsiveness. If I was better with autotools, I'd offer to help. However I'm still learning and fear that this isn't the best place to start.

**Comment by natoscott** [comment]
@whbruce no problem at all, there are plenty of people here who can help.  We'll get it fixed up soon - I'm keen to hear how everything else goes with PCP on Yocto.
