### ISSUE TITLE
RFE: pmdaprometheus autoconfig

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#308]
It would be helpful to pmdaprometheus deployment, if it did not require a large manually generated configuration file.  Sometimes _all_ we have ahead of time is a set of candidate prometheus endpoint URLs.  The endpoints may not even exist or be up yet.  Yet we need the pmda to make its best effort: start, try polling the URLs, and when/if they come online, then to auto-generate configuration and start relaying to pmcd.  The set of URLs may itself vary.

ISTM one way of doing this would be to have the pmdaprometheus code accept not just the thousands-of-lines-long .json files, but also a reduced one with nothing but a

    { "name": "foo", "endpoint" : "http://foo/bar?baz" }

in it.  Then the user can create these files by the dozen under the pmda metadata/ directory (or somewhere nearby, if you want to use metadata/ for the generated files only).

**Comment by jronak** [comment]
Hey,

I understand that PMDA should be able to work with the sources whose config cannot be generated at the installation time. Should the PMDA poll the endpoint or lookup the endpoint on a fetch and if the source seems to be up, then it adds those metrics in the PMDA and refreshes the pmns?.
Should we update the config file with the generated metric configs when the endpoint is available or should it stay autogenerate mode ?

**Comment by fche** [comment]
Hi!  I suspect a one-time generation would be fine, if one can be sure that the prometheus schema does not change during runtime.  That sounds like a safeish assumption, except with respect to instances (metric label sets), which seems to me more changeable.  If the instances are hard-coded in the pmdaprometheus config file today, and the code cannot handle changes on the fly, then IMHO that's another problem.

Maybe both birds can be killed with one stone - namely making metadata generation entirely on-the-fly, hidden, internal.  It could generate and persistent-cache pmids, instance numbers etc. sort of the same way.  (It'd just need to be ready to generate new ones.)  And yeah, some heuristic-override mechanism might be nice, maybe, but IMHO still that's less important.

**Comment by natoscott** [comment]
| I understand that PMDA should be able to work with the sources whose config cannot be generated at the installation time.

+1

Ideally, in the end, we'll reach the point that we can use the target API to (perhaps optionally) extend the list of known endpoints beyond a canned set.

| Should the PMDA poll the endpoint or lookup the endpoint on a fetch 

Fetch time is not the best time to be thinking about tackling this.  Remember that fetch just gets a list of PMIDs, so operates well after namespace PDUs which also need visibility into newly found endpoints.  Fetch is also the most latency sensitive of the PDU operations - the last place to add more work if we can possibly avoid it.

So, ideally we need to find some other time to update the PMDA's world view.  A good option would be to run the PMDA in generate mode (and auto-endpoint-probe mode too, once the target API is in use) on some interval, in a separate process - maybe every minute, or two, or five - and write newly found/configured endpoints to a new directory.  This process could be forked/exec'd from within the PMDA on a timer, or from cron.  Neat & simple code progression from the PMDAs point of view, and it keeps fetch latency low.

| Should we update the config file with the generated metric configs when the endpoint is available or should it stay autogenerate mode ?

Currently we have a single source of configs in one "metadata" directory - we could split this into two directories - one where generated configs reside, the other with fixed, known (potentially user-corrected) metric configurations.  The PMDA would then prefer configs from the fixed user-created set, and fallback to those dynamically discovered.

When responding to PDUs from pmcd, the PMDA can simply stat(2) the dynamic metadata directory - which is a low-cost check, no network involved - and only if it has changed (i.e. stat(2) st_mtime's differ), reload its view of available metrics based on the configurations found there.

Any approach that removes the users ability to correctly set metric metadata is not going to be acceptable, so let's move on from that restricted thinking already.

**Comment by fche** [comment]
The PDMA has no choice but to fetch the prometheus endpoint's data file upon a PMAPI/PMDA fetch (since that's the only way to get new metric values), *and* on a PMAPI/PMDA PMNS enumeration (since that's how a pcp client would look up names).  So we already have two opportunities to scan & rescan the whole prometheus text file for generating / refreshing pcp metadata.  Even something heavy-weight like writing out whole new 100K JSON text files when something changes could be tolerable.

Though IMHO the 100K JSON metadata files are unnecessary.  The pmdacache for metric names / instances is plenty for storing persistent data about those metrics for which the heuristic generator is right on.  For those metrics that we speculate might benefit from user-specified pcp metadata overrides, let a user specify _only_ those, rather than force her to flip through 99.5K of unrelated JSON to find the 0.5K for the metric of interest.

**Comment by jronak** [comment]
My bad somehow lost track of this issue.

> Fetch time is not the best time to be thinking about tackling this. Remember that fetch just gets a list of PMIDs,

Especially if there are many dynamic endpoints to be scraped will failure of fetch due to latency. 

> I suspect a one-time generation would be fine

Then let's assume that instances metrics don't change dynamically. 
I propose something similar to what @natoscott has suggested. 
Let's have another directory called **auto-config** which holds the metadata of a dynamic endpoint such as `name`, `url` and `description` only. 

On PMDA `init`, if there are entries in the auto-config directory then we start a `Daemon Thread` or `Fork a process` which scrapes the endpoints at some interval. When the endpoint is live, generate and store the metadata for that endpoint and delete itself from auto-config. The new source will be added on next fetch as the `stat` functionality has already been implemented in the pmda.

**Comment by lberk** [comment]
Hey Ronak,

Looking over this patch, I'm not sure we totally solve what @fche was looking for here.  While it properly seems to enumerate metrics from a specified node, we'd still have to run the pmda in 'Generate mode' for each node of interest.  I think we'd want to be able to specify that ahead of time, and then with one run in the generate mode, (perhaps like @natoscott mentioned, in a different metadata dir).

It also might be worthwhile having the refresh interval (hard set to 15 seconds) as a pcp metric, configurable via a pmstore.

**Comment by fche** [comment]
A 15s poll by an external process is extraneous work.  The main pmdaprometheus process can already poll the same HTTP ports (at the pmapi-client requested rates), and notice if a server that was down is now up (or vice versa).  Then it wouldn't need to send itself the giant metadata files to describe the server, as it would have the prometheus exported text data _right there_.

Plus ... imagine having a couple of hundred potential URLs in the list.  The autowatch widget would have to serially poll them, each with some timeout ... it'd have a hard time just getting through the list on a timely basis.

**Comment by fche** [comment]
Why was this issue closed? PR #320 has not been merged.

**Comment by jronak** [comment]
Hey @fche 
I took up this feature as two different things, 
1) metadata refresh:  where it checks if the metrics have changed on the prometheus endpoint (by diffing) and and updates the config file of the source (JSON). This does not block the PMDA, as it runs as a subprocess.
2) metadata reload: update PMNS if the config file has been updated (Stat). This does block the PMDA, but it is a very minimal overhead as we don't update the entire PMNS of the cluster, rather other the changed ones which we find out by diff the old and new configs.

PR: #323

**Comment by fche** [comment]
Does there currently exist a configuration that, given a long list of URLs (which may not immediately resolve), it can start a pmdaprometheus to read data from them (when they are available)?

**Comment by natoscott** [comment]
@jronak I think the answer there is "yes" but maybe we're lacking some man page updates (e.g. -r/-u/-n options for scanning) - is that right?

**Comment by natoscott** [comment]
Oh, except for the bit about "start a pmdaprometheus" of course, that doesn't make sense from my understanding of the code.

**Comment by jronak** [comment]
@natoscott Yes, I have work on the man pages. 
@fche currently generator does not support bulk list of URLs, do you think it's needed ? (Might need name of the endpoint along with URL)

**Comment by fche** [comment]
> do you think it's needed ?

Yes, that sort of thing was the purpose of this issue.  The desired model is that a list of URLs is made available to pmdaprometheus, then it starts.  It collects data/metadata automatically when/as any of those URLs come online.  I'm experimenting with some pmdaprometheus modifications to this effect.

**Comment by jronak** [comment]
@fche got it. Also checkout QA 1194 as it tests for auto refresh and reload for a endpoint.
