### ISSUE TITLE
cannot reset pmcd.client.container once stored

### ISSUE THREAD

**Issue by brendangregg** [performancecopilot/pcp#312]
I can do a store of pmcd.client.container to a container. But if I then want to reset this, and go back to host-wide analysis, everything stops working until I do a pmcd restart (restarting pmdaroot). I was resetting it by storing ''.

This means some Vector changes I'm working on would let you select a container, but then you can't reverse that without a pmcd restart.

Some pmcd debug trace:

```
->20:56:51 Recv: ERROR PDU, fd=16, pdubuf=0x...ce103f10
->20:56:51 Recv error: expecting RESULT PDU, fd=16, err=-12399: Container not found
->20:56:51 Xmit: RESULT PDU, fd=21, numpmid=3
```

How to reproduce:

```
# c=$(curl -s http://100.66.37.162:7402/pmapi/context?hostspec=localhost | jq .context)
# curl http://100.66.37.162:7402/pmapi/$c/_fetch?names=kernel.all.load,kernel.all.cpu.sys,kernel.all.cpu.user
{"timestamp":{"s":1497558499,"us":715982 }, "values":[{"pmid":4194310,"name":"containers.cgroup","instances":[
{"instance":3, "value":"/docker/1d4db2b03c3e961e0f797ce3061dbe43172c8d6679f7385f14c7702b04422d31" },{"instance":15, "value":"/docker/1d567f439319020410140fcb4094b142962530e42e91eb61d5af9d871cf2c973" },{"instance":18, "value":"/docker/ea550d13e30d2d0eb114cb705ae2aa5366b71005d7ed245a1abfd33bc597fe7e" }]},
{"pmid":4194305,"name":"containers.name","instances":[
{"instance":0, "value":"goofy_mahavira" },{"instance":1, "value":"stupefied_davinci" },{"instance":2, "value":"jovial_mclean" },{"instance":3, "value":"clever_brahmagupta" },{"instance":4, "value":"stupefied_bassi" },{"instance":5, "value":"awesome_kirch" },{"instance":6, "value":"reverent_agnesi" },{"instance":7, "value":"elated_wozniak" },{"instance":8, "value":"high_mayer" },{"instance":9, "value":"loving_feynman" },{"instance":10, "value":"modest_spence" },{"instance":11, "value":"hopeful_spence" },{"instance":12, "value":"jovial_lichterman" },{"instance":13, "value":"sharp_panini" },{"instance":14, "value":"peaceful_euler" },{"instance":15, "value":"loving_hawking" },{"instance":16, "value":"distracted_galileo" },{"instance":17, "value":"peaceful_hoover" },{"instance":18, "value":"modest_swanson" },{"instance":19, "value":"tiny_keller" },{"instance":20, "value":"adoring_bohr" },{"instance":21, "value":"evil_newton" },{"instance":22, "value":"happy_yalow" },{"instance":23, "value":"cranky_payne" }]},
{"pmid":251660288,"name":"kernel.all.load","instances":[
{"instance":1, "value":3.03 },{"instance":5, "value":3.05 },{"instance":15, "value":2.79 }]},
{"pmid":251658262,"name":"kernel.all.cpu.sys","instances":[
{"instance":-1, "value":551287230 }]}]}
```

... so far, so good. Now setting a container:

```
# curl http://100.66.37.162:7402/pmapi/$c/_store?'name=pmcd.client.container&value=loving_hawking'
{"success":1 }
# curl http://100.66.37.162:7402/pmapi/$c/_fetch?names=kernel.all.load,kernel.all.cpu.sys,kernel.all.cpu.user
{"timestamp":{"s":1497558555,"us":368977 }, "values":[{"pmid":251660288,"name":"kernel.all.load","instances":[
{"instance":1, "value":3.01 },{"instance":5, "value":3.04 },{"instance":15, "value":2.8099999 }]},
{"pmid":251658262,"name":"kernel.all.cpu.sys","instances":[
{"instance":-1, "value":551331800 }]},
{"pmid":251658260,"name":"kernel.all.cpu.user","instances":[
{"instance":-1, "value":803715530 }]}]}
```

... that also works. Now resetting the container back to the host by storing '':

```
# curl http://100.66.37.162:7402/pmapi/$c/_store?'name=pmcd.client.container&value='
{"success":1 }
# curl http://100.66.37.162:7402/pmapi/$c/_fetch?names=kernel.all.load,kernel.all.cpu.sys,kernel.all.cpu.user
{"timestamp":{"s":1497558562,"us":41589 }, "values":[]}
```

Now it's not returning the values (I imagine due to the container not found issue).

Any other API calls possible to reset pmdaroot's state? Or something else to set pmcd.client.container to? Thanks.

**Comment by fche** [comment]
Is there some reason you want to change things this way?  You can create a new container-focused context to pmwebd via the  `/pmapi/context?hostspec=STRING&container=FOOBAR`.

**Comment by brendangregg** [comment]
Thanks, I'll try that.

Should have also mentioned that creating a new context after setting the container to '', also fails to work properly. Hence the pmcd restart.

**Comment by brendangregg** [comment]
If I set the container in the context, it doesn't populate pmcd.client.container.

```
# c2=$(curl -s http://100.66.37.162:7402/pmapi/context?hostspec=localhost'&container=loving_hawking' | jq .context)
 # curl http://100.66.37.162:7402/pmapi/$c2/_fetch?'names=pmcd.client.container'
{"timestamp":{"s":1497565348,"us":614654 }, "values":[{"pmid":8394754,"name":"pmcd.client.container","instances":[
{"instance":1, "value":"" }]}]}
```

As a workaround, I think I can create new contexts for containers and then call the store. So that I'm never calling a store of ''.

**Comment by brendangregg** [comment]
Ah, that doesn't work. Once I start storing to pmcd.client.container, then new contexts inherit its container value. :(

**Comment by natoscott** [comment]
@brendangregg it should be possible to clear the container setting on a context using an empty string with the store interface - looks like a bug.  I'll look into fixing it up today, thanks.

**Comment by brendangregg** [comment]
Ok, thanks @natoscott . The store of pmcd.client.container approach was easier.

**Comment by brendangregg** [comment]
@natoscott if it's fixed quickly, would a new package version be on bintray? (We're looking to deploy some new container support that prod needs ASAP.)

**Comment by natoscott** [comment]
@brendangregg I'm testing the fix now - working nicely so far, should hit master branch later this morning.
In terms of bintray updates, that'll happen with the next release - http://pcp.io/roadmap - two weeks away.

**Comment by fche** [comment]
"Ah, that doesn't work. Once I start storing to pmcd.client.container, then new contexts inherit its container value. :("

That sounds like a wholly separate bug (in libpcp).  Chances are though that it is/was related to socket connection-sharing, which has just now been removed, so this part will also start working.  If able, try git master pcp.
