### ISSUE TITLE
Debian stretch binary builds

### ISSUE THREAD

**Issue by rlex** [performancecopilot/pcp#314]
Hello, can you please add debian 9 (stretch) as build target to bintray?

**Comment by natoscott** [comment]
@rlex sure thing - will include that platform with the next release's builds (next Friday).

**Comment by rlex** [comment]
Sweet, thanks!

**Comment by natoscott** [comment]
I made a couple of attempts at installing debian9 VMs today, but both failed to boot.  And I'm outta time for now, so these will have to wait for a few weeks until I'm back online - sorry 'bout that.

**Comment by natoscott** [comment]
Third time's a charm: https://bintray.com/pcp/stretch
