### ISSUE TITLE
RFE: pmdaprometheus / prometheus-exporter round-trip capability: PMNS encoding

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#319]
It will be desirable to be able to connect a future pcp prometheus-exporter with pmdaprometheus, so as to pass pcp data through a prometheus exporter webapi.  For this to work at a high fidelity, there is a need to allow passage of the pcp metric names (regex `[a-ZA-Z0-9_]` dotted components) through the prometheus naming constraints (regex `[a-zA-Z_:][a-zA-Z0-9_:]*` sans components).

It seems as though the `.` separators in the pcp pmns could be mapped to/from the prometheus `:` character.  (We can handle not-quite-well-formed names like prometheus 'foo::bar:::' with any heuristic approach we like, since a pcp prometheus-exporter wouldn't generate them in the first place.)

**Comment by fche** [comment]
Another complication is the encoding of pmDesc semantics/types through prometheus.
As per https://prometheus.io/docs/practices/naming/ , base units may appear encoded as suffixes of the metric names.  It's not as powerful as pcp (up to one dim*=1 and other dim*=0), but very few pcp metrics don't fit.

Anyway, the pmdaprometheus metadata generator should strip away those type/dim suffixes from incoming prometheus names as they're passed into pcp.  e.g.:

`go_memstats_gc_sys_bytes` -> `goo_memstats_gc_sys` (pmUnits=bytes, sem=instant)
`prometheus_local_storage_series_ops_total` -> `prometheus_local_storage_series_ops` (sem=counter)

**Comment by jronak** [comment]
`_` replacement with `:` sounds good, any reason to avoid `.` ?

And yes the units conversion is on my todo. Will be on it soon

**Comment by fche** [comment]
> any reason to avoid `.` ?

Yeah, apparently it's not a valid character in prometheus metrics names.

**Comment by natoscott** [comment]
| pcp metric names (regex [a-ZA-Z0-9_] dotted components) through 

The above regex is not quite correct - see the SYNTAX section of the PMNS(5) man page.  In particular:

"Each component [...] must begin with an alphabetic character, and be followed by zero or more characters drawn from the alphabetics, the digits and the underscore ``_'') character."

(IOW, a metric name cannot start with digit or underscore, and neither can any metric name component)

| the prometheus naming constraints (regex [a-zA-Z_:][a-zA-Z0-9_:]* sans components).

I think the ':' to '.' translation is valid and good, but I'd be concerned about further name manipulation (like stripping units embedded in the prometheus names).  This introduces ambiguity and potential for name conflicts.  IOW, when two prometheus metric names like "foo_bytes" and "foo" exist, there is now ambiguity and a generated-name conflict on the generated PCP metric name "foo".

**Comment by fche** [comment]
> I'd be concerned about further name manipulation (like stripping units embedded in the prometheus names). This introduces ambiguity [...]

Yes, there is that hypothetical risk.  But in reality, when processing a prometheus-export document, we have a complete list of the metrics _actually_ present, and can reject the heuristic processing for such cases.  We can also ensure that no such ambiguity is presented by the pcp prometheus-exporter.

**Comment by natoscott** [comment]
| go_memstats_gc_sys_bytes -> goo_memstats_gc_sys (pmUnits=bytes, sem=instant)

There is no gain to be had from changing the metric names like this, and doing so clearly introduces (unnecessary) problems.  Even PCP developers routinely use suffixes like these all over the place - in PCP metric names - it's generally considered useful, clarifying information to end users working with the metrics ...

disk.dev.read_bytes
disk.dev.write_bytes
disk.dev.total_bytes
network.interface.in.bytes
network.interface.out.bytes
network.interface.total.bytes
tape.dev.write_byte_cnt
tape.dev.write_ns

**Comment by fche** [comment]
> There is no gain to be had from changing the metric names like this

The gain would be a high-fidelity round-trip capability, which is after all the topic of this PR.  We need a reversible mapping of pcp metric names + pmDesc metadata through prometheus export documents, while fitting in reasonably with a real prometheus server that could want to consume the same data.

Other mangling schemes that compromise differently are of course possible.  We could preserve the pcp/prometheus metric names (except for the `:` <-> `.` translation), and shove pmDesc matter into some name suffix.  Or extending the export format with another `# PCP $units $semantics` comment line that our pmda could look for.  This would penalize prometheus consumers, since they would lack the `_bytes` etc. name suffixes from those pcp metrics that don't already have it (and there are lots).

**Comment by fche** [comment]
See two commits on pcpfans.git fche/pmfuntools that are related to this.  They don't include an update to the pcpqa/662.out* but are otherwise ready to go.

https://sourceware.org/git/gitweb.cgi?p=pcpfans.git;a=commit;h=b54c65dda1ee84fb68ff8bda956a57116fd933bf
https://sourceware.org/git/gitweb.cgi?p=pcpfans.git;a=commit;h=7eddc5bfba144cfee8bfdbee8770016cf966ac76

**Comment by goodwinos** [comment]
@fche the two commits listed in the previous comment no longer exist. Do you happen to still have the split-out patches for the pmwebabi "gigapatch" around somewhere? Review and QA for all the changes in the 2000+ line gigapatch 65cc0bbcb "pmwebd graphite archive naming / caching major rework" is proving difficult.

thanks

**Comment by fche** [comment]
The fche/pmfuntools branch gets rebased periodically, so commit hashes must have become garbage-collected during the elapsed 7 weeks.  The current codes for those two commits are:

commit 5c67ac93c3d59973a0c4c74b58e2a34f90f08150
Author: Frank Ch. Eigler <fche@redhat.com>
Date:   Fri Aug 18 10:29:39 2017 -0400

    pmwebapi man: document prometheus extensions
    
    Including some examples so that the heuristic name mappings are
    plainly visible.

commit 2d28713070f8807779e8f11bec7904e0fb60eeaf
Author: Frank Ch. Eigler <fche@redhat.com>
Date:   Fri Aug 18 10:27:56 2017 -0400

    pmwebd prometheus exporter: fix HELP, quoting, etc.
    
    The HELP text must use the same encoded metric name as TYPE etc.
    Added a # PCP line to identify the original unmangled pcp metric name.
    Removed escaping of / characters in instance strings; it is
    unnecessary and unsightly.  Corrected HTTP Content-type of prometheus
    data to text/plain.

**Comment by fche** [comment]
> Do you happen to still have the split-out patches for the pmwebabi "gigapatch" around somewhere? Review and QA for all the changes in the 2000+ line gigapatch 65cc0bbcb "pmwebd graphite archive naming / caching major rework" is proving difficult.

I'd be glad to help advise that in greater detail, though those are not related to prometheus.  The pmwebd -J work is not too amenable to breaking up into little pieces for review purposes, since so much of the structure (archive metadata caching) is new.  As for QA, I'd run  `pmwebd -J -G -X -A $pcpqa/`, and then curl some time series graphite-api queries against a good subset of the bad and good archives.  That should give reasonable code coverage by itself.

**Comment by goodwinos** [comment]
Thanks Frank - regarding 2d28713070f8 "pmwebd prometheus exporter: fix HELP, quoting, etc." : you left an XXX marker in there. Was that to signify that perhaps we should also include other PCP metadata, e.g. the units and scale? Or something else? If the former, I'll add a call to also output "# UNITS"  and the pmUnitsStr from the descriptor.

**Comment by fche** [comment]
Good eye!  Yeah, I was thinking about adding a few more fields, adding a pmSemStr & pmUnitsStr string dump at the end of the # PCP line.

**Comment by goodwinos** [comment]
Regarding the gigapatch: it's mostly a rewrite of src/pmwebapi/pmgraphite.cxx and so I'll craft a QA test using those pmwebd options that you suggested, and also check the hostnames are correctly listed rather than the archive paths (since that's also part of the patch). Thanks for that. Do we really need all the configure and spec changes to check for and use boost? If so, we'll also need equivalent pcp.spec.in changes. Does the boost_devel stuff make much difference?

**Comment by fche** [comment]
> mostly a rewrite

Yeah, of the lower level part.

> Do we really need all the configure and spec changes to check for and use boost? 

Using the boost fliyweight objects allows us to reuse memory for the hugely replicated metadata (metric names, instance names) between different archives.  The code works without, just using more memory.  Yeah, the fedora.spec should include the boost-devel buildrequire.

**Comment by natoscott** [comment]
Everything here has been rebuilt from scratch multiple times, and any remaining work planned is covered by other GH issues.
