### ISSUE TITLE
RFE: linux per-process network connections

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#321]
Getting a list of active network connections of processes as been a frequently requested feature.  While there is no single `/proc/$id/FOO` file that has that info, pcp could assemble it from joining two tables.

`/proc/$id/fd/*` contains a list of file descriptors.  An lstat() over them may return `socket:[NNNNNN]`.
`/proc/$id/net/{tcp,udp,tcp6,udp6}` contain a list of tcp/udp sockets.  The inode column ($9) matches NNNNNN from the fd symlink.  `.../unix` too, just a different column.  The rest of the line is hex-encoded with ip addresses etc.  These `/net/` files contain all the records for the same (network) cgroup, so can be memoized across processes.

So we can get a list of sockets opened by each process.  To represent them as pcp metrics, we could add them as `proc.psinfo.{udp,tcp,udp6,tcp6,unix}.connected` metrics, with an instance domain that corresponds to the source/destination addresses, pretty-printed, and with a dummy 1 value for live connections.  Or at some point one could use the metric labels as a structured variant of the same.

**Comment by myllynen** [comment]
For an earlier request / discussion, see https://bugzilla.redhat.com/show_bug.cgi?id=1214364.

**Comment by myllynen** [comment]
Here's a rough summary of the currently available alternatives:

1) Custom kernel module based solutions

ntopng (http://www.ntop.org/) has something called PF_RING (http://www.ntop.org/products/packet-capture/pf_ring/), available at https://github.com/ntop/PF_RING.

atop (https://www.atoptool.nl/) can use their netatop module described in https://www.atoptool.nl/netatop.php.

These would seem to be provide accurate statistics with low overhead but the downside in some cases is that the system becomes unsupported when using 3rd party kernel modules.

2) libpcap based solutions

nethogs (https://github.com/raboof/nethogs), tcpdump (https://github.com/the-tcpdump-group/tcpdump), Wireshark (https://www.wireshark.org/), etc use libpcap which works but some think this introduces too much overhead.

3) SystemTap scripts

https://sourceware.org/systemtap/examples/network/nettop.stp and alike work but these at least used to be perhaps slightly inconvenient in case debuginfo kernels were needed, however overhead is probably less than with libpcap.

4) Netlink based solutions

For example ss -ip can provide socket statistics using the netlink interface, for details see https://github.com/shemminger/iproute2/blob/master/misc/ss.c.

5) BPF based solutions

tcptop uses Linux BPF capabilities, see: http://www.brendangregg.com/blog/2016-10-15/linux-bcc-tcptop.html

**Comment by myllynen** [comment]
We now have BCC PMDA (see https://github.com/performancecopilot/pcp/pull/409) which implements the option 5 from the earlier list that can be used, if suitable BPF programs are available, to provide per-process network metrics. However, since currently only TCP rx/tx metrics are provided, I don't think this RFE is complete yet. Thanks.

**Comment by myllynen** [comment]
One theoretical source might be even systemd which can keep track of IP based traffic (not just TCP) with the help of BPF; the downside would be that only systemd managed (system or user) services could be monitored this way, but if that is being anyway by systemd in some cases, that would avoid a double effort for this. I haven't investigated how feasible it would be to fetch this information from systemd to PCP (although there's an API for it, of course).

For more info, see http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html.

**Comment by myllynen** [comment]
BCC PMDA netproc module now allows monitorig per-process TCP/UDP traffic. That should address this issue, if there are some additional requirements or improvements those could be discussed in a more specific RFE. Thanks.
