### ISSUE TITLE
PCP 12.0 libvirt pmda missing for ubuntu 14.04

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#325]
I installed the bintray release for ubuntu 14.04 and the libvirt pmdas folder is missing. This folder was present in previous version of pcp (3.11.7)

**Comment by kmcdonell** [comment]
@hc000 I think this has been fixed.

I just checked and the pcp_3.12.1_amd64.deb package for trusty certainly contains the libvirt PMDA.
