### ISSUE TITLE
linux pmda crash - dso - bad free() memory error in pmdaDynamicMetricTable

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#339]
The pmda_linux, operated in DSO mode, causes bad-free() type crashes, because of the way the dynamic metric code in libpcp_pmns rearranges incoming `pmda->e_metrics`.

     ==29343== Invalid free() / delete / delete[] / realloc()
     ==29343==    at 0x4C2ED4A: free (vg_replace_malloc.c:530)
     ==29343==    by 0x4E47EF2: pmdaDynamicMetricTable (dynamic.c:232)
     ==29343==    by 0x4E47FE7: pmdaDynamicLookupName (dynamic.c:127)
     ==29343==    by 0x990EA7F: linux_children (pmda.c:7660)
     ==29343==    by 0x1177CE: traverse_dynamic (dopdus.c:781)
     ==29343==    by 0x1177CE: DoPMNSTraverse (dopdus.c:976)
     ==29343==    by 0x10F38A: HandleClientInput (pmcd.c:388)
     ==29343==    by 0x10E1FF: ClientLoop (pmcd.c:777)
     ==29343==    by 0x10E1FF: main (pmcd.c:1005)
     ==29343==  Address 0x9b27ea0 is 0 bytes inside data symbol "metrictab"
     ==29343== 

The code is not well set up for these metric tables being heap vs. statically allocated.

The following script tries to trigger this, via an unprivileged user running it out of `/tmp/foo`.  This sort of usage resembles pcp/pmcd operation in unprivileged containers.
[setup.txt](https://github.com/performancecopilot/pcp/files/1271469/setup.txt)

**Comment by goodwinos** [comment]
reference BZ 1451475 - "proc pmda crashes in -K/-L mode". Nathan just mentioned he has a fix for this now, so the problematic workaround in pmfuntools (to leak memory) could be reverted after updating to pcp-4.
