### ISSUE TITLE
pmfg crash with invalid scaling option

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#341]
In the following example the requested scale conversion does not make sense but I think it should be handled better than crashing at a random point. Perhaps rejecting it right away would be the best option?

$ cat test.py
#!/usr/bin/env pmpython

import time
from pcp import pmapi

pmfg = pmapi.fetchgroup()
test = pmfg.extend_indom("mem.util.free", None, "MB/s", 1024)

pmfg.fetch()
while True:
    time.sleep(1)
    pmfg.fetch()
    for icode, iname, value in test():
        print (value())
$ ./test.py
0
0
7
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    print (value())
  File "/usr/lib64/python2.7/site-packages/pcp/pmapi.py", line 2250, in
<lambda>
    (lambda i: (lambda: decode_one(self, i)))(i)))
  File "/usr/lib64/python2.7/site-packages/pcp/pmapi.py", line 2245, in
decode_one
    raise pmErr(self.stss[i])
pcp.pmapi.pmErr: PM_ERR_SIGN Negative value in conversion to unsigned

**Comment by fche** [comment]
The conversion does make some sense - by asking for a `MB/s` scale, you're asking the system to rate-convert the instant `mem.util.free` metric.  As the instant metric may decrease in value, libpcp computes a negative instantaneous rate.  That triggers the conversion signedness problem.

If you'd like to rate-convert metrics of unsigned base type, but up/down fluctuating value, ask for a signed (or floating point) type at the extend_indom point.

**Comment by myllynen** [comment]
Fair enough, see metric like free memory going up/down per second may make some sense.

But if this is bound to crash, how about something like:

--- a/src/python/pcp/pmapi.py
+++ b/src/python/pcp/pmapi.py
@@ -2374,7 +2374,10 @@ class fetchgroup(object):
         if mtype is None: # a special service to dynamically-typed python; not accepted at the C level
             pmids = self.ctx.pmLookupName(metric)
             descs = self.ctx.pmLookupDescs(pmids)
-            mtype = descs[0].type
+            if scale is None or '/' not in scale:
+                mtype = descs[0].type
+            else:
+                mtype = c_api.PM_TYPE_FLOAT
         v = fetchgroup.fetchgroup_item(mtype)
         sts = LIBPCP.pmExtendFetchGroup_item(self.pmfg,
                                              c_char_p(metric.encode('utf-8') if metric else None),
@@ -2400,7 +2403,10 @@ class fetchgroup(object):
         if mtype is None: # a special service to dynamically-typed python; not accepted at the C level
             pmids = self.ctx.pmLookupName(metric)
             descs = self.ctx.pmLookupDescs(pmids)
-            mtype = descs[0].type
+            if scale is None or '/' not in scale:
+                mtype = descs[0].type
+            else:
+                mtype = c_api.PM_TYPE_FLOAT
         vv = fetchgroup.fetchgroup_indom(mtype, maxnum)
         sts = LIBPCP.pmExtendFetchGroup_indom(self.pmfg,
                                               c_char_p(metric.encode('utf-8') if metric else None),

Thanks.

**Comment by fche** [comment]
I suppose that'd be OK.  It doesn't cover inferred rate conversion of ordinary counters (where scale is None); those too could go negative for anomalous data.  In a way, to be Safest Possible, we could simply infer `mtype=None` -> `mtype=PM_TYPE_DOUBLE`.

**Comment by myllynen** [comment]
We agreed that this is better done by a client (or, in case of pmrep/pcp2xxx, the new pmconfig module) so let's close this ticket, the changes agreed upon are already in master and will be part of 3.12.2. Thanks.
