### ISSUE TITLE
Zabbix Agent 3.4 support

### ISSUE THREAD

**Issue by darrynv** [performancecopilot/pcp#346]
Please add support for zabbix agent v3.4

**Comment by goodwinos** [comment]
@darrynv a new tool named pcp2zabbix is coming to PCP very soon, and will include a patch to use integer clock values rather than float as required by zabbixv3.4. Do you know of any other changes needed for 3.4 compatibility?

**Comment by darrynv** [comment]
No other changes needed that I am aware of. Any idea why you switched for LoadableModules to an external sender? The ability to load pcp call's natively in the Agent configuration is still needed?
