### ISSUE TITLE
pcp.io website down

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [performancecopilot/pcp#347]
The pcp.io DNS record is NXDOMAIN and www.pcp.io still redirects to pcp.io, so there is no website now.

**Comment by natoscott** [comment]
Not seeing any issues here, and no configuration has changed recently - could you have been affected by https://news.ycombinator.com/item?id=15293811 perhaps?

**Comment by kmcdonell** [comment]
@JohnPeacockMessageSystems, it is almost a month, and no further issues related to www.pcp.io availability that I'm aware of, so I am closing this issue in the absence of further evidence.
