### ISSUE TITLE
pmprobe -O does not work

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#354]
It seems that the -O option with pmprobe(1) does nothing:

$ pmval -z -a archives/rep -s 1 -O 0 mem.util.used | tail -n 1
14:39:13.883             13573328
$ pmval -z -a archives/rep -s 1 -O 2 mem.util.used | tail -n 1
14:39:15.883             13573256
$ pmprobe -z -a archives/rep -v -O 0 mem.util.used         
Note: timezone set to local timezone of host "slack" from archive

mem.util.used 1 13573328
$ pmprobe -z -a archives/rep -v -O 2 mem.util.used            
Note: timezone set to local timezone of host "slack" from archive

mem.util.used 1 13573328

**Comment by kmcdonell** [comment]
Simple fix ... pmSetMode() was being used with opts.start (pmprobe has no -S option) instead of opts.origin (where the -O timestamp is salted away).

Fixed in my nextrelease branch via commit  e780ab4

**Comment by kmcdonell** [comment]
Oops that should be commit 9b586f2.
