### ISSUE TITLE
pmdumplog -a does not show timezone

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#355]
pmdumplog(1) states:

       -a   Report everything, i.e. the flags -d, -i, -l, -m, -s and -t.

However, this does not include -L which would print timezone which is quite helpful information.

Please consider including -L in -a. Thanks.

**Comment by kmcdonell** [comment]
On 16/10/17 21:43, Marko Myllynen wrote:
> pmdumplog(1) states:
> 
> |-a Report everything, i.e. the flags -d, -i, -l, -m, -s and -t. |
> 
> However, this does not include -L which would print timezone which is 
> quite helpful information.
> 
> Please consider including -L in -a. Thanks.

Fixed in my nextrelease branch.

Code and man page changes are trivial ... qa fallout is a whole 
different kettle of fish!

**Comment by kmcdonell** [comment]
Closed by commit 1dba9ed
