### ISSUE TITLE
PMDA Initialisation Failed

### ISSUE THREAD

**Issue by pcpuser001** [performancecopilot/pcp#36]
Hi All, 
while exploring pcp 
in PMDAMMV.log we are getting error. 

Log for pmdammv on GFGPH32.egi.ericsson.com started Tue Aug 11 14:25:32 2015

[Tue Aug 11 14:25:42] pmdammv(24263) Warning: pduread: timeout (after 10.000 sec) while attempting to read 12 bytes out of 12 in HDR on fd=0
[Tue Aug 11 14:25:42] pmdammv(24263) Critical: __pmdaSetupPDU: PMDA pmdammv getting creds: Timeout waiting for a response from PMCD
[Tue Aug 11 14:25:42] pmdammv(24263) Error: PMDA Initialisation Failed

Let me know how to overcome this error.

Regards,
Prem

**Comment by kmcdonell** [comment]
This looks like you've run pmdammv directly ... if this is the case, that is not the right way to invoke a PMDA.

To get the mmv (or in general the foo) PMDA working you need ...

# cd /var/lib/pcp/pmdas/foo
# ./Install

If this diagnosis is not correct, please send us
- output from the pcp(1) command
- contents of /etc/pcp/pmcd/pmcd.conf
- contents of /var/log/pcp/pmcd/pmcd.log

**Comment by pcpuser001** [comment]
Its working now. Thanks alot
