### ISSUE TITLE
Debian 32-bit repos exist, but are empty

### ISSUE THREAD

**Issue by inflatador** [performancecopilot/pcp#364]
This one stumped me for awhile. Looking at [https://dl.bintray.com/pcp/stretch/dists/stretch/main/binary-i386/Packages](url), we can see that 32-bit Debian repos exist, but are empty.

Recommend either building the 32-bit packages or putting something explicit on the website (pcp.io) that says 32-bit packages are not available.

**Comment by natoscott** [comment]
We have no plans to provide 32 bit builds on bintray, they're becoming less and less relevant - if still needed, please use the upstream Debian package builds I guess.
