### ISSUE TITLE
pmie value's taken

### ISSUE THREAD

**Issue by pcpuser001** [performancecopilot/pcp#37]
Hi ALL,
Regarding pmie , May i know the value of metric is taken for consideration, what i read is metric's average value is taken. if so how to take current/recent value for that metric.

Regards,
Prem

**Comment by natoscott** [comment]
When in live mode, the current value is what is used on each sample, unless one of the avg_* operators is being used or an earlier sample value is being used via the @ keyword.  e.g.

$ echo 'ctxts = kernel.all.pswitch; ' | pmie -t 1second -ve
ctxts (Thu Aug 13 12:25:42 2015): ?

ctxts (Thu Aug 13 12:25:43 2015): 69257

ctxts (Thu Aug 13 12:25:44 2015): 69854

ctxts (Thu Aug 13 12:25:45 2015): 68973

ctxts (Thu Aug 13 12:25:46 2015): 69138

ctxts (Thu Aug 13 12:25:47 2015): 69777

**Comment by pcpuser001** [comment]
Thanks a lot natoscott.
