### ISSUE TITLE
Provide TTY device activity metrics

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#371]
PCP on Linux does not provide the corresponding metrics as what sar -y provides:

https://www.mankier.com/1/sar#-y

Please consider adding them (from at least partially /proc/tty/driver/serial). Thanks.

**Comment by lberk** [comment]
Patch proposed:
https://groups.io/g/pcp/message/17356

Commit:
commit c68b4b69527edae62ba0fed570fa3fd2cad17326
Author: Lukas Berk <lberk@...>
Date: Wed Dec 6 11:19:30 2017 -0500

pmdalinux: Add serial metrics

github issue 371 add metrics for /proc/tty/driver/serial

added qa as well as proc_tty.{c,h} for scraping values from proc and
using pmdacache functions to store the instance domains.

**Comment by lberk** [comment]
https://github.com/performancecopilot/pcp/commit/dbc48b21e7933e161a372e14f16c527a4a1d4ca7
