### ISSUE TITLE
PCP -S can't be used in live mode

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#375]
From https://bugzilla.redhat.com/show_bug.cgi?id=1309190:

From PCPIntro(1):

       -S starttime
              By default the time window commences  immediately  in  real-time
              mode, or coincides with time at the start of the PCP archive log
              in archive mode.  The -S option may be used to specify  a  later
              time for the start of the time window.

              interval
                     To  specify an offset from the current time (in real-time
                     mode) or the beginning of a PCP archive (in archive mode)
                     simply specify the interval of time as the argument.  For
                     example -S 30min will set the start of the time window to
                     be  exactly  30  minutes  from  now in real-time mode, or
                     exactly 30 minutes from the start of a PCP archive.

But:

$ pmval -S 1m kernel.all.sysfork
pmval: time window options are supported for archives only
Usage: pmval [options] metricname
...

So the man page and the libpcp code are not in sync.

**Comment by natoscott** [comment]
No plans to implement this option for (most) live mode tools - the documented live mode behaviour is optionally implemented in some though IIRC.
