### ISSUE TITLE
RFE: Optimize pmlc(1) disconnect

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#376]
From https://bugzilla.redhat.com/show_bug.cgi?id=1327259:

$ time echo status | pmlc -P
...
pmlc -P  0.00s user 0.00s system 0% cpu 1.006 total

Here the actual command output appears instantly, seems that most of the time is spent disconnecting / terminating pmlc(1), perhaps this could be optimized a bit.

**Comment by natoscott** [comment]
strace shows...

17:58:57.136422 close(3)                = 0
17:58:57.136460 nanosleep({tv_sec=1, tv_nsec=0}, 0x7ffd80be69d0) = 0
17:58:58.137327 exit_group(0)           = ?

... there's an explicit 1 second sleep in there.  I expect its from this snippet of code:

```
void
DisconnectLogger(void)
{
    if (logger_fd != -1) {
        __pmCloseSocket(logger_fd);
        logger_fd = -1;
        sleep(1);
    }
}
```

@kmcdonell any chance you remember what that's for?  This may explain some of our observed slowness in the pmlogger check/daily scripts too.
