### ISSUE TITLE
sending snmp based on pmie 

### ISSUE THREAD

**Issue by pcpuser001** [performancecopilot/pcp#38]
Hi ALL,
may i know is there any provision to send SNMP trap based on certain metric value? what i read is in pmie we can use shell to call executable's , apart from that is there any way to achieve the same.

Thanks

**Comment by natoscott** [comment]
Currently this can only be achieved using the shell action (and e.g. snmptrap utility from net-snmp).  Code could be added to pmie to make this a first class action, if there was demand & someone wrote the code... (similar to the stomp action already in the code).

**Comment by pcpuser001** [comment]
Thanks a lot natoscott.
