### ISSUE TITLE
pmlogger configuration issues

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#380]
```
$ pmval -s 1 'libvirt.dominfo.name[0e954425-8fa4-44fd-92cd-f1547bebfa46,a6e32ea8-d694-7b9a-f3b9-1fcab17804e0]'

metric:    libvirt.dominfo.name
host:      localhost
semantics: discrete instantaneous value
units:     none
samples:   1
full label for instance[0]: a6e32ea8-d694-7b9a-f3b9-1fcab17804e0
full label for instance[1]: 0e954425-8fa4-44fd-92cd-f1547bebfa46

a6e32ea8-d694-7b9a-f3 0e954425-8fa4-44fd-92 
      "rhel-7-server"          "f27-server" 
$ cat pmlogger.conf
log mandatory on default {
  libvirt.dominfo.name[0e954425-8fa4-44fd-92cd-f1547bebfa46,a6e32ea8-d694-7b9a-f3b9-1fcab17804e0]
}
$ rm -f test.0 test.index test.meta
$ pmlogger -c ./pmlogger.conf -t 1 test
zsh: exit 1     pmlogger -c ./pmlogger.conf -t 1 test
$ 
```

It's unclear why this fails, especially since no error message is provided.

In case there's a typo in the metric name, pmlogger again fails without an error message.

**Comment by natoscott** [comment]
@myllynen I think you'll find pmlogger always writes to a log file - when run by hand like you've done here, with no -l/--log option, the default is "pmlogger.log".

I suspect the second problem is the lack of quotes around your instance names - possibly the '-' character is special in the pmlogger language, or something like that.  If thats the case your log file will contain something like:

Specification error in configuration file (config)
[line 2] syntax error

cheers.

**Comment by myllynen** [comment]
Right you are, not sure how I managed to forget that. Yes, looks like '-' is the culprit here, after a bit of back and forth, doublequoting the instance names only seems to be the correct way:

```
log mandatory on default {
  libvirt.dominfo.name["0e954425-8fa4-44fd-92cd-f1547bebfa46","a6e32ea8-d694-7b9a-f3b9-1fcab17804e0"]
}
```

Let's close this one, mostly, if not entirely, an user issue. Thanks.
