### ISSUE TITLE
cgroup v2 support

### ISSUE THREAD

**Issue by brendangregg** [performancecopilot/pcp#381]
Now that the v2 CPU cgroup landed in 4.15, I'm creating this issue for cgroup v2 support. :)

I suppose the docs are here:

https://github.com/torvalds/linux/blob/master/Documentation/cgroup-v2.txt

**Comment by natoscott** [comment]
systemd in Fedora31 enables this only now (no longer using 'unified v1 + v2 mode), the PCP support is now well underway - expect we'll finish this for next release.
