### ISSUE TITLE
pmmgr: for 'monitor' subordinate daemons, preserve error messages

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#382]
When a pmmgr `monitor` daemon fails, it would be helpful for a sysadmin to be able to see the daemons' output.  pmmgr currently saves them to $logdir/$hostid/monitor-NN.err.  After an exit, the previous contents are lost.

`pmmgr` should probably just pass through its own stderr to the child process. Or else open & transcribe the .err files to its own logging stream during the daemon's cleanup or restart.

**Comment by fche** [comment]
implementation pushed to fche/pmfuntools on pcpfans.git

    commit 4a3b9fbd4c95005125359d9c3bfbbeab154bd60a
    Author: Frank Ch. Eigler <fche@redhat.com>
    Date:   Thu Dec 7 14:31:35 2017 -0500

    pmmgr: issue/382: for monitor subordinate daemons, preserve error message
    
    When a monitor daemon fails, its stderr messages in
    $hostid/monitor-NN.err should not quietly disappear as the daemon is
    restarted.  We now transcribe them to pmmgr's own error stream, just
    before a new copy of the daemon is started.  qa/1344 new.

**Comment by goodwinos** [comment]
merged from pcpfans into upstream master :
commit 289c13285631d6b87abf4b38554f69895517904b
Author: Frank Ch. Eigler <fche@redhat.com>
Date:   Thu Dec 7 14:31:35 2017 -0500

    pmmgr: issue/382: for monitor subordinate daemons, preserve error message

which includes an update to qa/1344
