### ISSUE TITLE
pmdaprometheus: non-root execution

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#383]
The python pmda should get the few lines added to drop its root privileges (if it has them to start with).

**Comment by goodwinos** [comment]
The python PMDA class has a static method for this:

PMDA.set_user(username)

which just calls : 
        return cpmapi.pmSetProcessIdentity(username)

So we probably want a -u username cmdline option, defaulting to not calling set_user() if the option is not given.

Does that sound like what you had in mind?

**Comment by fche** [comment]
Yup!

**Comment by goodwinos** [comment]
Implemented upstream (will be merged later today to master).

commit 69182af2cbac2c566ef101072e99844eaa9ea5d3
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Tue Dec 12 14:46:32 2017 +1100

    pmdaprometheus: add -u user option, update man page
    
    Allow the prometheus PMDA to run as a different user.
    QA for this coming later with a dbpmda script.
    
    GH #383, pmdaprometheus: non-root execution

**Comment by fche** [comment]
Sounds good. (Not sure it needs to be an Install prompt, up to you.)
