### ISSUE TITLE
pmdaprometheus: exec: option

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#384]
It could be useful to let pmdaprometheus run subsidiary programs on demand to generate prometheus exporter data.  It'd be similar to 'pmdapipe', except that it would accept structured data rather than text.  This can be done by accepting a syntax like    `exec:cmd arg arg arg` inside a `.url` file.

Then we can ship (or let people ship) shell scripts that scrape local system info, like `ss`/`netstat -t` and massage them into prometheus format data.  It could solve https://github.com/performancecopilot/pcp/issues/321 .

**Comment by goodwinos** [comment]
With this feature, pmdapropmetheus would really morph into an "ingest" PMDA, which is kind of what I've been going on about with an ingest2pcp importer (still currently prometheus2pcp and not committed yet).

"prometheus formatted data", with an "# PCP line", is really a PCP end-point - no reason we can't invent our own format for scraping and importing http sources.

**Comment by fche** [comment]
> no reason we can't invent our own format

IMHO, inventing new formats/apis/etc. is a last resort.  Converting to existing ones is better if at all possible.

**Comment by goodwinos** [comment]
Could help #321 and #370 e.g. could exec a small AWS RDS API client that would export metric data back to pmdaprometheus

**Comment by goodwinos** [comment]
I have patches almost ready for this issue - just doing the required QA updates and will add a couple of new tests. These changes should also help resolve or at least provide the scripting framework for #392, #389 and #370 and probably others.

**Comment by goodwinos** [comment]
This task is complete and merged upstream - 
commit 01655002fbebac6c184bc782fc54a667235b6182
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Wed Jan 10 20:16:31 2018 +1100

    pmda prometheus: add support for scripted configuation

commit 7baf4154c3dbc31f9b1bbf63fe2798561b4883ce
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Wed Jan 10 23:25:41 2018 +1100

    qa: QA updates incorporating prometheus PMDA scripted ingest support

.. and related follow-up commits
