### ISSUE TITLE
pmwebd graphite mode: normalize scales across multiple time series

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#385]
With the graphite /render webapi, it is easy to ask pmwebd to produce combined results from multiple time series from different metrics.  When those metrics share types/units but not scale, the resulting time series (whether raw json numbers or png graphics) will tend to let the smallest-scale (largest-raw-value) metrics stand out.

It would be better if pmwebd automatically normalized scales, when non-uniform metrics are sought, so the output time series are comparable.  (The png legends would naturally have to be adjusted similarly.)

One could also make the argument that pmwebd/graphite should, like prometheus does, routinely rescale all metrics to base-unit scales (seconds/bytes/counts).  That would solve the above problem, and also eliminate guesswork in interpreting dimensionless, legendless charts.

**Comment by natoscott** [comment]
pmwebd is retired since pcp v5, all new web efforts are focussed on Grafana.
