### ISSUE TITLE
pmcd should allow more time for pmdas to start

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#387]
There seems to be no mechanism for a (Python) PMDA to inform PMCD how long its startup is expected to take, PMCD seems to restart a newly installed PMDA after a ~5 second wait which most often is more than enough but in certain special cases (like the PMDA needing to wait for hardware, compile internal modules, wait for a 3rd party component to activate) five seconds may not be enough and in that case it seems that there are little options left (hardware is what it is and a module compiler or a proprietary 3rd party application are more or less immutable in this regard as well).

It would be helpful if PMDAs could tell PMCD an expected startup time to prevent timeout issues during startup.

**Comment by myllynen** [comment]
I should mention that there are two related issues relatively close around this but I think neither of them covers this particular aspect:

https://github.com/performancecopilot/pcp/issues/152
https://github.com/performancecopilot/pcp/issues/165

Please feel free to close this if this in fact is a dupe of either of those. Thanks.

**Comment by lberk** [comment]
Is the -t option, or the pmcd.control.timeout (accessed by pmstore), not sufficient in this case?

       -t timeout
              To prevent misbehaving clients or agents from hanging  the  entire  Performance  Metrics
              Collection  System  (PMCS),  pmcd uses timeouts on PDU exchanges with clients and agents
              running as processes.  By default the timeout interval is five seconds.  The  -t  option
              allows  an alternative timeout interval in seconds to be specified.  If timeout is zero,
              timeouts are turned off.  It is almost impossible to use the debugger  interactively  on
              an agent unless timeouts have been turned off for its "parent" pmcd.

              Once  pmcd  is  running,  the  timeout may be dynamically modified by storing an integer
              value (the timeout in seconds) into the metric pmcd.control.timeout via pmstore(1).

**Comment by fche** [comment]
It may be sufficient for Marko's purposes to do the same thing as the new pmdaprometheus does.  It handles the initial pmcd<->pmda handshaking process quickly.  (It does not help later timeouts associated with fetches.)

    class PrometheusPMDA(PMDA):
        def __init__(self,pmda_name,domain,config):
                ''' Initialize the PMDA '''
                # urgent: say hi the invoking pmcd, redirect stderr etc.
                PMDA.__init__(self,pmda_name,domain)
                self.connect_pmcd()
                # now everything else may take time
                self.pmda_name = pmda_name
                [...]

**Comment by goodwinos** [comment]
There is the PM_ERR_PMDANOTREADY / PM_ERR_PMDAREADY mechanism for this that PMDA can use to respond to requests when it is not yet ready. See examples of this in the sample, docker and rpm PMDAs.

**Comment by myllynen** [comment]
Thanks Mark, I was connecting to PMCD early already so that didn't help, changing PMCD default timeout seems to help but is probably not the optimal generic solution. The examples were all in C, we need to check are all the needed methods available in Python what is what I have in this case:

https://github.com/myllynen/pcp-bcc-pmda

Thanks.

**Comment by goodwinos** [comment]
@myllynen PM_ERR_PMDANOTREADY / PM_ERR_PMDAREADY isn't just for initial connection. A PMDA can respond with an PM_ERR_PMDANOTREADY err response to any incoming request .. and later issue an PM_ERR_PMDAREADY error - this is for slow startup, and also slow refresh scenarios; usually (but not always) involving a PMDA that has an asynchronous refresh thread, with the main thread servicing requests from pmcd and a separate refresh thread, or an all-in-one thread that has an augmented select() handler in the PMDA main loop.

**Comment by myllynen** [comment]
Thanks @goodwinos, I think that's all what's needed here after all, what was a bit confusing was that the thread doing the preparation work wasn't progressing anywhere when it entered lower level library parts but needed to yield (sleep) in the PMDA side before replying PM_ERR_PMDANOTREADY while still initializing, that allows the thread to actually do its work and get the PMDA ready.

Closing.

**Comment by myllynen** [comment]
Just for a reference, Nathan mentioned the check_delay parameter for Install scripts which looks like to be the most feasible option after all, see PMDA(3) for details.
