### ISSUE TITLE
RFE: Per-PMDA SELinux rules

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#388]
Currently pcp-selinux is a monolithic package that configures SELinux rules in a global on/off fashion. This means for example that access to libvirt is enabled regardless whether the libvirt PMDA is in use or not. It might be desirable to make this less monolithic so that rules are configured only when needed, perhaps setup by the Install script of the PMDA (where applicable).

**Comment by natoscott** [comment]
No plans to implement this at this stage - if anyone does someday, please feel free to provide patches though.
