### ISSUE TITLE
pmmgr should offer status metrics / webapi

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#389]
When pmmgr drives a busy container, it can be important for external tools to see how it's doing.  For example, whether any of its subordinate daemons are failing, how many there are, what target hostids are live, how much time log rotation operations have been taking, etc. etc.

It would be nice if these quantities were exposed to pcp itself, so that these pmmgr stats could be archived and graphed.  Also, it would be nice if these reports were accessible over TCP/HTTP, so that ordinary kubernetes liveness/health checking code can poll it for gross deadlock / responsivity detection.  Having pmmgr export a prometheus-flavoured http endpoint could satisfy both needs.  (pmdaprometheus would be configured to listen to it & pass the data on).

**Comment by goodwinos** [comment]
Frank, would we want a prometheus http end-point in a PCP tool? Or maybe a pmmgr PMDA? The latter would be the more traditional PCP way of exporting new metrics, especially for the wider use case where pmdaprometheus may not be deployed. Just a thought ..

**Comment by fche** [comment]
> Or maybe a pmmgr PMDA? The latter would be the more traditional PCP way 

Yeah.  Thing is that this wouldn't really help with the kubernetes-native health checking aspect of the problem.  There, HTTP/TCP are the native language of k8s.

> especially for the wider use case where pmdaprometheus may not be deployed

Who knows, if we start deploying more pmdaprometheus-based micropmdas, that wider use case may change.

**Comment by goodwinos** [comment]
just a note: we also discussed pmdaprometheus metrics for monitoring http get latency and frequency, per-source/URL. THis is also related to #391

**Comment by natoscott** [comment]
No further work is planned here.
