### ISSUE TITLE
pmdaprometheus: input throttling

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#391]
It may be desirable to hook up pmdaprometheus to potentially hostile data sources.  While we already protect against molasses-speed-traffic, someone could try to flood the pcp infrastructure with data and thereby use more than a designated portion of shared storage resources.

While some degree of throttling could be done downstream at the pmlogger stage (related https://github.com/performancecopilot/pcp/issues/372), it would probably work better upstream.  We can have pmdaprometheus impose some gross limits on the incoming traffic.  A (per-source-URL?) maximum of total

- number of metrics*instances
- http document size

could provide the needed protection.

**Comment by goodwinos** [comment]
agree, good idea. urls.d/source.throttle as an adjunct to source.url

**Comment by fche** [comment]
While the exec: trick in #392 #384 could possibly solve this too, there is some value in keeping some such processing within the pmda, because it can maintain persistent http[s] connections.  That saves cpu/net setup costs.

**Comment by goodwinos** [comment]
pmdaprometheus metrics for monitoring per-source http get latency and frequency :

prometheus.SOURCE.time (time counter) and prometheus.SOURCE.calls (counter)
(so we can derive min, max and avg latency)

**Comment by fche** [comment]
> prometheus.SOURCE.time (time counter) and prometheus.SOURCE.calls (counter)

FWIW I'd rather view them as indoms on two metrics   `prometheus.fetch_time[SOURCE]`  `prometheus.fetch_count[SOURCE]` rather than mix into the namespace of the SOURCEs themselves.

**Comment by goodwinos** [comment]
ok, makes sense then

**Comment by goodwinos** [comment]
Have implemented the fetch statistics, see the following my master branch :
(QA for this is still coming).

commit 02de1375beafa42ab9bf2b96c60e6146aa01b3c7
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Tue Feb 6 21:52:18 2018 +1100

    pmdaprometheus: add prometheus.pmda_stats.{calls,fetch_time,parse_time}
    
    GH #391
    
    This adds three counter metrics, each with one instance per end-point
    source as the instance domain. From this we can derive per-endpoint
    statistics such as total fetch calls (and fetch rate), fetch latency
    (when converted to a rate) and prometheus document parse times (also
    as rate). And other stats such as min, max, avg, etc. over some time
    period.
    
    Useful in diagnosing stalled, slow or hung end-point services e.g. using
    pmie alerting rules. It also helps with QA since "pminfo prometheus" no
    longer returns an error after ./Install with an empty configuration
    directory.
    
    Here's the metadata :
    
    prometheus.pmda_stats.parse_time PMID: 144.0.3 [per-end-point source parse time counter, excluding fetch time]
        Data Type: 64-bit unsigned int  InDom: 144.0 0x24000000
        Semantics: counter  Units: millisec
    
    prometheus.pmda_stats.fetch_time PMID: 144.0.2 [per-end-point source fetch time counter, excluding parse time]
        Data Type: 64-bit unsigned int  InDom: 144.0 0x24000000
        Semantics: counter  Units: millisec
    
    prometheus.pmda_stats.calls PMID: 144.0.1 [per-end-point source call counter]
        Data Type: 64-bit unsigned int  InDom: 144.0 0x24000000
        Semantics: counter  Units: count

**Comment by goodwinos** [comment]
per-source fetch and latency counters are implemented below prometheus.control in the PMNS. These metrics can be logged, and if necessary used by a scripted configs to impose throttling limits. These metrics are also useful for isolating failing or slow end-points; the timestamps of these events can be used in a log message analysis, etc.

**Comment by fche** [comment]
> if necessary used by a scripted configs to impose throttling limits

We can certainly hope that scripted one-shot fetch programs will provide sufficient performance, but in the interest of efficiency (http connection, see also #444), this function may need to sit in the native http client.  (For reference, an https connection setup latency of several hundred milliseconds is typical.)

**Comment by goodwinos** [comment]
FWIW, I still think pycurl (libcurl thin wrapper) should be used as a drop-in replacement for the requests module. The libcurl folks claim it is several times faster (not sure if that's latency or b/w or both) .. and it can make stateful connections (of course), and supports every conceivable security option you could ever want. Perhaps we could drop it in and re-run that benchmark?

**Comment by fche** [comment]
Which benchmark?  The hundreds-of-milliseconds per https connection were confirmed from a normal web browser's connection timing stats, and represent probably better numbers than the python requests client can do.  The point though is that for a pmdaprometheus script (one-shot executable), that latency has to be paid anew for each fetch, because connections cannot persist.
