### ISSUE TITLE
pmdaprometheus:input filtering

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#392]
Related to #391, it would be very useful to have a sed-style filter, per-source/URL. Many sites will have applications exporting end-point metrics that can't easily be changed (production environments). If such end-points have incorrect metadata or conflicting metric names, or whatever, we'd need a way to filter the incoming http text data stream to change an arbitrary regex to something else, sed-style.

This could live in the urls.d directory alongside the source.url, e.g. source.filter (where .filter only applies to the matching source.url). This would also be along-side urls.d/source.throttle (#391)

**Comment by fche** [comment]
Perhaps this part could be done by the end-user without new pmda code, using exec: https://github.com/performancecopilot/pcp/issues/384 URLs of the form `exec:curl FOO | sed BAR`.

**Comment by goodwinos** [comment]
exec:curl FOO | sed -e '/somethingidontwant/d'
would be handy :)

**Comment by goodwinos** [comment]
Resolved by #384. Scripted configs can apply whatever stream filters they want. The PMDA only sees what ends up on the script's stdout
