### ISSUE TITLE
pmmgr: better management of damaged archives

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#393]
There are a few cases where pmmgr's current pmlogcheck / corrupt-* renaming logic doesn't kick in.  This lets detritus from old failures build up and stick around.

- 0-length archive-* .index/.meta/.0 files
- corrupt old files that pmmgr tries to run `pmlogreduce` on, but fails
- 0-length reduce-* *output* files (created during ENOSPC), which prevent subsequent `pmlogreduce` runs (due to pre-existing output file)

**Comment by natoscott** [comment]
No further work is planned here.
