### ISSUE TITLE
pmdbg -l does not list values anymore

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#397]
Earlier pmdbg -l listed options, values, and meanings but since recent debug flag changes it lists only options and meanings although --help says:

  -l, --list            display values and text for all PCP debug options

Listing values was helpful at least for shell completions, perhaps they could be listed again in the future.

**Comment by kmcdonell** [comment]
@myllynen the use of "values" should be discouraged ... as we exhausted the number of bits in the pmDebug bitfield there are now some (and will be more in the future) pmDebugOptions that have no equivalent bitfield value.

pmdbg is correct ... the first field in the output from -l is the value, which is a word not a number.  Any shell completion stuff should be using this and building -D pdu,fetch (etc).

If, despite this advice, you really want the subset of the values that have bitfield equivalents, use pmdbg -l -o.

I don't think there is an issue here, so I'm closing this one.
