### ISSUE TITLE
qa/661 pmjson should not be piped into sort

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#407]
The whole point of using a canonicalizing json formatter in the pmwebd qa tests (https://github.com/performancecopilot/pcp/pull/400) was so that the .out file can have intelliglble json content to compare against, instead of a sorted/mangled one.  qa/661 etc. should ditch the 
 
    | sed -e 's/, *$//' \
    | LC_COLLATE=POSIX sort

parts throughout.

**Comment by goodwinos** [comment]
Perhaps we can nuke the sorting (if the output order is deterministic, x-platform), or just use $tmp.full for qualified output checking -

..... | tee -a $tmp.full \
|  sed -e 's/, *$//' \
| LC_COLLATE=POSIX sort
