### ISSUE TITLE
pmcollectl referencing pm before its instantiated

### ISSUE THREAD

**Issue by burn8** [performancecopilot/pcp#41]
When using the -R option 'pm' gets called before instantiation.

$ ./pmcollectl -R 1s -s m -v
Traceback (most recent call last):
  File "./pmcollectl", line 621, in <module>
    (timeval, errmsg) = pm.pmParseInterval(str(opts.duration_arg))
NameError: name 'pm' is not defined

**Comment by natoscott** [comment]
@burn8 this is fixed in the master branch now - thanks for the report.
