### ISSUE TITLE
pmdapostgresql: tolerate non-root invocation

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#415]
If pmdapostgres is invoked as a non-root user, i.e., already unprivileged, it will fail in its $pmda->set_user(...) unnecessarily.  It (and other pcp servers) should not try to setuid when invoked as non-root.  Patch attached.
[patch.txt](https://github.com/performancecopilot/pcp/files/1628456/patch.txt)

**Comment by fche** [comment]
> if the pmda is invoked as non-root and thus pmda->set_user("postgresql") fails, we probably want the PMDA to report the error and abort, as it currently does.

The purpose of my report was to point out that this is not the case, if pcp & pmdapostgresql are running within unprivileged tenants, with non-zero uid.  This is a "fact of life" kind of configuration, and many of our daemons do live with it: they don't even try to setuid() if geteuid() != 0.

**Comment by goodwinos** [comment]
hmm. well OK, but it should at least warn that it did not (could not) change uid/gid. I'll add that warning and then it seems OK to me then

**Comment by goodwinos** [comment]
merged upstream

**Comment by natoscott** [comment]
@goodwinos hmmm, what about all the other PMDAs that call set_user?
(I agree with the warning fwiw, but this problem is wider than just postgresql)
