### ISSUE TITLE
libpcp start time handling bug

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#418]
For reference / tracking purposes from the earlier list discussion at https://groups.io/g/pcp/message/17670:

$ pmdumplog -z -S "@00:00:28" pcp.git/qa/archives/value-test
Note: timezone set to local timezone of host "localhost" from archive

00:00:28.000  60.12.0 (kernel.uname.release): value
"some:åäöšŠžŽ€🙃§½¼¾:unicode"

00:00:28.000  60.12.0 (kernel.uname.release): value
"some:åäöšŠžŽ€🙃§½¼¾:unicode"

00:00:29.000  60.26.0 (kernel.all.uptime): value 7654321
              29.0.15 (sample.float.one): value 7654321
              60.12.0 (kernel.uname.release): value "3.2.1"

Notice the value at the time printed twice (this happens with this archive with other tools as well with -S).

Thanks.

**Comment by kmcdonell** [comment]
Turns out to be a corner-case related to non-interpolation mode starting in  the middle of an archive with a particular temporal index set up.  So not a wide-spread problem.

Commit c7b201a fixes it and adds qa/613 to exercise the issue and a bunch of related odd cases.
