### ISSUE TITLE
libpcp-opened file descriptors should be O_CLOEXEC

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#419]
A multithreaded program that deals with pcp archives and/or sockets, and forks child processes, may unintentionally pass open file descriptors to the children.  These somewhat harmless (in that the child process will leave them alone, if not buggy), except that they'd hold references to files/sockets that can't be completely released for perhaps an extended period.  It would be better not to pass them in the first place.

One possible cure would be to tweak the child process forking step in all programs that exec, so as to manually close all file descriptors between the fork() and exec() ... except that there aren't really good & simple & portable ways of doing that.

Another possible cure would be for libpcp to call fcntl(FD_CLOEXEC) on its file descriptors.  For files on modern linux, glibc's fopen(3) offers an "e" character to do the same fcntl under the covers.

**Comment by fche** [comment]
pmmgr patch that works around problem
[patch.txt](https://github.com/performancecopilot/pcp/files/1637431/patch.txt)

**Comment by natoscott** [comment]
No further work is planned here.
