### ISSUE TITLE
FYI: abidiff reports for libpcp.so.3 between 3.12.2 and git master

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#420]
On F27, installing pcp-libs, pcp-libs-debuginfo, libabigail, and build your own copy of pcp from git master.
Then `abidiff` indicates some ABI incompatibilities within the shared library:

    abidiff  /usr/lib64/libpcp.so.3 new_build/libpcp.so.3
    Functions changes summary: 46 Removed, 2 Changed (47 filtered out), 55 Added functions
    Variables changes summary: 0 Removed, 1 Changed, 0 Added variable
    [...]
    2 functions with some indirect sub-type change:
    [C]'function __pmContext* __pmCurrentContext()' at context.c:1869:1 has some indirect sub-type changes: [...]
    [C]'function int __pmGetArchiveEnd(__pmLogCtl*, timeval*)' at logutil.c:2676:1 has some indirect sub-type changes: [...]
    [C]'pmdebugoptions_t pmDebugOptions' was changed at pmapi.h:1119:1:
    size of symbol (in bytes) changed from 124 to 136 [...]

So ABI compatibility is pretty amazing, considering the amount of kenj's rework; just these three items are still found by `abidiff`.  They may not be worth fixing.  If we do, one possibility would be to add stub functions & a prior-type variable, tagged the old symbol-version alias, so hypothetical older binaries at least won't corrupt memory if they use these in a new shlib.

`abidiff` would be a good tool to consider dropping into the libpcp.so build sequence, alongside `check-statics`, as an ABI regression tester.

**Comment by natoscott** [comment]
No further work is planned here.
