### ISSUE TITLE
Root squash and permission denied for pmlogger

### ISSUE THREAD

**Issue by tsaiweiwu** [performancecopilot/pcp#423]
Our system has root squash on the compute nodes, so the root does not have the privileges as it should have. Whenever I "systemctl start pmcd pmlogger," pmlogger failed to write to /home/pcp and it gives me permission denied error.

It looks like even pmlogger is run as pcp user,  the root will try to go into the folder /home/pcp, which it does not have the permission due to root squash, and clean some files first. How can I buy pass this step? 
![systemctl--root](https://user-images.githubusercontent.com/10214345/35286185-4c233ed6-002d-11e8-8da6-83626fe72687.PNG)

**Comment by fche** [comment]
FWIW, if you use `service pmmgr` to drive your pmlogger instead of `service pmlogger`, it should not encounter such problems, because it doesn't do anything as `root` (nor via `cron`).

**Comment by natoscott** [comment]
These days pmlogger_check.log and the NOTICES live below PCP_LOG_DIR, which can be changed but must be writable - no coding changes planned here, this is a configuration issue I believe.
Please re-open if problems persist?  Thanks.

**Comment by darkggtech** [comment]
Just found this ticket is similar to my situation, please let me leave my case here.

I tried to relocate the log location by edit `/etc/pcp/pmlogger/control.d/local` to `/root/log`, applied `chmod -R 777` to this path.

when `service pmlogger restart`, pmlogger cannot be started due to some write permission issue.

`cat  /var/log/pcp/pmlogger/pmlogger_check.log`
> pmlogger_check [/etc/pcp/pmlogger/control.d/local:26]
> Warning: no write access in /root/log/centos-docker, skip lock file processing
> drwxrwxrwx. 2 pcp pcp 8192 Mar  2 23:25 /root/log/centos-docker
> rm: cannot remove 'Latest': Permission denied

**Comment by natoscott** [comment]
@darkggtech hmm, that's unexpected - can you paste 'ls -ld /root /root/log' from after the failure here please?  Is selinux enabled?  (if so, please also check the selinux access log in case thats what is preventing these operations).  Thanks.

**Comment by darkggtech** [comment]
@natoscott fyi

`ls -ld /root /root/log`

> drwxrwxrwx. 6 root root 221 Mar  2 23:43 /root
> drwxrwxrwx. 3 root root 152 Mar  3 12:11 /root/log

Is selinux enabled?
Yes.

you pointed out the issue, SELinux blocked the whole operation,
attached capture for your reference.
![image](https://user-images.githubusercontent.com/61701946/75742827-d8d42900-5d49-11ea-9f93-4079a164ad2d.png)

SELinux is preventing /usr/bin/bash from write access on the directory /root/log/centos-docker.
Allow this access for now by executing:
```
ausearch -c 'pmlogger_check' --raw | audit2allow -M my-pmloggercheck
semodule -i my-pmloggercheck.pp
```

SELinux is preventing /usr/bin/pmlogger from write access on the file /root/log/centos-docker/pmlogger.log.
Allow this access for now by executing:
```
ausearch -c 'pmlogger' --raw | audit2allow -M my-pmlogger
semodule -i my-pmlogger.pp
```

SELinux is preventing /usr/libexec/pcp/bin/pmlock from add_name access on the directory lock.
Allow this access for now by executing:
```
ausearch -c 'pmlock' --raw | audit2allow -M my-pmlock
semodule -i my-pmlock.pp
```

SELinux is preventing /usr/libexec/pcp/bin/pmlock from create access on the file lock.
Allow this access for now by executing:
```
ausearch -c 'pmlock' --raw | audit2allow -M my-pmlock
semodule -i my-pmlock.pp
```

SELinux is preventing /usr/bin/rm from remove_name access on the directory lock.
Allow this access for now by executing:
```
ausearch -c 'rm' --raw | audit2allow -M my-rm
semodule -i my-rm.pp
```

SELinux is preventing /usr/bin/chown from setattr access on the file /root/log/centos-docker/Latest.
Allow this access for now by executing:
```
ausearch -c 'chown' --raw | audit2allow -M my-chown
semodule -i my-chown.pp
```

SELinux is preventing /usr/bin/rm from unlink access on the file lock.
Allow this access for now by executing:
```
ausearch -c 'rm' --raw | audit2allow -M my-rm
semodule -i my-rm.pp
```

SELinux is preventing /usr/bin/mv from rename access on the file pmlogger.log.
Allow this access for now by executing:
```
ausearch -c 'mv' --raw | audit2allow -M my-mv
semodule -i my-mv.pp
```

SELinux is preventing /usr/bin/mv from rename access on the file /root/log/centos-docker/pmlogger.log.
Allow this access for now by executing:
```
ausearch -c 'mv' --raw | audit2allow -M my-mv
semodule -i my-mv.pp

```

**Comment by darkggtech** [comment]
after applied mentioned commands,
pmlogger can be start.
`systemctl status pmlogger`
> ● pmlogger.service - Performance Metrics Archive Logger
>    Loaded: loaded (/usr/lib/systemd/system/pmlogger.service; enabled; vendor preset: disabled)
>    Active: active (running) since Tue 2020-03-03 12:21:48 HKT; 27min ago
>      Docs: man:pmlogger(1)
>   Process: 21777 ExecStop=/usr/share/pcp/lib/pmlogger stop (code=exited, status=0/SUCCESS)
>   Process: 6587 ExecStart=/usr/share/pcp/lib/pmlogger start (code=exited, status=0/SUCCESS)
>  Main PID: 12030 (pmlogger)
>     Tasks: 1
>    Memory: 3.3M
>    CGroup: /system.slice/pmlogger.service
>            └─12030 /usr/libexec/pcp/bin/pmlogger -P -r -T 60mins -c config.default -U root -m pmlogger_check 20200303.12.21
> 
> Mar 03 12:21:39 centos-docker systemd[1]: Starting Performance Metrics Archive Logger...
> Mar 03 12:21:39 centos-docker pmlogger[6587]: Starting pmlogger ...
> Mar 03 12:21:39 centos-docker systemd[1]: Can't open PID file /run/pcp/pmlogger.pid (yet?) after start: No such file or directory
> Mar 03 12:21:48 centos-docker systemd[1]: pmlogger.service: Supervising process 12030 which is not our child. We'll most likely not notice when it exits.
> Mar 03 12:21:48 centos-docker systemd[1]: Started Performance Metrics Archive Logger.

**Comment by darkggtech** [comment]
just found `ausearch` will not work when I change the log path again, any permanent way to let service passthrough SElinux instead of turn off SELinux? thanks
