### ISSUE TITLE
pmdapostgresql: handle broken database connection

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#435]
If a database server dies after pmdapostgresql was connected to it. pmdapostgresql goes dead.  It does not try to recover by reconnecting or exiting, even if the database server comes back up.  The PMDA's logs simply collect an endless stream of:

    DBD::Pg::st execute failed: no connection to the server at /var/lib/pcp/pmdas/postgresql/pmdapostgresql.pl line 398. 

It should periodically $dbh->ping(), and attempt some kind of recovery.

**Comment by goodwinos** [comment]
postgresql_connection_setup function is called on every fetch, but will only attempt to connect if $dbh is not defined. A simple patch checks if $dbh is defined but $dbh->ping fails, and so a reconnection is attempted with a suitable message sent to the log. This seems to work fine and will be tested with new test qa/1362

**Comment by goodwinos** [comment]
completed and merged to master, including qa/1362
