### ISSUE TITLE
PCP Licensing Scheme Problem?

### ISSUE THREAD

**Issue by edfsl** [performancecopilot/pcp#44]
According to the FAQ at http://www.pcp.io/faq.html#Q1b all of the libraries in PCP should be licensed under “Version 2.1 of the GNU Lesser General Public License”. However upon a close examination of the source code we have discovered that the library sources contains some  code that is tagged as GPL.

Our analysis shows that the PCP libraries are clean for LGPL licensing up until (and including) version 3.5.8-1, at which time it appears that code from other components with a GPL license was brought into the library but the license was not changed. They remained as GPL.

We were wondering if you were aware of this issue and wanted to know if there was a way to clean this up. Would you be willing to change the licensing of the newer GPL code in library to LGPL to resolve the issue and maintain the intent of licensing the libraries under LGPL?

(If there is a better forum/contact to discuss this, please let me know. All emails to pcp@oss.sgi.com are bouncing)

**Comment by fche** [comment]
Please be specific.

**Comment by edfsl** [comment]
Here are some examples of the licensing 'issues' we see. 

include/pcp
pmapi.h: * under the terms of the GNU General Public License as published by the
pmda.h: * under the terms of the GNU General Public License as published by the


libpcp/src
avahi.c: * under the terms of the GNU General Public License as published by the
avahi.h: * under the terms of the GNU General Public License as published by the
getdate.y: * it under the terms of the GNU General Public License as published by
probe.h: * under the terms of the GNU General Public License as published by the
secureserver.c: * under the terms of the GNU General Public License as published by the

libpcp_pmda/src
dynamic.c: * under the terms of the GNU General Public License as published by the
queues.c: * under the terms of the GNU General Public License as published by the
queues.h: * under the terms of the GNU General Public License as published by the

**Comment by natoscott** [comment]
@edfsl thanks for letting us know.

Most of those are cases of cut&paste from other sources in PCP at time of authoring, and we will simply fix the license annotation for the next release (either myself, brolley, or kenj being the authors of all but one there).

The one that needs closer inspection is getdate.y in libpcp, I'll dig into that some more & we'll either fix that up or remove that functionality if it cannot be legitimately included in libpcp.

Let us know if there were any other issues.  Thanks again!

**Comment by edfsl** [comment]
@natoscott - you are very welcome! 

We may have other issues that we can report. The engineer in my team that ran the scan in the sources is out of the office until next week. As soon as he returns, I will verify the list and share the results.

A small question - is this the best forum to discuss pcp and future work? All emails I sent to   pcp@oss.sgi.com bounced. We have done some work with pcp in an embedded environment for our devices and I am wondering if there is an interest in that work.

**Comment by natoscott** [comment]
Here is fine - all posts here are CC'd to the list.  The list is a subscriber-only list, so you'd need to subscribe if you want to post directly there (you should have got notification about that when attempting to post there).

There is bound to be interest in your embedded work, so please go ahead and share information about that too.

**Comment by natoscott** [comment]
@edfsl all issues listed here have been resolved now in the pcp master branch, and will release in pcp-3.10.7 soon.  If you or your colleague do find others, please let me know (preferably within the next week, so we can fix 'em up before the next release) - thanks!

Also, I realised my earlier comment regarding your mail to the list was not correct.  If your mail bounced, then the oss.sgi.com server / mail service must have been unreachable, it would not have been related to being subscribed to the list or not.

What actually happens in the case of an unsubscribed address posting is the mail gets forwarded to one of several list administrators, who allow legitimate emails through - such as this recent one:
http://pcp.io/pipermail/pcp/2015-August/008179.html

I'm one of those administrators, and I can confirm that no mail arrived on this topic ... could you resend it perhaps, or fwd me the bounce message and let's see if we can diagnose further?  Thanks.

**Comment by edfsl** [comment]
Nathan,

Thanks for the update. I am asking my team tonight to see if they can give me an update regarding any additional licensing items and if we find anything we will submit ASAP.

I am also attaching one of the bounce messages I received when I originally tried to contact you all. I got similar bounces when I tried to email from a personal email address as well. Let me know if I did something wrong.

Thanks for all of the help.

Ed

**Comment by edfsl** [comment]
Hello Nathan,

One of our engineers has completed a manual scan on the updated sources looking for potential license ‘disconnects” This is what he has reported:


1)      All sources from “src/libpcp_pmcd” are GPLv2+

2)      Most sources from “src/libpcp_qed” are GPLv2+



3)      libpcp_qmc  library has two source files as GPL: “src/libpcp_qmc/src/qmc_time.cpp” and  “src/libpcp_qmc/src/qmc_time.h”

I don’t know whether this is the licensing that you intended for these modules or not.

Please let me know if you have any questions. If you decide that the issues above need to be fixed, then let me know if you want me to open a new issue to track it.

Thanks,

Ed

**Comment by natoscott** [comment]
Hi Ed,

2 and 3 should both be LGPL, but 1 is correct as-is (libpcp_pmcd is not an exported library with any kind of API, its just used to share some code between pmcd, pmdapmcd and soon pmdaroot).

Don't worry about opening a new issue, I'll commit those other updates with a reference to this issue.
