### ISSUE TITLE
pmTraversePMNS() return codes are inconsistent with documentation

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#441]
pmTraversePMNS(3) says it returns the number of children in the PMNS of the name argument, but it is not consistently doing this. If the name argument is a leaf node in the PMNS, it should return 0 but actually always returns 1, unless the name is a derived metric.  In addition, if the name is a non-leaf node that has any derived metrics in it's PMNS subtree, then pmTraversePMNS() seems to always returns 0. 

I've opened this issue for discussion because either the documentation is wrong, or the libpcp function is wrong, or both .. and yet there may be existing client code that relies on these return values. I suspect we should fix the libpcp code to be consistent with the documentation and release that with pcp-4.0.

simple test program:
```
#include <stdlib.h>
#include <pcp/pmapi.h>

void
dometric(const char *name)
{
    printf("    %s\n", name);
}

int
main(int argc, char *argv[])
{
    if (pmNewContext(PM_CONTEXT_HOST, "local:") >= 0) {
	printf("%s :\n", argv[1]);
    	printf("-> %d\n", pmTraversePMNS(argv[1], dometric));
    }
}
```

Here are some examples :
``
### ./trav sample.hordes
sample.hordes :
    sample.hordes.one
    sample.hordes.two
-> 2
### ./trav sample.hordes.one
sample.hordes.one :
    sample.hordes.one
-> 1

### ./trav nosuchmetric
nosuchmetric :
-> -12357

### ./trav disk.dev.read
disk.dev.read :
    disk.dev.read
-> 1

### ./trav disk.dev.await
disk.dev.await :
    disk.dev.await
-> 0

### ./trav disk.dev
disk.dev :
    disk.dev.read
    disk.dev.write
    disk.dev.total
    disk.dev.blkread
    disk.dev.blkwrite
    disk.dev.blktotal
    disk.dev.read_bytes
    disk.dev.write_bytes
    disk.dev.total_bytes
    disk.dev.read_merge
    disk.dev.write_merge
    disk.dev.avactive
    disk.dev.read_rawactive
    disk.dev.write_rawactive
    disk.dev.total_rawactive
    disk.dev.aveq
    disk.dev.scheduler
    disk.dev.await
    disk.dev.r_await
    disk.dev.w_await
    disk.dev.avg_qlen
    disk.dev.avg_rqsz
    disk.dev.r_avg_rqsz
    disk.dev.w_avg_rqsz
    disk.dev.util
-> 0

**Comment by kmcdonell** [comment]
Mark ... I'll bet this is a case of the man page was written and then the code was written without reference to the man page.
We all know who to blame, so I'll take a look.

**Comment by goodwinos** [comment]
Ken, I'm happy to work on it, just wanted some discussion on which is correct, man page or the code!

**Comment by kmcdonell** [comment]
OK. As to discussion, the man page looks sensible (and hence correct) to me.
If I had to guess, I'd postulate that the code was close to correct before the addition of derived metrics, and totally broken thereafter.

**Comment by goodwinos** [comment]
Any thoughts Ken? - for pmlogger use, we're only interested in the 0 result, i.e. if 'name' is a leaf node or not.  The man page says "On success pmTraversePMNS returns the number of children of name, which may be zero.", so that would be immediate children, right? Or would it be the number of leaf nodes traversed in the entire subtree rooted at the given name?

**Comment by natoscott** [comment]
@goodwinos I don't think it can be entire subtree - that would involve recursive names PDUs being required, just to calculate the return code.  I think the intention is more likely to mean "the number of times the do_metric[_r] callback was called"... i.e. immediate children.

**Comment by goodwinos** [comment]
The callback is invoked for each leaf node found in a depth first recursive traversal. i.e. the number of leaf nodes in the entire subtree, not the number of immediate children. TraversePMNS_local() is recursive for local and archive requests. For remote, it calls __pmSendTraversePMNSReq(), which does this 

```
        if ((sts = __pmDecodeTraversePMNSReq(pb, &name)) >= 0) {
            if (HAVE_V_FOUR(dispatch->comm.pmda_interface)) {
                sts = dispatch->version.four.children(name, 1, &offspring, &statuslist, pmda);
                ....

That ultimately calls pmdaTreeChildren(), which is recursive (depending on the parameters).
```

**Comment by natoscott** [comment]
@goodwinos ah, right - I was thinking of pmGetChildren(3).

**Comment by kmcdonell** [comment]
I think it should be the total number of leaf nodes found (the traversal happens either locally or at pmcd, there is no pdu-round-trips for the recursive descent).

So if something really bad happens, I'd expect the result to be < 0.
If the argument is a leaf node in the PMNS, I'd expect the result to be 1.
If the argument is a non-leaf of an empty subtree, I'd expect the result to be 0.
If the argument is a non-leaf of a non-empty subtree, I'd expect the result to be number of leaf nodes found (>= 1).

**Comment by goodwinos** [comment]
HI Ken, thanks for the reply - I have reached the same conclusion, with the additional test case for derived metrics being treated the same as first class leaf nodes. i.e. if the argument is a derived metric, result is 1. And if the argument is a non-leaf, the result is the number of leaf-nodes visited in the traversal, which may include derived metrics.

This makes the most sense for the PMAPI - the return code is consistent with the intent of the function. It does however mean that we still can't tell the difference between a non-leaf with one leaf child, and a leaf (or derived metric). e.g. kernel.all.cpu.wait and  kernel.all.cpu.wait.total both return 1. In this case, kernel.all.cpu.wait is potentially a dynamic root node that has one leaf child. So be it, we just have to call pmLookupName on those names to distinguish the leaves from the non-leaves (the pmlogger code already does this).

I have a patch ready, but will also updates the docs, remake 633 and add a new test to exercise all the combinations.

**Comment by goodwinos** [comment]
This task is completed and merged to master, including docs, QA tests 1177 and 633.
