### ISSUE TITLE
use uniform archive index recording rate

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#442]
pmlogger and pmlogextract hard-code a 100K "flushsize" amount to trigger emission of a 20-byte record into the archive temporal index.  This number forms a rough limit on the read costs (of unrelated data) of time-series extraction from the resulting archives.

pmlogreduce and libpcp_import don't do this; they just record some indom changes and/or overall start/stop times.  It would be good if these archive generation tools also used the same algorithm, so they too could be indexed into efficiently.

**Comment by kmcdonell** [comment]
As of commit 65ef4e1d2 this is done for pmlogreduce.

**Comment by kmcdonell** [comment]
As of commit 18ddef818 this is done for libpcp_import ... so this issue is done with.
