### ISSUE TITLE
RFE: More complete NFS server metrics

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#447]
`sar -n NFSD 1` provides the following metrics:

```
scall/s badcall/s  packet/s     udp/s     tcp/s     hit/s    miss/s   sread/s  swrite/s saccess/s sgetatt/s
```

It seems that the latter four ("Number of RPC calls received per second") are not available with PCP (like the corresponding metrics are available for the client courtesy of the nfsclient PMDA).

See also https://groups.io/g/pcp/message/18123. Thanks.

**Comment by natoscott** [comment]
@myllynen I think those numbers may be ...

sread = (nfs4.server.calls[read] + nfs3.server.calls[read] + nfs.server.calls[read])
swrite = (nfs4.server.calls[write] + nfs3.server.calls[write] + nfs.server.calls[write])
saccess = (nfs4.server.calls[access] + nfs3.server.calls[access])
sgetatt = (nfs4.server.calls[getattr] + nfs3.server.calls[getattr] + nfs.server.calls[getattr])

**Comment by myllynen** [comment]
@natoscott You mean nfs.server.reqs, thanks for pointing them out.

However, I can't see a way to use them with derived metrics - a quick overview of existing derived metrics QA cases doesn't show any references to such use so I'm not sure is this something that has been implemented?

```
root@localhost:~# pmval -s 2 'nfs4.server.reqs[read]'

metric:    nfs4.server.reqs
host:      localhost.localdomain
semantics: cumulative counter (converting to rate)
units:     count (converting to count / sec)
samples:   2
interval:  1.00 sec

    read    
     0.0    
     0.0    
root@localhost:~# grep z d.conf                      
z = (nfs.server.reqs[read] + nfs3.server.reqs[read] + nfs4.server.reqs[read])
root@localhost:~# PCP_DERIVED_CONFIG=./d.conf pmval -s 2 z
[./d.conf:3] Error: pmRegisterDerived(z, ...) syntax error
 (nfs.server.reqs[read] + nfs3.server.reqs[read] + nfs4.server.reqs[read])
                 ^                                                        
Illegal character
pmval: pmLookupName(z): Unknown metric name
root@localhost:~# 
```

If we can use individual instances for derived metrics, then we might be able to drop usage of nfsclient PMDA from the recently added NFS client side metricset in pmrep.conf as well. Thanks.

**Comment by kmcdonell** [comment]
On 23/02/18 19:28, Marko Myllynen wrote:
> ...
> If we can use individual instances for derived metrics, then we might be 
> able to drop usage of nfsclient PMDA from the recently added NFS client 
> side metricset in pmrep.conf as well. Thanks.

Paul Smith asked for this in Mar 2012 ... the fact that I've not 
implemented it in almost 6 years should give you a hint ... this would 
be _really_ hard to do.  Sorry.

**Comment by myllynen** [comment]
This is not a show-stopper now that we decided to provide only NFSv4 NFS/NFSD metricsets by default in pmrep.conf. So what's left here is to conclude whether additional server side metrics still exists that are not already covered and are those worth adding. (I don't have an answer to that ATM.) Thanks.

**Comment by natoscott** [comment]
@myllynen when I audited the kernel code the other day, I didn't come across any we are missing at the moment ... but there's always the chance there's some lurking in new proc/sysfs files somewhere.

**Comment by myllynen** [comment]
Ok, thanks, sounds like it's safe to close this one then.
