### ISSUE TITLE
security and authentication for pmwebd

### ISSUE THREAD

**Issue by martin2176** [performancecopilot/pcp#449]
It is very difficult to use pmweb is any moderate security environment without having a secure (SSL) or a user authentication mechanism in place or both.
The request is for
a) a user authentication mechanism for pmweb 
b)a https access

**Comment by martin2176** [comment]
attached is a diagram of the configuration I have in mind.
the security I was referring to is "between pmcd and pmwebd".
Reading through pmcd, it appears pmcd can support SASL authentication and SSL encryption.
Does pmweb support SASL and SSL encryption for the conversation which happens between pmwebd <--> pmcd
![auth2](https://user-images.githubusercontent.com/14482998/36795137-3589c762-1c70-11e8-9a17-c1a6ad4f0662.jpg)

**Comment by fche** [comment]
pmwebd is a normal pmapi client, so can indeed speak pcp's own flavour of ssl to the remote pmcds.  Use the "pcps://HOSTNAME" type hostspec url to force ssl protection.  It can carry userids/passwords.  (pmwebd is not able to let a web client participate in an interactive authentication steps that are possible with command line tools via SASL, so userids/passwords would need to be passed explicitly.)

**Comment by martin2176** [comment]
That is good to know that pmwebd can work with pcp's sasl and ssl even though its not interactive.
I would think the hostspec in this case would be something like this?
pcps://10.206.25.20:44321?user=username&pass=password

**Comment by martin2176** [comment]
here is the problem I am running into.
I have ssl enabled on pcp and I am able to query the collector from a remote host (the same host which is running pmwebd) using pminfo . 
If I try to access pmwebd using hostspec pcps://rhelrepo.sys.woslab.com , it doesnt work and logs the below error in pmwebd log.

"[Thu Mar  1 00:36:57] pmwebd(6872): [10.130.124.3:55152] new context failed: No cipher suites are present and enabled in this program.
"
Looks like pmwebd doesnt know about the location of certs. Is there a configuration parameter 

# pminfo -fmdt -h pcps://rhelrepo.sys.woslab.com kernel.all.load  //this works fine//
kernel.all.load PMID: 60.2.0 [1, 5 and 15 minute load average]
    Data Type: float  InDom: 60.2 0xf000002

**Comment by fche** [comment]
Nothing in pminfo or pmwebd is aware of cipher / certificate issues.  Those are all handled down by common code down at the libpcp level.  If the pminfo ran from exactly the same host as the pmwebd, then an strace or pcp debug-trace-enabled run may help diagnose the cause.

**Comment by martin2176** [comment]
When I run pminfo for the first time (as root), it asks to accept certificate and it store it under /root/.pki/nssdb and from that point on pminfo knows the cert store 
What I dont quite understand is, how does pmwebd know about what cert to use and where to locate it?



[root@RHEL74G10 nssdb]# pminfo -fmdt -h pcps://xx.sys.xx.com kernel.all.load
WARNING: issuer of certificate received from host xx.sys.xx.com is not trusted.
SHA1 fingerprint is E5:49:87:34:00:C1:CA:B9:F8:22:B3:6A:87:12:91:99:3D:4D:A3:1C
Do you want to accept and save this certificate locally anyway (y/n)?

**Comment by fche** [comment]
Ah, that message does help inform the situation.  The certificate in question is the remote pmcd server's certificate, not a client-side one.  Since there is no CA web-of-trust type facility in effect, pcp users are interactively asked to confirm that the remote server is "who it says it is".  Then this accepted certificate is used in the future to confirm that there is no woman-in-the-middle attack in progress.

So ... this policy is clearly not that helpful for a noninteractive server process such as pmwebd (since there's no one sitting at the pmwebd console).  Nor is it useful if it has no writeable space where it can store its list of approved certificates (which you worked around with pminfo by running it as root).  

Maybe libpcp should have a policy of automatically accepting remote certificates, when pcps:// is used from a console-less server ... or maybe just whenever !isatty(FILENO_STDIN).  Maybe the local accepted-certificate database needs to default to a location where the pcp user can read/write it, which won't be /etc.

**Comment by martin2176** [comment]
So in short, does it mean:
even though  pmwebd can use pcps for security, there is no practical way to use it because it doesnt know where to get the cert from or nor the libpcp has a policy to automatically accept the certificate.

**Comment by fche** [comment]
> because it doesn't know where to get the cert from

It always gets the certificate from the remote pmcd, and would compare it to a locally saved copy, in order to skip the verification prompt.

Otherwise yeah, looks that way.

**Comment by martin2176** [comment]
would this be an enhancement request ?

**Comment by fche** [comment]
I believe so, against libpcp rather than pmwebd.

**Comment by martin2176** [comment]
could you file this as a bug against libpcp?

Or would that be something I have to

**Comment by fche** [comment]
IMHO the easiest thing would be to relabel this issue as something like "libpcp support for unattended, low-privilege pcp daemons making pcps:// connections".

**Comment by minnus** [comment]
Its been a while but I think I worked around this with pmproxy by setting the following environment variables:

PCP_SECURE_DB_PATH
PCP_ALLOW_SERVER_SELF_CERT

Documentation at "man 1 pcpintro"

Set the path where you want the cert to be stored, and then auto accept them.  I suppose the alternative would be to prepopulate that location and not just blindly accept the cert but in our case this approach satisfied our needs.

I'm not sure if the same approach would work with pmwebd

**Comment by fche** [comment]
@minnus, ok, so it looks like the needed libpcp functionality is probably there.  We just need those env vars set usably in the systemd/sysvinit configurations for all the various daemons / cron-jobs.

**Comment by minnus** [comment]
Yeah in my case it was a single purpose system so I just put them in pcp.conf.  But there is probably a smarter way to do it in general.

**Comment by martin2176** [comment]
I think I have some success getting the certificate to work.
I need more testing, but so far looks good. 
In pcp.conf added these :  -C sql:/etc/pcp/nssdb -M pmserver_cert -Q
on the pmwebd, from shell 
#export PCP_SECURE_DB_PATH=/etc/pcp/nssdb
#export PCP_ALLOW_SERVER_SELF_CERT=1
Then I started pmwebd from shell #/usr/libexec/pcp/bin/pmwebd -l pmwebd.log -R /usr/share/pcp/webapps -A /var/log/pcp   -v 

Now from vector I am able to use "HOSTSPEC pcps://<IP of pmcd collector>:44321" without any connection error.
I should be able to supply these environment variables as part of systemd init script or /etc/pcp/pmwebd/pmwebd.options

Thanks a lot for suggesting those 2 ENV variables .

**Comment by natoscott** [comment]
pmwebd is retired, its replacement supports TLS and authentication.
