### ISSUE TITLE
pmdaprometheus: label filtering

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#453]
When attached fetching from the `/federate/` endpoint of a prometheus server, metrics are quite ... verbose.  We may not need many of them preserved from a pcp point of view, so it would be nice not to litter the indom/pmns/ui with them.  For example:

    container_cpu_usage_rate{ 
    beta_kubernetes_io_arch="amd64"
    beta_kubernetes_io_instance_type="m4.2xlarge"
    beta_kubernetes_io_os="linux"
    container_name="content-repository"
    failure_domain_beta_kubernetes_io_region="some-cluster"
    failure_domain_beta_kubernetes_io_zone="some-clustera"
    hostname="starter-some-cluster-node-compute-e2e3a"
    id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb39d3528_2200_11e8_a099_02d7377a4b17.slice/docker-8563b28b292ec169a32b01380f1c2672ba4be5419ffbfa1ec7b64b4bee605527.scope"
    image="docker.io/fabric8/caddy-server@sha256:8f8982dc8810f1e75e0c3467e323cb589dccef64f6181221b9e4eb9bc127c288"
    image_inspector_enabled="True"
    instance="ip-ip-ad-dr-es.some-cluster.compute.internal"
    job="kubernetes-cadvisor"
    kubernetes_io_hostname="ip-ip-ad-dr-es.some-cluster.compute.internal"
    logging_infra_fluentd="true"
    name="k8s_content-repository_content-repository-5-5sdgf_nobody-jenkins_b39d3528-2200-11e8-a099-02d7377a4b17_0"
    namespace="nobody-jenkins"
    ops_node="new"
    pod_name="content-repository-5-5sdgf"
    region="some-cluster"
    type="compute"} 5.007815833333318e-05 1520464808577

(originally one line) ... may have only the following keys of interest: `namespace`, `pod`.  The pmda should have facilities inspired by [prometheus relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Crelabel_config%3E) except that we could probably get by with just 'include' and/or 'exclude' key-list operators.

I imagine this could be configured on a per-`.url` config-file basis, extending the idea for authentication in issue #444 by adding more config lines.  Note that in order for this facility to apply to 'scripted' pmdaprometheus sources, it would be nice if their configuration was unified with the `.url` ones, as #384 suggested.

**Comment by goodwinos** [comment]
will be implementing this to filter labels (with similar include/exclude regex matching semantics as the metric filtering). Label filtering is definitely needed because PCP instance names currently use all the labels, which is way too many for e.g. federated end-point URLs - we just want to pick out the important ones. It's up to the user/config to select a unique set of label/value, though we might be able to come up with an algorithm to determine the minimal labelset to guarantee unique instance names (apart from the instance number prefix that is always added to PCP instance names).

Will NOT be implementing whole metric filtering based on label regex match. No pressing need for that.

**Comment by goodwinos** [comment]
include/exclude label filtering committed upstream, plus QA and doc updates.
CAVEAT: label filtering can change the instance naming, and introduce duplicates. Best done when the config URL is first introduced and not changed thereafter.
optional label filtering is not yet done .. have a draft patch but wanted to get include/exclude out first.

**Comment by goodwinos** [comment]
Support for metric and label filtering feature has been completed, see description in pmdaopenmetrics(1).
