### ISSUE TITLE
PCP for PostgreSQL 10.2 

### ISSUE THREAD

**Issue by abdulkave** [performancecopilot/pcp#456]
Please help with PCP for PostgreSQL 10.2 
we find some tables columns are difference as below 
# pg_stat_replication table
                     
old column 9.6
----------------
sent_location  
 write_location 
 flush_location 
 replay_location

replace with new column 10.2
------------------------------
sent_lsn  
write_lsn 
flush_lsn 
replay_lsn

new column added 10.2
-----------------------------
write_lag 
 flush_lag 
 replay_lag

# pg_stat_activity table

new column added 10.2
backend_type

The below function also changes.
pg_active  ====>  pg_current_xlog_location() instead of this --> pg_current_wal_lsn();  in 10.2
pg_recovery  ====>  
pg_last_xlog_receive_location()   -->  pg_last_wal_receive_lsn();
pg_last_xlog_replay_location() -->  pg_last_wal_replay_lsn();

**Comment by goodwinos** [comment]
Hi @abdulkave,

we've just finished updating the PCP postgresql PMDA to support postgresql 9.6, which will be released with pcp-4.0.1 in a few weeks. I've noticed 10.2 is now available, but hasn't yet hit the fedora updates-testing repos for F27. I was waiting for that before embarking on the 10.2 update for the PMDA. But since you are requesting this, we can move the work forward. Give me some time to download and install 10.2 on my test systems .. and I'll get back to you here.

In the mean-time, if you want to push ahead - there are some audit tools in the directory src/pmdas/postgresql/audit_tools in the upstream PCP source master branch (git clone https://github.com/performancecopilot/pcp.git).

If you already have 10.2 installed, then can you run the script named postgresql_audit_tables.sh and send the output here or to me via email? The diff between that output and the file named postgres_pg_stat_tables.9.6.7 in the same directory should show us what has changed between 9.6 and 10.2 and hence guide the required updates to the PMDA.

Best regards
-- Mark

**Comment by abdulkave** [comment]
Thanks Mark for quick response.
Please find the postgresql_audit_tables.sh scripts out put below.
I did not find ant changes apart from one column adding  019 **pg_stat_activity** # backend_type
Will waiting for your update.

#version psql   (PostgreSQL) 10.2
#table pg_stat_all_tables
000 pg_stat_all_tables relid
001 pg_stat_all_tables schemaname
002 pg_stat_all_tables relname
003 pg_stat_all_tables seq_scan
004 pg_stat_all_tables seq_tup_read
005 pg_stat_all_tables idx_scan
006 pg_stat_all_tables idx_tup_fetch
007 pg_stat_all_tables n_tup_ins
008 pg_stat_all_tables n_tup_upd
009 pg_stat_all_tables n_tup_del
010 pg_stat_all_tables n_tup_hot_upd
011 pg_stat_all_tables n_live_tup
012 pg_stat_all_tables n_dead_tup
013 pg_stat_all_tables   n_mod_since_analyze
014 pg_stat_all_tables last_vacuum
015 pg_stat_all_tables last_autovacuum
016 pg_stat_all_tables last_analyze
017 pg_stat_all_tables last_autoanalyze
018 pg_stat_all_tables vacuum_count
019 pg_stat_all_tables autovacuum_count
020 pg_stat_all_tables analyze_count
021 pg_stat_all_tables autoanalyze_count
#table pg_stat_activity
000 pg_stat_activity datid
001 pg_stat_activity datname
002 pg_stat_activity pid
003 pg_stat_activity usesysid
004 pg_stat_activity usename
005 pg_stat_activity application_name
006 pg_stat_activity client_addr
007 pg_stat_activity client_hostname
008 pg_stat_activity client_port
009 pg_stat_activity backend_start
010 pg_stat_activity xact_start
011 pg_stat_activity query_start
012 pg_stat_activity state_change
013 pg_stat_activity wait_event_type
014 pg_stat_activity wait_event
015 pg_stat_activity state
016 pg_stat_activity backend_xid
017 pg_stat_activity backend_xmin
018 pg_stat_activity query
019 pg_stat_activity backend_type
#table pg_stat_bgwriter
000 pg_stat_bgwriter checkpoints_timed
001 pg_stat_bgwriter checkpoints_req
002 pg_stat_bgwriter   checkpoint_write_time
003 pg_stat_bgwriter checkpoint_sync_time
004 pg_stat_bgwriter buffers_checkpoint
005 pg_stat_bgwriter buffers_clean
006 pg_stat_bgwriter maxwritten_clean
007 pg_stat_bgwriter buffers_backend
008 pg_stat_bgwriter   buffers_backend_fsync
009 pg_stat_bgwriter buffers_alloc
010 pg_stat_bgwriter stats_reset
#table pg_stat_database
000 pg_stat_database datid
001 pg_stat_database datname
002 pg_stat_database numbackends
003 pg_stat_database xact_commit
004 pg_stat_database xact_rollback
005 pg_stat_database blks_read
006 pg_stat_database blks_hit
007 pg_stat_database tup_returned
008 pg_stat_database tup_fetched
009 pg_stat_database tup_inserted
010 pg_stat_database tup_updated
011 pg_stat_database tup_deleted
012 pg_stat_database conflicts
013 pg_stat_database temp_files
014 pg_stat_database temp_bytes
015 pg_stat_database deadlocks
016 pg_stat_database blk_read_time
017 pg_stat_database blk_write_time
018 pg_stat_database stats_reset
#table pg_stat_all_tables
000 pg_stat_all_tables relid
001 pg_stat_all_tables schemaname
002 pg_stat_all_tables relname
003 pg_stat_all_tables seq_scan
004 pg_stat_all_tables seq_tup_read
005 pg_stat_all_tables idx_scan
006 pg_stat_all_tables idx_tup_fetch
007 pg_stat_all_tables n_tup_ins
008 pg_stat_all_tables n_tup_upd
009 pg_stat_all_tables n_tup_del
010 pg_stat_all_tables n_tup_hot_upd
011 pg_stat_all_tables n_live_tup
012 pg_stat_all_tables n_dead_tup
013 pg_stat_all_tables   n_mod_since_analyze
014 pg_stat_all_tables last_vacuum
015 pg_stat_all_tables last_autovacuum
016 pg_stat_all_tables last_analyze
017 pg_stat_all_tables last_autoanalyze
018 pg_stat_all_tables vacuum_count
019 pg_stat_all_tables autovacuum_count
020 pg_stat_all_tables analyze_count
021 pg_stat_all_tables autoanalyze_count
#table pg_stat_sys_tables
000 pg_stat_sys_tables relid
001 pg_stat_sys_tables schemaname
002 pg_stat_sys_tables relname
003 pg_stat_sys_tables seq_scan
004 pg_stat_sys_tables seq_tup_read
005 pg_stat_sys_tables idx_scan
006 pg_stat_sys_tables idx_tup_fetch
007 pg_stat_sys_tables n_tup_ins
008 pg_stat_sys_tables n_tup_upd
009 pg_stat_sys_tables n_tup_del
010 pg_stat_sys_tables n_tup_hot_upd
011 pg_stat_sys_tables n_live_tup
012 pg_stat_sys_tables n_dead_tup
013 pg_stat_sys_tables   n_mod_since_analyze
014 pg_stat_sys_tables last_vacuum
015 pg_stat_sys_tables last_autovacuum
016 pg_stat_sys_tables last_analyze
017 pg_stat_sys_tables last_autoanalyze
018 pg_stat_sys_tables vacuum_count
019 pg_stat_sys_tables autovacuum_count
020 pg_stat_sys_tables analyze_count
021 pg_stat_sys_tables autoanalyze_count
#table pg_stat_all_indexes
000 pg_stat_all_indexes relid
001 pg_stat_all_indexes indexrelid
002 pg_stat_all_indexes schemaname
003 pg_stat_all_indexes relname
004 pg_stat_all_indexes indexrelname
005 pg_stat_all_indexes idx_scan
006 pg_stat_all_indexes idx_tup_read
007 pg_stat_all_indexes idx_tup_fetch
#table pg_stat_sys_indexes
000 pg_stat_sys_indexes relid
001 pg_stat_sys_indexes indexrelid
002 pg_stat_sys_indexes schemaname
003 pg_stat_sys_indexes relname
004 pg_stat_sys_indexes indexrelname
005 pg_stat_sys_indexes idx_scan
006 pg_stat_sys_indexes idx_tup_read
007 pg_stat_sys_indexes idx_tup_fetch

Warm Regards
Abdul

**Comment by goodwinos** [comment]
Hi Abdul,

I've downloaded and installed latest postgresql 10.3 from Fedora rawhide (e.g. from this mirror http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/fedora/linux/development/rawhide/Everything/x86_64/os/). This is on my Fedora/F27 test system.

Running the audit script, I get the same output as you (which is good, since you're on 10.2 and I'm on 10.3). Diffing that output with the 9.6.7 audit listing shows one new field 'pg_stat_activity backend_type' has been added to the pg_stat_activity table in column 19 (20th column since the first column is zero).

```
[mgoodwin@f27 audit_tools]$ diff postgres_pg_stat_tables.9.6.7 postgres_pg_stat_tables.10.3.1
1c1
< #version psql (PostgreSQL) 9.6.7
---
> #version psql (PostgreSQL) 10.3
44a45
> 019 pg_stat_activity backend_type 

```

Also note there are a couple of tables missing in the audit script, e.g. pg_stat_replication. Rerunning the script shows the pg_stat_replication.{sent,write,flush,replay}_location columns have been renamed ("location" changed to "lsn"). So I'll need to fix those up too - not quite sure how to do that and still remain compatible with 9.x, but I'll figure something out - will probably need some version dependent code for those columns.

Regards
-- Mark

**Comment by goodwinos** [comment]
After adding the missing tables to the audit script, here's the diff between 9.6.7 and 10.3.
```
$ diff -u postgres_pg_stat_tables.9.6.7 postgres_pg_stat_tables.10.3.1
--- postgres_pg_stat_tables.9.6.7	2018-03-19 15:22:14.037543217 +1100
+++ postgres_pg_stat_tables.10.3.1	2018-03-19 15:15:44.563565453 +1100
@@ -1,4 +1,4 @@
-#version psql (PostgreSQL) 9.6.7
+#version psql (PostgreSQL) 10.3
 #table pg_stat_activity
 000 pg_stat_activity datid
 001 pg_stat_activity datname
@@ -19,6 +19,7 @@
 016 pg_stat_activity backend_xid
 017 pg_stat_activity backend_xmin
 018 pg_stat_activity query
+019 pg_stat_activity backend_type
 #table pg_stat_bgwriter
 000 pg_stat_bgwriter checkpoints_timed
 001 pg_stat_bgwriter checkpoints_req
@@ -70,12 +71,15 @@
 007 pg_stat_replication backend_start
 008 pg_stat_replication backend_xmin
 009 pg_stat_replication state
-010 pg_stat_replication sent_location
-011 pg_stat_replication write_location
-012 pg_stat_replication flush_location
-013 pg_stat_replication replay_location
-014 pg_stat_replication sync_priority
-015 pg_stat_replication sync_state
+010 pg_stat_replication sent_lsn
+011 pg_stat_replication write_lsn
+012 pg_stat_replication flush_lsn
+013 pg_stat_replication replay_lsn
+014 pg_stat_replication write_lag
+015 pg_stat_replication flush_lag
+016 pg_stat_replication replay_lag
+017 pg_stat_replication sync_priority
+018 pg_stat_replication sync_state
 #table pg_stat_all_tables
 000 pg_stat_all_tables relid
 001 pg_stat_all_tables schemaname
```

**Comment by goodwinos** [comment]
Rather than continue struggling with the perl PMDA and it's version dependent column remapping mechanism, which seems to be getting a bit out of hand, I think it would be better to rewrite the PMDA in python, using pgdb — The DB-API Compliant Interface of the PyGreSQL package, see http://www.pygresql.org/contents/pgdb/index.html
A python version of the PMDA would query the column headers of the various pg_stat* tables on startup and dynamically create the metrics (with persistent PMIDs and instance names) based on what column names are present. The PyGreSQL package has been around since 1995 (almost as long as PCP!!) and is in Fedora, and probably all other major distros.

Alternatively, we could ingest the perf data using the prometheus [postgres_exporter](https://github.com/wrouesnel/postgres_exporter) via the PCP prometheus PMDA.

**Comment by abdulkave** [comment]
Hello Mark,

it would be grate if it's in python.

**Comment by goodwinos** [comment]
Hi Abdul, yes I agree, a python re-implementation would be good. I should be able to get to this some time next week.

Best regards
-- Mark

**Comment by abdulkave** [comment]
Hi Mark, it's great to hear from you. Thanks a lot.

**Comment by abdulkave** [comment]
Hello Mark how are you. Any update?

**Comment by goodwinos** [comment]
Hi Abdul,
the python re-implementation of the postgresql PMDA supporting v10.2 is currently scheduled for pcp-4.1.1 in early August - see the PCP roadmap at https://pcp.io/roadmap for details

Regards
-- Mark

**Comment by abdulkave** [comment]
Hi Mark,

Thank You for information.When last time i seen roadmap it's shown 16 JUN now it's shown Aug but now i get clear picture of it.
Once again Thank You very much.

**Comment by abdulkave** [comment]
Hi Mark,
Thank You for python implementation PMDA for postgresql.
pmdapostgresql.conf have below parameters.

1.  host=localhost
2. dbname=postgres
3. user=postgres
4. password=password

can we have port number also i am unable to connect db on different port apart from default 5432 port.

Regards,
Abdul K

**Comment by goodwinos** [comment]
Hi Abdul, you are correct: we need a port configuration (hostname:port does not work). I'll add this. You should be able to connect on UNIX domain socket locally, but it also requires a port number (which is used for the UNIX domain socket filename). The default port 5432 works for both tcp and unix domain, but any other port does not work.

Regards
-- Mark

**Comment by abdulkave** [comment]
Thank You Mark.
will wait for the update.
Just for your information.
after installation pmda-postgresql the below logs.

`# ./Install
postgres user defined in /var/lib/pcp/pmdas/postgresql/pmdapostgresql.conf is "postgres"
group id for user "postgres" is "26"
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Switching to user 'postgres'
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Connecting to db 'ebiz_prod' as user 'postgres'
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Successfully connected to db 'ebiz_prod' as user 'postgres'
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Connected to postgres server VERSION 10.2
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Setting up indoms
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Setting up metrics
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: setup_table_column_mappings: setting up table/column mapping dicts
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: WARNING: table pg_active not available: relation "pg_active" does not exist
LINE 1: SELECT * from pg_active;
                      ^

[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: WARNING: table pg_recovery not available: relation "pg_recovery" does not exist
LINE 1: SELECT * from pg_recovery;
                      ^

[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.stat.replication.flush_location', table 'pg_stat_replication', column 'flush_location' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.stat.replication.replay_location', table 'pg_stat_replication', column 'replay_location' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.active.is_in_recovery', table 'pg_active', column 'is_in_recovery' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.active.xlog_current_location_log_id', table 'pg_active', column 'xlog_current_location_log_id' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.recovery.is_in_recovery', table 'pg_recovery', column 'is_in_recovery' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.active.xlog_current_location_offset', table 'pg_active', column 'xlog_current_location_offset' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.recovery.xlog_receive_location_log_id', table 'pg_recovery', column 'xlog_receive_location_log_id' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.recovery.xlog_receive_location_offset', table 'pg_recovery', column 'xlog_receive_location_offset' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.recovery.xlog_replay_location_log_id', table 'pg_recovery', column 'xlog_replay_location_log_id' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.recovery.xlog_replay_location_offset', table 'pg_recovery', column 'xlog_replay_location_offset' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.stat.replication.sent_location', table 'pg_stat_replication', column 'sent_location' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: Warning: metric 'postgresql.stat.replication.write_location', table 'pg_stat_replication', column 'write_location' has no mapping
[Mon Oct  8 17:57:07] pmdapostgresql(144075) Info: completed __init__
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Switching to user 'postgres'
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Connecting to db 'ebiz_prod' as user 'postgres'
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Successfully connected to db 'ebiz_prod' as user 'postgres'
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Connected to postgres server VERSION 10.2
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Setting up indoms
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Setting up metrics
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: setup_table_column_mappings: setting up table/column mapping dicts
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: WARNING: table pg_active not available: relation "pg_active" does not exist
LINE 1: SELECT * from pg_active;
                      ^

[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: WARNING: table pg_recovery not available: relation "pg_recovery" does not exist
LINE 1: SELECT * from pg_recovery;
                      ^

[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.stat.replication.flush_location', table 'pg_stat_replication', column 'flush_location' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.stat.replication.replay_location', table 'pg_stat_replication', column 'replay_location' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.active.is_in_recovery', table 'pg_active', column 'is_in_recovery' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.active.xlog_current_location_log_id', table 'pg_active', column 'xlog_current_location_log_id' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.recovery.is_in_recovery', table 'pg_recovery', column 'is_in_recovery' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.active.xlog_current_location_offset', table 'pg_active', column 'xlog_current_location_offset' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.recovery.xlog_receive_location_log_id', table 'pg_recovery', column 'xlog_receive_location_log_id' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.recovery.xlog_receive_location_offset', table 'pg_recovery', column 'xlog_receive_location_offset' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.recovery.xlog_replay_location_log_id', table 'pg_recovery', column 'xlog_replay_location_log_id' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.recovery.xlog_replay_location_offset', table 'pg_recovery', column 'xlog_replay_location_offset' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.stat.replication.sent_location', table 'pg_stat_replication', column 'sent_location' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: Warning: metric 'postgresql.stat.replication.write_location', table 'pg_stat_replication', column 'write_location' has no mapping
[Mon Oct  8 17:57:08] pmdapostgresql(144083) Info: completed __init__
Updating the Performance Metrics Name Space (PMNS) ...
Terminate PMDA if already installed ...
Updating the PMCD control file, and notifying PMCD ...
Check postgresql metrics have appeared ... 208 warnings, 208 metrics and 0 values
`
Regards,
Abdul

**Comment by goodwinos** [comment]
Hi Abdul, those warnings are expected on 10.2 e.g. pg_stat_replication table not available unless enabled on the server config). In any case, I've toned down the warnings, added 'port' config option, updated man page and QA tests. This is all in PCP master branch now at https://github.com/performancecopilot/pcp.git

Also note: there was an SELinux CVE denial causing UNIX domain socket connections from the PMDA to the postgreSQL server to fail - this is now fixed in latest pcp-selinux package (in master branch). That may be why you're getting 0 values. You can either update pcp-selinux or "setenforce permissive" to test.

Regards
-- Mark

**Comment by abdulkave** [comment]
Thank You Mark.
In my host SELinux is disabled.
After adding port config option.
./Install
postgres user defined in /var/lib/pcp/pmdas/postgresql/pmdapostgresql.conf is "postgres"
group id for user "postgres" is "26"
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Switching to user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Connecting to host 'local', port '2090', db 'ebiz_prod' as user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Successfully connected to db 'ebiz_prod' as user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Connected to postgres server VERSION 10.2
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Setting up indoms
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: Setting up metrics
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: setup_table_column_mappings: setting up table/column mapping dicts
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: table pg_active not available for this version of postgreSQL
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: table pg_recovery not available for this version of postgreSQL
[Tue Oct  9 13:10:14] pmdapostgresql(108185) Info: completed __init__
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Switching to user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Connecting to host 'local', port '2090', db 'ebiz_prod' as user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Successfully connected to db 'ebiz_prod' as user 'postgres'
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Connected to postgres server VERSION 10.2
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Setting up indoms
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: Setting up metrics
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: setup_table_column_mappings: setting up table/column mapping dicts
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: table pg_active not available for this version of postgreSQL
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: table pg_recovery not available for this version of postgreSQL
[Tue Oct  9 13:10:14] pmdapostgresql(108201) Info: completed __init__
Updating the Performance Metrics Name Space (PMNS) ...
Terminate PMDA if already installed ...
Updating the PMCD control file, and notifying PMCD ...
Check postgresql metrics have appeared ... 208 warnings, 208 metrics and 0 values

Regards,
Abdul

**Comment by goodwinos** [comment]
Hi Abdul, that sure looks like it's connected correctly. Can you send me /var/log/pcp/pmcd/postgresql.log and also the output of pminfo -fmd postgresql

That's all too voluminous to post here. Please compress and email to mgoodwin@redhat.com  

Thanks

**Comment by goodwinos** [comment]
resolved with the python re-write then went into pcp-4.1.3
