### ISSUE TITLE
RFE: dmthin pmie example

### ISSUE THREAD

**Issue by moriwaka** [performancecopilot/pcp#46]
dmthin pools' monitoring by pmie would be normal story. 
I hope dmthin monitoring pmie example.

I wrote following pmie script, but I'm not familiar to pmie manner, yet.
Please review and include into examples if it is applicable.

```
delta = 10 min;
threshold_data = 90;
threshold_metadata = 80;

some_host (
  some_inst (
    100 * dmthin.pool.data.used / dmthin.pool.data.total > $threshold_data
  ) 
) -> print "dmthin pool data %v%used [%i]@%h";

some_host (
  some_inst (
    100 * dmthin.pool.metadata.used / dmthin.pool.metadata.total > $threshold_metadata
  ) 
) -> print "dmthin pool metadata %v%used [%i]@%h";
```

**Comment by natoscott** [comment]
Nice!  Have a look at src/pmdas/cisco and src/pmdas/shping in the PCP tree and the parameterised pmie rules that are installed with those PMDAs.  We could do the same thing with your rules above, in src/pmdas/dm - could you send through a patch / pull request?

**Comment by moriwaka** [comment]
Yes, I'll try this weekend.

**Comment by natoscott** [comment]
@moriwaka thanks, that's merged now.
