### ISSUE TITLE
pmdagluster: pmda enablement via pmstore'd control metrics considered harmful

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#462]
pmdagluster is dead in the water until someone sends it a pmstore on a control metric to wake it up.  There is no infrastructure in pcp to automate setting such control metrics.  Thus, this is a manual process, making the code appear broken, unable to be routinely pmlogger'd.

pmdas should not rely on manual pmstore operations to turn on or off.  They should respond to the traffic of pmapi clients doing normal enumeration/fetches to do so.  This has been demonstrated as a simple & successful approach with pmdapapi: it consumes resources iff there are pmapi clients actively talking to it.  It's time to bring such advanced technology to the other pmdas.

**Comment by natoscott** [comment]
No further work is currently planned on this area.
