### ISSUE TITLE
[bcc pmda] new tools

### ISSUE THREAD

**Issue by spiermar** [performancecopilot/pcp#465]
Users could benefit from more BCC tools being available in the PMDA. Corresponding Vector widgets will be created and development is being tracked under https://github.com/Netflix/vector/issues/186

- [ ] ext4dist/xfsdist/zfsdist - as input for a latency heat map
- [ ] biosnoop - as input (end time, latency, type: R or W) for a scatter plot: completion time vs latency, and coloring reads red and writes blue
- [ ] biosnoop - as input (end time, device, offset) for an offset heat map: showing per-device access patterns
- [ ] execsnoop - as input for a table of process details
- [ ] tcpretrans - as input for a table of retransmit details
- [ ] tcptop - as input for a live table or line chart of per-process TCP throughput
- [ ] runqlat - as input for a latency heat map

**Comment by spiermar** [comment]
@brendangregg

**Comment by myllynen** [comment]
Thanks to Andreas, these are now part of PCP 4.1.1 so this can be closed (I'm missing rights to do so).
