### ISSUE TITLE
pmdapostgresql: use u64 for counters

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#469]
The postgresql stats data comes in the form of bigints (64-bit integers).  Operation / tuple counts can easily exceed 2**31 over a busy database, and we should preserve the underlying quantity to avoid overflows or conversion errors through the pgsql-perl-pcp pipe.

**Comment by goodwinos** [comment]
conversion to u64 counters will be done as part of the python re-write (see pcp.io/roadmap), including pmlogrewrite rules to convert existing archives. Targeting pcp-4.0.2

**Comment by goodwinos** [comment]
IIRC, native counter units (32 or 64 bit) were reviewed and preserved in the python re-write that went into pcp-4.1.3
