### ISSUE TITLE
Issue with cgroup.* metrics after setting pmcd.client.container

### ISSUE THREAD

**Issue by spiermar** [performancecopilot/pcp#476]
Having trouble retrieving some metrics after setting `pmcd.client.container`.

For example, this order of requests.

1. `http://XXX.XXX.XXX.XXX/pmapi/1161938372/_fetch?names=containers.name`

```json
{
    "timestamp": {
        "s": 1522695119,
        "us": 311720
    },
    "values": [
        {
            "pmid": 4194305,
            "name": "containers.name",
            "instances": [{
                "instance": 0,
                "value": "Container-0"
            }, {
                "instance": 1,
                "value": "Container-1"
            }, {
                "instance": 2,
                "value": "Container-2"
            }]
        }
    ]
}

2. `http://XXX.XXX.XXX.XXX/pmapi/1161938372/_fetch?names=cgroup.cpuacct.usage`

```json
{
    "timestamp": {
        "s": 1522695123,
        "us": 812708
    },
    "values": [
        {
            "pmid": 12624898,
            "name": "cgroup.cpuacct.usage",
            "instances": [{
                "instance": 0,
                "value": 9500193052102874
            }, {
                "instance": 1,
                "value": 9142166131910412
            }, {
                "instance": 2,
                "value": 2176504439
            }, {
                "instance": 3,
                "value": 1362026392
            }, {
                "instance": 4,
                "value": 6711187572955585
            }, {
                "instance": 5,
                "value": 17260047088064
            }, {
                "instance": 6,
                "value": 127507328763205
            ...
            }]
        }
    ]
}
```

3. `http://XXX.XXX.XXX.XXX/pmapi/1161938372/_store?name=pmcd.client.container&value=Container-2`

```json
{"success":1 }
```

4. `http://XXX.XXX.XXX.XXX/pmapi/1161938372/_fetch?names=kernel.all.cpu.sys,cgroup.cpuacct.usage`

```json
{
    "timestamp": {
        "s": 1522695135,
        "us": 202333
    },
    "values": [
        {
            "pmid": 251658262,
            "name": "kernel.all.cpu.sys",
            "instances": [{
                "instance": -1,
                "value": 563953150
            }]
        }
    ]
}
```

Before issuing the `_store`, `pmcd.client.container` request, PCP was returning values for `cgroup.cpuacct.usage`, but nothing after. This used to work if I'm not mistaken, but maybe the `value` passed to the `_store` request changed and it's not the name from `containers.name` anymore.

**Comment by natoscott** [comment]
@spiermar can you check the internal container lookup for "Container-2" for me?  What does this say:

$ pminfo --fetch --container=Container-2 cgroup.cpuacct.usage

thanks.

**Comment by spiermar** [comment]
```
~ $ pminfo --fetch containers.name

containers.name
    inst [2 or "0bf17ac8d70a6469c4b1915eeb21eb205447700e9c19f7451a18c260b0ee8e18"] value "Container-1"
    inst [9 or "9836044ee858934c63fb0432aeece039f1a2da8771b5515556a77cfbe74a6c3a"] value "Container-2"

~ $ pminfo --fetch --container=Container-2 cgroup.cpuacct.usage

cgroup.cpuacct.usage
No value(s) available!
```

**Comment by natoscott** [comment]
Interesting, so that's why pmwebd doesn't see it (pminfo doesn't either) - what does this command say re Container-2?

$ pminfo --fetch containers.state.running

cheers.

**Comment by spiermar** [comment]
```
~ $ pminfo --fetch containers.state.running

containers.state.running
    inst [0 or "879e0119ca0e1410bc64971495e57739040fe1dc38975d36ffa24c7b72cdc60d"] value 1
    inst [1 or "612fcbdbdee62f0f023897593ceced57fb09efa31c393c032d929ca9e4977013"] value 1
    inst [2 or "ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"] value 1
    inst [3 or "639d6f60b3231d04c39189abbeb22f2f8a1e6b06cf384b6d15e77cd536532e1b"] value 1
    inst [4 or "4a6fcd82e33685614f4773b1d80b170f06311a7e7fd52b3d77079776aaba4f35"] value 1
    inst [5 or "3123810294e3b9ea8e8b0eae114e273d3861d51ce4d12e81e4a4bc4b88ac7176"] value 1
    inst [6 or "850b80dbdd86551e1dd5b3065620db79b47130e433d83c4337777c4396b5f770"] value 1
    inst [7 or "6d00804cf4a4f855ede08ac81f061e0f843ee35908096133a799bcfc2ce0543c"] value 1
    inst [8 or "7a65ea85ea6324411477d4ceb99b76693c1077176045371a06883c95b361f85b"] value 1
    inst [9 or "a35a31b86910ee44f72195cec984f07200017ba69b77a24f8f8783b83fb88d73"] value 1
```

Same ids from `containers.name`

**Comment by natoscott** [comment]
OK, so looks like containers have been identified correctly, and are in running state - good - next, has the main PID and cgroup been identified correctly for each?

$ pminfo --fetch containers.pid containers.cgroup

If these don't look right, next step will be having a look in the /var/lib/docker/containers files for each to figure out why the PID is not available.
OTOH, if they do look correct, we'll need to start setting some pmdaroot and pmdaproc debugging flags and investigating in that direction.

**Comment by spiermar** [comment]
```
~ $ pminfo --fetch containers.pid containers.cgroup

containers.pid
    inst [0 or "879e0119ca0e1410bc64971495e57739040fe1dc38975d36ffa24c7b72cdc60d"] value 25762
    inst [2 or "ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"] value 78209
    inst [4 or "4a6fcd82e33685614f4773b1d80b170f06311a7e7fd52b3d77079776aaba4f35"] value 77418
    inst [5 or "3123810294e3b9ea8e8b0eae114e273d3861d51ce4d12e81e4a4bc4b88ac7176"] value 102910
    inst [6 or "850b80dbdd86551e1dd5b3065620db79b47130e433d83c4337777c4396b5f770"] value 120023
    inst [7 or "6d00804cf4a4f855ede08ac81f061e0f843ee35908096133a799bcfc2ce0543c"] value 123029
    inst [8 or "7a65ea85ea6324411477d4ceb99b76693c1077176045371a06883c95b361f85b"] value 126645
    inst [9 or "a35a31b86910ee44f72195cec984f07200017ba69b77a24f8f8783b83fb88d73"] value 7035
    inst [10 or "42bf05379ee455497a066f9d5a6bc279ae37065537ba9646169cab41a52f2a7e"] value 122188

containers.cgroup
    inst [0 or "879e0119ca0e1410bc64971495e57739040fe1dc38975d36ffa24c7b72cdc60d"] value "/docker/879e0119ca0e1410bc64971495e57739040fe1dc38975d36ffa24c7b72cdc60d"
    inst [2 or "ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"] value "/docker/ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"
    inst [4 or "4a6fcd82e33685614f4773b1d80b170f06311a7e7fd52b3d77079776aaba4f35"] value "/docker/4a6fcd82e33685614f4773b1d80b170f06311a7e7fd52b3d77079776aaba4f35"
    inst [5 or "3123810294e3b9ea8e8b0eae114e273d3861d51ce4d12e81e4a4bc4b88ac7176"] value "/docker/3123810294e3b9ea8e8b0eae114e273d3861d51ce4d12e81e4a4bc4b88ac7176"
    inst [6 or "850b80dbdd86551e1dd5b3065620db79b47130e433d83c4337777c4396b5f770"] value "/docker/850b80dbdd86551e1dd5b3065620db79b47130e433d83c4337777c4396b5f770"
    inst [7 or "6d00804cf4a4f855ede08ac81f061e0f843ee35908096133a799bcfc2ce0543c"] value "/docker/6d00804cf4a4f855ede08ac81f061e0f843ee35908096133a799bcfc2ce0543c"
    inst [8 or "7a65ea85ea6324411477d4ceb99b76693c1077176045371a06883c95b361f85b"] value "/docker/7a65ea85ea6324411477d4ceb99b76693c1077176045371a06883c95b361f85b"
    inst [9 or "a35a31b86910ee44f72195cec984f07200017ba69b77a24f8f8783b83fb88d73"] value "/docker/a35a31b86910ee44f72195cec984f07200017ba69b77a24f8f8783b83fb88d73"
    inst [10 or "42bf05379ee455497a066f9d5a6bc279ae37065537ba9646169cab41a52f2a7e"] value "/docker/42bf05379ee455497a066f9d5a6bc279ae37065537ba9646169cab41a52f2a7e"
```

Checked the PIDs, they are all running. Any special debug flag?

**Comment by andrew-leung** [comment]
The containers here are being run in nested cgroups. When looking at the cgroup for a process:

`$cat /proc/78209/cgroup
11:freezer:/containers.slice/766e4ade-2504-4a15-b191-2730d553e9a3/ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a`

the path is nested. So the sys fs path is `/sys/fs/cgroup/systemd/containers.slice/766e4ade-2504-4a15-b191-2730d553e9a3/ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a` but it looks like that path is not being parsed properly.

The path above ```inst [2 or "ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"] value "/docker/ff8ae45ee6aadf51a684afbd02f2fd077652f5f6c14d6551276c9a1eadb0777a"```, which I think is from here https://github.com/performancecopilot/pcp/blob/master/src/pmdas/root/docker.c#L131 doesn't match.

**Comment by fche** [comment]
pcp/pmdaroot do not support nested containers.  There was some discussion of this in 2015.

**Comment by natoscott** [comment]
(nested cgroups not nested containers FWLIW).

@mspier @andrew-leung  from looking at the code, there are multiple issues to be resolved here - stemming from this being a non-default Docker setup (this causes the initial systemd-mis-detection - since the host pid1 is not systemd, we're also expecting system.slice not containers.slice - and it all goes pear-shaped from there).

I'll take a deeper look at Andrew's notes today and see if I can suggest a patch - the presence of that unexpected UUID-alike string also presents a new (more general) pattern-matching need that the code doesn't handle so far, as it goes about attempting to generate the cgroup paths.

**Comment by andrew-leung** [comment]
Thanks. I'm not exactly sure how it's detecting a systemd setup but on this host, depending where you're looking:

```
$ sudo ls -l /proc/1/exe
lrwxrwxrwx 1 root root 0 Apr  3 15:33 /proc/1/exe -> /lib/systemd/systemd
$ ps aux | grep /sbin/init
root          1  0.4  0.0 334812  7992 ?        Ss   Apr03  38:40 /sbin/init kaslr
```

We are setting up containers.slice as the systemd slice to run containers spawned by Docker and we're telling dockerd to use that slice

```
/usr/bin/dockerd --cgroup-parent=/containers.slice
```
Though non-default, being able to support Docker's nested cgroups would be useful.

**Comment by natoscott** [comment]
@andrew-leung yes, for sure.

The heuristic uses /proc/1/cmdline IIRC - hence only finds /sbin/initkaslr at present and takes the wrong fork in that road.  That part is relatively easily fixed I think.

**Comment by natoscott** [comment]
@spiermar @andrew-leung could you try the patch here ... ?
https://gist.github.com/natoscott/3fa7f8c6fd27220dfa8a771e434d7917

**Comment by spiermar** [comment]
Thanks Nathan! We will test it as soon as possible.

- Martin

**Comment by natoscott** [comment]
@spiermar I've updated the patch to improve the coverage to all situations (incl. other metrics that I think you folk are not using so far, like proc.id.container) - and have committed it to master now - could you try with that and let me know if any issues persist?  Thanks.

**Comment by spiermar** [comment]
@natoscott It fixed the issue. Required a small change on Vector too, but I'm pushing the fix now.
