### ISSUE TITLE
Zabbix module and unsupported metrics

### ISSUE THREAD

**Issue by rlex** [performancecopilot/pcp#477]
Hello. I am using pcp with zabbix (using pcpzbx.so). While 99% of time it works great (for couple of years now) i noticed that some metrics on some machines (3 of them, to be precise) started to fail. In zabbix server logs, it looks like this:
```
 25013:20180404:180036.624 item "php-2.srv.example.org:pcp.network.interface.in.errors[lo]" became not supported: Unknown error.
 25013:20180404:180051.700 item "mysql-3.srv.example.org:pcp.mysql.status.innodb_buffer_pool_pages_free" became not supported: Unknown error.
 25013:20180404:180051.700 item "mysql-3.srv.example.org:pcp.mysql.status.innodb_buffer_pool_pages_misc" became not supported: Unknown error.
 25013:20180404:180051.700 item "mysql-3.srv.example.org:pcp.mysql.status.threads_running" became not supported: Unknown error.
 25013:20180404:180051.700 item "mysql-3.srv.example.org:pcp.mysql.variables.key_buffer_size" became not supported: Unknown error.
 25013:20180404:180051.700 item "mysql-3.srv.example.org:pcp.mysql.variables.max_connections" became not supported: Unknown error.
 25015:20180404:180056.716 item "mysql-3.srv.example.org:pcp.mysql.status.innodb_buffer_pool_pages_total" became not supported: Unknown error.
 25014:20180404:180105.773 item "tpdl.srv.example.org:pcp.disk.partitions.write_bytes[vda5]" became not supported: Unknown error.
 25015:20180404:180108.780 item "mysql-3.srv.example.org:pcp.mysql.status.innodb_rows_deleted" became not supported: Unknown error.
 25013:20180404:180120.798 item "php-2.srv.example.org:pcp.disk.partitions.read_bytes[vda5]" became not supported: Unknown error.
```

After some time (usually on second run of zabbix_agent) they are back to supported.

I hasn't found anything useful in logs (both in zabbix_agent and pmcd) except this in mysql but it doesn't seem to be related:
```
Log for pmdamysql on mysql-3.srv.timepad.ru started Wed Apr  4 17:54:49 2018

[Wed Apr  4 17:55:12] pmdamysql(5172) Info: MySQL connection established

Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
Use of uninitialized value $_[0] in lc at /root/pcp/src/pmdas/mysql/pmdamysql.pl line 40.
```

Since those 3 machines are under some heavy load and they can be slow sometimes, i suspect that PCP doesn't extract metrics in time and skips them, which causes "unknown error" messages. I also have couple of boxes with slow I/O (cheap VPSes) and i sometimes see similar fails on them (they are, however, are not connected to I/O metrics).

I tried increasing timeout in pmcd.config and enabled debug of fetch (with no luck, no errors there) but this hasn't helped. Sample log: https://privatebin.net/?e89a501871fbad08#8Vfq2L8WaIXo0KJUL+ovRMqLhIGfYJkX4Vl3GwQEIbg=

I'm wondering if something can be done about this (maybe this is zabbix bug?)

**Comment by fche** [comment]
Can you by any chance check the availability of those pcp metrics using a tool other than zbxpcp.so, during those outage times?  Something as simple as 

    pminfo -f disk.partitions.read_bytes
    pminfo -f mysql.status

to see whether the respective pcp agents are still alive during the pcpzbx-signalled times?

**Comment by rlex** [comment]
Yep, it reports.
For example,  
```
25015:20180405:142033.811 item "php-2.srv.example.com:pcp.network.interface.in.bytes[lo]" became not supported: Unknown error.
```
```
lex@php-2.srv.example.com ⇣⇡ ❯ pminfo -f network.interface.in.bytes

network.interface.in.bytes
    inst [0 or "lo"] value 2069862837878
    inst [1 or "eth0"] value 3433636073755
```

**Comment by rlex** [comment]
Yes, it is available.

**Comment by red-tux** [comment]
Question, is the Zabbix related item in question an active or passive item?

To rule out server performance could you change it to being an active item if it is not already?  It may take about 15-30 minutes for the change to fully propagate under a default configuration.

**Comment by fche** [comment]
The next thing to try could be to turn on internal pcpzbx / libpcp level debugging with environment variables.  env PCP_DEBUG=65535 zabbix-process-that-loads-zbxpcp.so, or some other external tracing machinery like systemtap or strace, to see what zbxpcp.so's beef is.  Similarly, one could turn on tracing at the pmcd side (which zbxpcp hardcodes at `localhost`, see #281) to see what traffic is making it there.

**Comment by red-tux** [comment]
Can you set the debug level to at least 4 or 5 in the zabbix agent?
https://www.zabbix.com/documentation/3.4/manual/appendix/config/zabbix_agentd

**Comment by dimir** [comment]
There are a couple of places in function _zbx_module_pcp_fetch_metric_ returning _SYSINFO_RET_FAIL_ without setting _errmsg_. I would change that to set _errmsg_ in each case when _SYSINFO_RET_FAIL_ is returned.

**Comment by myllynen** [comment]
@rlex would you be able to compile and test the new zbxpcp module to allow us to see if the newly set error messages in addition to PCP debug level would provide some help? Thanks.

**Comment by rlex** [comment]
Sorry, not yet. I'll try to get back to it ASAP.

**Comment by rlex** [comment]
Probably worth mentioning here (i forced overwrite on that box)
```
Unpacking pcp-export-zabbix-agent (4.0.2-1) over (4.0.1-1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/etc/zabbix/zabbix_agent.d/zbxpcp.conf', which is also in package pcp 4.0.2-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/zabbix/modules/zbxpcp.so', which is also in package pcp 4.0.2-1
```

Git revision https://github.com/performancecopilot/pcp/commit/6a32574aaba623b2185cbe3344f52165054a9162

**Comment by natoscott** [comment]
Not sure there's anything else we can do here - please re-open if the new information requested by Marko becomes available.  Thanks!
