### ISSUE TITLE
support cri-o / runc containers in pmdaroot

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#480]
cri-o/runc are turning out to be important in the RHEL ecosystem as a docker alternative.  On f27, crio puts running-container metadata in /run/runc/XXXXXX/state.json files.

    # yum install crio-c podman
    # service crio start
    # podman pull docker.io/busybox
    # podman run --net none -i  YYYYYYY

I hope our luck that container id#s are hashy-unique continues across engines, and that the design decision NOT to annotate container.* indom keys with a namespace (docker:/runc:/lxc:) prefix stays defensible.

See also #191, #190.

**Comment by natoscott** [comment]
http://tasks.pcp.io/b/cbEf5fxGPp8BrbGYS/roadmap/gGTf6pgGbb5bN3Z4L

| luck that container id#s are hashy-unique continues across engines [...]

Luck doesn't come into it, and the hashy-ness or otherwise of container naming is (still) irrelevant.

Docker and LXC support already co-exists in the code.  No-one has ever shown any need for multiple container engines running on the same host simultaneously over many years now, and I don't expect that to change.

**Comment by fche** [comment]
> No-one has ever shown any need for multiple container engines running on the same host simultaneously

As we speak, I am running multiple container engines on the same host simultaneously.

**Comment by natoscott** [comment]
That's nice - but obviously, not in a production environment.

**Comment by natoscott** [comment]
Closing for lack of end-user demand - will continue to improve the podman integration though.

**Comment by mallilinux1980** [comment]
i was following the documentation https://pcp.readthedocs.io/en/latest/QG/AnalyzeLinuxContainers.html and try to monitor container metrics on RHEL8.6 but erroring out.

# pminfo --fetch containers.name containers.state.running

containers.name
No value(s) available!

containers.state.running
No value(s) available!

i've installed PMDA from /var/lib/pcp/pmdas/podman but command (# crictl ps) shows a bunch of containers running.

# ps -ef | grep [p]mda
root        2481    2469  0 02:26 ?        00:00:00 /var/lib/pcp/pmdas/root/pmdaroot
root        2491    2481  0 02:26 ?        00:00:03 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
root        2504    2481  0 02:26 ?        00:00:00 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
root        2520    2481  0 02:26 ?        00:00:01 /var/lib/pcp/pmdas/linux/pmdalinux
root        2536    2481  0 02:26 ?        00:00:00 /var/lib/pcp/pmdas/kvm/pmdakvm -d 95
root       47416    2481  0 04:32 ?        00:00:00 /var/lib/pcp/pmdas/podman/pmdapodman -d 33

did i mess anything?
