### ISSUE TITLE
Bionic builds

### ISSUE THREAD

**Issue by rlex** [performancecopilot/pcp#496]
Hello, just a request to enable building PCP packages under ubuntu bionic: 
https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes

**Comment by andihit** [comment]
There are already packages for bionic: https://packages.ubuntu.com/bionic/pcp

Or do you want to build your own package of PCP?
This is possible with the `./Makepkgs` script

**Comment by rlex** [comment]
Oh, i was using https://bintray.com/pcp for a long time. Possible to add on bintray?

**Comment by natoscott** [comment]
@rlex sure, will do.

**Comment by natoscott** [comment]
@rlex @scotte just FYI, there appears to be an issue with bintray and bionic uploads currently.  I'm seeing the same issue others are reporting when attempting to upload bionic debs, namely:
    "Could not extract metadata for artifact 'pcp-[...].deb', content might be malformed"

https://unix.stackexchange.com/questions/441032/deb-package-cannot-upload-to-bintray-when-package-is-build-using-ubuntu-18-04

I tried several ways of building pcp & generating .gz files over .xz - no uploads worked though.

I'll have another go when we release pcp-4.1.0 end of next week, see if bintray have fixed it in the interim.

**Comment by scotte** [comment]
Interesting - I'll check in with our contacts over at jfrog, too...

**Comment by scotte** [comment]
Answer from bintray is: "can you try disable uniform compression and build with compression form tar.gz" - they do not yet support uniform compression, support for that is some months out.

**Comment by natoscott** [comment]
@scotte thanks, eventually managed to find the right combination of options ... should be good to go:
https://bintray.com/pcp/bionic/pcp

**Comment by scotte** [comment]
Awesome, thanks @natoscott - we appreciate it!
