### ISSUE TITLE
GPG key 0xA51D3ADCDEA2C114 (debian packages via bintray) unavailable

### ISSUE THREAD

**Issue by draeath** [performancecopilot/pcp#500]
The bintray website does not provide the public key required for APT, and this key does not appear to be present via popular PGP keyservers, and indeed there are zero hits from, say, Google.

Please include a way to get this key [on the downloads page.](https://pcp.io/download.html)

The refrenced bintray "set me up" link is insufficient. [See this screenshot.](https://imgur.com/a/iscb0Zm) It's almost useless.

    W: GPG error: https://dl.bintray.com/pcp/stretch stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A51D3ADCDEA2C114
    E: The repository 'https://dl.bintray.com/pcp/stretch stretch Release' is not signed.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by draeath** [comment]
I was able to infer the URL to pull this from bintray directly, from an unrelated project's issue tracker. I suggest adding this to that downloads page!

https://bintray.com/user/downloadSubjectPublicKey?username=pcp

**Comment by natoscott** [comment]
@draeath thanks, will do!

**Comment by natoscott** [comment]
Added a link to the pcp.io download page, will appear shortly.  Thanks!  (and congrats on issue #500)

**Comment by frague59** [comment]
How to use that key ? I can't figure how to install that key on my stretch server...

Thanks !

**Comment by natoscott** [comment]
```
wget -qO - https://pcp.io/GPG-KEY-PCP | sudo apt-key add -
sudo rpm --import https://pcp.io/GPG-KEY-PCP
```
