### ISSUE TITLE
set up username and password for pmwebd

### ISSUE THREAD

**Issue by ghost** [performancecopilot/pcp#502]
Since http protocol is not secure. I want to connect to vector interface with a username and a password.
In the [documentation](https://pcp.io/man/man1/pmwebd.1.html), it is said that we can set up a user and a password to connect to the web user interface with -C parameters.

Does it really work? DO you have examples?

**Comment by fche** [comment]
You could configure pwmebd with `-C`, and pass the pcp-level userid/password on the vector `hostspec` box in the `pcp://HOST:PORT?user=FOO&pass=BAR` syntax.  This would serve as authentication.

To protect that authentication data with https for confidentiality/integrity, you could use any https reverse proxy to pass the vector webapp & pmwebapi traffic securely.

**Comment by sbe68** [comment]
Thanks @fche fo your answer but I am afraid I don't really understand this
> you could configure pwmebd with -C, and pass the pcp-level userid/password on the vector hostspec box in the pcp://HOST:PORT?user=FOO&pass=BAR syntax. This would serve as authentication.

This is how I configured my conf files. 
_/etc/pcp/pmwebd/pmwebd.options_
```
# Add password authentication
OPTIONS="$OPTIONS -C foo/bar" 
```
What is the way to specify a username and a password?

**Comment by fche** [comment]
pmwebd's `-C` option merely mandates that userid/password authentication come in, and it passes that data down to libpcp and thereby the remote pmcd.  The remote pmcd is what checks the userid/password pair via SASL.  As far as I know, we do not ship any out-of-the-box authentication configurations for pmcd.  See https://pcp.io/docs/lab.auth.html for some information about this.

If that is too unwieldy, you can drop that `-C`, you can ignore pmcd, instead performing authentication/authorization via an http reverse-proxy in front of pmwebd/pcp.  That in turn can use any httpd-style .htpasswd or other scheme, and add tls secure transport.

**Comment by nucc1** [comment]
do you mind sharing an example of what the "HOSTSPEC" should look like once you have enabled authentication with username foo and password bar? The manuals simply say: `/pmapi/context?hostspec=STRING` and I cannot work out how to create an authenticated context once I've required and configured authentication.

**Comment by nucc1** [comment]
The curse of asking. I worked it out after asking. Posting here for whoever finds themselves in my shoes in the future:

`GET http://<pmwebapi_hostname>:<port>/pmapi/context?hostspec=pcp%3A%2F%2Flocalhost%3A44321%3Fuser%3Dfoo%26bar%3Dtest%26method%3Dplain`

The hostspec is a PCP url, urlencoded to make the trip over http as a query parameter. In raw text, it looks as follows: `pcp://localhost:44321?user=foo&bar=test&method=plain`

**Comment by fche** [comment]
Why `bar=test` though?  It should be `pass=test` or such to identify the password keyword.

**Comment by nucc1** [comment]
My mistake, sorry. The syntax is correct. I tried to edit the string afterwards just to remove my actual password and made a mess of it.  If you fail to supply a 'pass' or 'password' parameter, you get an error saying credentials required. Still unable to create a valid authenticated session. Mind you, the pmwebapi returns a session context, but the session returns empty results for everything. It' s the pmcd log file that lets me know that password verification failed. (i'll edit original post to correct the error in the hostspec).

**Comment by fche** [comment]
I'd start looking at the pmcd-side authentication setup then.  It's not connected to the host PAM, for whatever reason.  See https://pcp.io/docs/lab.auth.html for setup instructions.

**Comment by natoscott** [comment]
pmwebd has been retired, pmproxy (its replacement in pcp v5 and later) supports authentication and TLS.
