### ISSUE TITLE
extend pmrep with PMNS_CHANGED logic

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#521]
For pcp2zabbix and other tooling, it would be useful if pmrep's core were able to adapt on-the-fly to metrics arriving late, during their runtime.  The visible user interface would be, like pmlogger, about the same as before, except that metric names/hierarchies that cannot be resolved at startup would not result in an error.  Instead, pmrep would remember those names, and if a fetch comes back with a PMNS_CHANGED flag, it would re-attempt resolving the names, add any new ones, and get back to business of the main loop.

This would allow simpler pcp2FOO relay operations, where _hypothetical_ metric names could be added to a standard command line, even if they do not (yet) exist.

**Comment by goodwinos** [comment]
This can be done by simply restarting pmrep / pcp2xxx. If dynamic PMNS handling is required, we should seek @myllynen's opinion when he gets back. It may only work well for JSON formatted output (for txt or csv output, the downstream parser/utility may not not tolerate columns appearing or disappearing on-the-fly)

**Comment by myllynen** [comment]
This kind of flexibility could be helpful for some users but not sure yet would it be worth the effort and additional code required. But this work would not be limited to pmrep/pcp2xxx only, as

> if a fetch comes back with a PMNS_CHANGED flag

I don't see any related PMNS constants defined in Python PMAPI so looks like lower-level building blocks are currently missing even if this would be determined feasible.

**Comment by fche** [comment]
> This can be done by simply restarting pmrep / pcp2xxx.

No, because pmrep dies if any of the supplied metric names are unresolvable at startup.

> so looks like lower-level building blocks are currently missing

Nah, only one, and I mistyped: PMCD_NAMES_CHANGE is already there.

**Comment by myllynen** [comment]
If anyone were to implement this, it would be needed for that effort (and also for QA) to have a simple way to emulate this - do we know how to do that?

> No, because pmrep dies if any of the supplied metric names are unresolvable at startup.

I think I have a quick patch somewhere on the corner of a disk to provide an option to ignore unknown metrics and/or options, do you think that would be helpful in any way?

**Comment by goodwinos** [comment]
We've added "[libpcp] fetchgroup collector state change event propogation" (sic) to the roadmap for pcp-4.3. This is the "lower level building block" mentioned above.

**Comment by fche** [comment]
BTW, the C pmFetchGroup function already returns the underlying pmFetch rc (including the bitflags).  The Python binding at the end of pmapi.py doesn't propagate sts back, but could do so with one extra line.  The substantial work - if any - is probably all in the pmrep code proper.

**Comment by myllynen** [comment]
Agreed, given that PMCD_NAMES_CHANGE exists, I'm unaware of any lower level building blocks missing. However, the question about emulation this to aid with implementation and testing seems still to be open?

**Comment by natoscott** [comment]
@myllynen as of git master today, there should be no changes needed outside of the client tool(s) - the fetchgroup fetch() return code is now propagated to the python API caller.  The bitfield names are available using these macros:

| $ grep PMCD_ src/python/pmapi.c

The name-change fetch() return code can be observed (QA'd) using the approach in test qa/1351 (see qa/1351.out in particular) - this uses mmv_genstats to generate name change events originating from pmdammv (which is handy, since its always installed and available during QA).

cheers.

**Comment by myllynen** [comment]
This has now been implemented for pmrep/pcp2xxx, will be part of PCP 4.3.0. Thanks.
