### ISSUE TITLE
bring back pmmgr monitor-host-env option

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#522]
We are encountering more and more cases where letting pmmgr pass a target pcp hostspec in an environment variable would be a lot more convenient than as a "-h $hostapec" command line suffix.  A new example came up today where it would be good to compute some monitor command line parameters from the hostspec:

    pcp2zabbix -X `pmprobe -v pmcd.hostname | cut -f2 -c'"' | cut -f1 -d-` ...

where the inferior `pmprobe` naturally wishes to operate on the same target pcp host as the pcp2zabbix will.  If the $hostspec were available as an environment variable, it would just work.  As it is, we are forced to write and refer to some auxiliary shell script.  We've had other instances like this too (gluster related e.g.).

This code still exists in pcpfans.git.  Tweak the commit message to no longer describe its imply as a workaround for github issue/195 (now fixed), tweak the code a little, and bob's your uncle.

commit 219ad9fa58202785ec84b29b2c5317151f6bc2dc
Author: Frank Ch. Eigler <fche@redhat.com>
Date:   Fri Mar 24 16:30:08 2017 -0400

**Comment by natoscott** [comment]
What has changed to make this no longer a regression for existing pmmgr deployments with tools using -h/--host already?  That issue has been raised several times in the past, but it seems like its not been understood (not mentioned / addressed above).  Here's a simple example to show the problem one more time though:

$ PCP_HOST=foo pmprobe -v --host bar pmcd.hostname
pmprobe: too many hosts requested: bar

Also, again as requested several times in the past: please open pull requests against the pcp master branch on github - thanks.

**Comment by fche** [comment]
> What has changed to make this no longer a regression for existing pmmgr deployments with tools using -h/--host already?

There was never such a regression.  The `monitor-host-env` option was an alternative, which did not put `-h FOO` into the command line.  So your example has not and would not arise.

> again as requested several times in the past: please open pull requests against the pcp master branch on github

That might be appropriate for finished patches, but not for bug reports or RFEs.  Indeed, I am reporting this as an RFE, with the previous patch as a resource.

**Comment by natoscott** [comment]
| The monitor-host-env option was an alternative, which did not put -h FOO into the command line.

Hmm, fair enough.  Its still problematic that a user might choose to or accidentally use a conflicting -h option in this mode ... but I guess that's something they'll have to deal with themselves and its worthwhile to have the convenience.

| That might be appropriate for finished patches ...  I am reporting this as an RFE ...

OK - please complete the work and open a PR when ready.

**Comment by natoscott** [comment]
No further work is planned on this.
