### ISSUE TITLE
Python PMAPI Labels Segfault

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#557]
As reported back in January (https://groups.io/g/pcp/message/17706) the following code segfaults:

```
#!/usr/bin/env pmpython

import json
from pcp import pmapi

pmfg = pmapi.fetchgroup()
ctx = pmfg.get_context()
pmid = ctx.pmLookupName("mem.util.used")[0]
labels = ctx.pmLookupLabels(pmid)
lset = ctx.pmMergeLabelSets([labels], None, None)
```

**Comment by goodwinos** [comment]
Resolved for pcp-4.3.0 with the following : 

commit 8c6b56ecae6451988026da7be91911c9f797b5ee
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Tue Dec 11 15:03:27 2018 +1100

    python pmapi binding: rework labels lookup, merge and free functions
