### ISSUE TITLE
Unclear which is the latest version

### ISSUE THREAD

**Issue by fxcoudert** [performancecopilot/pcp#565]
PCP 4.1.3 has been announced but Github still lists 4.1.1 as the “latest release”:

<img width="741" alt="capture d ecran 2018-09-24 a 21 38 37" src="https://user-images.githubusercontent.com/1980544/45974640-37b84d80-c042-11e8-999c-4a4b48259a69.png">

**Comment by natoscott** [comment]
Thanks, updated now (if anyone knows if there's a github API that can be used to automate this step, please let me know!)
