### ISSUE TITLE
pcp-pmda-bcc should require kernel-devel

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#568]
If kernel-devel with version matching the running kernel isn't installed, pmdabcc fails to compile some BPF modules, e.g.

```
[Wed Oct 10 09:41:03] pmdabcc(22773) Info: biolatency
chdir(/lib/modules/4.18.10-200.fc28.x86_64/build): No such file or directory
[Wed Oct 10 09:41:03] pmdabcc(22773) Error: biolatency: Failed to compile BPF module b'/var/lib/pcp/pmdas/bcc/modules/biolatency.bpf'
[Wed Oct 10 09:41:03] pmdabcc(22773) Error: biolatency: Module NOT active!
[Wed Oct 10 09:41:03] pmdabcc(22773) Error: Failed to compile module biolatency, aborting.

```
Once kernel-devel is installed, we see :

```
$ ls -l /lib/modules/`uname -r`/build
lrwxrwxrwx. 1 root root 40 Sep 26 20:11 /lib/modules/4.18.10-200.fc28.x86_64/build -> /usr/src/kernels/4.18.10-200.fc28.x86_64/

$ rpm -qf /usr/src/kernels/4.18.10-200.fc28.x86_64/
kernel-devel-4.18.10-200.fc28.x86_64
```

But pcp-pmda-bcc doesn't require kernel-devel

```
$ rpm -q --requires pcp-pmda-bcc
/bin/sh
/bin/sh
/bin/sh
/usr/bin/pmpython
python3-bcc
python3-pcp
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Also, it needs to be the right version of kernel-devel (to match the running kernel and kernel-core).
There are probably similar issues on other distros/platforms than fc28.

**Comment by myllynen** [comment]
As discussed on IRC, `pcp-pmda-bcc` pulls in `python3-bcc` which eventually (vial `bcc-tools`) require `kernel-devel`. The issue you are seeing might be due to mismatch of the running kernel vs the version of `kernel-devel` package installed.

**Comment by goodwinos** [comment]
yes you are correct, as we discussed upgrading the kernel but not rebooting can lead to this failure. So it's operator/admin error and nothing bcc/bpf can do about it really. We may be able to implement a runtime check using os.uname() or something so the failure messages are more user friendly
Thanks and regards
-- Mark
