### ISSUE TITLE
pmwebd binaries and init scripts missing from Solaris 11 package

### ISSUE THREAD

**Issue by gkoh** [performancecopilot/pcp#57]
Just downloaded and installed provided binaries for PCP 3.10.8 for Solaris 11.
Although the SMF entry for pmwebd exists:

```
# svcs '*pmwebd*'
STATE          STIME    FMRI
disabled       Dec_12   svc:/application/pcp/pmwebd:default
```

The service fails to start because the pmwebd binary and init files are not included in the package:

```
[ Dec 12 15:43:17 Method "start" exited with status 127. ]
[ Dec 12 15:43:17 Executing start method ("/etc/init.d/pmwebd start"). ]
/sbin/sh[1]: exec: /etc/init.d/pmwebd: not found
[ Dec 12 15:43:17 Method "start" exited with status 127. ]
```

I'm not sure if this is deliberate or a bug.

**Comment by natoscott** [comment]
The pmwebd binary is not built there because a libmicrohttpd build (needed by pmwebd) was not readily available for Solaris, IIRC.  The existence of the SMF entry is an oversight - the fix would be to build build/sun/pcp.xml using conditionally-included XML fragments based on state from configure.ac - rather than simply hard-coding everything in there (including filesystem paths, hmm).

**Comment by gkoh** [comment]
That's what I figured, thanks for explaining.
It would seem that the release of Solaris 11.3 changes this by providing a package for libmicrohttpd:
https://blogs.oracle.com/alanc/entry/solaris_11_3_beta_changes
and
http://pkg.oracle.com/solaris/release/en/search.shtml?token=libmicrohttpd&action=Search
leading to:
http://pkg.oracle.com/solaris/release/manifest/0/library%2Flibmicrohttpd%400.9.37%2C5.11-0.175.3.0.0.30.0%3A20150821T165535Z

**Comment by kmcdonell** [comment]
Just tidying up ... this is is resolved.  If you install the libmicrohttpd package and the gnutls package it requires, then we build and install all the required pieces ... e.g.

kenj@vm13:~/src/pcp$ ps auxw | grep '[p]mwebd'
pcp       8481  0.0  0.5 20932 10224 pts/2    S 21:53:06  0:00 /usr/libexec/pcp/bin/pmwebd -l pmwebd.log -R /usr/share/pcp/webapps -A
kenj@vm13:~/src/pcp$ qa/admin/whatami
vm13        4.1.1    i86pc   OpenIndiana Hipster 2017.10 [py=3.4.7 se=none]
