### ISSUE TITLE
pmdaelasticsearch issues

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#576]
There are some issues remaining with the current pmdaelasticsearch code:

* example config file missing (should provide similar as pmda{haproxy,libvirt} do)
* config file documentation missing from the man page
* user setting seems not effective
* crashes/exceptions when starting the PMDA without Elasticsearch reachable
* should recover (e.g. during system startup) if started prior Elasticsearch

Thanks.

**Comment by natoscott** [comment]
These issues have been resolved now, fixes will be in pcp-5.2.2
