### ISSUE TITLE
pmdapostgresql user= configuration overloaded

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#586]
The new (incompatible with old) pmdapostgresql configuration file uses the 'user=XXXX' field in two ways: one to authenticate to the target pgsql server, and also to setuid to that.  There's no way to suppress the latter.  But this setuid work is orthogonal: there is no reason to assert that a database server level user name should match a client side unix userid.  Worse, it is counterproductive on an installation where the pmda process cannot setuid at all, and thus the set_user() fails, killing the pmda.

The setuid stuff should be optional, and configured from a different configuration field.

**Comment by fche** [comment]
1037             params = "host=%s port=%s dbname=%s user=%s password=%s" % (self.host, self.port, self.dbname, self.user, self.password)

This part also looks suspicious with respect to passwords that may contain special characters like ' ' or punctuation.  I believe psycopg2 allows you to wrap those %s's in single-quotes.  (I haven't looked into what syntax it uses to escape a ' within the password text.)  Such passwords have been observed in the wild.

**Comment by fche** [comment]
http://initd.org/psycopg/docs/module.html#psycopg2.connect indicates connection parameters may be passed as keyword arguments rather than being stringified.
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING indicates stringified parameters may include `\'` and `\\` escapes.

**Comment by goodwinos** [comment]
here's a patch to add 'osuser' support to the configuration file. If osuser is not specified, then the PMDA will just run as the current user (no setuid will be made). The patch also now 'quotes' the password passed in to pg_connect(), so the password may contain spaces. Testing with local unix domain socket connection, and also with tcp/inet connection seems to work fine. Does this do what you need?

```
diff --git a/src/pmdas/postgresql/pmdapostgresql.1 b/src/pmdas/postgresql/pmdapostgresql.1
index da04418dc..a0b42862e 100644
--- a/src/pmdas/postgresql/pmdapostgresql.1
+++ b/src/pmdas/postgresql/pmdapostgresql.1
@@ -43,16 +43,25 @@ dbname \- database name, [default: 'postgres']
 username \- username to run as and to connect to the database [default: 'postgres']
 .IP "\(bu" 4
 password \- password to connect to the database [default: 'password']
+.IP "\(bu" 4
+osuser \- operating system user the PMDA runs as [default: not set]
 .PD
 .PP
 The defaults (as above) will result in the PMDA running as the
-.B postgres
-user, using a UNIX domain socket connection to the PostgreSQL server on the localhost.
+current user, using a UNIX domain socket connection to the PostgreSQL server on the localhost.
+If
+.B osuser
+is not specified in the configuration file, the PMDA will run as the current user.
 A host specification of "local" will use a UNIX domain socket, which uses peer authentication,
 see comments in the
 .B pg_hba.conf
 file.
-As such, it is normally not necessary to alter the default configuration file for monitoring
+In this case, the
+.B osuser
+setting should probably be set to
+.BR postgres .
+.PP
+It is generally not necessary to alter the default configuration file for monitoring
 the local PostgreSQL server instance with a default server configuration.
 Note the port number is required even for a UNIX domain
 connection because it's used as the socket filename by the server.
diff --git a/src/pmdas/postgresql/pmdapostgresql.conf b/src/pmdas/postgresql/pmdapostgresql.conf
index f251fa306..099751063 100644
--- a/src/pmdas/postgresql/pmdapostgresql.conf
+++ b/src/pmdas/postgresql/pmdapostgresql.conf
@@ -4,3 +4,4 @@ port=5432
 dbname=postgres
 user=postgres
 password=password
+# osuser=postgres
diff --git a/src/pmdas/postgresql/pmdapostgresql.python b/src/pmdas/postgresql/pmdapostgresql.python
index b6506f305..9981be842 100755
--- a/src/pmdas/postgresql/pmdapostgresql.python
+++ b/src/pmdas/postgresql/pmdapostgresql.python
@@ -1,4 +1,4 @@
-#!/usr/bin/env pmpython
+#!/usr/bin/pmpython
 
 # Copyright (c) 2018 Red Hat.  All Rights Reserved.
 # Copyright (c) 2011 Nathan Scott.  All Rights Reserved.
@@ -732,8 +732,13 @@ class POSTGRESQLPMDA(PMDA):
         self.user = self.conf["user"]
         self.password = self.conf["password"]
 
-        self.log("Switching to user '%s'" % self.user)
-        self.set_user(self.user)
+        try:
+            self.osuser = self.conf["osuser"]
+            self.log("Switching to user '%s'" % self.osuser)
+            self.set_user(self.osuser)
+        except KeyError as error:
+            # just run as the current user
+            pass
 
         self.log("Connecting to host '%s', port '%s', db '%s' as user '%s'" % (self.host, self.port, self.dbname, self.user))
         while not self.pg_connect():
@@ -1032,9 +1037,9 @@ class POSTGRESQLPMDA(PMDA):
         """ connect to the postgresql server """
         if self.host == "local":
             # local UNIX domain, but still need port number for the socket filename
-            params = "port=%s dbname=%s user=%s password=%s" % (self.port, self.dbname, self.user, self.password)
+            params = "port=%s dbname=%s user=%s password='%s'" % (self.port, self.dbname, self.user, self.password)
         else:
-            params = "host=%s port=%s dbname=%s user=%s password=%s" % (self.host, self.port, self.dbname, self.user, self.password)
+            params = "host=%s port=%s dbname=%s user=%s password='%s'" % (self.host, self.port, self.dbname, self.user, self.password)
         try:
             self.conn = psycopg2.connect(params)
         except (psycopg2.DatabaseError) as error: # pylint disable: broad-except
```

**Comment by fche** [comment]
Great, that should do 95% of it!  One missing bit is the needed `\`-escaping for `'` and `\` characters in the password.

**Comment by goodwinos** [comment]
wouldn't that be parsed server side? So the config would just specify e.g.
password=abc\\def \'hij
which would be specified for a password that is literally abc\def'hij

If not, is there a python function that will map the escape characters correctly?

**Comment by fche** [comment]
The string has to be parsed at some point; but just transcribing abc\def 'hij into that string would be a syntax error.  Putting the quoting burden into the configuration file would be possible but more confusing.
Escaping (only) these two chars could probably be done via
     password.replace("\\","\\\\").replace("'","\\'")

**Comment by goodwinos** [comment]
ok, will just add that then. And maybe replace double quotes with escaped double quotes too

**Comment by fche** [comment]
The docs linked above indicate only `\` and `'` need escaping.

**Comment by goodwinos** [comment]
Resolved with the following upstream commit for pcp-4.3.0

```
commit 9c30349f6772ee49b7c80c0751e42468e9475bc4
Author: Mark Goodwin <mgoodwin@redhat.com>
Date:   Thu Dec 13 10:33:32 2018 +1100

    pmdapostgresql: add optional 'osuser' to configuration
    
    GH#586 - pmdapostgresql user= configuration overloaded
    
    Adds 'osuser' to configuration, separate to 'user' (which is the dbuser).
    If osuser is set, the PMDA will set_user() on startup to that user.
    Previously the code always set_user() to 'user', which doesn't work too
    well in a non-root environment. Also suitably escape "'" and "\" in the
    configured password before passing it to pg_connect.
```
