### ISSUE TITLE
pmcd notready/ready packet checking should give verbose errors

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#589]
pmda misconfiguration (absence or presence of "notready" flag in pmcd.conf) can result in mystifying errors with affected pmdas: PM_ERR_IPCs alternated with different errors or empty results.  For example,
    % (nuke notready from pmdaprometheus line in pmcd.conf) 
    % restart pmcd
    % pminfo -f prometheus
    % pminfo -f prometheus
will give PM_ERR_IPC and/or other values; with the pmda being intermittently restarted - or not

Diagnosing such a misconfiguration took too long, partly because pmcd doesn't explain the situation well.  In this particular case, pmcd's dopdus.c CheckError is in a position to let us know of a missing `notready`, but only produces the useful diagnostics in `-Dappl0` mode.  It seems to me that such a situation is incurable via internal restart type efforts, and an unconditional `pmNotifyErr` is warranted (maybe even with the `notready in pmcd.conf` line given as a hint).

**Comment by natoscott** [comment]
No further work is currently planned on this area.
