### ISSUE TITLE
pmlogger_daily run "find . -daystart -name NoSuchFile" over all NFS mounts...

### ISSUE THREAD

**Issue by imsedgar** [performancecopilot/pcp#597]
Commit 7570a314ed657589f31830dc880d811b6ff589e9 adds the line

find . -daystart -name NoSuchFile >/dev/null 2>&1 && FIND_DAYSTART="-daystart"

to pmlogger_daily.sh .
This is bad because find starts at "/" and scans every file system, even remote network filesystems like nfs, which creates a high and unnecessary load on local systems and nfs servers.

See https://bugzilla.redhat.com/show_bug.cgi?id=1662034 .

**Comment by goodwinos** [comment]
Hi Edgar, in testing cwd was /var/log/pcp/pmlogger but it seems when run from cron, cwd is /. So clearly this patch is flawed  (it was trying to be BSD friendly, where find doesn't have the -daystart option).

This check should have been done during the build configure phase, and a variable set in /etc/pcp.conf.
I'll fix this as soon as possible - in the mean-time, please either downgrade to pcp-4.2.0 or edit /usr/libexec/pcp/bin/pmlogger_daily and comment out or delete the offending line in the script.

Regards

**Comment by fche** [comment]
Another easy option is to make this probing `find` operate on a known-small directory, like `/dev`, or a temp directory or file created just for the purpose.

**Comment by goodwinos** [comment]
pcp-4.3.0-2 with the reverted patch is now in fedora stable release streams (rawhide, f29 and f28).
