### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [performancecopilot/pcp#6]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/performancecopilot/pcp/blob/bbb283ee37c1ea676be0e59c7c5e06c8d3939ed5/configure.ac#L1753 "Configuration checks")?

**Comment by kmcdonell** [comment]
Seems like AX_PTHREAD needs ax_pthread.m4 to have been previously installed.
We're reluctant to add even more dependencies into the the build process, so unless (a) I've misunderstood something about making AX_PTHREAD work, or (b) there is some demonstrable problem with the way the existing PCP configure.ac probes for pthread availability, I think the status quo will prevail.

I'm closing this issue, please re-open if (a) or (b) apply.

**Comment by elfring** [comment]
Would you like to improve your software builds by reusing current macros from the GNU autoconf archive?

**Comment by kmcdonell** [comment]
Unless there is something broken in the current autoconf use with PCP, I don't understand how pulling in another build dependency "improves" our builds.
