### ISSUE TITLE
RFE: Support for /proc/pressure information

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#601]
Linux kernel 4.20 introduced support for `/proc/pressure`:

https://lwn.net/Articles/759781/
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/Documentation/accounting/psi.txt

It would be nice if PCP could provide this information as well. Thanks.

**Comment by natoscott** [comment]
See kernel.all.pressure.* now - thanks Marko.
