### ISSUE TITLE
pmcd.build incorrect for a patched spec build e.g. pcp-4.3.0-3 on Fedora

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#604]
For an RPM spec build (as in Fedora, RHEL, SLES, etc), pmcd.build should reflect the build revision number. For the pmcd.build metric, the pmcd PMDA source uses PACKAGE_BUILD, as determined by configure by reading VERSION.pcp. For pcp-4.3.0-3, this is still set to 1 (should be 3). Either the RPM spec should patch VERSION.pcp or configure.ac should figure out the build revision from %{version} in the spec. Since configure.ac is also used in non-RPM based builds, it would probably be preferable for the packaging mechanism to patch VERSION.pcp during the build.

Getting this right is important for support purposes, e.g. so the pcp-summary(1) command reports accurate information and pmlogger logs correct values for pmcd.version and pmcd.build.
```
f29# pminfo -f pmcd.version pmcd.build

pmcd.version
    value "4.3.0"

pmcd.build
    value "1"
f29# rpm -q pcp
pcp-4.3.0-3.fc29.x86_64

```

**Comment by fche** [comment]
BTW:

    git=`git rev-parse HEAD | cut -c1-8`
    date=`date +%Y%m%d%H%M`
    release=0.${date}.git${git}
    sed -i -e 's,PACKAGE_BUILD.*$,PACKAGE_BUILD='$release',' VERSION.pcp
    cat $specfile | sed -e 's,Release: 1,Release: '$release',' -e "s,Version:.*$,Version: ${PACKAGE_MAJOR}.${PACKAGE_MINOR}.${PACKAGE_REVISION},"> pcp.spec

The above is how I build 'rawhide'y snapshots of pcp branches so they self-identify properly.

**Comment by goodwinos** [comment]
Thanks Frank - I have a similar update to fedora.spec that just makes PACKAGE_BUILD match whatever %{release} has been set to at the top of the spec, vis.

```
 diff --git a/build/rpm/fedora.spec b/build/rpm/fedora.spec
index 8a3ebb8a1..bc8d3c62c 100644
--- a/build/rpm/fedora.spec
+++ b/build/rpm/fedora.spec
@@ -2236,6 +2236,10 @@ updated policy package.
 %setup -q
 
 %build
+# fix up build version
+_build=`echo %{release} | sed -e 's/\..*$//'`
+sed -ie "/PACKAGE_BUILD/s/=[0-9]*/=$_build/" VERSION.pcp
+
 %if !%{disable_python2} && 0%{?default_python} != 3
 export PYTHON=python%{?default_python}
 %endif
```

**Comment by goodwinos** [comment]
closing this out - the patch should set PACKAGE_BUILD in VERSION.pcp
