### ISSUE TITLE
Build fails on Mac OS Mojave

### ISSUE THREAD

**Issue by fbacchella** [performancecopilot/pcp#607]
On my mac:
```
$ uname -a
Darwin lmac-fa4-dsy 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

```
$ git clone https://github.com/performancecopilot/pcp.git
$ cd pcp
$ ./configure
$ make install
...
./install-sh -o root -g wheel -m 755 -d /usr/local//usr/local/var/lib/pcp
```

What a very strange path: `/usr/local//usr/local/var/lib/pcp`

In GNUMakefile, I see:
```
install_pcp :  default_pcp
        # install the common directories _once_
        $(INSTALL) -m 755 -d $(INSTALL_PREFIX)$(PCP_VAR_DIR)
```

And in config.log:
```
pcp_var_dir='/usr/local/var/lib/pcp'
prefix='/usr/local'
```

I'm trying to install a new pcp from git, as the build for mac OS is too old, at https://bintray.com/pcp/macosx/pcp

**Comment by kmcdonell** [comment]
configure without options is not going to do the right thing.

You'll need to run ./Makepkgs (from the top-level directory) or extract the configure options from there and use these to run configure directly.
