### ISSUE TITLE
use DNF weak dependencies for pmdas

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#608]
The current RPM dependency pattern used in pcp pmda subrpms is that a pmda Requires: the application that the pmda is monitoring.  This pattern precludes routine/preemptive installation of pmda subrpms generally, because it would pull in undesired applications too.  And no user wants to install an application **because** they want to install some pcp monitoring.  It's the other way around.

With modern fedora / rhel8, we have weak and backwards dependencies available.  These better express the nature of the real user desire: "If I install application X, and have PCP installed, I'd like the system to auto-install pcp-pmda-X".  I believe the "Enhances:" or "Supplements:" backward-weak dependencies put into the pmdas can express this.

So please consider replacing the Requires: in pmda subrpms with Supplements: or Enhances:, whichever is easier to explain.

**Comment by goodwinos** [comment]
See Weak Dependencies in http://rpm.org/user_doc/dependencies.html
I like the idea - each PMDA could have a weak reverse dependency using Supplements: someapplication

**Comment by natoscott** [comment]
Closing as there's no plans/resources to implement any change to the current strong dependencies employed by PCP agents.
