### ISSUE TITLE
pcp-pdma-bcc support on centos 7.6

### ISSUE THREAD

**Issue by f0** [performancecopilot/pcp#614]
Hi,

with rhel/centos7 , ebpf and the bcc tools are aviable.
Is ther a reason why not enabeling pcp-pdma-bcc  on the rhel/centos builds?

regards

**Comment by myllynen** [comment]
pcp-pmda-bcc package is available for RHEL 7.6 in the rhel-7-server-optional repo.

**Comment by f0** [comment]
you are correct, i missed this
