### ISSUE TITLE
How to collect 'cumulative counter event data' using python

### ISSUE THREAD

**Issue by nasastry** [performancecopilot/pcp#620]
Wrote a small python script to collect the event data.

```
from pcp import pmapi
import cpmapi as c_api

pmfg = pmapi.fetchgroup(c_api.PM_CONTEXT_HOST, "local:")
vv = pmfg.extend_indom("kernel.all.intr", c_api.PM_TYPE_FLOAT)
t = pmfg.extend_timestamp()

pmfg.fetch()
for icode, iname, value in vv():
    print("iname=%s, Value=%f" % (iname, value()))
```

Using the above script, can see the data for `semantics: instantaneous value` but not for `semantics: cumulative counter (converting to rate)`. 
For `cumulative counter data` seeing the following error.
```
Traceback (most recent call last):
  File "t.py", line 10, in <module>
    print("iname=%s, Value=%f" % (iname, value()))
  File "/usr/lib64/python2.7/site-packages/pcp/pmapi.py", line 2662, in <lambda>
    (lambda i: (lambda: decode_one(self, i)))(i)))
  File "/usr/lib64/python2.7/site-packages/pcp/pmapi.py", line 2657, in decode_one
    raise pmErr(self.stss[i])
pcp.pmapi.pmErr: PM_ERR_AGAIN Try again. Information not currently available
```

How to get the data for `cumulative counter`?

Example of events:
```
# pmval hinv.cpu.online

metric:    hinv.cpu.online
host:      linux-l9tb
semantics: instantaneous value
units:     none
samples:   all
...
```

```
# pmval kernel.all.intr

metric:    kernel.all.intr
host:      linux-l9tb
semantics: cumulative counter (converting to rate)
units:     count (converting to count / sec)
```

Thanks in advance.

**Comment by kmcdonell** [comment]
You need to have called fetch() more than once before printing the results ... to do the rate conversion for counter metrics you need a value v1 at time t1 (the first fetch()) and a second value v2 at time t2 (the second fetch()) and the computed rate is then (v2 - v1) / (t2 - t1).

**Comment by nasastry** [comment]
@kmcdonell Thank you very much for your earlier response.

This is my understanding of the above

```
from pcp import pmapi
import cpmapi as c_api
import time

pmfg = pmapi.fetchgroup(c_api.PM_CONTEXT_HOST, "local:")
v1 = pmfg.extend_indom("kernel.all.intr")
pmfg.fetch()
time.sleep(5)
v2 = pmfg.extend_indom("kernel.all.intr")
pmfg.fetch()

v_diff = (v2 - v1) / 5

```

But the above is throwing the following error.
```
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    v_diff = (v2 - v1) / 5
TypeError: unsupported operand type(s) for -: 'fetchgroup_indom' and 'fetchgroup_indom'
```

Tried other variant also
```
pmfg = pmapi.fetchgroup(c_api.PM_CONTEXT_HOST, "local:")
v1 = pmfg.extend_item("kernel.all.intr")
pmfg.fetch()
time.sleep(10)
pmfg1 = pmapi.fetchgroup(c_api.PM_CONTEXT_HOST, "local:")
v2 = pmfg1.extend_item("kernel.all.intr")
pmfg1.fetch()

v_diff = (v2 - v1) / 5
```
This also throwing error:
```
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    v_diff = (v2 - v1) / 5
TypeError: unsupported operand type(s) for -: 'fetchgroup_item' and 'fetchgroup_item'
``` 

Till this gets resolved can you please `open` this issue? I don't have sufficient privileges to `re-open`. Thanks in advance.

**Comment by nasastry** [comment]
I have read the `pcp-programmers-guide.pdf - Chapter 3. PMAPI--The Performance
Metrics API`, but didn't get any clue on how to deal with `cumulative counter` other than
```
idle = fg.extend_item('kernel.all.cpu.idle, scale='s/100s')  # this event gives cumulative counter
values = fg.extend_indom('disk.dm.read') # this event also gives cumulative counter
After fetch:
idle is used as:
print(idle())
values is used as:
for icode, iname, value in values():
print('disk %s reads %d' % (iname, value()))
```

Both `idle and values` examples didn't work on pcp-4.3.0

**Comment by kmcdonell** [comment]
OK, I'll reopen this and leave to someone who knows something about Python and the fetchgroup wrapper to respond.

**Comment by natoscott** [comment]
@nasastry have a look at the sample code in the PCP git repo - src/pmclient/pmclient_fg.python (this code is also in the pcp-devel package if that's easier).  See for example the handling of the dkiops metric, which is a simple counter, and note how info.get_sample() is called twice before any reporting is done.

So, the problem with your code snippets is that you should need be doing the rate conversion manually.  Rate conversion is done in the libpcp fetchgroup code for counter metrics.

**Comment by myllynen** [comment]
@nasastry I've added a directory `src/pcp2template` which should be helpful, it contains a template which can be used to get quickly started creating new `pcp2xxx` like tools (and it will give you features like configuration file support, archive support, filtering, etc out of the box). See https://github.com/performancecopilot/pcp/tree/master/src/pcp2template and e.g. `pcp2xml` for more details. Thanks.

**Comment by nasastry** [comment]
Thank you @natoscott and @myllynen 
I am going through the provided content.

**Comment by nasastry** [comment]
I got my working code: still need to do some cosmetic changes.

```
#!/usr/bin/env pmpython
from __future__ import print_function

import sys
from pcp import pmapi
import cpmapi as c_api
import time

fg = pmapi.fetchgroup(c_api.PM_CONTEXT_HOST, 'local:')
hv_24x7 = fg.extend_indom('perfevent.hwcounters.hv_24x7.PM_PB_CYC.value')
timestamp = fg.extend_timestamp()

#Get the samples
fg.fetch()

lines = 0
samples = 10

while True:
    if samples >= 0:
        if samples == 0:
            break
        samples -= 1
    fg.fetch()
    lines += 1
    time.sleep(1)
    for icode, iname, value in hv_24x7():
        print("values are %s: %f" % (iname, value()))
```

Thanks a lot for your timely help.
