### ISSUE TITLE
Debian packages missing postgres PMDA

### ISSUE THREAD

**Issue by ioguix** [performancecopilot/pcp#621]
Hello,

The PostgreSQL PMDA is missing from the Debian package in Buster (testing) and Sid (unstable).

See:
* https://packages.debian.org/buster/amd64/pcp/filelist
* https://packages.debian.org/sid/amd64/pcp/filelist

Note that the manpage is included, but not the PMDA folder.

**Comment by natoscott** [comment]
This has been fixed by commit 167e9ca58f99 - will be in pcp-4.3.2

**Comment by ioguix** [comment]
oh, oops, sorry for the noise.
