### ISSUE TITLE
fetchgroup desynchronization when metrics have offset timestamps? (Python API)

### ISSUE THREAD

**Issue by pphysch** [performancecopilot/pcp#623]
I followed the documentation at https://pcp.io/books/PCP_PG/html/fetchgroup.html to write some Python code that boils down to:

```
fg = pmapi.fetchgroup(c_api.PM_CONTEXT_ARCHIVE, './foo.meta')
ctx = fg.get_context()

metrics = dict()
def process_metric(metric_name):
    # use the ctx to get pmid/desc and detect if the metric has an InDom
    if has_indom:
        metrics[name] = fg.extend_indom(metric_name)
    else:
        metrics[name] = fg.extend_item(metric_name)

ctx.pmTraversePMNS("", process_metric)
get_timestamp = fg.extend_timestamp()

ts = get_timestamp()
end = datetime.datetime.fromtimestamp(ctx.pmGetArchiveEnd().tv_sec)

while (ts <= end):
    fg.fetch()
    ts = get_timestamp()
    for metric, result in metrics.items():
        # check if result() exists and is valid else continue, do stuff with result
```
In theory, this code should temporally walk through the archive and let the programmer access each unit of data for each metric.

It runs without any runtime error and seems to work fine when I let it loose on a complete archive. However, I noticed some unusual omissions in the output; entire metrics would have no valid values, even though they should be present and are visible through pminfo/pmval/pmrep.

I then filtered the metrics so that the Python code would only include e.g. "nfsclient.\*" metrics in its dictionary. "nfsclient.\*" metrics were previously among those incorrectly ignored by the code. When I did this, Python started seeing the "nfsclient.\*" metric results, unlike before. I then added "lustre.\*" metrics, and the program ceases to find any valid metric values at all. If I take out "nfsclient.\*" and look only for "lustre.\*" metrics, now it can see the correct "lustre.\*" metric values. 

In summary,

Fetchgroup extended with all available items/indoms:
-> Python API sees a lot of valid metric values, but some are unexpectedly missing.

Extend fetchgroup with only "nfsclient.\*" indoms:
-> Python API successfully sees all the "nfsclient.*" values as expected.

Extend fetchgroup with only "lustre.\*" indoms:
-> Python API successfully sees all the "lustre.*" values as expected.

Extend fetchgroup with only "nfsclient.\*" and "lustre.\*" indoms
-> Expected: Python API sees both sets of values that were previously individually accessed.
-> Reality: Python API finds zero valid metric values.

I noticed that the nfsclient and lustre metrics had different timestamps. lustre metrics are first available at 00:10:46.**63**2004, while nfsclient metrics do not appear until 00:10:46.**67**7465 in the archive, milliseconds later. Throughout the archive, these metrics remain offset by milliseconds. This data "desynchronization" should not be a problem, and when extended with both groups of metrics, PMAPI correctly fetchs at ...46.63... and the next fetch is at ...46.67... .

However, the metric results are incorrect. At this first notable timestamp, when lustre metrics are demonstrably present, the result handle from `extend_indom` unexpectedly returns an empty list [], while the nfsclient result returns a non-empty list of instances and their results at this same timestamp. Trying to retrieve the values from the non-empty nfsclient results then leads to a pmErr exception citing unavailable data, as expected. At the next timestamp, when nfsclient metrics were shown to be available, the roles are switched, and nfsclient metrics returns an empty []. In aggregate, zero valid results are found in the entire archive.

It seems that the (Python) API is upset by the different time steps and is looking for particular metrics at the wrong times.

In conclusion, I can work around this and complete my task by looking at individual metrics or families of metrics, but it breaks down when I try to do it all at once.

Am I misunderstanding the Python API or is there unintentional behavior going on here? I can provide more details if needed.

**Comment by myllynen** [comment]
Thanks for your report, it's obviously been a very long time since then, not sure is this relevant any more?

Now that I noticed this I could mention two things that might in theory be related or not but they are all I can think of at the moment. The difference in timestamps reminds me of the issue https://github.com/performancecopilot/pcp/issues/433 and the missing instances reminds of the _maxnum_ parameter of `extend_indom`, not sure would increasing it help, at least it would be trivial to try it out and see. But it could be well that we're talking something different than either of these two speculations.

Thanks.

**Comment by pphysch** [comment]
This is not relevant for us anymore, feel free to close. Thanks!
