### ISSUE TITLE
pcp dstat hangs on archive collected via pcp-zeroconf

### ISSUE THREAD

**Issue by mbaldessari** [performancecopilot/pcp#624]
I collected the pcp archives on a rhel8-based VM:
 [root@undercloud-0 pmlogger]# rpm -qa |grep pcp
pcp-doc-4.3.0-3.el8.noarch
pcp-zeroconf-4.3.0-3.el8.x86_64
pcp-4.3.0-3.el8.x86_64
pcp-libs-4.3.0-3.el8.x86_64
pcp-system-tools-4.3.0-3.el8.x86_64
pcp-conf-4.3.0-3.el8.x86_64
pcp-pmda-nfsclient-4.3.0-3.el8.x86_64
python3-pcp-4.3.0-3.el8.x86_64
pcp-selinux-4.3.0-3.el8.x86_64
pcp-pmda-dm-4.3.0-3.el8.x86_64

When I try to analyze the data with dstat, the command hangs towards the end of the archive:
 pcp -a 20190326.0 dstat -t -v -y -p  1h 

At this point CPU is stuck in python3 and I get the following backtrace in gdb:
(gdb) bt
#0  0x00007faa1fed06c5 in pmfg_reinit_indom (item=item@entry=0x55685afea600) at fetchgroup.c:592
#1  0x00007faa1fed18de in pmFetchGroup (pmfg=0x556859bb6c70) at fetchgroup.c:1613
#2  0x00007faa1f3c5b28 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#3  0x00007faa1f3c5339 in ffi_call (cif=cif@entry=0x7fffd438c9c0, fn=fn@entry=0x7faa1fed1890 <pmFetchGroup>, rvalue=<optimized out>, rvalue@entry=0x7fffd438c920, avalue=<optimized out>) at ../src/x86/ffi64.c:525
#4  0x00007faa1ff694b5 in _call_function_pointer (argcount=1, resmem=0x7fffd438c920, restype=<optimized out>, atypes=<optimized out>, avalues=0x7fffd438c910, pProc=0x7faa1fed1890 <pmFetchGroup>, flags=<optimized out>)
    at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/_ctypes/callproc.c:827
#5  _ctypes_callproc (pProc=<optimized out>, argtuple=<optimized out>, flags=<optimized out>, argtypes=<optimized out>, restype=<optimized out>, checker=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/_ctypes/callproc.c:1184
#6  0x00007faa1ff69cd4 in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/_ctypes/_ctypes.c:3969
#7  0x00007faa2d57c47c in _PyObject_FastCallKeywords (callable=<_FuncPtr(__name__='pmFetchGroup') at remote 0x7faa1f307b38>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:203
#8  0x00007faa2d57d869 in call_function (pp_stack=0x7fffd438cc30, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:4619
#9  0x00007faa2d5cdd12 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3093
#10 0x00007faa2d568412 in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#11 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x556859bbb850, nargs=1, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#12 0x00007faa2d57d6df in call_function (pp_stack=0x7fffd438ce30, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:4616
#13 0x00007faa2d5c902e in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3110
#14 0x00007faa2d568412 in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#15 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x556859a88cd8, nargs=2, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#16 0x00007faa2d57d6df in call_function (pp_stack=0x7fffd438d030, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:4616
#17 0x00007faa2d5c902e in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3110
#18 0x00007faa2d568412 in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#19 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x556859a11bc8, nargs=1, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Objects/call.c:408
#20 0x00007faa2d57d6df in call_function (pp_stack=0x7fffd438d230, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:4616
#21 0x00007faa2d5c902e in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3110
#22 0x00007faa2d567420 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3930
#23 0x00007faa2d5682e9 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:3959
#24 0x00007faa2d56830b in PyEval_EvalCode (co=co@entry=<code at remote 0x7faa200fb540>, 
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated), 
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated))
    at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/ceval.c:524
#25 0x00007faa2d63b50f in run_mod (mod=mod@entry=0x556859aeb840, filename=filename@entry='/usr/libexec/pcp/bin/pcp-dstat', 
    globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated), 
    locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated), 
    flags=flags@entry=0x7fffd438d520, arena=arena@entry=0x7faa203140a8) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/pythonrun.c:1035
#26 0x00007faa2d63b877 in PyRun_FileExFlags (fp=0x556859a18010, filename_str=<optimized out>, start=<optimized out>, 
    globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated), 
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/libexec/pcp/bin/pcp-dstat') at remote 0x7faa2024d550>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7faa2030dc28>, '__file__': '/usr/libexec/pcp/bin/pcp-dstat', '__cached__': None, 'OrderedDict': <type at remote 0x7faa2d75d440>, 'ConfigParser': <module at remote 0x7faa1fde2e08>, 'termios': <module at remote 0x7faa200b4d68>, 'struct': <module at remote 0x7faa200b4ea8>, 'atexit': <module at remote 0x7faa200b4f48>, 'fcntl': <module at remote 0x7faa200d2408>, 'sched': <module at remote 0x7faa200d24f8>, 'errno': <module at remote 0x7faa20083458>, 'time': <module at remote 0x7faa200d2728>, 're': <module at remote 0x7faa1fdb5048>, 'sys': <module at remote 0x7faa20307f98>, 'os': <module at remote 0x7faa20250db8>, 'pmapi': <module at remote 0x7faa20083598>, 'pmconfig': <module at remote 0x7faa20083868>, 'PM_CONTEXT_ARCHIVE': 2, 'PM_CONTEXT_HOST': 1, 'PM_CONTEXT_LOCA...(truncated), closeit=1, flags=0x7fffd438d520)
    at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/pythonrun.c:988
#27 0x00007faa2d6415d6 in PyRun_SimpleFileExFlags (fp=0x556859a18010, filename=<optimized out>, closeit=1, flags=0x7fffd438d520) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Python/pythonrun.c:429
#28 0x00007faa2d643864 in pymain_run_file (p_cf=0x7fffd438d520, filename=<optimized out>, fp=0x556859a18010) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/main.c:427
#29 pymain_run_filename (cf=0x7fffd438d520, pymain=0x7fffd438d630) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/main.c:1627
#30 pymain_run_python (pymain=0x7fffd438d630) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/main.c:2877
#31 pymain_main (pymain=0x7fffd438d630) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/main.c:3038
#32 0x00007faa2d643c0c in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3-3.7.3-1.fc30.x86_64/Modules/main.c:3073
#33 0x00007faa2d7a8f33 in __libc_start_main () from /lib64/libc.so.6
#34 0x0000556858ad608e in _start ()

Archives to reproduce the issues are here:
http://acksyn.org/files/tripleo/undercloud-0.redhat.local/

**Comment by natoscott** [comment]
@mbaldessari this appears to be a failure to handle the end-of-archive condition correctly in some situations - I'll have a fix shortly, thanks for reporting it.
