### ISSUE TITLE
Suspicious strcmp assert in qa/src/fetchgroup.c

### ISSUE THREAD

**Issue by rikardfalkeborn** [performancecopilot/pcp#626]
In `qa/src/fetchgroup.c` we have the following lines which look suspicious (look at the last call to `strcmp()` which is not compared to zero):

https://github.com/performancecopilot/pcp/blob/b6c1b4d7bd7a7bc6b0635db140bbd2cb9dc704c8/qa/src/fetchgroup.c#L224-L226

which essentially say `values2[j].cp` can be anything but `"thirteen"`. I'm pretty sure line 226 should be `strcmp(values2[j].cp, "thirteen") == 0`, but I'm not really able to test it so I'll just open an issue instead of sending a PR.

**Comment by natoscott** [comment]
@rikardfalkeborn yes, it's definitely incorrect - I'll get that fixed up shortly - thanks for reporting it.
