### ISSUE TITLE
pcp dstat --output in csv is malformed. 

### ISSUE THREAD

**Issue by manasamanohar** [performancecopilot/pcp#639]
pcp dstat when run with --output <filename> option and opened in Excel (comma specified as delimiter) shows inconsistencies between header and datapoints. Some columns are missing headers. This results in few metrics at the right most end of the file to be empty without any datapoints. 

The command-line interface for the same works fine with 1:1 alignment of header:datapoints 

------output------------------------------------------------------------------------------------------------
/*** START OF PROFILING OUTPUT ***/
"pcp-dstat 4.3.1 CSV Output"
"Author:","PCP team <pcp@groups.io> and Dag Wieers <dag@wieers.com>",,,,"URL:","https://pcp.io/ and http://dag.wieers.com/home-made/dstat/"
"Host:","system1",,,,"User:","user"
"Cmdline:","dstat --nocolor --noheaders --epoch --cpu --net -N ens192,virbr0,virbr0-nic,total -dD sda --io --mem --page --vm --output /tmp/.vpp-collector/user/._tmp_storage",,,,"Date:","08 May 2019 13:24:33 PDT"
"epoch","total usage",,,,,,,,,"net/ens192",,"net/virbr0",,"net/virbr0-nic",,"net/total",,,"dsk/sda",,,"io/total",,"memory usage",,,,"paging",,"virtual memory"
"epoch","total usage:usr","total usage:sys","total usage:idl","total usage:wai","total usage:stl","net/ens192:recv","net/ens192:send",,"net/virbr0:recv","net/virbr0:send",,"net/virbr0-nic:recv","net/virbr0-nic:send",,"net/total:recv","net/total:send","dsk/sda:read","dsk/sda:writ","read","writ","used","free","buf","cach","in","out","majpf","minpf","alloc","free"
1557347073,,,,,,,,,,,,,,2845036,3436352,240976,3852044,,,,,,
1557347074,0.499,0.250,99.140,0,0,249.723,417.536,0,0,0,0,249.723,417.536,0,0,0,0,2845068,3436320,240976,3852048,0,0,0,30.966,35.960,17.980
1557347075,0.750,0,99.497,0,0,249.993,351.990,0,0,0,0,249.993,351.990,0,0,0,0,2845036,3436352,240976,3852048,0,0,0,5.000,19.999,24.999
1557347076,0.250,0.250,99.264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2845036,3436352,240976,3852048,0,0,0,1.000,13.002,12.002
1557347077,0.250,0.250,99.486,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2845160,3436228,240976,3852048,0,0,0,0,12.998,12.998
1557347078,0.500,0,99.258,0,0,76.006,76.006,0,0,0,0,76.006,76.006,0,0,0,0,2845160,3436228,240976,3852048,0,0,0,0,12.001,12.001
1557347079,0.500,0.250,99.754,0,0,0,0,0,0,0,0,0,0,0,1676.060,0,13.000,2845280,3436104,240976,3852052,0,0,0,0,32.001,28.001

**Comment by natoscott** [comment]
@yuokada126 thoughts?

**Comment by yuokada126** [comment]
@manasamanohar Thanks for reporting it. The fix was merged into upstream. Please let me know if have any questions.

**Comment by manasamanohar** [comment]
Hi yuokada126, 

Thanks for your reply. I tested **pcp dstat 4.3.2** on my Fedora 29 and the problem still perists.
Attaching the dataset here. Problem (i.e misalignment of header:values) might be more apparent when there are >1 disks that are supplied using -d option or >1 network devices that are supplied using -N option.

Let me know if you need more details or if I have got the wrong version (?)

"pcp-dstat 4.3.2 CSV Output"
"Author:","PCP team <pcp@groups.io> and Dag Wieers <dag@wieers.com>",,,,"URL:","https://pcp.io/ and http://dag.wieers.com/home-made/dstat/"
"Host:","test-system1",,,,"User:","user"
"Cmdline:","dstat --nocolor --noheaders --epoch --cpu --net -N ens192,virbr0,virbr0-nic,total -dD sda --io --mem --page --vm --output storage.dat",,,,"Date:","11 Jun 2019 10:46:15 PDT"
"epoch","total usage",,,,,,,,,"net/ens192",,"net/virbr0",,"net/virbr0-nic",,"net/total",,,"dsk/sda",,,"io/total",,"memory usage",,,,"paging",,"virtual memory"
"epoch","total usage:usr","total usage:sys","total usage:idl","total usage:wai","total usage:stl","net/ens192:recv","net/ens192:send",,"net/virbr0:recv","net/virbr0:send",,"net/virbr0-nic:recv","net/virbr0-nic:send",,"net/total:recv","net/total:send","dsk/sda:read","dsk/sda:writ","read","writ","used","free","buf","cach","in","out","majpf","minpf","alloc","free"
1560275175,,,,,,,,,,,,,,3024188,1137908,383652,5971020,,,,,,
1560275176,0,0,99.762,0,0,60.007,812.100,0,0,0,0,60.007,812.100,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,9.001,3.000,0
1560275177,0,0,99.997,0,0,59.998,257.993,0,0,0,0,59.998,257.993,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,5.000,4.000,1.000
1560275178,0,0,99.751,0,0,60.001,258.003,0,0,0,0,60.001,258.003,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275179,0.750,0.250,98.751,0,0,1050.016,1006.015,0,0,0,0,1050.016,1006.015,0,156.002,0,30.000,3024284,1137812,383652,5971024,0,0,0,22.000,13.000,5.000
1560275180,0,0,100.001,0,0,60.001,258.002,0,0,0,0,60.001,258.002,0,0,0,0,3024284,1137812,383652,5971024,0,0,0,0,0,0
1560275181,0,0,99.749,0,0,60.000,257.998,0,0,0,0,60.000,257.998,0,0,0,0,3024284,1137812,383652,5971024,0,0,0,0,1.000,1.000
1560275182,0.250,0,100.002,0,0,60.001,258.006,0,0,0,0,60.001,258.006,0,0,0,0,3024284,1137812,383652,5971024,0,0,0,0,0,0
1560275183,0.250,0,99.999,0,0,59.999,257.997,0,0,0,0,59.999,257.997,0,0,0,0,3024284,1137812,383652,5971024,0,0,0,0,1.000,1.000
1560275184,0.250,0.250,99.501,0,0,60.001,258.004,0,0,0,0,60.001,258.004,0,0,0,0,3024284,1137812,383652,5971024,0,0,0,0,1.000,9.000
1560275185,0.750,0.250,98.497,0,0,59.998,257.991,0,0,0,0,59.998,257.991,0,463.984,0,92.997,3024220,1137876,383652,5971024,0,0,0,0,26.999,33.999
1560275186,0,0,99.750,0,0,60.000,257.999,0,0,0,0,60.000,257.999,0,0,0,0,3024220,1137876,383652,5971024,0,0,0,0,0,0
1560275187,0,0,100.004,0,0,60.002,258.009,0,0,0,0,60.002,258.009,0,0,0,0,3024220,1137876,383652,5971024,0,0,0,0,1.000,1.000
1560275188,0,0,100.000,0,0,60.000,257.999,0,0,0,0,60.000,257.999,0,0,0,0,3024220,1137876,383652,5971024,0,0,0,0,0,0
1560275189,0.250,0,99.751,0,0,60.001,258.002,0,0,0,0,60.001,258.002,0,0,0,0,3024220,1137876,383652,5971024,0,0,0,0,1.000,1.000
1560275190,0,0,99.996,0,0,59.997,257.989,0,0,0,0,59.997,257.989,0,0,0,0,3024220,1137876,383652,5971024,0,0,0,1.000,1.000,0
1560275191,0,0,99.501,0,0,60.001,258.003,0,0,0,0,60.001,258.003,0,4.000,0,1.000,3024252,1137844,383652,5971024,0,0,0,0,9.000,1.000
1560275192,0,0,99.992,0,0,59.995,257.980,0,0,0,0,59.995,257.980,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275193,0,0,100.008,0,0,60.005,258.021,0,0,0,0,60.005,258.021,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,1.000,1.000
1560275194,0.250,0,100.003,0,0,60.002,258.008,0,0,0,0,60.002,258.008,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275195,0,0,99.995,0,0,59.997,257.987,0,0,0,0,59.997,257.987,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275196,0,0,100.000,0,0,60.000,257.999,0,0,0,0,60.000,257.999,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,1.000,1.000
1560275197,0,0,99.502,0,0,60.001,258.005,0,0,0,0,60.001,258.005,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275198,0,0,100.001,0,0,60.000,258.002,0,0,0,0,60.000,258.002,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,1.000,1.000
1560275199,0.250,0,100.001,0,0,60.000,258.002,0,0,0,0,60.000,258.002,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,0,0
1560275200,0,0,99.749,0,0,59.999,257.997,0,0,0,0,59.999,257.997,0,0,0,0,3024252,1137844,383652,5971024,0,0,0,0,1.000,1.000

**Comment by yuokada126** [comment]
Hi @manasamanohar The fixed version is not released yet. It will be released as pcp-4.3.3 on Jun 28, 2019. (Fedora builds will follow a few days after that.) Please see https://github.com/performancecopilot/pcp/projects/1 for details on upstream release date.
