### ISSUE TITLE
python API: metric labels support

### ISSUE THREAD

**Issue by natoscott** [performancecopilot/pcp#655]

**Comment by goodwinos** [comment]
reminder to self: like pmLookupLabels, but for indom/instances. This also covers additions to LOGIMPORT(3) python functions to write labels to archives - needed for pmrep and other tools.

**Comment by goodwinos** [comment]
segfault issues and API updates completed, but pmrep changes to use the revamped API  moved to a later release

**Comment by goodwinos** [comment]
python API has been fixed and updated and labels reporting has been added to pmrep and related export tools (-m flag).
