### ISSUE TITLE
sar2pcp man page ought to acknowledge native pcp support within sar itself

### ISSUE THREAD

**Issue by stevekay** [performancecopilot/pcp#677]
sysstat [12.0.5 onwards](http://sebastien.godard.pagesperso-orange.fr/) features the means to read `sar` datafiles using `sadf` and produce pcp archive files, e.g.

    sadf -l -O pcparchive=foo sar.dat -- -A

Unsure whether there's a case for marking `sar2pcp` as *deprecated*, but I think it's worth acknowledging this native support somewhere within the `sar2pcp` [man page](https://github.com/performancecopilot/pcp/blob/master/man/man1/sar2pcp.1).

**Comment by lberk** [comment]
Thanks for mentioning this Steve!  Considering older sysstat versions are still being shipped in a variety of repos, I'd suggest it isn't quite time to mark sar2pcp(1) as _deprecated_ just yet.  Closing based on #678
