### ISSUE TITLE
pcp grafana and graphite - grafana and graphite do not show derived metrics

### ISSUE THREAD

**Issue by sogandshirinbab** [performancecopilot/pcp#695]
I followed all the steps in -> (https://groups.io/g/pcp/topic/2878731)
But grafana and graphite do not show my derived metrics.
PCP version : 3.11.3-1
export PCP_DERIVED_CONFIG=./pctavg
systemctl restart pmmgr pmie pmlogger pmcd  pmwebd
Is there any other step after these?

/Sogand

**Comment by fche** [comment]
An environment variable set that way will not generally propagate to the pcp service processes.
You could instead drop your derived-metrics spec in the directory that libpcp automatically scans; or you could arrange to set that env variable in the pmwebd process only, maybe by editing the .service file; or you can run your own copy of pmwebd under your own userid.

**Comment by sogandshirinbab** [comment]
I have added 
"PCP_DERIVED_CONFIG=$HOME/pctavg.conf
export PCP_DERIVED_CONFIG"
in "/etc/pcp/pmwebd/pmwebd.options"
and restart the service but still graphite and grafana don't show those metrics.

not sure how to do this:
"you can run your own copy of pmwebd under your own userid."
do you have any links/documents?

/Sogand

**Comment by fche** [comment]
If you can edit those options files, you could also deposit that .conf file straight under the `/var/lib/pcp/config/derived/` directory, and all the tools will pick it up there.

As to running pmwebd as an ordinary personal service:
`env PCP_DERIVED_CONFIG=/path/to/file /usr/libexec/pcp/bin/pmwebd -l pmwebd.log -R /usr/share/pcp/webapps -A /var/log/pcp -G -X -i 30 -J -v -M16 -p 9999`

**Comment by sogandshirinbab** [comment]
I moved the .conf file to "/var/lib/pcp/config/derived/" directory and it works now. Thank you!

**Comment by Manosankar** [comment]
Hi sogandshirinbab and fche,
It would be great and thankful if you can help me out this issue.

Me too facing same issue like not show derived metrics in pcp grafana 
PCP version -3.10.6-1.

I have followed below steps and pls let me know if any other steps are missed out
1)Added below lines in /etc/pcp/pmwebd/pmwebd.option file 
=================================================================
PCP_DERIVED_CONFIG=/var/lib/pcp/config/derived/cpu-util.conf
export PCP_DERIVED_CONFIG
=================================================================

cat cpu-util.conf file display below
# derived metrics for cpu utilization
kernel.cpu.util.user = (100 * rate(kernel.all.cpu.user)) / hinv.ncpu
kernel.cpu.util.nice = (100 * rate(kernel.all.cpu.nice)) / hinv.ncpu
kernel.cpu.util.sys = (100 * rate(kernel.all.cpu.sys)) / hinv.ncpu
kernel.cpu.util.idle = (100 * rate(kernel.all.cpu.idle)) / hinv.ncpu
kernel.cpu.util.intr = (100 * rate(kernel.all.cpu.intr)) / hinv.ncpu
kernel.cpu.util.wait = (100 * rate(kernel.all.cpu.wait.total)) / hinv.ncpu
kernel.cpu.util.steal = (100 * rate(kernel.all.cpu.steal)) / hinv.ncpu

In pcp 3.10.6  we dont have derived folder ,so i have create derived folder and then copy the content of pctavg to cpu-util.conf

and then restarted all services pmcd,pmlogger,pmwebd,pmie.

still pcp grafana not showing the metrics and i was struggling this issue around 2 weeks..

Is any steps i have to follow?

**Comment by natoscott** [comment]
In the new world order (i.e. modern Grafana and the grafana-pcp plugin) the pmseries language provides comparable functionality to derived metrics for historical data, and (interactive creation of) derived metrics is being added to the grafana-pcp Vector data source - this work can be tracked here:
https://github.com/performancecopilot/grafana-pcp/issues/13
