### ISSUE TITLE
pmwebapi - graphite emulation - please expose string/text data

### ISSUE THREAD

**Issue by screentan** [performancecopilot/pcp#70]
Grafana lets us build great dashboards against our pcp data, but it would very helpful to see which kernel version, OS version and other details in the dashboards.

**Comment by fche** [comment]
AFAIK grafana 1.9ish and the graphite data service doesn't support textual metrics at all.  Did you have an idea how this could be represented?  (At the pmwebapi level, textual metrics are passed fine, but grafana doesn't speak that api.)

**Comment by screentan** [comment]
I did more research on this and there are only two paths to getting pcp string data into grafana and both are outside of pcp.  One would be to add a plugin to grafana that understands pmwebd's native api.  The other is to add an input plugin to influxdb/telegraf that pulls pcp data.  We put a request in to the influxdb team for the later.
