### ISSUE TITLE
pcp2graphite fails with unicode from pmcd

### ISSUE THREAD

**Issue by screentan** [performancecopilot/pcp#747]
Using pcp-4.3.2-2 from centos & rhel, pcp2graphite is crashing when getting unicode from pmcd.

backtrace:
:pcp2graphite:439:write_graphite:TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
:
:Traceback (most recent call last):
:  File "/usr/bin/pcp2graphite", line 463, in <module>
:    P.execute()
:  File "/usr/bin/pcp2graphite", line 366, in execute
:    self.report(self.pmfg_ts())
:  File "/usr/bin/pcp2graphite", line 380, in report
:    self.write_graphite(tstamp)
:  File "/usr/bin/pcp2graphite", line 439, in write_graphite
:    msg = str.encode(message)
:TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
:
:Local variables in innermost frame:
:name: u'/dev/sdb1'
:timestamp: 'Tue Sep 17 21:54:02 2019'
:metric: u'pcp.amelia.disk.partitions.capacity._sda1'

**Comment by myllynen** [comment]
Thanks for the report. Could you try changing in /usr/bin/pcp2graphite line 437 from:

> msg = str.encode(message)

to

> msg = message.encode()

and see if this resolves the issue? Thanks.

**Comment by screentan** [comment]
Marko,

Yes, that fixed the error.

Thanks!
Peter
