### ISSUE TITLE
Makepkgs fails on 3.11.0 tag

### ISSUE THREAD

**Issue by rvernica** [performancecopilot/pcp#75]
I checked out the `3.11.0` tag and tried to build the `deb` packages. `Makepkgs` seems to be failing.

Here is what I did:
```
$ git checkout tags/3.11.0
$ ./Makepkgs --verbose
...
=== pcp ===
rm -rf  dep dep.bak *.[1-9].gz *.[1-9].bz2 *.[1-9].lzma *.[1-9].xz *.[1-9].tmp           
for d in `echo  `; do if test -d "$d" -a -f "$d/GNUmakefile"; then /bin/echo === $d ===; /usr/bin/make --no-print-directory -C $d clean || exit $?; fi; done
make[1]: Leaving directory `/home/debian/src/pcp-github/build/deb/pcp-3.11.0/src/python'
dh_installdocs
dh_installchangelogs
dh_link
dh_strip
dh_compress
dh_fixperms -X/tmp
dh_installdirs
dh_install --sourcedir=debian/pcp
cp: cannot stat `debian/pcp/usr/lib/pcp/bin/install-sh': No such file or directory
dh_install: cp -a debian/pcp/usr/lib/pcp/bin/install-sh debian/libpcp3-dev//usr/lib/pcp/bin/ returned exit code 1
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```
A bit more about my system:
```
$ cat /etc/issue
Debian GNU/Linux 7
$ uname -a
Linux beaglebone-01 3.8.13-bone56 #1 SMP Wed Jun 4 23:59:23 UTC 2014 armv7l GNU/Linux
```

**Comment by natoscott** [comment]
Hmm, works for me.  This file (install-sh) should be placed in debian/pcp/usr/lib/pcp/bin/install-sh by line ~112 of the top-level GNUmakefile in git (via the install_pcp make target).

**Comment by kmcdonell** [comment]
Works for me also on Debian 8.

But my install-sh gets put here ...
$ find * -name install-sh
build/deb/pcp-3.11.0/install-sh
build/deb/pcp-3.11.0/debian/libpcp3-dev/usr/lib/pcp/bin/install-sh
install-sh

Rares, any chance you can send us  this file:
build/deb/pcp-3.11.0/config.status

**Comment by rvernica** [comment]
See attached. (Added the `.TXT` extension for GitHub to accept it.) Thanks!
[config.status.TXT](https://github.com/performancecopilot/pcp/files/141714/config.status.TXT)

**Comment by kmcdonell** [comment]
OK ... despite your system being Debian, you have a /usr/bin/rpm and /usr/bin/rpmbuild ... the latter is confusing the hell out of Makepkgs and you're running a part-Debian and part-RPM schizo build.  To test my theory, could you please (a) mv /usr/bin/rpmbuild aside temporarily, or (b) edit Makepkgs and change this line:
if [ -x /usr/bin/rpmbuild ]
to:
if [ -x /usr/bin/rpmbuild_foobar ]

And then try Makepgks again?

**Comment by rvernica** [comment]
Your theory is correct. I got rid of `/usr/bin/rpmbuild`. Now `Makepkgs` completes successfully. Thanks for looking into this!

**Comment by kmcdonell** [comment]
I've checked in a change to Makepkgs that will hopefully prevent this issue in the future, should we come across another build system with a similar installation setup.
