### ISSUE TITLE
Monitor docker containers

### ISSUE THREAD

**Issue by panda87** [performancecopilot/pcp#76]
Hi

I have machine with many docker containers on.
How can I use Vector (which pcp already installed on that machine) to filter to see metrics only from one specific container?

Thanks

**Comment by natoscott** [comment]
@panda87 this github issue is more directed toward the Vector project than PCP - please check the open issues there, as there has been folks working on it.  All necessary PCP support is in place in current releases of PCP, so I'll close this github issue.

**Comment by panda87** [comment]
@natoscott, sorry, I meant how can I monitor docker containers stats in case I have multiple docker containers on one machine?

**Comment by natoscott** [comment]
@panda87 http://pcp.io/docs/lab.containers.html describes the PCP mechanism.
