### ISSUE TITLE
./Install PMDAs when installing them with a package manager

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#765]
Currently users need to run `./Install` after installing PMDAs via a package manager, which is unexpected from a users point of view.

Can we run `./Install` in the rpm/deb install step? Or add `.NeedInstall` to every PMDA rpm/deb and restart `pmcd`?

**Comment by natoscott** [comment]
For a variety of reasons this is not viable in general (in particular, plenty of users choose to install *all* PMDA packages for whatever reason) - individual, new PMDAs might choose to be auto-enabled though if they provide a generally useful source of metrics for everyone that we should always expect to be enabled once installed.  And assuming they don't need configuration, which many do - it's often a complex situation unfortunately.
