### ISSUE TITLE
pcp2graphite - pcmd hostname in prefix under pmmgr

### ISSUE THREAD

**Issue by screentan** [performancecopilot/pcp#78]
Now that pcp2graphite is supported under pmmgr we would like to use it to put data directly into graphite or graphite compatible data store.  The prefix defaults to "pcp." and though it can be changed via "-m", there does not appear to be a way to automatically change it while using pmmgr.  So 100 instances of pcp2graphite would dump the data under "pcp." instead of "pcp.host.".  Assuming I didn't miss something I would like to see a change in the way the prefix is handled.

The default should be "pcp." as it is currently.  I'm reqeusting that If the "-h <hostname>" option is used then the prefix should be "pcp.<hostname>.".  Another option would be to have some kind of variable expansion within the pmmgr configuration files.

**Comment by fche** [comment]
This could be accomplished with a small auxiliary shell script invoked by /etc/pcp/pmmgr/monitor 

#! /bin/sh
# assume pmmgr invocation as -h $HOSTSPEC
host="$2"
graphitehost=`pmprobe -v -h "$host" pmcd.hostname | awk '{print $3}' `  # or something like that
exec pcp2graphite [...options...] -m "pcp.$graphitehost" -h "$host"

**Comment by natoscott** [comment]
Sounds like that approach is feasible for you @screentan based on lack of followups?  I'll close the issue, please re-open as necessary.
