### ISSUE TITLE
bintray docker images gone

### ISSUE THREAD

**Issue by lukelast** [performancecopilot/pcp#787]
I can no longer find the pcp-collector or pcp-pmwebd docker images on bintray.

```
$ docker pull pcp-docker-containers.bintray.io/pcp-collector
Error response from daemon: unknown: Repo 'containers' was not found
```

**Comment by natoscott** [comment]
These containers have been removed to make way for modern PCP containers.  The previous set had not been updated for years - pmwebd had been deprecated for some time and was retired completely in pcp v5.

We'll provide a new set soon, still based on the latest Fedora PCP and related package builds.  Currently its likely to be: a single base PCP container (including both pmcd and REST APIs), a Grafana container with grafana-pcp (including the new Vector), and a Redis container to complete the set.

If anyone ( @lukelast ? ) would like to help with this effort, please let me know.

**Comment by lukelast** [comment]
What can I help with?

**Comment by natoscott** [comment]
@lukelast are you on slack?  Several recent discussion threads going on there, joining us there might be best way to get involved with the effort.
