### ISSUE TITLE
pcp-webapi-4.3.4-1.x86_64 is obsoleted 

### ISSUE THREAD

**Issue by 307105141** [performancecopilot/pcp#791]
I'd like to ask you how the PCP version is 5 and how the web interface calls for display.  
安装webapi时候报错，如下:
Error is reported when installing webapi, as follows:  
Package pcp-webapi-4.3.4-1.x86_64 is obsoleted by pcp-5.0.1-1.x86_64 which is already installed

**Comment by natoscott** [comment]
The contents of the old 'pcp-webapi' rpm has been replaced by the 'pcp' rpm itself, which now provides REST API services via pmproxy(1).

See also https://github.com/performancecopilot/grafana-pcp - the 'grafana-pcp' rpm obsoletes 'pcp-webapp-grafana' and 'pcp-webapp-vector'.

**Comment by 307105141** [comment]
'pcp-webapp-grafana' and 'pcp-webapp-vector'.Both packages are installed, and the page can also be opened. But I don't know how to call pmcd interface. 
Is the new version without vertor.

**Comment by 307105141** [comment]
vector

**Comment by natoscott** [comment]
I'm not 100% sure what you're asking there but as I mentioned previously, those two packages are obsolete, unmaintained and no longer shipped with PCP.  Vector is now part of the grafana-pcp package where it is a Grafana datasource, not a standalone app.

There's further discussion of these topics in the PCP man pages pcpcompat(1) and pmwebapi(3).

**Comment by 307105141** [comment]
ok,tks
