### ISSUE TITLE
grafana-pcp configure datasources Report errors 

### ISSUE THREAD

**Issue by 307105141** [performancecopilot/pcp#793]
Error: ace is not defined Evaluating http://localhost:3000/public/plugins/performancecopilot-pcp-app/datasources/bpftrace/module.js Loading plugins/performancecopilot-pcp-app/datasources/bpftrace/module

**Comment by natoscott** [comment]
@307105141 could you open this issue in the grafana-pcp repo -

    https://github.com/performancecopilot/grafana-pcp/issues

I think this is a known issue relating to the version of Grafana you're using, but lets discuss it in the correct project.  Thanks.

**Comment by natoscott** [comment]
Actually, its definitely this issue:

    https://github.com/performancecopilot/grafana-pcp/issues/16

So, don't worry about opening a new issue, please just contribute to that existing one.

**Comment by 307105141** [comment]
After adding redis, an error is reported: 
Error: Bad Gateway .
Where can I find out how to configure it.

**Comment by 307105141** [comment]
When configuring a data source, an error is reported: 
Error: Bad Gateway 
I can help you with the configuration.

**Comment by ranicete** [comment]
Hi, i'm seeing this issue on my system. please see error msg below.  

Im using the following version:
grafana pcp v1.0.7
grafana Version 6.6.1 
pmcd: Version 4.3.1-1
Redis version=5.0.3


ace is not defined Evaluating http://10.100.168.161:3000/public/plugins/performancecopilot-pcp-app/datasources/bpftrace/module.js Loading plugins/performancecopilot-pcp-app/datasources/bpftrace/module

**Comment by ranicete** [comment]
> Hi, i'm seeing this issue on my system. please see error msg below.
> 
> Im using the following version:
> grafana pcp v1.0.7
> grafana Version 6.6.1
> pmcd: Version 4.3.1-1
> Redis version=5.0.3
> 
> ace is not defined Evaluating http://10.100.168.161:3000/public/plugins/performancecopilot-pcp-app/datasources/bpftrace/module.js Loading plugins/performancecopilot-pcp-app/datasources/bpftrace/module

i also update grafana pcp to 2.0.0 and i see the same issue

**Comment by natoscott** [comment]
> > Hi, i'm seeing this issue on my system. please see error msg below.
> > pmcd: Version 4.3.1-1

You'll want to be using pcp-5.0.2 or later.

**Comment by andreasgerstmayr** [comment]
Did you try grafana-pcp 2.0.0-beta1 from https://github.com/performancecopilot/grafana-pcp/archive/v2.0.0-beta1.zip? This version resolves the issue `ace is not defined`. After placing the files into `/var/lib/grafana/plugins` and restarting grafana-server it should work.

**Comment by ranicete** [comment]
Thank you very much for your quick response.  i loaded grafana pcp 5.0.1-1 and using grafana 6.3.6.  This seems to fix the original issue.However, when i try to add data source, i'm getting bad gateway error.  I check the pm proxy and the pmproxy is not getting Active.  I tried re-start, force load but it does not help.  
● pmproxy.service - Proxy for Performance Metrics Collector Daemon   Loaded: loaded (/lib/systemd/system/pmproxy.service; enabled; vendor preset: enabled)   Active: failed (Result: resources) since Thu 2020-02-13 21:47:04 PST; 9min ago     Docs: man:pmproxy(8)ranicete@sv-debian-02:~$ systemctl status pmproxy● pmproxy.service - Proxy for Performance Metrics Collector Daemon   Loaded: loaded (/lib/systemd/system/pmproxy.service; enabled; vendor preset: enabled)   Active: failed (Result: resources) since Thu 2020-02-13 21:47:04 PST; 10min ago     Docs: man:pmproxy(8)

Rodel Anicete 

    On Thursday, February 13, 2020, 12:57:44 PM PST, Andreas Gerstmayr <notifications@github.com> wrote:  
 
 
Did you try grafana-pcp 2.0.0-beta1 from https://github.com/performancecopilot/grafana-pcp/archive/v2.0.0-beta1.zip? This version resolves the issue ace is not defined. After placing the files into /var/lib/grafana/plugins and restarting grafana-server it should work.

**Comment by ranicete** [comment]
> Thank you very much for your quick response.  i loaded grafana pcp 5.0.1-1 and using grafana 6.3.6.  This seems to fix the original issue.However, when i try to add data source, i'm getting bad gateway error.  I check the pm proxy and the pmproxy is not getting Active.  I tried re-start, force load but it does not help.   ● pmproxy.service - Proxy for Performance Metrics Collector Daemon   Loaded: loaded (/lib/systemd/system/pmproxy.service; enabled; vendor preset: enabled)   Active: failed (Result: resources) since Thu 2020-02-13 21:47:04 PST; 9min ago     Docs: man:pmproxy(8)ranicete@sv-debian-02:~$ systemctl status pmproxy● pmproxy.service - Proxy for Performance Metrics Collector Daemon   Loaded: loaded (/lib/systemd/system/pmproxy.service; enabled; vendor preset: enabled)   Active: failed (Result: resources) since Thu 2020-02-13 21:47:04 PST; 10min ago     Docs: man:pmproxy(8) Rodel Anicete On Thursday, February 13, 2020, 12:57:44 PM PST, Andreas Gerstmayr <notifications@github.com> wrote: Did you try grafana-pcp 2.0.0-beta1 from https://github.com/performancecopilot/grafana-pcp/archive/v2.0.0-beta1.zip? This version resolves the issue ace is not defined. After placing the files into /var/lib/grafana/plugins and restarting grafana-server it should work. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Just a quick update:
Re-installed everything.  Using latest 
Grafana-pcp 2.0 beta, 5.0.2 PCP, latest redis and grafana-server.  Im still getting the gateway error when adding the data source.  url is http:/localhost:44322.  Are there any other configuration i need to make in pmproxy and redis?  thanks.

**Comment by goodwinos** [comment]
It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.

Can you post each of the following (as a quoted message so the lines don't all get joined together):

```
systemctl status pmproxy.service
journalctl -xe -u pmproxy.service
cat /var/log/pcp/pmproxy/pmproxy.log
```

Thanks

**Comment by ranicete** [comment]
> It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.
> 
> Can you post each of the following (as a quoted message so the lines don't all get joined together):
> 
> ```
> systemctl status pmproxy.service
> journalctl -xe -u pmproxy.service
> cat /var/log/pcp/pmproxy/pmproxy.log
> ```
> 
> Thanks

Thanks again.  From the log is can see pmproxy: disabled time series, requires libuv support (missing).

**Comment by ranicete** [comment]
> > It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.
> > Can you post each of the following (as a quoted message so the lines don't all get joined together):
> > ```
> > systemctl status pmproxy.service
> > journalctl -xe -u pmproxy.service
> > cat /var/log/pcp/pmproxy/pmproxy.log
> > ```
> > 
> > 
> > Thanks
> 
> Thanks again. From the log is can see pmproxy: disabled time series, requires libuv support (missing).

# systemctl status pmproxy.service
● pmproxy.service - Proxy for Performance Metrics Collector Daemon
   Loaded: loaded (/lib/systemd/system/pmproxy.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-02-14 22:33:21 PST; 12h ago
     Docs: man:pmproxy(8)
  Process: 24889 ExecStop=/usr/share/pcp/lib/pmproxy stop (code=exited, status=0/SUCCESS)
  Process: 24930 ExecStart=/usr/share/pcp/lib/pmproxy start (code=exited, status=0/SUCCESS)
 Main PID: 24974 (pmproxy)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pmproxy.service
           └─24974 /usr/libexec/pcp/bin/pmproxy

Feb 14 22:33:21 sv-debian-02 systemd[1]: Starting Proxy for Performance Metrics Collector Daemon...
Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.

**Comment by ranicete** [comment]
> > > It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.
> > > Can you post each of the following (as a quoted message so the lines don't all get joined together):
> > > ```
> > > systemctl status pmproxy.service
> > > journalctl -xe -u pmproxy.service
> > > cat /var/log/pcp/pmproxy/pmproxy.log
> > > ```
> > > 
> > > 
> > > Thanks
> > 
> > 
> > Thanks again. From the log is can see pmproxy: disabled time series, requires libuv support (missing).
> 
> # systemctl status pmproxy.service
> ● pmproxy.service - Proxy for Performance Metrics Collector Daemon
> Loaded: loaded (/lib/systemd/system/pmproxy.service; disabled; vendor preset: enabled)
> Active: active (running) since Fri 2020-02-14 22:33:21 PST; 12h ago
> Docs: man:pmproxy(8)
> Process: 24889 ExecStop=/usr/share/pcp/lib/pmproxy stop (code=exited, status=0/SUCCESS)
> Process: 24930 ExecStart=/usr/share/pcp/lib/pmproxy start (code=exited, status=0/SUCCESS)
> Main PID: 24974 (pmproxy)
> Tasks: 1 (limit: 4915)
> CGroup: /system.slice/pmproxy.service
> └─24974 /usr/libexec/pcp/bin/pmproxy
> 
> Feb 14 22:33:21 sv-debian-02 systemd[1]: Starting Proxy for Performance Metrics Collector Daemon...
> Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
> Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.

-- Unit pmproxy.service has begun starting up.
Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.
-- Subject: Unit pmproxy.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support"""

**Comment by ranicete** [comment]
> > > > It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.
> > > > Can you post each of the following (as a quoted message so the lines don't all get joined together):
> > > > ```
> > > > systemctl status pmproxy.service
> > > > journalctl -xe -u pmproxy.service
> > > > cat /var/log/pcp/pmproxy/pmproxy.log
> > > > ```
> > > > 
> > > > 
> > > > Thanks
> > > 
> > > 
> > > Thanks again. From the log is can see pmproxy: disabled time series, requires libuv support (missing).
> > 
> > 
> > # systemctl status pmproxy.service
> > ● pmproxy.service - Proxy for Performance Metrics Collector Daemon
> > Loaded: loaded (/lib/systemd/system/pmproxy.service; disabled; vendor preset: enabled)
> > Active: active (running) since Fri 2020-02-14 22:33:21 PST; 12h ago
> > Docs: man:pmproxy(8)
> > Process: 24889 ExecStop=/usr/share/pcp/lib/pmproxy stop (code=exited, status=0/SUCCESS)
> > Process: 24930 ExecStart=/usr/share/pcp/lib/pmproxy start (code=exited, status=0/SUCCESS)
> > Main PID: 24974 (pmproxy)
> > Tasks: 1 (limit: 4915)
> > CGroup: /system.slice/pmproxy.service
> > └─24974 /usr/libexec/pcp/bin/pmproxy
> > Feb 14 22:33:21 sv-debian-02 systemd[1]: Starting Proxy for Performance Metrics Collector Daemon...
> > Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
> > Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.
> 
> -- Unit pmproxy.service has begun starting up.
> Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
> Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.
> -- Subject: Unit pmproxy.service has finished start-up
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support"""

Log for pmproxy on sv-debian-02 started Fri Feb 14 22:33:21 2020

pmproxy: PID = 24974, PDU version = 2, user = pcp (999)
pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     0 44322 inet   INADDR_ANY
  ok     3 44322 ipv6   INADDR_ANY"""

**Comment by ranicete** [comment]
> > > > It looks like the pmproxy service is enabled and started, but failed. If it's not listening on localhost port 44322 (as configured in the datasource URL field), then that would cause the bad gateway errors.
> > > > Can you post each of the following (as a quoted message so the lines don't all get joined together):
> > > > ```
> > > > systemctl status pmproxy.service
> > > > journalctl -xe -u pmproxy.service
> > > > cat /var/log/pcp/pmproxy/pmproxy.log
> > > > ```
> > > > 
> > > > 
> > > > Thanks
> > > 
> > > 
> > > Thanks again. From the log is can see pmproxy: disabled time series, requires libuv support (missing).
> > 
> > 
> > # systemctl status pmproxy.service
> > ● pmproxy.service - Proxy for Performance Metrics Collector Daemon
> > Loaded: loaded (/lib/systemd/system/pmproxy.service; disabled; vendor preset: enabled)
> > Active: active (running) since Fri 2020-02-14 22:33:21 PST; 12h ago
> > Docs: man:pmproxy(8)
> > Process: 24889 ExecStop=/usr/share/pcp/lib/pmproxy stop (code=exited, status=0/SUCCESS)
> > Process: 24930 ExecStart=/usr/share/pcp/lib/pmproxy start (code=exited, status=0/SUCCESS)
> > Main PID: 24974 (pmproxy)
> > Tasks: 1 (limit: 4915)
> > CGroup: /system.slice/pmproxy.service
> > └─24974 /usr/libexec/pcp/bin/pmproxy
> > Feb 14 22:33:21 sv-debian-02 systemd[1]: Starting Proxy for Performance Metrics Collector Daemon...
> > Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
> > Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.
> 
> -- Unit pmproxy.service has begun starting up.
> Feb 14 22:33:21 sv-debian-02 pmproxy[24930]: Starting pmproxy ... pmproxy: disabled time series, requires libuv support (missing)
> Feb 14 22:33:21 sv-debian-02 systemd[1]: Started Proxy for Performance Metrics Collector Daemon.
> -- Subject: Unit pmproxy.service has finished start-up
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support"""

Hi guys.  Thanks again for your help.  I was able to resolved the issue.  I build libuv from the source and rebuilt pcp-5.0.2.  Restarted everything and this time i'm able to get redis data source/dashboard to work. The other dashboards are not working yet but this is a good start.  thanks again.

**Comment by andreasgerstmayr** [comment]
Ah, looks like the pcp build for 5.0.2 was built without libuv support, sorry for that :|
Are you using the bintray builds or the version in the debian repositories?

For debian buster we have a nightly repository containing snapshot builds from the latest pcp version from master (and built with libuv support): https://bintray.com/pcp/buster-nightly/pcp
I can also add a repository for debian bullseye.

> The other dashboards are not working yet but this is a good start. thanks again.
Can you double-check if you use the same datasource settings (pmproxy URL) for the redis and vector datasources? If redis works, Vector should also work (it's less complex than the redis one as it doesn't depend on redis and pmlogger, only pmproxy & pmcd).

**Comment by ranicete** [comment]
Thanks.  Vector works fine.
Rodel Anicete 

    On Sunday, February 16, 2020, 01:12:20 PM PST, Andreas Gerstmayr <notifications@github.com> wrote:  
 
 
Ah, looks like the pcp build for 5.0.2 was built without libuv support, sorry for that :|
Are you using the bintray builds or the version in the debian repositories?

For debian buster we have a nightly repository containing snapshot builds from the latest pcp version from master (and built with libuv support): https://bintray.com/pcp/buster-nightly/pcp
I can also add a repository for debian bullseye.


The other dashboards are not working yet but this is a good start. thanks again.
Can you double-check if you use the same datasource settings (pmproxy URL) for the redis and vector datasources? If redis works, Vector should also work (it's less complex than the redis one as it doesn't depend on redis and pmlogger, only pmproxy & pmcd).

**Comment by andreasgerstmayr** [comment]
@ranicete: did you compile PCP by source previously?

**Comment by ranicete** [comment]
Yes I did. I got the source from github. 

Please excuse any typos.  Sent from my iPhone

**Comment by andreasgerstmayr** [comment]
Ok, thanks for clarification!
