### ISSUE TITLE
Fix pmFreeLabelSets segv in pmDiscoverPurgeDeleted()

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#800]
The labelsets data structure created by libpcp_web discovery segfaults when free'd by pmFreeLabelSets(). See TODO near line 181 in src/libpcp_web/src/discover.c

This labelsets data structure is built by pmDiscoverDecodeMetaLabelSet() by reading the PCP metadata file directly off disk.

**Comment by natoscott** [comment]
@goodwinos as discussed, test 1661 no longer seems to reproduce this - I've added some code cleanups to libpcp_web that may help (see commit a9495cb06) or perhaps some other fix has resolved this as a side-effect.  Closing for now, lemme know if it re-appears.
