### ISSUE TITLE
Memory leak in pmproxy when re-using connection

### ISSUE THREAD

**Issue by nickoakman** [performancecopilot/pcp#801]
I noticed pmproxy memory usage was growing steadily when repeatedly fetching data, and it isn't going back down.  The issue seems to be with the dictionaries created for keeping track of the http headers and parameters.  They are freed when the connection closes, however, if you keep the connection open, each request causes client->u.http.headers and client->u.http.parameters to be overwritten with a new dictionary.  Here's some relevant data from a valgrind test:

`==22175== 3,157,011 (314,496 direct, 2,842,515 indirect) bytes in 3,276 blocks are definitely lost in loss record 120 of 121
==22175==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22175==    by 0x4E63EAD: zmalloc (util.c:72)
==22175==    by 0x4E6E202: dictCreate (dict.c:108)
==22175==    by 0x113242: http_parameters (http.c:450)
==22175==    by 0x113467: http_url_decode (http.c:502)
==22175==    by 0x113501: servlet_lookup (http.c:521)
==22175==    by 0x1135D4: on_url (http.c:540)
==22175==    by 0x4E488B9: http_parser_execute (http_parser.c:1037)
==22175==    by 0x113EDC: on_http_client_read (http.c:755)
==22175==    by 0x110CEE: on_protocol_read (server.c:329)
==22175==    by 0x110E2B: on_client_read (server.c:353)
==22175==    by 0x58025CE: ??? (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==22175== 
==22175== 4,718,623 (314,496 direct, 4,404,127 indirect) bytes in 3,276 blocks are definitely lost in loss record 121 of 121
==22175==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22175==    by 0x4E63EAD: zmalloc (util.c:72)
==22175==    by 0x4E6E202: dictCreate (dict.c:108)
==22175==    by 0x113616: on_url (http.c:543)
==22175==    by 0x4E488B9: http_parser_execute (http_parser.c:1037)
==22175==    by 0x113EDC: on_http_client_read (http.c:755)
==22175==    by 0x110CEE: on_protocol_read (server.c:329)
==22175==    by 0x110E2B: on_client_read (server.c:353)
==22175==    by 0x58025CE: ??? (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==22175==    by 0x580333B: ??? (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==22175==    by 0x580833F: uv__io_poll (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)
==22175==    by 0x57F8CC7: uv_run (in /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0)`

**Comment by natoscott** [comment]
Thanks @nickoakman - I have been looking into this recently and several memory leak fixes will arrive this week.
