### ISSUE TITLE
pmproxy: High ram usage

### ISSUE THREAD

**Issue by jazbina** [performancecopilot/pcp#810]
I have high ram usage by pmproxy on Debian bullseye.

Ram usage slowly raises to cca 50%. I have 8GB of ram.

`top -u pcp`
`  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                   `
`1694 pcp       20   0 4335904   4.1g   3056 S   0.0  55.3   0:30.46 pmproxy `

What can I do ?

**Comment by natoscott** [comment]
> [...]
> What can I do ?

Upgrading to pcp-5.0.2 is your best option.
