### ISSUE TITLE
pmrep is using BrokenPipeError which is not available in Python 2

### ISSUE THREAD

**Issue by happz** [performancecopilot/pcp#82]
Test case 880 failed for me with the following traceback:

--- /var/lib/pcp/testsuite/880.out	2016-03-16 08:18:27.000000000 -0400
+++ /var/lib/pcp/testsuite/880.out.bad	2016-03-16 10:32:05.774197932 -0400
@@ -1,2 +1,14 @@
 QA output created by 880
 expect no broken pipe exceptions or Exception Ignored errors
+Traceback (most recent call last):
+  File "/usr/bin/pmrep", line 1371, in <module>
+    P.finalize()
+  File "/usr/bin/pmrep", line 1351, in finalize
+    except BrokenPipeError:
+NameError: global name 'BrokenPipeError' is not defined
+Traceback (most recent call last):
+  File "/usr/bin/pmrep", line 1371, in <module>
+    P.finalize()
+  File "/usr/bin/pmrep", line 1351, in finalize
+    except BrokenPipeError:
+NameError: global name 'BrokenPipeError' is not defined

BrokenPipeError was added in Python 3.3, and this was ran with Python 2.7. I guess catching IOError and checking whether its errno == errno.EPIPE might work for Python 2.

**Comment by natoscott** [comment]
Marko's fix for this is in the master branch now.
