### ISSUE TITLE
bintray RPM pmproxy is broken (missing libuv)

### ISSUE THREAD

**Issue by pphysch** [performancecopilot/pcp#820]
CentOS 7, kernel version 3.10.0-1062.4.1.el7.x86_64

### Problem

I downloaded PCP v5.0.2 RPMs from https://bintray.com/pcp/el7/pcp and found that the new and improved pmproxy is not working:

```
$> sudo /usr/libexec/pcp/bin/pmproxy -f -l- -Dhttp
pmproxy: disabled time series, requires libuv support (missing)
Log for pmproxy on <hostname> started Mon Jan 13 16:52:54 2020

pmproxy: PID = 24688, PDU version = 2, user = pcp (0)
pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     3 44322 inet   INADDR_ANY
  ok     4 44322 ipv6   INADDR_ANY
```

Even though it should adapt to the "deprecated" mode, I still get "connection reset" errors when trying to connect on 44322.

### Partial Fix

I built and installed 5.0.2 RPMs from source, with libuv present, and got pmproxy to successfully serve metrics over HTTP. However, the pmproxy daemon was crashing immediately in systemd, though I was able to run it directly with the same command as above.

Can the official el7 RPM get rebuilt with libuv support? Thanks.

**Comment by andreasgerstmayr** [comment]
I've added RHEL 7 to our CI/CD Pipeline now, here's the first build of the current master: https://dev.azure.com/performancecopilot/pcp/_build/results?buildId=487&view=artifacts&type=publishedArtifacts

libuv-devel is not in the main repositories for el7, therefore I've built it with libuv from EPEL. Unfortunately libuv needs a matching libuv runtime installed on the system, so now we have a dependency on EPEL, which is an issue. Should we integrate libuv-static instead @natoscott @goodwinos?

**Comment by natoscott** [comment]
@andreasgerstmayr if its easy to do, sure lets try libuv-static instead, but I wouldn't worry too much about it if EPEL is required for older RHEL versions.

**Comment by pphysch** [comment]
@andreasgerstmayr Is this still WIP? I tried installing the latest rhel7 build you linked but have the same error:

```
$> sudo /usr/libexec/pcp/bin/pmproxy -f -t -l- -Dhttp
pmproxy: disabled time series, requires libuv support (missing)
...
```

**Comment by andreasgerstmayr** [comment]
@pphysch: Sorry, there was an error with the build I linked. Can you please try again, with the new build for RHEL 7 with the dependency on libuv from EPEL: https://dev.azure.com/performancecopilot/pcp/_build/results?buildId=520&view=artifacts&type=publishedArtifacts and report if it works. Thanks!

**Comment by pphysch** [comment]
@andreasgerstmayr Thank you, works like a charm!

**Comment by andreasgerstmayr** [comment]
Great, thanks!
Btw, few days back I've setup a el7-nightly repository on bintray: https://bintray.com/beta/#/pcp/el7-nightly/pcp?tab=overview containing the latest builds from master.

Also, the next PCP version (5.0.3) for el7 will be published with libuv support on bintray.

**Comment by pphysch** [comment]
@andreasgerstmayr Great to hear. At this time, is the pcp bintray a temporary or long-term repo for pcp packages?

**Comment by andreasgerstmayr** [comment]
It's a long-term repo for upstream PCP releases.
