### ISSUE TITLE
Package for Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by zokier** [performancecopilot/pcp#84]
There are Bintray packages for older Ubuntu versions, but not for the upcoming new 16.04. Because Xenial includes only Python 3 in default install, now would be a good time to make the packages fully Python 3 based/compatible to reduce dependencies, especially as per my understanding PCP itself is already Python 3 compatible.

The final release of 16.04 is scheduled to happen April 21st.

**Comment by zokier** [comment]
I made the Ubuntu package Python3 based, here is the diff: https://github.com/performancecopilot/pcp/compare/master...zokier:xenial . Note that I haven't tested the package very thoroughly, but it seems to work fine for me.

I noticed that the package is built with `--without-systemd`. Now that both Debian and Ubuntu are systemd based, it probably would be a good idea to change that? I'm not sure what is needed to systemdify the package otherwise.

**Comment by natoscott** [comment]
@zokier thanks for the info & patch!

The patch takes the approach of removing the python2 support - could you change it to support both python2 and python3 side-by-side?  (IOW, build depend on both, and generate both a python-pcp and a python3-pcp deb package)

I'll attempt to get a 16.04 bintray build in place for the next PCP release (http://pcp.io/roadmap - timing looks good from the dates you gave).

**Comment by natoscott** [comment]
@zokier oh, regarding systemd:

> I noticed that the package is built with --without-systemd.

This is fairly well tested on Fedora and RHEL7 now.  For Debian builds, it's a matter of enabling that build option, updating the debian packaging (like you did for python3) and testing the resulting debs.

cheers.

**Comment by natoscott** [comment]
(Merged modified support for py2 & py3 side-by-side.)
