### ISSUE TITLE
cgroup.memory.limit returning incorrect value?

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#85]
While doing some testing I noticed this metric is returning the max value of 64-bit unsigned integer.

<img width="494" alt="screen shot 2016-04-13 at 5 17 55 pm" src="https://cloud.githubusercontent.com/assets/3950207/14513440/bb308f4a-019c-11e6-8751-a681bab754d1.png">

Tested on a VM with 2GB of ram and a bare metal with 256GB of ram.
Saw this in Version 3.10.9-1 and 3.11.0

**Comment by natoscott** [comment]
Hi Henry,

This value is extracted directly the kernel via /sys/fs/cgroup/memory/[...]memory.limit_in_bytes ... do you see different values in those files?

**Comment by hc000** [comment]
Hi Nathan,

It does indeed show match the value.

root@slave2:/sys/fs/cgroup/memory/docker/f4a901378ba4ef619091a4ee9c71607eeb81e25ec75bdd66184e147471d95dfe# cat memory.limit_in_bytes && cat memory.usage_in_bytes 
18446744073709551615
29466624

Memory usage in bytes seems to be correct but not memory limit.
