### ISSUE TITLE
Kubuntu 19.10: Unable to install

### ISSUE THREAD

**Issue by TriMoon** [performancecopilot/pcp#852]
I'm unable to install on Kubuntu 19.10...
pcp version 4.3.4-1build1

Tried to install using:
- `sudo apt install cockpit-pcp pcp-gui libpcp-import-perl pcp-doc xvfb`
But it failed with some error so afterwards i cleaned-up using:
- `sudo apt purge --autoremove cockpit-pcp pcp-gui libpcp-import-perl pcp-doc xvfb; sudo rm -vR /var/lib/pcp /var/log/pcp`

```console
> neofetch --stdout
OS: Ubuntu 19.10 x86_64 
Model: Manual build Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2017-08-10 AMI Ver:3801 
Kernel: 5.3.0-40-generic 
Uptime: 14 hours, 30 mins 
Packages: 2775 (dpkg), 9 (snap) 
Shell: zsh 5.7.1 
Resolution: 1680x1050 @ 59.88Hz, 2560x1080 @ 60.00Hz 
DE: KDE 
WM: KWin 
Theme: Breeze [KDE], Adapta-Nokto [GTK2], Default [GTK3] 
Icons: breeze [KDE], breeze [GTK2/3] 
Terminal: konsole 
Terminal Font: Hack 16 
Font: [KDE], Noto Sans, 10 [GTK2/3] 
Locale: en_US.UTF-8 
Memory: 4241MiB / 32026MiB (13%) [37m[-==============[37m] 
CPU: Intel i7-5820K (12) @ 4.0GHz [44.0°C] 
GPU: NVIDIA GeForce GTX 1080 Ti 
GPU Driver: NVIDIA 430.50 
CPU Usage: 4% 
Disk (/): 18G / 146G (13%) 
Disk (home): 27G / 63G (45%) 
Disk (efi): 89M / 511M (18%) 
Disk (efi-other): 5.4M / 549M (1%) 
Disk (Data): 551G / 3.5T (17%) 
Local IP: 192.168.0.2 
```

**Comment by natoscott** [comment]
@TriMoon this appears to be a failure to install from the Kubuntu packages (pcp-4.3.4-1build1), not a bug in the upstream PCP - please report it to the Kubuntu folk as only they can fix it.  They will want to know the exact error messages from the failure (missing from your report here).

Latest upstream PCP version will also be pcp-5.0.3 later this week - they may find the issue resolved (whatever it is) on upgrading.
