### ISSUE TITLE
Support for PCP on QNX OS and PPC processor 

### ISSUE THREAD

**Issue by rduttainfinera** [performancecopilot/pcp#878]
1. Has PCP ever been tried on QNX, I found that it has compilation support for QNX OS platform ?
2. Is PCP supported on Power PC processors family ?
3. PCP needs libuv1 library at runtime, which is available for Linux platforms. Has it ever been tried on QNX OS.

**Comment by natoscott** [comment]
@rduttainfinera I'm not aware of anyone running PCP on QNX, although I've been in discussions from time to time with folk running PCP on embedded systems (possibly QNX, not sure).  If you have issues building it, please post the failures here and we'll work through them with you.

PCP works well on Power PC - its a supported architecture in RHEL and Fedora.

Regarding libuv, I'm not sure if its been built/used on QNX - this is an optional component though, not mandatory to get most of PCP working.  Without it, the build will lack pmseries and REST API support - but this you may want to run on a remote host anyway, with just the pmcd service running on your embedded system(s).

**Comment by rduttainfinera** [comment]
Thanks a lot. I will try it out on QNX OS + PPC Arch. Appreciate in advance for future help that I may need on this.
