### ISSUE TITLE
Updated container images for PCP?

### ISSUE THREAD

**Issue by hc000** [performancecopilot/pcp#88]
Hey guys,

If its not too much trouble, can we have updated version of dockerized PCP on bintray?

https://bintray.com/pcp/containers is still from February.

Thank you!

@natoscott: can this process be added as part of releases?

**Comment by goodwinos** [comment]
Hi Henry, the PCP container images are based on fedora:latest, and come with PCP from that same fedora release pre-installed and configured (services enabled, etc). There has been some talk that the PCP RPMS in these containers should use the bintray RPMS, rather than the Fedora RPMS. Thoughts?

Also: what about the base image itself? Continue to use fedora:latest? RHEL? Debian? Maybe build images for a variety of base images?

Cheers
-- Mark

**Comment by goodwinos** [comment]
BTW, fedora:latest is about to become f24, once it releases.

**Comment by natoscott** [comment]
@goodwinos @hc000 - my 2c - let's use the bintray pcp packages, so we don't have to wait awhile after each release.  Re base platform, I'm really not sure whats going to be best base for people (but using the bintray pcp packages at least gives us all those options).

**Comment by hc000** [comment]
@goodwinos @natoscott on dockerhub you guys can have different version of the same docker image and just tag it differently. Does bintray support this? maybe one tag can be based off of fedora:latest, and the other can be based off of bintray?

**Comment by pcpemail** [comment]
On 04/30/2016 06:14 AM, hc000 wrote:
> Hey guys,
>
> If its not too much trouble, can we have updated version of dockerized PCP on bintray?
>
> https://bintray.com/pcp/containers is still from February.

Hi Henry, I've built new container images based on fedora:latest, with
the PCP 3.11.2-1 RPMs pre-installed and the relevant service in each container
enabled by default.

I've also written a knowledge solution explaining how to use these images, see

     How can I run PCP services in a Docker container?
     https://access.redhat.com/solutions/2329251

I've tested this - if it's working for you hopefully we can close out this issue.

Regards
-- Mark

**Comment by goodwinos** [comment]
neglected to mention - the 3.11.2-1 based container images have been pushed to the bintray repo at  https://bintray.com/pcp/containers

**Comment by hc000** [comment]
@pcpemail @goodwinos 
Thank you!!
