### ISSUE TITLE
pmda-bind2: "get_server_stats: unknown node name 'version' at /var/lib/pcp/pmdas/bind2/pmdabind2.pl line 605."

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/pcp#886]
On current code:

root@fluxcoil:/var/lib/pcp/pmdas/bind2# ./Install 
get_server_stats: unknown node name 'version' at /var/lib/pcp/pmdas/bind2/pmdabind2.pl line 605.
get_server_stats: unknown node name 'version' at /var/lib/pcp/pmdas/bind2/pmdabind2.pl line 605.
Updating the Performance Metrics Name Space (PMNS) ...
Terminate PMDA if already installed ...
Updating the PMCD control file, and notifying PMCD ...
Check bind2 metrics have appeared ... 145 metrics and 145 values
root@fluxcoil:/var/lib/pcp/pmdas/bind2# 

This is due to bind handing out a piece of data which our current code does not deal with. Besides the output when installing the PMDA, the warning also accumulates in the PMDA's logfile. My patch simply ignores the "version" we get from bind2. We get quite verbosely other data which ends up in 145 metrics.

Patched version:
root@fluxcoil:/var/lib/pcp/pmdas/bind2# ./Install 
Updating the Performance Metrics Name Space (PMNS) ...
Terminate PMDA if already installed ...
Updating the PMCD control file, and notifying PMCD ...
Check bind2 metrics have appeared ... 145 metrics and 145 values
root@fluxcoil:/var/lib/pcp/pmdas/bind2# 

[bind2_ignore_version_status.patch.txt](https://github.com/performancecopilot/pcp/files/4495677/bind2_ignore_version_status.patch.txt)

**Comment by natoscott** [comment]
@christianhorn thanks!  Fix looks good to me - could you also provide a file for qa/named for automated regression testing of the output from this version of bind?

**Comment by christianhorn** [comment]
Here is one, from bind-9.11.13 from RHEL8. I see the same on 9.11.5-P4-5.1-Debian .

[bind-9.11.13-stats.xml.txt](https://github.com/performancecopilot/pcp/files/4507440/bind-9.11.13-stats.xml.txt)
