### ISSUE TITLE
how to make data qualified for pmseries or redis 

### ISSUE THREAD

**Issue by rduttainfinera** [performancecopilot/pcp#890]
We added a new few metrics and they are available on Vector - showing up on grafana and I can also dump them from pmlogger (pmlc), pminfo -f. 
But these new metric do not show up on pmseries or redis. Is there something else needed to be done differently to make them qualify for pmseries query or redis storage. This new metric is collected in regular interval and it does not return any null data.
Regards,
Raj

**Comment by natoscott** [comment]
@rduttainfinera yes, the data needs to be logged via pmlogger(1).  You can read up about pmlogconf(1) and pmlogger_daily(1) to learn more about the PCP logging process - it is relatively easy to extend to include your own metrics.
