### ISSUE TITLE
pmlogctl/pmiectl for managing pmlogger and pmie instances and pmfind for discovering them

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#896]
On platforms supporting systemd, use a template service unit configuration for managing multiple pmlogger instances. Similarly for pmie.

**Comment by goodwinos** [comment]
**Design notes for templated service units for pmlogger.** Similar (though simpler) concepts apply for pmie services.

**Service units**
We keep the pmlogger.service config as-is (for the primary logger) and add a new config named "pmlogger@.service". The latter is templated (see below) and shared by all pmloggers (if any) except the primary.

For the primary logger, there are pretty much no changes. The rc scripting for start-systemd will be called without the (new) optional host argument. The primary logger config in the control file will still be used. Same pidfile etc. On non-systemd platforms there is no change; the pmlogger service manages all pmloggers configured in the control files (primary and all remote loggers, if any) and the control files continue to be manually edited / configured.

For remote pmlogger instances, the pmlogger@HOST service manages the pmlogger for each HOST. In the template, %i substitutes HOST. Each templated service instance is individually managed as a systemd service.

```
    [Unit]
    Description=Performance Metrics Archive Remote Logger for %i
    Documentation=man:pmlogger(1)
    After=network-online.target

    [Service]
    Type=notify
    NotifyAccess=all
    TimeoutSec=120
    Restart=always
    ExecStart=@PCP_RC_DIR@/pmlogger start-systemd %i
    ExecStop=@PCP_RC_DIR@/pmlogger stop-systemd %i
    PIDFile=@PCP_RUN_DIR@/pmlogger-%i.pid

    [Install]
    WantedBy=multi-user.target
```

**Advantages of service unit templating include:**

- individual pmloggers can be managed (started / stopped etc), rather than the entire farm. Regexs can be used to manage multiple loggers by matching on the first field in each control file entry (i.e. hostname).

- all pmloggers can start in parallel rather than serially (=> better boot times) and each will notify systemd when they're started and ready (or stopping)

- new pmloggers can be configured and enabled dynamically without manually editing the control file, e.g. systemctl enable pmlogger@host1 pmlogger@host2 ...

A disadvantage is that "systemctl start pmlogger" only starts the primary logger, not the whole farm. A systemd 'target' config such as "pmlogger-farm.target" could be used to start or stop all enabled pmloggers if we want. This is how Redis v6 handles management of all Redis instances. Or we can use regex, e.g. systemctl start pmlogger@*

The pmlogger@.service needs network services but not local pmcd. The '%i' metachar substitutes the string after '@', e.g. systemctl enable pmlogger@HOST.  Each service instance does not need to bind to the timers or polling services (see below).

All the pmloggers are now independently managed by systemd and can start in parallel rather than serially. New loggers can be dynamically added or removed using systemctl enable pmlogger@HOST and removed with systemctl disable pmlogger@HOST (under the covers, systemd just creates/removes symlinks).

The rc script gets a new optional argument (i.e. start-systemd [HOST]) to specify the HOST service to start. If missing, it applies to the primary logger, same as existing. This argument will be passed to pmlogger_check (when invoked by the rc script) and then also passed to various internal functions _start_pmlogger, _start_pmcheck, _parse_control etc.

In pmlogger_check, if the argument host isn't already present in any of the control files, then it will be added and the associated infrastructure set up, (archive directory created, etc.), BEFORE actually starting the pmlogger process.  This could instead be done in a ExecStartPre entry). Any changes the user has made (e.g. logger arguments) in any of the control files should be preserved.  For dynamically added loggers, default arguments will be used initially, e.g. :

`    %i  n   n   PCP_ARCHIVE_DIR/%i   -r -T24h10m -c config.%i -v 100Mb`

**pmlogger binary**
Pretty much no changes. May need an argument for the new pid filename though this could simply be taken from the -h option, which must be unique. The primary logger is already distinguished by the -P option. All pmlogger services started by systemd will now be run with the -N option, so they will all notify systemd individually when started and can start in parallel. No changes affecting non-systemd platforms and no change when manually running pmlogger.

**Logutil Scripts**
When invoked from their timers (or cron for non-systemd platforms), pmlogger_daily and pmlogger_check will still walk the control file(s) and process ALL pmlogger entries serially. THis allows the pmlogger_daily/check messages/log files to remain as-is and contain messages for all pmloggers, same as for existing farms. Note that each pmlogger@.service instance does not need to bind to any timer or poll services.

**Nits**
Need a %postin script to handle upgrades / migration for existing pmlogger farms This would need to run systemctl enable pmlogger@HOST for each host that is already configured. This is a no-op for service instances that are already present.

The rc script, pmlogger_daily and pmlogger_check may need mutex for access to the control file(s) since pmlogger_check (when invoked by the rc script) can now modify them. The existing pmlock file may be sufficient and is already
honoured by the logutil scripts.

**QA Fallout**
hopefully not too bad (famous last words;) - there are essentially no functional changes to the primary logger. New QA tests would be needed to exercise the dynamic control file editing, upgrade/migration and logger farm instance management.

**Comment by andreasgerstmayr** [comment]
:100: 
Looks awesome!

The only thing I can think of is: instead of having `pmlogger.service` and the templated version `pmlogger@.server` we  could only use the templated version and use `pmlogger@primary` for the primary pmlogger?

+1 on the `pmlogger-farm.target`! (could be renamed to `pmlogger.target` if we only use the templated systemd unit)

**Comment by natoscott** [comment]
@goodwinos looks good, and I like that idea for backwards compatibility @andreasgerstmayr 

If we cannot keep that compatibility (for some reason?), we'll need a section in pcpcompat(1) and plenty of documentation about the impact of these changes (announce mail, release notes, etc) to existing installations with pmie and pmlogger farms.

Using this systemd templates functionality pmmgr(1) is essentially defunct.  The only remaining piece there is integration with host discovery - i.e. pmfind(1).  It would be worthwhile considering now how that would look too, to ensure we have a path to retiring that daemon while integrating with the rest of PCP properly.

I wonder if we could create a pmfind systemd timer (along with a pmfind_check.sh helper script) to perform the host probing (on pmmgr -p probing interval, if enabled), and the helper script perform the systemd template file creation/removal.  This would really be a much better fit with the architecture of  PCP, where small tools work together to complete the larger picture.

**Comment by goodwinos** [comment]
> Looks awesome!
> 

thanks for the feed-back!

> The only thing I can think of is: instead of having `pmlogger.service` and the templated version `pmlogger@.server` we could only use the templated version and use `pmlogger@primary` for the primary pmlogger?

Well, 'primary' is a valid hostname. This reason and also for back-compat with the common case of a primary-only default install are why I opted to keep pmlogger.service for the primary logger.

> 
> +1 on the `pmlogger-farm.target`! (could be renamed to `pmlogger.target` if we only use the templated systemd unit)

We _should_ be able to have a pmlogger.target (rather than pmlogger-farm.target). Will see once the implementation gets to that point. Having each template instance wantedby pmlogger.target would also probably allow farms with no local primary logger.

**Comment by goodwinos** [comment]
> @goodwinos looks good, and I like that idea for backwards compatibility @andreasgerstmayr
> 
> If we cannot keep that compatibility (for some reason?), we'll need a section in pcpcompat(1) and plenty of documentation about the impact of these changes (announce mail, release notes, etc) to existing installations with pmie and pmlogger farms.
> 
> Using this systemd templates functionality pmmgr(1) is essentially defunct. The only remaining piece there is integration with host discovery - i.e. pmfind(1). It would be worthwhile considering now how that would look too, to ensure we have a path to retiring that daemon while integrating with the rest of PCP properly.
> 
> I wonder if we could create a pmfind systemd timer (along with a pmfind_check.sh helper script) to perform the host probing (on pmmgr -p probing interval, if enabled), and the helper script perform the systemd template file creation/removal. This would really be a much better fit with the architecture of PCP, where small tools work together to complete the larger picture.

yes all good points. As discussed on IRC, let's get the infrastructure in place. As suggested, a new timer using pmfind sounds promising, or perhps that could be driven off the existing half-hourly pmlogger_check timer invocation. Further notes and ideas are welcome!

**Comment by natoscott** [comment]
|  %i n n PCP_ARCHIVE_DIR/%i -r -T24h10m -c config.%i -v 100Mb

Will these defaults come from a configuration file? (like /etc/sysconfig/pmlogger, /etc/sysconfig/pmie)  I think it best if so, and I need to make sure I don't clobber 'em in ansible-pcp.  :) 

| Further notes and ideas are welcome!

Another thought, could we extend this scheme to handle logging of individual containers?  Or any of the other connection options from PCPIntro(1)...
```

            $ pcp --host pcps://app2.acme.com?container=cae8e6edc0d5
            $ pcp --host pcps://nas1.acme.com:44321?username=tanya&method=gssapi
            $ pcp --host pcps://nas2.acme.com@firewalls.r.us?method=plain
            $ pcp --host pcp://nas3.acme.com
            $ pcp --host 192.168.0.103?container=cae8e6edc0d5,method=digest-md5
            $ pcp --host unix:
            $ pcp --host local:

```

**Comment by goodwinos** [comment]
> | %i n n PCP_ARCHIVE_DIR/%i -r -T24h10m -c config.%i -v 100Mb
> 
> Will these defaults come from a configuration file? (like /etc/sysconfig/pmlogger, /etc/sysconfig/pmie) I think it best if so, and I need to make sure I don't clobber 'em in ansible-pcp. :)

As with current pmlogger services, the config is a line in a control file from below /etc/pcp/pmlogger/control.d, as existing. The first field is the hostname of the remote pmcd, which is then also used as the directory name below $PCP_ARCHIVE_DIR, and the pmlogger config (config.%i).

> | Further notes and ideas are welcome!
> 
> Another thought, could we extend this scheme to handle logging of individual containers? Or any of the other connection options from PCPIntro(1)...

All such valid host specifications are going to need a mapping from the service instance name to the desired hostspec, for the case where they are not the same.  At the moment, the host / service instance name is also the hostspec for the remote pmcd connection (with the special case for the primary logger being 'local:' for a unix domain connection to the local pmcd).

The supplied args at the end of the control line could optionally supply a -h hostspec and the scripts could look for that as the hostspec to use (verbatim) instead of defaulting to the service instance name. If there is no -h arg present, then default to the service instance name. That seems to be the most simple and back-compat approach to me.

Thoughts?

> ```
> 
>             $ pcp --host pcps://app2.acme.com?container=cae8e6edc0d5
>             $ pcp --host pcps://nas1.acme.com:44321?username=tanya&method=gssapi
>             $ pcp --host pcps://nas2.acme.com@firewalls.r.us?method=plain
>             $ pcp --host pcp://nas3.acme.com
>             $ pcp --host 192.168.0.103?container=cae8e6edc0d5,method=digest-md5
>             $ pcp --host unix:
>             $ pcp --host local:
> ```

**Comment by goodwinos** [comment]
Also, yes the default control line for dynamically added service instances can be specified in $PCP_SYSCONFIG_DIR/pmlogger so it can be site customized, e.g. 

`PMLOGGER_SERVICE_DEFAULT_ARGS="%i n n PCP_ARCHIVE_DIR/%i -r -T24h10m -c config.%i -v 100Mb"`

What I was trying to explain above is the situation when the service instance name (%i) is not literally the hostspec that we want pmlogger to connect to. We need a 1:1 mapping somewhere/somehow in a file or an environment variable or something, perhaps /etc/pcp/pmlogger/control.d/hostspec, containing lines like:

tanya=pcps://nas1.acme.com:44321?username=tanya&method=gssapi
backup=192.168.0.103?container=cae8e6edc0d5,method=digest-md5
whatever=somehostspec 

And then use those variables in the template to apply the mapping from service instance name to hostspec, e.g. for the -h argument where we want to insert the hostspec:

`PMLOGGER_SERVICE_DEFAULT_ARGS="%i n n PCP_ARCHIVE_DIR/%i -r -T24h10m -c config.%i -v 100Mb -h ${%i}"`

[not sure if the above would work, but it would be nifty!]

**Comment by natoscott** [comment]
The scenario I'm thinking of involves automatically discovered hosts and containers - there's no opportunity (or need) to assign human-meaningful names.  For such cases I think the automatically generated unique source identifiers as reported by pmseries(1) would be best suited.  These would also be unlikely to conflict with real host names, which would pose a problem for the human-readable, manual id:hostspec mapping scheme.

I think the upshot is - whether manually or automatically mapping sources or manual names to hostspecs, we'd want to be careful to *not* make the assumption that the pmlogger --host option and the systemd service template name are the same thing (though it is a good default behaviour which we definitely want IMO, for anyone manually setting up pmloggers).

**Comment by andreasgerstmayr** [comment]
> tanya=pcps://nas1.acme.com:44321?username=tanya&method=gssapi
> backup=192.168.0.103?container=cae8e6edc0d5,method=digest-md5
> whatever=somehostspec

Another solution would be just using these hostspecs in a systemd-escaped format:
tanya would be `pmlogger@pcps:--nas1.acme.com:44321\x3fusername\x3dtanya\x26method\x3dgssapi`
backup would be `pmlogger@192.168.0.103\x3fcontainer\x3dcae8e6edc0d5\x2cmethod\x3ddigest\x2dmd5`

Inside the systemd unit `%I` (capital i) refers to the unescaped instance name.
There are already a few units using escaped (device) paths, see `systemctl --list-units`.

This would remove the need for a mapping file, and any confusion (is the systemd template referring now a real host or an identifier which is mapped in the mapping file?).

**Comment by natoscott** [comment]
> Another solution would be just using these hostspecs in a systemd-escaped format:

+1  - that does seem to be the 'systemd way'.

Looking back at Marks earlier mail, we have control lines like:
| %i n n PCP_ARCHIVE_DIR/%i -r -T24h10m -c config.%i -v 100Mb

So the "%i" (which in this case would be the full quoted hostspec) gets used in several places:
- the hostspec passed to pmlogger, via the first field in each line in the control file(s)
- the pmlogger configuration file name
- the final pathname component when specifying where archives are created

as long as we're OK with all of these places containing (quite unwieldy) escaped strings, we're good.

There's some remaining issues still, e.g. in this case
> pmlogger@pcps:--nas1.acme.com:44321\x3fusername\x3dtanya\x26method\x3dgssapi

- the arguments (username, method, etc) can be presented in any order, so we could end up with multiple loggers for the same target pmcd
- the arguments can contain a password.

> Inside the systemd unit `%I` (capital i) refers to the unescaped instance name.

Despite those couple of issues, I think this is a pretty good option.  Perhaps we could enforce a policy of alphabetic ordering or arguments, and perhaps advise people against using passwords?

> There are already a few units using escaped (device) paths, see `systemctl --list-units`.
> 
> This would remove the need for a mapping file, and any confusion (is the systemd template referring now a real host or an identifier which is mapped in the mapping file?).

+1

**Comment by natoscott** [comment]
I'm planning on tackling the pmfind service idea, to better integrate service discovery with pmie and pmlogger.  I think its now straight forward, with expansion on the ideas described earlier in this issue.  My plan of attack is:

1. Extend pmfind(1) to be able to discover containers running pmcd, and to report source identifiers in the same way pmseries(1) does.  Sample output:

```
243f90596d76cf23e8da47476ec452a2adbe0b32  pcp://slick:44321
8d00c4cf51d11bb9dced8a0e7507542653635377  pcp://slack:44321
7745e45ed37ca712f418ec7b871c04fc898b9276  pcp://localhost:44321?container=b0cd2cc912a3
68dcffbdd4111d3ee82bb855286e3e35da828ca2  pcp://localhost:44321?container=77475e5fa09c
```

2. Create a helper script - pmfind_check(1) - which runs pmfind, iterates over each line of this output and creates entries below /etc/pcp/{pmlogger,pmie}/control.d.  There will be an individual file for each discovered pmcd, named using the (unique) source identifier.  A pmlogger control file for the first line of sample pmfind output above would look like:

```
> cat /etc/pcp/pmlogger/control.d/243f90596d76cf23e8da47476ec452a2adbe0b32
$version=1.1
pcp://slick:44321   n   n   PCP_ARCHIVE_DIR/243f90596d76cf23e8da47476ec452a2adbe0b32 -c config.243f90596d76cf23e8da47476ec452a2adbe0b32   -r -T24h10m -v 100Mb
```

3. Create systemd service and timer files.  The systemd service file wraps pmfind_check and the timer goes off on the interval chosen to perform host discovery.  Create a systemd path file to monitor /etc/pcp/pmfind such that touching this triggers a manual discovery pass (as an alternate to the timer). 

4.  Profit!  As we now have host discovery properly integrated with the existing pmie and pmlogger services, including their daily log rotation, archive compression, etc - we'll be doing a better job than pmmgr and without the additional daemon.  pmmgr can be deprecated, and retired after a release or two.  Once the pmie and pmlogger systemd service templating is done (in a backwards-compatible way for existing installs), the pmfind-discovered pmlogger and pmie control entries will benefit from isolated systemd control - individual stop, start, journals, etc - with no additional effort.

5.  As a future extension, we could add to the pmproxy service (which pmfind can also be instructed to discover) to allow host discovery in any network 'behind' pmproxy, such that a monitor host could run pmie/pmlogger for hosts pmproxy knows about as well.

Thoughts?

**Comment by kmcdonell** [comment]
Based on the recent experience getting the primary pmlogger control to work reliably with systemd, I suggest it is time for a rethink here.

I don't want to rain on the parade, but systemd has always been an over-engineered solution looking for a problem, and I think we risk falling into the trap of doing just that here with the templated systemd approach.

Let's go back to Mark's "Advantages" at the start of this issue, and recast that into Use Cases.  Others should add more if I've missed any.
1. Individual pmlogger instances should be able to be controlled (here I mean control to be operations like start, restart, stop ... I see this as different to create and destroy which are addressed below).
2. Control should also be easily applied to groups of pmloggers based on a variety of criteria, e.g. regexp matching on hostname, based on "class" (more on that below), archive size, ....
3. The mechanism(s) for controlling non-primary loggers should also work for the local primary logger.
4. Starting non-primary pmloggers in parallel is **not** a requirement.  Think about a logger farm, you do not want logger farm host boot time to be delayed by starting a bunch of remote pmloggers, and leisurely starting of pmloggers (serially, not in parallel) is much kinder on the logger farm host.  Primary pmlogger start should be in the boot sequence, and systemd is fine for that.  If start/stop in parallel is deemed important it can easily be added to the solution proposed below by pmlogctl running each pmlogger_check -c ... in the background
5.  Loggers naturally fall into "classes", as in HTTP servers, DB servers, app servers, authentication servers, mail servers, ... All loggers in a class share the same pmlogger configuration file.  Different classes will have different configuration files.  For convenience there may be a default class (which if not defined might use the current config.default configuration file).  Classes may also have a deletion policy, e.g. manual, on pmlogger exit, automatic after 15mins absence, ...
6. Loggers may be created either by user action or automatically based on discovery.  In either case a hostname and optionally a classname are required.  In the automatic case, we probably need some policy file to determine (a) should a pmlogger be enabled at all, (b) persistence criteria (e.g. don't log unless the host has been up for 5mins to avoid load-balancer flapping), (c) which class should it belong to, etc ... the policy may be driven statically from the hostname and/or dynamically, e.g. based on (pm)probing the host.
7. Loggers should be deleted either by user action or automatically.  In the automatic case we probably needs some policy file to determine (a) should the pmlogger never be deleted, (b) persistence criteria (wait 10mins and if has not re-appeared, delete it), etc ...
8. All of the above should be achieved with **no** requirement for manual editing of the pmlogger control files.
9. Existing configs have to be imported automatically and the existing manual processes for managing pmloggers still have to work, with or without systemd in the picture.

My assertions are:
(a) systemd is a really bad fit for all of the above (except possibly the primary pmlogger)
(b) we already have 90% (guess) of the infrastructure to make this work ... out pmlogger control file captures all of the parameters needed to start each pmlogger, pmlogger_check -c controlfile allows us to start individual pmloggers, pmcd.pmlogger.* gives us cheap access to the pid and pathnames to kill/report on pmloggers, use 1 control file per host below /etc/pcp/pmlogger/control.d/ to avoid file read/write/update concurrency issues (stop/start is the only operation that might need an existing control file to be edited, but this can be an near-atomic mv), ...

What's missing:
1. A new small, specialized front-end, say, pmlogctl that supports basic actions like start, restart, stop, create, destroy, status, a hostname argument and some optional arguments like -c classname, and catches the operations on the (local) primary pmlogger and maps 'em to systemd operations (if systemd is managing the primary pmlogger), and implements all other operations independent of systemd.
2. The policy and class files (maybe the one file).  Format, defaults, how to update ... pmlogctl is the only one that will use these file(s).
3. Whatever plumbing needs to go between pmfind and pmlogctl.

We don't need any additional systemd support, I think the existing pmlogger_check.service will do just fine.  In the logger farm case, I think restart for a failed pmlogger can be driven either by pmfind (the remote host reappears), or the 30 min pmlogger_check.timer checks (these are probably candidates for the policy/class file(s)).

Lots more needs to be fleshed out, but I think this path is more promising than the systemd-based one.

**Comment by goodwinos** [comment]
Over to Kenj with the final solution for this feature ...

**Comment by goodwinos** [comment]
Resolved by: https://github.com/performancecopilot/pcp/pull/985
