### ISSUE TITLE
no pmcd agent for domain request for hinv.cpu.clock on installation of linux-tools

### ISSUE THREAD

**Issue by pradykaushik** [performancecopilot/pcp#897]
Right after installing linux-tools-4.15.0-39-generic and linux-cloud-tools-4.15.0-39-generic, I was not able to get information of the hinv.cpu.clock performance metric using the command `pminfo -dfmT hinv.cpu.clock` and it gave me the error - **hinv.cpu.clock: pmLookupDesc: No PMCD agent for domain of request**.

However, when I removed the those packages and rebooted, I was able to get information and monitor cpu clock frequencies once again.

Processor - Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Architecture - x86_64
Operating System - Ubuntu 18.04.1 LTS
Linux Kernel - 4.15.0-39-generic
PCP version - 4.0.1

## Reproducing the Issue
Assuming pcp is installed.
Run the following commands to install necessary packages.
1. `apt-get install linux-tools-4.15.0-39-generic`
2. `apt-get install linux-cloud-tools-4.15.0-39-generic`

Now run the below command to get information regarding the metric hinv.cpu.clock.
```commandline
pminfo -dfmT hinv.cpu.clock
```
This should be produce the error message **_hinv.cpu.clock: pmLookupDesc: No PMCD agent for domain of request_**.

Now run the below command in an attempt to monitor clock frequencies.
```commandline
pmdumptext -t 1.0 hinv.cpu.clock
```
This should produce the error message **_pmdumptext: Error: local::hinv.cpu.clock: No PMCD agent for domain of request_**.

Now, let's remove the installed packages using the below commands.
1. `apt-get remove linux-tools-4.15.0-39-generic`
2. `apt-get remove linux-cloud-tools-4.15.0-39-generic`

Reboot the system.

Now `pminfo -dfmT hinv.cpu.clock` and `pmdumptext -t 1.0 hinv.cpu.clock` should give you the expected information and values respectively.

## Why I think this is happening?
Upon some reading, I am under the assumption that the package installations resulted in some metrics and namespaces to be added which conflicted with those of the linux PMDA. However, I have not been able to verify this.

Would really like to know why this is happening. Any pointers are very much appreciated.

**Comment by goodwinos** [comment]
@pradykaushik, thanks for the report - will investigate - stating by installing a Ubuntu 18.04.1 VM.

**Comment by goodwinos** [comment]
@pradykaushik I set up a Ubuntu bionic 18.04.4 VM and ran the reproducer instructions that you provided. I'm not seeing the issue unfortunately.

```
mgoodwin@ubuntu-bionic:~$ pminfo -dfmT hinv.cpu.clock

hinv.cpu.clock PMID: 60.18.0
    Data Type: float  InDom: 60.0 0xf000000
    Semantics: discrete  Units: / microsec
Help:
clock rate in Mhz for each CPU as reported by /proc/cpuinfo
    inst [0 or "cpu0"] value 2793.5161
    inst [1 or "cpu1"] value 2793.5161

```

The message "no pmcd agent for the domain of the request" is an error reply from pmcd indicating that the PMDA for the requested metric isn't running or not configured, but the PMNS name is still in the PCP PMNS (namespace). In this case the agent is the Linux PMDA, which should be running by default may have died for some reason .. can you check /var/log/pcp/pmcd/pmcd.log and also linux.log in the same directory?

Regards

**Comment by goodwinos** [comment]
@pradykaushik anything to report here? Or will we just close it out?  Thanks

**Comment by pradykaushik** [comment]
Oh shoot!! Got caught up with something and couldn’t get to this. Give me two more days and I’ll check the logs and get back you. Would that be okay? Sorry for the delay.

**Comment by goodwinos** [comment]
no probs, thanks

**Comment by pradykaushik** [comment]
Interestingly, I don't get the error now after installing those packages.
As per your request, I took a look at the logs from Apr 24 (the day I raised this issue). Below is a piece of the log that repeats a lot.
```commandline
Log for pmcd on stratos-001 started Fri Apr 24 16:48:12 2020


active agent dom   pid  in out ver protocol parameters
============ === ===== === === === ======== ==========
root           1  1871   6   7   2 bin pipe cmd=/var/lib/pcp/pmdas/root/pmdaroot
pmcd           2                 2 dso i:6  lib=/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so entry=pmcd_init [0x7f32eb1116f0]
proc           3  1877  11  12   2 bin pipe cmd=/var/lib/pcp/pmdas/proc/pmdaproc -d 3
linux         60  1879  13  14   2 bin pipe cmd=/var/lib/pcp/pmdas/linux/pmdalinux
mmv           70                 2 dso i:7  lib=/var/lib/pcp/pmdas/mmv/pmda_mmv.so entry=mmv_init [0x7f32eaf07320]
perfevent    127  1880  15  16   2 bin pipe cmd=/var/lib/pcp/pmdas/perfevent/pmdaperfevent -d 127

Host access list:
00 01 Cur/MaxCons host-spec                               host-mask                               lvl host-name
== == =========== ======================================= ======================================= === ==============
 y  y     0     0 128.226.116.30                          255.255.255.255                           0 localhost
 y  y     0     0 /                                       /                                         1 unix:
    n     0     0 0.0.0.0                                 0.0.0.0                                   4 .*
    n     0     0 ::                                      ::                                        8 :*
User access list empty: user-based access control turned off
Group access list empty: group-based access control turned off


pmcd: PID = 1862, PDU version = 2
pmcd request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     4       unix   /var/run/pcp/pmcd.socket
  ok     0 44321 inet   INADDR_ANY
  ok     3 44321 ipv6   INADDR_ANY
[Fri Apr 24 16:48:19] pmcd(1862) Warning: pduread: timeout (after 5.000000 sec) while attempting to read 12 bytes out of 12 in HDR on fd=14
[Fri Apr 24 16:48:19] pmcd(1862) Info: CleanupAgent ...
Cleanup "linux" agent (dom 60): protocol failure for fd=14
Warning: restartAgents=1 from PMCD_RESTART_AGENTS=1 in environment
[Fri Apr 24 16:48:19] pmcd(1862) Info: Auto-restarting agents.
[Fri Apr 24 16:48:19] pmcd(1862) Info: 

pmcd RESTARTED at Fri Apr 24 16:48:19 2020
```

From looks of it, I keep seeing that the agents were restarted often and that `pduread` timed out often too. Could this potentially be the issue?

**Comment by goodwinos** [comment]
Hi @pradykaushik, thanks for following up. You may need to increased the pmcd-pmda timeout in /etc/pcp/pmcd/pmcd.options. Search for "longer timeout delay for slow agents" in that file and uncomment the suggested -t and -q options to increase to a 30 second timeout (default is 5 seconds, which doesn't seem to be long enough on your systems.

Cheers

**Comment by pradykaushik** [comment]
@goodwinos yes I will do that. I hope the timeouts resolve the issue (if any). Thanks a lot.

**Comment by goodwinos** [comment]
OK cool. Please reopen if you have further issues. Thanks
