### ISSUE TITLE
Can PM namespace be updated(prepended) dynamically ?

### ISSUE THREAD

**Issue by rduttainfinera** [performancecopilot/pcp#898]
Can PM namespace be updated(prepended) dynamically as it flows via PM collector hierarchy ? I am planning to user PM collection in a hierarchical manner 
1) Data module(D#) -> Chassis Controller(A#)-> Cluster Controller(C#) -> Network Controller(N#)
For example D5 pmlogger writes to log on A10,  A10 pmlogger write to cluster C1 log, C1 pmlogger write to N2 log ...
Is it possible to prepend the namespace at it flows through the pipeline of logs -- i.e.
On A10 for D5 it will have datametric NS = A10-D5
On C1 it will become : C1-A10-D5
On N2 it will endup as : N2-C1-A10-D5

Please provide some guidance.
Regards,
Raj

**Comment by natoscott** [comment]
I'm not 100% sure I follow what you're asking, but there isn't really a pipeline of PCP archives - its a one pmlogger to one pmcd model.  Once the archive is written, its complete - unless pmlogrewrite is used later to modify the archive metadata.

The best place to influence metric names and instance names is on the machine where pmcd is running.

It might make sense in your case to use metric labels - you can add labels that apply to all metrics from a (host / archive) context using /etc/pcp/labels (pmcd and pmlogger) or later pmlogrewrite.

Again, it depends what you're trying to achieve - and labels are relatively new, not all tools support them yet.  The grafana-pcp Redis data source and pmseries language certainly do though, and this may be what you're looking for.

**Comment by natoscott** [comment]
Closing this as there seems to be no problem here.  Raj, feel free to send this kind of question to the PCP mailing list, or chat with us on slack and/or IRC, details here:  https://pcp.io/community.html
