### ISSUE TITLE
rpm pmda depends on inotify

### ISSUE THREAD

**Issue by jeffpc** [performancecopilot/pcp#899]
This causes build failures on systems that do not provide inotify (e.g., FreeBSD).

```
=== rpm ===
gcc9 -fPIC -fno-strict-aliasing -D_GNU_SOURCE -fvisibility=hidden	 -Wall -O2 -g -DPCP_VERSION=\"5.1.1\" -I../../../src/include -I../../../src/include/pcp -o pmdarpm  -Wall -L../../../src/libpcp/src -L../../../src/libpcp_web/src -L../../../src/libpcp_pmda/src  -fPIC -fno-strict-aliasing -D_GNU_SOURCE -fvisibility=hidden	 -Wall -O2 -g -DPCP_VERSION=\"5.1.1\" -I../../../src/include -I../../../src/include/pcp  rpm.o timer.o      -lpcp_pmda -lpcp -lrpm -lpthread 
/usr/local/bin/ld: rpm.o: in function `rpm_inotify':
/usr/home/jeffpc/src/pcp/src/pmdas/rpm/rpm.c:556: undefined reference to `inotify_init'
/usr/local/bin/ld: /usr/home/jeffpc/src/pcp/src/pmdas/rpm/rpm.c:562: undefined reference to `inotify_add_watch'
collect2: error: ld returned 1 exit status
```

This is on current master branch (5.1.0-2-g5890d31f0).

**Comment by andreasgerstmayr** [comment]
We'll need to
* update `configure.ac` to exclude this PMDA on FreeBSD
* or implement an alternative to inotify in the rpm PMDA

**Comment by jeffpc** [comment]
Personally, I'm ok with simply excluding it.

**Comment by goodwinos** [comment]
> Personally, I'm ok with simply excluding it.

makes sense to exclude this PMDA on platforms that don't support RPM packaging.

**Comment by jeffpc** [comment]
> > Personally, I'm ok with simply excluding it.
> 
> makes sense to exclude this PMDA on platforms that don't support RPM packaging.

Technically, rpm runs on FreeBSD (and it is even packaged in ports), but it isn't used by the FreeBSD itself.
