### ISSUE TITLE
Compiling from source on Ubuntu 14.04 leaves no pmwebd binary

### ISSUE THREAD

**Issue by batasrki** [performancecopilot/pcp#9]
Hello all,

I'm unsure what's needed to reproduce this issue. I've been trying to set up Netflix's Vector tool and I installed pcp from source onto a 14.04 server. When I look at ```/usr/libexec/pcp/bin```, I see no pmwebd binary and this is confirmed when I try to start the service by running:
```
sudo /etc/init.d/pmwebd start && sudo /etc/init.d/pmwebd status
Checking for pmwebd: stopped
```
```make``` and ```make install``` seem to succeed and when I pipe the output of either into grep, I get the following message:

```
sudo make install | grep -A 5 -B 5 pmweb
make[2]: Nothing to be done for `default_pcp'.
=== pmwebapi ===
```
Let me know what other output I need to add. I installed ```libmicrohttpd10```, ```libmicrohttpd-dev```, ```bison```, ```flex``` and ```autoconf```.

Thanks

**Comment by batasrki** [comment]
Update, I also installed ```qt4-dev-tools``` and ```qt4-qmake``` and the result is the same.

**Comment by batasrki** [comment]
OK, I got this working. The server needed to have ```pkg-config``` and ```libmicrohttpd-dev``` installed and then having PCP re-compiled. Maybe, it'd be worth noting that in the docs?

**Comment by kmcdonell** [comment]
As the recent postings suggest, people new to PCP are more often trying to build PCP from source than we've seen in the past.

I've reviewed the INSTALL notes in the source, and added the following to section B. ...

0. Preliminaries

   The PCP code base is targeted for many different operating
   systems and many different combinations of related packages,
   so a little planning is needed before launching into a build
   from source.

   Package dependencies come in several flavours:

   (a) hard build dependencies - without these PCP cannot be
       build from source, and the build will fail in various
       ways at the compilation or packaging stages, e.g. gmake,
       autoconf, flex, bison, ...;

   (b) optional build dependences - if these components are not
       installed the build will work, but the resultant packages
       may be missing some features or entire applications, e.g.
       extended authentication, secure connections, service
       discovery, pmwebd, ...;

   (c) QA dependencies - you can ignore these unless you want to
       run the (extensive) PCP QA suite.

   It is strongly recommended that you run the script:
        $ qa/admin/check-vm
   and review the output before commencing a build.
------

And, check-vm would have reported on both pkg-config (required for debian based systems) and libmicrohttpd-dev (build optional).

**Comment by airforceboricua** [comment]
That did it!  Thank you so much!
