### ISSUE TITLE
pmda-smart read almost no metrics, parsing of new smartmon format

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/pcp#901]
For nvme SSD's on multiple systems (Fedora 31, 32), I just get these metrics from pmda-smart:
smart.health
smart.info.device_model
smart.info.serial_number
smart.info.capacity_bytes
smart.info.sector_size
smart.info.rotation_rate

From looking at qa/smart/smart-root*, it seems like the output of "smartctl -a" has changed since the pmda was written. The QA suite was simply always using the data from the older versions, and did not catch this.

**Comment by pauljevans** [comment]
@christianhorn, could you post the output of "lsblk" along the outputs from "smartctl -Hi" and "smarctl -A" from one of the systems that you are seeing issues with?

**Comment by christianhorn** [comment]
[pmda_smart.txt](https://github.com/performancecopilot/pcp/files/4650124/pmda_smart.txt)
