### ISSUE TITLE
bond and lo is not dropped on centos8.1

### ISSUE THREAD

**Issue by winndows** [performancecopilot/pcp#903]
statistics for bond and lo is not dropped on centos8.1

# dstat -n -N eth0, total
--net/eth0---net/total-     
 recv  send: recv  send
 186   102 : 372   204
 126   246 : 252   491
  66   134 : 132   268
 126   126 : 252   252
 332   118 : 664   236  

 Above, only eth0 and bond( the only slave is eth0) have packets. and "total" includes bond and eth0.

 "total" includes lo too if we generate some packets on lo.

**Comment by natoscott** [comment]
@winndows thanks, will be fixed in pcp-5.1.1
