### ISSUE TITLE
cleanup various obsolete things

### ISSUE THREAD

**Issue by goodwinos** [performancecopilot/pcp#904]
This issue is for a list of things needing cleanup or to be nuked

**Comment by goodwinos** [comment]
- src/pmlogger/rc_pmlogger - remove the conditional code around "$PCP_CONTAINER_IMAGE" - that was only ever for containers not using systemd as pid1. Same for rc_pmcd, rc_pmie, rc_pmmgr and rc_pmproxy. Also src/pmlogger/crontab.docker.in is obsolete too and all or most of build/containers.

**Comment by natoscott** [comment]
PMLOGGER_CHECK_SKIP_LOGCONF can be safely removed now I think

**Comment by goodwinos** [comment]
- PMLOGGER_CHECK_SKIP_LOGCONF is probably obsolete now that pmlogconf runs much faster. On the other hand, there may be cases where a user specifically does not want pmlogconf to run (globally).

**Comment by natoscott** [comment]
contents of the build/containers directory has been superceded by Andreas work on a PCP container
