### ISSUE TITLE
cgroups v2 support

### ISSUE THREAD

**Issue by Fodoj** [performancecopilot/pcp#915]
Is that right that current PCP versions do not support cgroups v2?

 I have Fedora Workstation 32, pcp version 5.1.0. It seems pcp searches for metrics in cgroups v2 hierarchy:

```
  cgroup.memory.usage
  No value(s) available!
   
   cgroup.memory.limit
   No value(s) available!
   
  cgroup.memory.failcnt
  No value(s) available!
   
   cgroup.memory.stat.cache
  No value(s) available!
   
   cgroup.memory.stat.rss
   No value(s) available!
```

Instead of the cgroups v2. Or is there a way to enable v2 support?

**Comment by natoscott** [comment]
@Fodoj these particular metrics you've listed no longer exist in cgroups v2.  pcp-5.1.0 has full support for cgroups v2, including all the new metrics that provides ... try:

```
pminfo -f cgroup.memory cgroup.pressure.memory | less
```

many of these metrics are supported for cgroup v2 only (others are v1 only, like the ones you listed).  Have a look in the memory.stat files in any running cgroups you have below /sys/fs/cgroup/

**Comment by Fodoj** [comment]
I could not find any metrics responsible for rss memort or some total memory usage of a cgroup, couple you please point me to one?
