### ISSUE TITLE
pcp-pmda-bind2 requires List::MoreUtils

### ISSUE THREAD

**Issue by weijianwen** [performancecopilot/pcp#926]
It seems that pcp-pmda-bind2 requries List::MoreUtils module, which dependency should be added to the RPM spec file.

Steps to reproduce this issue
------------------------------

```
# uname -a
Linux ns1.pi.sjtu.edu.cn 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# yum install -y pcp-pmda-bind2
# cd /var/lib/pcp/pmdas/bind2/
# ./Install
List::MoreUtils perl module is not installed
```

**Comment by natoscott** [comment]
@weijianwen thanks for the report.  After reviewing the code, it looks like pmdabind2 doesn't use List::MoreUtils (anymore?) so this check can be safely removed from the Install script, and no spec changes are needed after all.
