### ISSUE TITLE
container metrics broken (F31, cgroups v2)

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#927]
```
sudo podman run -d --name testcontainer fedora:31 sleep 999999
sudo pminfo -f --container testcontainer cgroup
```

Doesn't show any metric values except `cgroup.subsys` and `cgroup.mounts`. The `containers.name` metric works as expected.

**Comment by natoscott** [comment]
Fixed in commit 53e0d587bb476ffc4c1ca17c8c425cadb51c722a
