### ISSUE TITLE
Load PCP archive logs into Redis

### ISSUE THREAD

**Issue by makothap** [performancecopilot/pcp#933]
Hi, 

The PCP archive logs for different hosts were copied to a  central logging host as shown below:

```
PCP_LOG_DIR/host1/
PCP_LOG_DIR/host2/
...
PCP_LOG_DIR/hostn/
```

Is there a way to load the archive logs from above directories into PCP Redis server for retrospective analysis? Any guidelines or pointers would be helpful!

**Comment by natoscott** [comment]
| Is there a way to load the archive logs [...] into PCP Redis [...]

Refer to the pmseries(1) man page and -L/--load option.

| archive logs for different hosts were copied to a central logging host

You might want to explore the pmlogger_daily(1) approach, where the logs are collected via centrally running pmlogger(1) processes - no need to copy them from remote hosts then.

**Comment by makothap** [comment]
Thanks for quick response!

The pmeries --load <archive-file> was used to load the data into Redis server successfully. But for some-reason, the "Redis Host Overview" dashboard (in Grafana) doesn't display the data loaded into Redis (say, for the OOTB metrics such as `kernel.all.load`; Are there any additional steps or configuration needed for the Grafana visualizations to work?

[Currently, there's no n/w connectivity between hosts for which PCP archive logs were collected and the central server]

**Comment by natoscott** [comment]
I think by default the dashboard shows current time back to last 6 hours - you may need to set the time window in the top right corner?  Let's continue the discussion on slack :)
