### ISSUE TITLE
Ubuntu Systemd

### ISSUE THREAD

**Issue by udf2457** [performancecopilot/pcp#94]
Hello,

FYI

From https://wiki.ubuntu.com/SystemdForUpstartUsers

> System Init Daemon
> This has changed as part of the Ubuntu 15.04 devel cycle.
> Ubuntu 15.04 (using Systemd by default)

With 15.04, Upstart was still present and available for use in parallel. However now with the advent of 16.04LTS, Ubuntu have eradicated Upstart and Systemd is the one and only option.

PCP will therefore need to amend its packages to ensure people running 16.04 don't encounter problems. 

Thanks

**Comment by natoscott** [comment]
The systemd unit files are all present in the PCP git tree, and have been in use on Fedora & RHEL for some time.  Still needed here though are some packaging/makefile changes, and testing/verification that the systemd integration functions correctly on Debian & Ubuntu too.

**Comment by natoscott** [comment]
This was resolved some time ago.
