### ISSUE TITLE
pmclient.c, pmclient_fg.c and pmclient_fg.python seem to report wrong cpu util values

### ISSUE THREAD

**Issue by wooloo1121** [performancecopilot/pcp#952]
Hi,

I'm playing with the pmclient_fg.python program and find that the cpu util values are always zero. I checked the code and see a problem in line 61 (self.cpu_util /= self.ncpu()) which should probably work with float(self.ncpu()). The pmclient.c always reports 0.99 and pmclient_fg.c always reports 1.00. Is there a problem with the program?

Thank you so much.

Best,
Kaiyue

**Comment by natoscott** [comment]
@wooloo1121 the C versions of the program appear to work correctly, for me, its only the python version I see an issue with.  For the C variants, are you certain you do not have something running utilizing your CPU(s)?  ('pcp atop' will help diagnose further).

For the python version, the always-zero problem seems to be related to the units conversion for the CPU utilization metrics (the lines containing 'second/second') - this always seems to result in zero values, for some reason (if I change these to just 'second', I do see the raw values).  Quite possibly its related to type confusion as you suggest - but the problems earlier than the line you point out I believe.

**Comment by wooloo1121** [comment]
@natoscott That should be the problem with the python program. I checked the cpus and they are indeed utilized, so the c programs should be working correctly. Thanks for the reply :)
