### ISSUE TITLE
pyslurm.job().get() doesn't work in PMDA

### ISSUE THREAD

**Issue by wooloo1121** [performancecopilot/pcp#958]
Hi,

I'm developing a PMDA program to grab more Slurm info than the given Slurm PMDA. Since I'm writing in python, I use the pyslurm module. But when I try to call pyslurm.job().get() to get Slurm job info, it always returns an empty dict. The code using this expression does work outside of pmda, but stops working when tested with dbpmda and loaded into PMCD. (pyslurm.node().get() works) I'm considering if there is a problem with pcp that causes this, could you please check and possibly fix it if there is one? Thank you so much and look forward to your reply.

**Comment by natoscott** [comment]
@wooloo1121 could this be an SE Linux issue?  (when run from pmcd, agents run with restricted selinux policy).  See src/selinux/README in the PCP git repo for details on how to diagnose this.

**Comment by natoscott** [comment]
Oops, didn't mean to close.

**Comment by wooloo1121** [comment]
@natoscott Thanks for the reply. But SE linux is disabled on our system, do agents still run with selinux policy? I checked the /var/log/audit/audit.log file, when testing the pmda (slurm_info) with dbpmda there is a relevant line says:
type=USER_CMD msg=audit(1594019172.660:5613): pid=66521 uid=0 auid=0 ses=568 msg='cwd="/root/slurm_info" cmd=6462706D6461202D6E20706D6E732D666F722D74657374696E67 terminal=pts/0 res=success'
And I don't see any failed records.

**Comment by natoscott** [comment]
OK, if selinux is disabled or in permissive mode, this isn't going to be the problem.
OOC, does the current perl agent work?

Can you put the code somewhere (gist, pastebin, something like that) that shows the working and failing cases?

**Comment by wooloo1121** [comment]
The perl agent should work. The code is here:
https://gist.github.com/wooloo1121/42087a12e97eb5cb4bb149cd550a58ee
where lines 175 and 176 don't work causing it returns 9999999 for item in range(4, 17).

**Comment by wooloo1121** [comment]
Hi,

I also tried to get job info directly through squeue in pmda, it still doesn't work. The line of code to get job info is as follows:
states = subprocess.check_output(["squeue", "-p", "small", "-h", "-Ostate"])
where state is empty. But the small partition does have many jobs.

**Comment by wooloo1121** [comment]
@natoscott Thank you so much for your attention. I just found out that this issue is due to the following line:
self.set_user(PCP.pmGetConfig('PCP_USER'))
If I comment it out, then the Slurm job info can be obtained through squeue command in pmda. I guess this line restricted the information we could get. Is it necessary in pmda? Can I leave it out or is there any other parameter I could use? Thank you and look forward to your reply.

**Comment by natoscott** [comment]
Ah, yes - I should have thought of that - good catch!

That line makes your PMDA run as the unprivileged 'pcp' user.  If you remove it, the PMDA will run as 'root'.  You may find that Slurm installs its own unprivileged user - perhaps 'slurm'? (look in /etc/passwd, or at some of the slurm processes in 'ps' output)

Its usually best to run with the least privileges possible, so you might be able to change that line to self.set_user('slurm') ... but otherwise, root is fine (I notice the perl version of the PMDA runs as root).
