### ISSUE TITLE
PCP_DIR is missing from the infiniband Install script

### ISSUE THREAD

**Issue by mac133k** [performancecopilot/pcp#968]
All PMDAs Install scripts support custom PCP installation paths when looking for pcp.env. Only the one for InfiniBand metrics has it missing, ie. in src/pmdas/infiniband/Install or var/lib/pcp/pmdas/infiniband/Install after installation the line reads:

`. /etc/pcp.env`

where it should be:

`. $PCP_DIR/etc/pcp.env`

**Comment by kmcdonell** [comment]
Thanks for catching this @mac133k.
Fixed (with some other similar cases) in commit b0fd04b3 that is included in this PR https://github.com/performancecopilot/pcp/pull/970
