### ISSUE TITLE
linux_proc PMDA does not clean up temp accounting file

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#969]
/tmp/pcp-pacct
1. needs onexit() handler to remove it
2. not sure /tmp is the right place for this to exist ... $PCP_TMP_DIR may be a better place

**Comment by natoscott** [comment]
@kmcdonell thanks, this is an area @shogo-matsumoto and I are still working on - had thought of point #2 but point #1 is equally valid - we'll add it to our list.

Relates to https://github.com/performancecopilot/pcp/pull/962

**Comment by kmcdonell** [comment]
If file stays open once created and is not shared with other processes, you don't need the name in the filesystem so you can unlink() after open and avoid atexit().

**Comment by shogo-matsumoto** [comment]
Thank you for the comment. I will deal with the issue this week.

**Comment by shogo-matsumoto** [comment]
I made a PR for this issue. I adopted atexit because we want to stop process accounting (acct(0)) as well as to do unlink when pmcd exits.
