### ISSUE TITLE
calculating cpu utilization (%) from user, sys and idle cpu time retrieved from pmdumptext

### ISSUE THREAD

**Issue by pradykaushik** [performancecopilot/pcp#977]
I am using `pmdumptext` to fetch system-wide metrics.
Below are the three metrics that we're fetching and they are stored in a file named _metrics_.
```commandline
host:kernel.all.cpu.user
host:kernel.all.cpu.sys
host:kernel.all.cpu.idle
```

The above metrics are fetched from a host that has the following processor architecture.
```commandline
Architecture:        x86_64
CPU(s):              40
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           2
```

The command used to fetch PCP data is given below.
```commandline
pmdumptext -m -l -f '' -t 1.0 -d , -c metrics_file
```

The host is running idle and below is the data retrieved for a span of 5 seconds.

|host:kernel.all.cpu.user                          |host:kernel.all.cpu.sys|host:kernel.all.cpu.idle|
|-----------------------------------------------|--------------------|---------------------|
|0.000                                          |0.000               |39993.761            |
|10.000                                         |0.000               |39990.360            |
|0.000                                          |10.000              |39979.760            |
|90.008                                         |20.002              |39903.751            |
|0.000                                          |0.000               |39992.839            |

[Using information given here](https://pcp.io/docs/howto.cpuperf.html) I calculate cpu utilization as shown below.

```commandline
cpuutil_idle = 100 * (kernel.all.cpu.idle / (1000 * 40))
cpuutil_nonidle = 100 * ((kernel.all.cpu.user + kernel.all.cpu.sys) / (1000 * 40)) # or 100 - cpuutil_idle
```
1. Diving by 1000 as the documentation states that cpu-time is converted to milliseconds/second.
2. Dividing by 40 to get cpu utilization between 0-100 %.

is this calculation correct?
Typically, one takes the delta in cpu-time (current - prev) and then divides by the elapsed time. However, as the cpu-time data is already sampled and converted to milliseconds/second, I figured that it is not required. In addition, the values are not monotonically increasing and therefore deltas can result in negative values.

**Comment by natoscott** [comment]
@pradykaushik have a look at the derived metrics that ship with modern versions of PCP, as these do the calculations for you.  I've included a copy here for reference:

```
$ cat /var/lib/pcp/config/derived/cpu-util.conf 
# derived metrics for cpu utilization

kernel.cpu.util.user = (100 * rate(kernel.all.cpu.user)) / hinv.ncpu
kernel.cpu.util.user(oneline) = percentage of user time across all CPUs, including guest CPU time

kernel.cpu.util.nice = (100 * rate(kernel.all.cpu.nice)) / hinv.ncpu
kernel.cpu.util.nice(oneline) = percentage of nice user time across all CPUs, including guest nice CPU time

kernel.cpu.util.sys = (100 * rate(kernel.all.cpu.sys)) / hinv.ncpu
kernel.cpu.util.sys(oneline) = percentage of sys time across all CPUs

kernel.cpu.util.idle = (100 * rate(kernel.all.cpu.idle)) / hinv.ncpu
kernel.cpu.util.idle(oneline) = percentage of idle time across all CPUs

kernel.cpu.util.intr = (100 * rate(kernel.all.cpu.intr)) / hinv.ncpu
kernel.cpu.util.intr(oneline) = percentage of interrupt time across all CPUs
kernel.cpu.util.intr(helptext) = '\
Percentage of time spent processing interrupts across all CPUs.
This value includes both soft and hard interrupt processing time.'

kernel.cpu.util.wait = (100 * rate(kernel.all.cpu.wait.total)) / hinv.ncpu
kernel.cpu.util.wait(oneline) = percentage of wait time across all CPUs

kernel.cpu.util.steal = (100 * rate(kernel.all.cpu.steal)) / hinv.ncpu
kernel.cpu.util.steal(oneline) = percentage of virtualization CPU steal time across all CPUs
kernel.cpu.util.steal(helptext) = '\
Percentage of time across all CPUs when a CPU had a runnable process,
but the hypervisor (virtualisation layer) chose to run something else
instead.'
```
